Lara/action list filter basic layout/comp1199
looker-open-source/components pull request #1371
Opened 2020-08-26 23:20 UTC by laraharrow

### :sparkles: Changes

- **Thank you for your contribution to Looker Components!**
- To ensure a successful review, please double check our checklist of requirements below.
- Also including a short description of changes and relevant screenshots will help us more quickly understand the ultimate goal of your work (🗑 replace this introduction with your summary of changes).

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-09-09 17:26 UTC, lukelooker requested changes
This is coming along! 

Broad strokes:

- [x] `InputFilters` should act like other `Inputs` with a similar border presentation and behavior (`ActionListFilter` should take care of the modifications to make `InputFilters` visually distinct for use within an `ActionList`)
- [x] `ActionList` should directly handle `filters` prop, not require composition of `ActionList` + `ActionListFilters`
- [x] Consolidate Storybook story for filters into the larger `ActionList` example as is done with `select` and `bulk` features

2020-09-09 17:26 UTC, lukelooker commented on packages/components/src/ActionList/ActionList.tsx
> +    </>
Fragment wrapper isn't needed:

```suggestion
      <ActionListContext.Provider value={context}>
        <div className={className}>
          {actionListHeader}
          {bulk && select && select.selectedItems.length > 0 && (
            <ActionListControlBar {...bulk} />
          )}
          <div>{children}</div>
        </div>
      </ActionListContext.Provider>
```

2020-09-09 17:26 UTC, lukelooker commented on packages/components/src/ActionList/ActionListFilters.tsx
> +`
Borders should be assigned on the `ActionListFilters` component.

2020-09-09 17:26 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +
InputFilters should look visually consistent with other inputs:

![image](https://user-images.githubusercontent.com/34253496/92630761-2b584a00-f285-11ea-958d-a3be65bd9924.png)

vs. 

![image](https://user-images.githubusercontent.com/34253496/92630806-3a3efc80-f285-11ea-8a78-cb45c662e53b.png)

Filter icon should probably also be removable like `InputSearch` supports

![image](https://user-images.githubusercontent.com/34253496/92630943-78d4b700-f285-11ea-9378-6a9b9348ff63.png)

2020-09-09 17:26 UTC, lukelooker commented on storybook/src/ActionList/ActionList.stories.tsx
> +)
I'd prefer to see Filters and "Column Selector" added to the default story so we don't have a further proliferation of props. 

You can copy the existing setup for "select" and "bulk" to get the same behavior. 

Storybook 6 introduced "Controls" which is the replacement to "Knobs" currently used - might be a good chance to introduce that and switch to those. See documentation at: https://storybook.js.org/docs/react/essentials/controls

2020-09-09 17:26 UTC, lukelooker commented on storybook/src/ActionList/data.ts
> +export const filterableItems = [
For consistency's sake I'd prefer to see this named `availableFilters` :)

2020-09-09 17:26 UTC, lukelooker commented on storybook/src/Forms/InputFilters.stories.tsx
> +]
Use `availableFilters` here instead of `filterableItems` - also might be good to pick more generic options "Flavor", "Size", etc.

2020-09-09 17:26 UTC, lukelooker commented on www/src/documentation/components/content/action-list.mdx
> +    </>
Fragment not needed.
```suggestion
      <ActionList columns={columns}>{items}</ActionList>
```

2020-09-09 17:26 UTC, lukelooker commented on storybook/src/ActionList/ActionList.stories.tsx
> +    />
`ActionList` should be handling the `fieldFilters` and `availableFilters` props directly (like it does `select`, `bulk`, etc`). 

Probably something like:

`filters={ available: filtersAvailable, fields: [ { expression: 'admin,manager', field: 'role' } ]}`

2020-09-10 19:32 UTC, lukelooker requested changes
Realized a few interface changes need to happen to support proper Chip display as well as some other feedback on implementation choices.

2020-09-10 19:32 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +}
These should get annotated with JS Doc strings. E.g.:

```
/**
  * List of filters the user can select from
  **/
availableFilters: ...
```

I also think the typing should change a bit:

```suggestion
export interface FieldFilter {
   /* specify field to filter against */
   field: string
   /* text displayed in drop-down, optional, `field` is used if not specified */
   label?: string
}

export interface FieldFilterExpressions extends FieldFilter {
   expression?: string
}

export interface InputFiltersProps {
  available: FieldFilter[]
  filters?: FieldFilterExpressions[]
  hideFilterIcon?: boolean
  className?: string
}
```

2020-09-10 19:32 UTC, lukelooker commented on packages/components/src/ActionList/ActionList.tsx
> +
Extend `InputFilterProps` so the interfaces are bound together.

Also `columnsCustomizeable` doesn't really require Filters so we should separate that out (see below)

```suggestion
export interface FiltersConfig extends Omit<InputFiltersConfig, 'hideFilterIcon', 'className'> {}
```

2020-09-10 19:32 UTC, lukelooker commented on packages/components/src/ActionList/ActionList.tsx
> +  filters?: FiltersConfig
- Separate responsibilities for filters vs column selection.
- Rename `columnsCustomizable` to more explicitly name `canSelectDisplayedColumns`

```suggestion
  /** Add description here **/
  filters?: FiltersConfig
  /** Add description here **/
  canSelectDisplayedColumns?: boolean
```

2020-09-10 19:32 UTC, lukelooker commented on packages/components/src/ActionList/ActionList.tsx
> +      )}
Need to deal with a case where `filters === undefined` and `canSelectDisplayedColumns === true`

2020-09-10 19:32 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +        ))}
Need to properly display more complex `filter` definition as type'd above.

Also would be great to implement `onDelete` so users can remove one filter at a time.

```
{fieldFilters.map((filter, i) => (
  <Chip key={i} onClick={editFilter} onDelete={deleteFilter}>
    {filter.field}:{filter.expression}
  </Chip>
))}
```

2020-09-10 19:32 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +      )}
White-space (margin/padding) around "x" icon is inconsistent with `InputSearch`. Can you make them match?

![image](https://user-images.githubusercontent.com/34253496/92789201-75adf980-f35f-11ea-9e67-5ef80c6ef8c0.png)

![image](https://user-images.githubusercontent.com/34253496/92789255-88283300-f35f-11ea-9293-81ec365499b8.png)

2020-09-10 19:32 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +// padding-left: ${props.theme.space.xsmall}
Remove unused code :)

2020-09-10 19:32 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +  }
Recommend taking a slightly simpler approach here - always applying padding to the `Input` itself and then just adjusting the padding on `Icon` to compensate for pre-existing padding on the left.

```suggestion
  padding: 0 ${({ theme }) => theme.space.xxsmall};

  ${Icon} {
    margin-left: ${({ theme }) => theme.space.xxsmall};
    margin-right: ${({ theme }) => theme.space.xsmall};
  }
```

2020-09-18 16:14 UTC, lukelooker commented on packages/components/src/ActionList/ActionList.tsx
> +      )}
Rename `ActionListFilters` to `ActionListControls`

2020-09-21 17:59 UTC, laraharrow commented on packages/components/src/ActionList/ActionList.tsx
> +      )}
We should probably deal with the case when `filters === undefined` and `canSelectDisplayedColumns === true` when  we add `canSelectDisplayedColumns`?

2020-09-24 16:59 UTC, lukelooker requested changes
A few small notes on tests and a lodash function improvement

2020-09-24 16:59 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +  })
Use `lodash`'s `partition` function here => https://lodash.com/docs/4.17.15#partition

```
const [ assigned, unassigned ] = partition(filters, (filter) => filter.value )
```

2020-09-24 18:30 UTC, lukelooker approved these changes

2020-09-24 18:33 UTC, merged