theme.fonts Improvements
looker-open-source/components pull request #1390
Opened 2020-09-03 19:10 UTC by lukelooker

- Adds `theme.fonts.body` and uses that as the default font-family
- Removes font specification from the GlobalStyle to prevent font
"leakage"
- Adds font specification to reset to ensure that it's broadly applied
- Apply `fonts.brand` to `Button*`, 'Heading` and `Tabs`
- Allow font specification on `Heading` (sometimes folks might want a
heading with `fonts.body`
- Removed `fontWeights.extraBold` (not used anywhere in components or
product)
- Removed all usage of `fontWeights.light` (deprecation to follow when
product usage is removed)

- Introduced new GoogleFontsLoader to allow for easy loading of Google
fonts in standalone applications
- Leveraged GoogleFontsLoader in ComponentsProvider

- Fixed a variety of small Storybook configuration errors to silence
console warnings when running Storybook

### :sparkles: Changes

- **Thank you for your contribution to Looker Components!**
- To ensure a successful review, please double check our checklist of requirements below.
- Also including a short description of changes and relevant screenshots will help us more quickly understand the ultimate goal of your work (🗑 replace this introduction with your summary of changes).

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-09-08 16:26 UTC, jhardy submitted a review, later dismissed

2020-09-08 16:26 UTC, jhardy commented on packages/components/src/Avatar/__snapshots__/Avatar.test.tsx.snap
> +  font-family: 'Roboto','Noto Sans JP','Noto Sans CJK KR','Noto Sans Arabic UI','Noto Sans Devanagari UI','Noto Sans Hebrew','Noto Sans Thai UI','Helvetica','Arial','sans-serif','Noto Sans';
A couple things here. 'sans-serif' in quotes won't work, it will default to a serif font. 

'Noto Sans' is at the end here, should be before `Helvetica...sans-serif`

2020-09-08 16:26 UTC, jhardy commented on packages/components/src/Avatar/__snapshots__/Avatar.test.tsx.snap
> +  font-family: 'Roboto','Noto Sans JP','Noto Sans CJK KR','Noto Sans Arabic UI','Noto Sans Devanagari UI','Noto Sans Hebrew','Noto Sans Thai UI','Helvetica','Arial','sans-serif','Noto Sans';
I think you might have explained this to me before, but do we need the `Noto` fonts here? 

Would be nice to just keep our base font stack to system fonts `Helvetica, Arial, sans-serif` and then let users choose their font stack at implementation level.

2020-09-08 16:26 UTC, jhardy commented on packages/components/src/Text/__snapshots__/Code.test.tsx.snap
> +  font-family: 'Roboto Mono','Monaco','Menlo','Ubuntu Mono','Consolas','source-code-pro','monospace';
font-family declared twice here. Should just be the mono family

2020-09-08 16:26 UTC, jhardy commented on packages/components/src/Text/__snapshots__/Heading.test.tsx.snap
> +  font-family: 'Red Hat Display','Noto Sans JP','Noto Sans CJK KR','Noto Sans Arabic UI','Noto Sans Devanagari UI','Noto Sans Hebrew','Noto Sans Thai UI','Helvetica','Arial','sans-serif','Noto Sans';
headings have two font family declarations

2020-09-08 16:26 UTC, jhardy commented on packages/design-tokens/src/tokens/typography/font_families.ts
> +  code: 'Roboto Mono',
I wonder if we should default to system fonts? I don't have a strong opinion here just more of an open question.

2020-09-08 17:58 UTC, lukelooker commented on packages/components/src/Text/__snapshots__/Heading.test.tsx.snap
> +  font-family: 'Red Hat Display','Noto Sans JP','Noto Sans CJK KR','Noto Sans Arabic UI','Noto Sans Devanagari UI','Noto Sans Hebrew','Noto Sans Thai UI','Helvetica','Arial','sans-serif','Noto Sans';
Fixed. `reset` now handles font-family globally so we get only one instance.

2020-09-08 17:58 UTC, lukelooker commented on packages/components/src/Text/__snapshots__/Code.test.tsx.snap
> +  font-family: 'Roboto Mono','Monaco','Menlo','Ubuntu Mono','Consolas','source-code-pro','monospace';
Same as `Heading`, `reset` handles this now

2020-09-08 18:12 UTC, lukelooker commented on packages/components/src/Avatar/__snapshots__/Avatar.test.tsx.snap
> +  font-family: 'Roboto','Noto Sans JP','Noto Sans CJK KR','Noto Sans Arabic UI','Noto Sans Devanagari UI','Noto Sans Hebrew','Noto Sans Thai UI','Helvetica','Arial','sans-serif','Noto Sans';
Doh - I had strings properly double-quoted at one point to make this work and then un-did it (thinking I had made a mistake). Fixed now to _actually_ work right.

`Noto Sans` is at the end of the font-stack in the CORE product and I originally just left that because I hadn't dug into _why_. On further reflection I think you're right that it doesn't make any sense to be there. Our previous stock font "Open Sans" had a lot of missing characters so Noto Sans was used to fill in those gaps, now that we're defaulting to better quality font without missing characters (Roboto) I think that fallback is no longer needed.

The entries for the rest of the Noto fonts are to address broad i18n support for characters that aren't included in most fonts (Korean, Japanese, etc.).  We leave it to the implementor to actually load those fonts but I'd like to leave them in place because applications running within the CORE application such as Extensions will have access to them. In general I think having them in the font-stack shouldn't have any impact itself – it's really whether or not they're loaded which is a separate concern.

2020-09-08 18:23 UTC, mdodgelooker requested changes
This is so neat! Just a couple of minor suggestions.

2020-09-08 18:23 UTC, mdodgelooker commented on packages/design-tokens/src/theme.ts
> +}
Rad!

2020-09-08 18:25 UTC, mdodgelooker commented
Oh and quick question about `Heading` – is it always supposed to be Red Hat Display or do we want to sometimes style it as `font-family: inherit`, like in `Select` with descriptions: 
![image](https://user-images.githubusercontent.com/53451193/92514000-0bae1c80-f1c6-11ea-9cbc-e90440611894.png)

2020-09-08 18:48 UTC, lukelooker commented on packages/components/src/Button/Button.test.tsx
> +test('Render', () => renderTest(<Button />))
Whoops... this was entirely unrelated (I was verifying a text fix in another repo and accidentally committed this)

2020-09-08 20:22 UTC, lukelooker commented
> Oh and quick question about `Heading` – is it always supposed to be Red Hat Display or do we want to sometimes style it as `font-family: inherit`, like in `Select` with descriptions:
> ![image](https://user-images.githubusercontent.com/53451193/92514000-0bae1c80-f1c6-11ea-9cbc-e90440611894.png)

Great point. Went through and audited all uses of `Heading` internally - specified `body` explicitly on `CalendarNav, MenuGroupLabel, SelectOptions, SidebarGroup` components :)

2020-09-08 20:24 UTC, lukelooker commented on packages/design-tokens/src/GoogleFontsLoader/GoogleFontsLoader.tsx
> +  uri += `wght@${weights.join(';')}`
Doh! You're totally right :)

2020-09-09 05:01 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Select/SelectOptions.tsx
> +      >
Should `SelectOptionGroupTitle` below also have font="body"?

2020-09-09 05:02 UTC, mdodgelooker reviewed
Everything looks good! Just had one question about the font on `SelectOptionGroupTitle`.

2020-09-09 16:09 UTC, jhardy commented on packages/components/src/Avatar/__snapshots__/Avatar.test.tsx.snap
> +  font-family: 'Roboto','Noto Sans JP','Noto Sans CJK KR','Noto Sans Arabic UI','Noto Sans Devanagari UI','Noto Sans Hebrew','Noto Sans Thai UI','Helvetica','Arial','sans-serif','Noto Sans';
Sounds good to me. No harm in declaring the font families.

2020-09-09 16:42 UTC, lukelooker commented on packages/components/src/Form/Inputs/Select/SelectOptions.tsx
> +      >
Yep! (missed it, doh)

2020-09-09 17:18 UTC, mdodgelooker approved these changes
LGTM!

2020-09-09 17:28 UTC, merged