MenuItem detail Icon Fix
looker-open-source/components pull request #1402
Opened 2020-09-09 18:43 UTC by dbchristopher

### :sparkles: Changes

- Deletes hard-coded MenuItem -> Icon color 

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [x] Build and tests are passing
- [ ] Update documentation
- [x] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [x] PR is ideally < ~400LOC

### :camera: Screenshots
<img width="790" alt="Screen_Shot_2020-09-09_at_11_41_05_AM" src="https://user-images.githubusercontent.com/238293/92640120-acb5d980-f291-11ea-8a80-fdf0684029f4.png">

2020-09-09 18:46 UTC, dbchristopher commented on packages/components/src/Menu/MenuItemLayout.tsx
> -    color: ${({ theme: { colors } }) => colors.text1};
@mdodgelooker it turns out the Icon default color was already `text1`. So the ultimate fix was just to delete this line 🥳

2020-09-09 19:03 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Checkbox/__snapshots__/Checkbox.test.tsx.snap
> +    checked={false}
So odd... this snapshot passed for me, but then failed after I ran `yarn`.

2020-09-09 19:07 UTC, dbchristopher commented on packages/components/src/Form/Inputs/Checkbox/__snapshots__/Checkbox.test.tsx.snap
> +    checked={false}
oh dang! looks like I needed to run yarn too. I'll upload some new snapshots...

2020-09-09 19:26 UTC, mdodgelooker requested changes
Looks good! Just one more `text1` to remove and then the example in playground should either move to `Menu.stories.tsx` or be deleted before merging.

2020-09-09 19:26 UTC, mdodgelooker commented on packages/components/src/Menu/MenuItemLayout.tsx
> -    }
I think the one for `[disabled]` down on line 150 can also be removed.

2020-09-09 21:52 UTC, dbchristopher commented on packages/components/src/Menu/MenuItemLayout.tsx
> -    }
oh good catch!

2020-09-09 22:35 UTC, dbchristopher commented
Ok @mdodgelooker I updated the menu storybook and reverted the playground changes. this should be ready for final ✅

2020-09-10 02:47 UTC, mdodgelooker approved these changes
LGTM!

2020-09-10 16:40 UTC, merged