Tree label wrapping and truncation behavior
looker-open-source/components pull request #1408
Opened 2020-09-11 18:00 UTC by dbchristopher

### :sparkles: Changes

- Updates tree layout to allow for items and labels to either wrap or truncate based on desired behavior. 
- When truncating, text will be cut off after one line, but a tooltip will be provided to view the rest of the text

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

![tree-labels](https://user-images.githubusercontent.com/238293/92957736-e1ef3280-f41d-11ea-91c3-008f6f62f13f.gif)

2020-09-14 07:38 UTC, lukelooker commented
Neat! (screenshot looks awesome) 💯

2020-09-14 23:26 UTC, dbchristopher commented
@jhardy I implemented your feedback, and this is ready for another look. I also added additional logic so that the truncated text component only renders the tooltip when the text actually overflows:

![text-overflow-behavior](https://user-images.githubusercontent.com/238293/93147760-f3973b00-f6a6-11ea-8ccb-3124e2e4dc2b.gif)

2020-09-18 11:45 UTC, jhardy commented
@dbchristopher only small nit I see now is when tree labels wrap the icons are misaligned, other than this is so cool  
![image](https://user-images.githubusercontent.com/170681/93593858-adbdc980-f969-11ea-8a66-2ae5f037de9a.png)

2020-09-18 11:47 UTC, jhardy commented on packages/components/src/Accordion/AccordionDisclosureGrid.tsx
> +  align-items: align-items;
Meta :D

2020-09-18 11:57 UTC, jhardy commented on packages/components/src/Text/useIsTextTruncated.ts
> +}
This is really neat! I would love to see it documented a bit more, just because I want to learn to write more things like this. I think it would be great to have a bit more verbose descriptions of what everything is doing. 

I don't know best practices are here, so feel free to ignore this request as well :)

2020-09-21 19:09 UTC, dbchristopher commented on packages/components/src/Text/useIsTextTruncated.ts
> +}
oh yeah for sure! I'm definitely planning to clean up and document this stuff better

2020-09-22 17:29 UTC, dbchristopher commented on packages/components/src/ActionList/ActionListItemColumn.tsx
> +  width: 100%;
had to add a width style in order for the Truncate component to work in the actionlist context

2020-09-22 23:09 UTC, dbchristopher commented on www/src/documentation/components/content/action-list.mdx
> +## Truncation
Added a truncation example to the Action list, as I believe that could be a common use case for it.

2020-09-22 23:13 UTC, dbchristopher commented on packages/components/src/Overlay/OverlaySurface.tsx
> +        maxWidth={maxWidth}
added maxWidth support here for a little more style control over the long-text tooltips

2020-09-22 23:51 UTC, dbchristopher commented on packages/components/src/Text/Truncate.tsx
> +  font: inherit;
I'm just doing a blunt inherited font style rather than allowing people to pass fontSize and other props directly to this component. My thinking is that Truncate should just be concerned with the truncation behavior, and not any other styling

2020-09-23 19:21 UTC, dbchristopher commented on packages/components/src/Overlay/OverlaySurface.tsx
> +        maxWidth={maxWidth}
I wonder if we might just want to hard-code a sane default max-width rather than accepting this as a prop? @jhardy what do you think?

2020-09-23 19:21 UTC, dbchristopher commented on packages/components/src/Layout/FlexItem/FlexItem.tsx
> +  min-width: 0; /* IMPORANT!! Do not delete! */
This was... 🤯  to debug

2020-09-24 04:23 UTC, mdodgelooker requested changes
This is so great, can't wait to use `Truncate` in `InputChips` and `SelectMulti`.

I think `useTooltip` will streamline `Truncate` a bit, and I noticed a small height issue when `detail` is used:
![image](https://user-images.githubusercontent.com/53451193/94100552-ceab7200-fde2-11ea-99c3-6a7451e92f79.png)
Before:
![image](https://user-images.githubusercontent.com/53451193/94100601-ef73c780-fde2-11ea-9f9f-18414d3a7410.png)

2020-09-24 04:23 UTC, mdodgelooker commented on packages/components/src/Text/Truncate.tsx
> +      <HiddenText ref={textRef}>{children}</HiddenText>
This is a good use case for `useTooltip`
```suggestion
  const { tooltip, ...triggerProps } = useTooltip({
    content: children,
    disabled: !isTruncated,
    maxWidth: '700px',
    placement: 'top-start',
    surfaceStyles: {
      backgroundColor: 'background',
      border: '1px solid',
      borderColor: 'ui3',
      color: 'text3',
    },
    textAlign: 'left',
    triggerElement: domNode,
    width: 'auto',
  })

  return (
    <TextWrapper>
      {tooltip}
      <TextStyle {...triggerProps} ref={textRef}>
        {children}
      </TextStyle>
```

2020-09-24 18:53 UTC, dbchristopher commented on packages/components/src/Tree/TreeItem.tsx
> +          <FlexItem flex="1" width="100%" pr={truncate ? 'large' : 'none'}>
Initially I kept running into a bug where the text would continue outside the container a bit before getting truncated, and this was may hacky one-off fix to resolve that. But I just double checked, and it doesn't seem to be an issue any more. Maybe that FlexItem `min-width` change helped fix things here too 🤷 I'll delete!

2020-09-24 18:56 UTC, dbchristopher commented on packages/components/src/Text/Truncate.tsx
> +      <HiddenText ref={textRef}>{children}</HiddenText>
Oh awesome! Thanks that's much better

2020-09-24 22:18 UTC, dbchristopher commented
ok @mdodgelooker I updated it so that it could align `detail` prop better for both truncated and wrapped text. Should be ready for final review!
 
<img width="713" alt="Screen Shot 2020-09-24 at 3 10 54 PM" src="https://user-images.githubusercontent.com/238293/94205894-0ebd3400-fe79-11ea-9bc5-db1dd2ef10b1.png">

2020-09-25 04:15 UTC, mdodgelooker approved these changes
Looks great! 🚢

2020-09-25 05:04 UTC, lukelooker commented on packages/components/src/Overlay/OverlaySurface.tsx
> +        maxWidth={maxWidth}
It seems like setting a maxWidth here via `defaultProps` could make sense in that it at least addresses the awkwardness of having a "magic value" (`700px`) deep within `Truncate`. 

If it was set here `Truncate` could simply absorb that and we could, if later requested, add an optional `maxWidth` to `Truncate` (or other `OverlaySurface` consumers) to override it.

I'd argue for `30rem` or `48rem` since either could be derived from our pre-existing breakpoints.

2020-09-25 05:29 UTC, lukelooker requested changes
Found a few small clean-ups and color tweaks that are off-spec.

Noticed in testing that the "field picker" tree example in Storybook has some fairly large hover-state issues (in master it appears to work fine):

![12aecc92-dbc5-465e-acf8-c1f99948e4d3](https://user-images.githubusercontent.com/34253496/94229761-44800e00-feb5-11ea-91b4-1eb5673b8394.gif)

2020-09-25 05:29 UTC, lukelooker commented on packages/components/src/Text/Truncate.tsx
> +      borderColor: 'ui3',
`ui2` is more common border color.

2020-09-25 05:29 UTC, lukelooker commented on packages/components/src/Text/Truncate.tsx
> +      borderColor: 'ui3',
Verified in spec that`ui2` is correct value here:

![image](https://user-images.githubusercontent.com/34253496/94228700-67f58980-feb2-11ea-8977-6a820a126a81.png)

2020-09-25 05:29 UTC, lukelooker commented on packages/components/src/Text/Truncate.tsx
> +      color: 'text3',
```suggestion
      color: 'text5',
```

2020-09-25 05:29 UTC, lukelooker commented on packages/components/src/Text/Truncate.tsx
> +      borderColor: 'ui3',
```suggestion
      borderColor: 'ui2',
```

2020-09-25 05:29 UTC, lukelooker commented on packages/components/src/Tree/TreeItem.tsx
> +  const TextWrapper = truncate ? Truncate : Identity
Named `[React].Fragment` can be used here instead.

```suggestion
  const TextWrapper = truncate ? Truncate : Fragment
```

2020-09-25 05:29 UTC, lukelooker commented on packages/components/src/Tree/TreeItem.tsx
> +
Not needed (see below)

```suggestion
```

2020-09-25 05:29 UTC, lukelooker commented on packages/components/src/Tree/TreeItem.tsx
> +              <TextWrapper>{children as string}</TextWrapper>
`Fragment` doesn't require `any` workaround.

```suggestion
              <TextWrapper>{children}</TextWrapper>
```

2020-09-25 05:31 UTC, lukelooker commented on www/src/documentation/components/content/action-list.mdx
> +## Truncation
This super cool. I'm working on updating `ActionList` to use a `table` underneath and I'm going to take a look at doing "baked in" support similar to `Tree` as I think you're totally correct about how useful this will be. :)

2020-09-25 17:26 UTC, dbchristopher commented on packages/components/src/Tree/TreeItem.tsx
> +  const TextWrapper = truncate ? Truncate : Identity
oh that's awesome!

2020-09-26 13:11 UTC, jhardy commented on packages/components/src/Overlay/OverlaySurface.tsx
> +        maxWidth={maxWidth}
My vote would be for something that is a comfortable line length, `48rem` is on the larger end of that comfortable reading line length, but I think its a good starting point and a better choice than `30rem`

2020-09-26 13:28 UTC, jhardy commented on www/src/documentation/components/content/tree.mdx
> +  label="A very label that wraps to a second line. Both the label and the tree item will wrap to two or more lines because there is just too much text."
```suggestion
  label="A very long label that wraps to a second line. Both the label and the tree item will wrap to two or more lines because there is just too much text."
```

2020-09-26 13:47 UTC, jhardy commented
This is looking really great, two things I think we may want to consider and wanted to your's and @lukelooker  feedback here:

1.  I think we should have a longer delay before showing the truncation tooltip. This would be something we need to test a bit, but my first guess would be somewhere between 200-400ms, possibly longer, but would need to test it out

2. If possible, I think we might want to try hiding the truncation tooltip  when the user leaves the trigger area, even if their mouse is over the tooltip. 

I attached a gif here to try to demonstrate why I am suggesting these changes:

-  In the scenario where you have a long list of items that could be truncated, when you are moving through that list quickly you really don't need to see the truncation tooltip until you rest on an item. 
- When moving up through a lists of truncated items, the tooltip blocks you from hovering over the previous item, or items if the tooltip has lots of content,  in the list.  I think it would be a better experience if we just close the tooltip right away so you can get back to the previous item, with out having to move your mouse left or right outside of the truncation target area 

![2020-09-26_06-37-45 (1)](https://user-images.githubusercontent.com/170681/94342163-fc034600-ffc3-11ea-8cdf-d8a82bfda99f.gif)

2020-09-26 17:14 UTC, lukelooker commented on packages/components/src/Overlay/OverlaySurface.tsx
> +        maxWidth={maxWidth}
It's worth noting that `OverlaySurface` is used underneath `Tooltip` & `Popover` so this would be a fairly global value. We may want to set a larger threshold here and then narrow it for `Truncate` specifically perhaps?

2020-09-26 17:52 UTC, lukelooker commented
> This is looking really great, two things I think we may want to consider and wanted to your's and @lukelooker feedback here:
> 
> 1. I think we should have a longer delay before showing the truncation tooltip. This would be something we need to test a bit, but my first guess would be somewhere between 200-400ms, possibly longer.

I like the idea of a delay but I wonder if it might be better implemented as global functionality to `Tooltip` itself – we've heard comments about tooltip being "too aggressive" and giving it a subtle delay would probably be helpful with that feedback as well.

> 2. If possible, I think we might want to try hiding the truncation tooltip  when the user leaves the trigger area, even if their mouse is over the tooltip.

Having using this pattern in other products (cloud console is my reference) I would actually find this frustrating because it would preclude me from being able to select the text for copy & paste – something that's common with long non-breaking strings in technical products (e.g.: server address, GUID, etc)

2020-09-26 18:09 UTC, jhardy commented
> Having using this pattern in other products (cloud console is my reference) I would actually find this frustrating because it would preclude me from being able to select the text for copy & paste – something that's common with long non-breaking strings in technical products (e.g.: server address, GUID, etc)

I think you are right here and this was the use case that almost made me not suggest that change but figured it was worth having a discussion about 😄 

I can see cases in like an long list of tree items (exploring) where it may be annoying, but that seems to be the tradeoff between wrapping and truncation

2020-09-26 18:17 UTC, lukelooker commented
> I think you are right here and this was the use case that almost made me not suggest that change but figured it was worth having a discussion about 😄

Yeah - I was actually running this a bit yesterday when trying to paste something that was truncated :)

Thoughts on a general `Tooltip` delay?

2020-09-26 21:11 UTC, jhardy commented
I like the idea of the global tool tip delay.

2020-09-26 21:43 UTC, lukelooker commented
> I like the idea of the global tool tip delay. I could see a way to opt out of delay being helpful, things like an info icon where its holding more info, but for our icons button and things like truncation a delay makes a lot of sense

Sounds awesome. I've added a ticket to track that change separately from this PR.

2020-09-28 18:50 UTC, dbchristopher commented
> Sounds awesome. I've added a ticket to track that change separately from this PR.

Thanks @lukelooker! Punting the general tooltip behavior changes for another sprint makes sense to me. 

> I would actually find this frustrating because it would preclude me from being able to select the text for copy & paste – something that's common with long non-breaking strings in technical products (e.g.: server address, GUID, etc)

Yeah I had that exact internal battle. It's annoying that it blocks the content when you move up the list, but it seems important to allow them to copy the text. One potential solution: if they click the truncated text it could automatically copy the full content to your clipboard. I'm not sure how best to indicate that behavior in the UI though. Any thoughts @jhardy or @lukelooker? 

Might be worth leaving that as a future optimization either way though

2020-09-29 00:05 UTC, dbchristopher commented on packages/components/src/Overlay/OverlaySurface.tsx
> +        maxWidth={maxWidth}
I added the default value to Tooltip, so it should be reasonably global but shouldn't affect any Popover content

2020-09-29 00:09 UTC, dbchristopher commented on packages/components/src/Tree/Tree.tsx
> +  }
I hate having to do style overrides like this 😕 This pattern makes the child components inherently impure and harder to debug, as you can't just look at IconButton to reason about why it's rendering the way it is. But it's consistent with how most a lot of tree content is styled, and seemed to be the only way I could get the FieldPicker example to behave

2020-09-29 00:19 UTC, dbchristopher commented on storybook/src/Tree/FieldPicker.stories.tsx
> +    mt="xxxsmall"
had to do a little one-off fix to fix alignment on the FieldPicker story itself. We'll probably have to double check any [INTERNAL REPO] instances of tree in case they're using this pattern and the flex-start alignment throws anything off.

I had to go with flex-start alignment to support how we want the detail content to line up when text wraps 

<img width="489" alt="Screen Shot 2020-09-28 at 5 19 00 PM" src="https://user-images.githubusercontent.com/238293/94498346-bd7daf00-01ae-11eb-9620-83db5449557c.png">

2020-09-29 00:22 UTC, dbchristopher commented
ok @lukelooker I implemented feedback and resolved those tricky Field Picker bugs! Should be ready for another review

2020-10-02 05:28 UTC, lukelooker requested changes
My apologies for the delay on reviewing this – I want to have image-snapshots in place because there's a lot of nuance within this component.

I went ahead and built a quick branch (`dc/tree-truncate-rebased`) with this work on top of the new Tree image snapshots (#1498) - in so doing I found two issues:

1. TreeItem height changed from `25px` to `26px` - after discussing with Jared the correct value should actually be `24px` so regardless of what happens snapshot updates will be needed.
2. When using the `Truncate` component within the prototype field picker story the `detail` items fall outside of the `Tree` space itself:
![image](https://user-images.githubusercontent.com/34253496/94890708-deefcc80-0434-11eb-9d99-bfd635da1764.png)

2020-10-02 17:37 UTC, dbchristopher commented
@lukelooker it appears that these screenshots aren't always consistent with what a real browser renders:
<img width="576" alt="Screen Shot 2020-10-02 at 10 35 49 AM" src="https://user-images.githubusercontent.com/238293/94952600-14c79c00-049b-11eb-94a4-204dac3bf78d.png">

Probably most useful to alert you when something unintentionally changed, rather than to be used as a primary vehicle for QA. I'll condense the vertical space a little bit though!

2020-10-02 17:40 UTC, dbchristopher commented
sorry @lukelooker I just fully processed what you were saying. It's friday and I'm tired lol. I'll look into the truncation/fieldpicker combo now

2020-10-02 18:42 UTC, dbchristopher commented on packages/components/src/Tree/TreeItem.tsx
> +  padding-top: calc(${({ theme }) => theme.space.xxsmall} - 1px);
had to do a manual tweak here to get it to add up pixel perfectly

<img width="380" alt="Screen_Shot_2020-10-02_at_11_34_55_AM" src="https://user-images.githubusercontent.com/238293/94958391-4bee7b00-04a4-11eb-96b9-a543bb018f9b.png">

2020-10-02 19:27 UTC, dbchristopher commented on packages/components/src/utils/HoverDisclosure/HoverDisclosure.tsx
> +`
I'm not sure what unintended consequences this could cause. But it seems like we need to make sure the content actually exists in the layout to prevent situations like this when it toggles into view:

![disclosure-hover](https://user-images.githubusercontent.com/238293/94961940-7e9b7200-04aa-11eb-9191-31e6a971ac71.gif)

2020-10-03 00:01 UTC, dbchristopher commented
Ok this component might be the death of me but I **think** I've gotten it all buttoned up for now 😂 😭 

![field-picker](https://user-images.githubusercontent.com/238293/94978121-c7feb800-04d0-11eb-939b-b6510d11df42.gif)

Ready for another look @lukelooker!

2020-10-03 00:03 UTC, dbchristopher commented on packages/components/src/Tree/Tree.tsx
> +  }
![eye twitch](https://media.giphy.com/media/xU1spRleFHmtjvskXw/giphy.gif)

2020-10-03 02:35 UTC, dbchristopher commented on packages/components/src/Tree/TreeItem.tsx
> +  padding-top: calc(${({ theme }) => theme.space.xxsmall} - 1px);
I do have to say that I really hope the new image snapshots don't push us towards a ton of magic numbers and finicky tweaks sprinkled out through the codebase. I feel that if our normal T-shirt sizing doesn't add up to the exact pixels shown in Figma, then the answer is to update Figma.

Ultimately there isn't a material difference between 24px rows and 26px rows. I'm fine with this as an exception, but I just really hope this is not a glimpse into the future of our codebase.

2020-10-05 09:13 UTC, lukelooker reviewed
> I do have to say that I really hope the new image snapshots don't push us towards a ton of magic numbers and finicky tweaks sprinkled out through the codebase. I feel that if our normal T-shirt sizing doesn't add up to the exact pixels shown in Figma, then the answer is to update Figma.

I totally agree with your point here - I don't want to be chasing arbitrary number – that said, `24` is a codified `size` in our theme and that got me thinking about simpler ways to chase this problem – I added a commit that backs out the complexity through two major changes:

```min-height: ${({ theme }) => theme.sizes.medium}```

+ changing all use of `border: 1px solid transparent` (and its focusVisible alternate) to use `outline` instead. This effectively makes the the math a moot-point as "outline" doesn't mess with the box-sizing.

Additionally I flipped all of the flex arrangement back to positioning everything vertically centered so that as the `TreeItem` (and `AccordionDisclosure`) height changes everything just tracks along with the change in height.

Try pulling my changes and see what you think – I wasn't able to find any glaring issues

2020-10-05 18:00 UTC, dbchristopher commented on packages/components/src/Accordion/AccordionDisclosureLayout.tsx
> +  padding-top: ${({ theme }) => theme.space.xxsmall};
@lukelooker yeah exactly. Jared requested that all the icons align with the first line of text when it starts wrapping. So we can't rely on flex API to handle our vertical alignment for us :( 

<img width="560" alt="Screen Shot 2020-10-05 at 10 59 31 AM" src="https://user-images.githubusercontent.com/238293/95115160-e267aa00-06f9-11eb-96fb-59f9f6cae9b0.png">

2020-10-05 18:35 UTC, dbchristopher commented on package.json
> +    "-preimage-snapshots": "yarn storybooks-build",
@lukelooker is `-preimage-snapshots` an intentional change here?

2020-10-05 18:40 UTC, dbchristopher commented on packages/components/src/Accordion/AccordionDisclosure.tsx
> +    focusVisible && theme.colors.keyFocus};
`outline` is a great call 👍 👍

2020-10-05 18:46 UTC, dbchristopher commented
@lukelooker thanks for helping simplify things and talking us down from the more finicky vertical alignment. I just gave it another once-over and I think things are ready to merge whenever you want to give the ✅ !

2020-10-05 19:06 UTC, lukelooker submitted a review, later dismissed

2020-10-05 21:52 UTC, lukelooker approved these changes

2020-10-05 21:53 UTC, merged