Luke/dialog improvements
looker-open-source/components pull request #1427
Opened 2020-09-14 07:41 UTC by lukelooker

### :sparkles: Changes

In progress...

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-10-07 21:58 UTC, lukelooker commented on package.json
> +    "image-snapshots": "yarn image-snapshots-only"
Accidentally created an endless loop in an earlier PR. Whoops!

2020-10-07 21:58 UTC, lukelooker commented on packages/components/src/Dialog/Backdrop.tsx
> +  'data-testid': 'backdrop',
Used to test style and allow direct-click via RTL.

2020-10-07 21:58 UTC, lukelooker commented on packages/components/src/Dialog/Backdrop.tsx
> -  opacity: ${(props) => props.opacity || 0.4};
@jhardy This changes the "Backdrop" overlay color. Can I get you to weigh in on the value? You can look at the snapshots above to see the effect.

2020-10-07 21:58 UTC, lukelooker commented on packages/components/src/Dialog/DialogRender.tsx
> +export const DialogRender: FC<DialogRenderProps> = ({
Extracted this for re-use in `Drawer`. When `content` vs `children` override game in `Dialog` goes away this might be able to move back within `Dialog` itself.

2020-10-07 21:58 UTC, lukelooker commented on packages/components/src/Dialog/Backdrop.tsx
> -  backgroundColor: 'ui2',
@jhardy - this part 2 of the backdrop color change.

2020-10-07 21:58 UTC, lukelooker commented on packages/components/src/Dialog/DialogManager.tsx
> +export const DialogManager = Dialog
Just a proxy to keep the `DialogManager` name intact for a little while.

2020-10-07 21:58 UTC, lukelooker commented on packages/components/src/Dialog/DialogSurface.tsx
> +  box-shadow: ${({ theme }) => theme.shadows[5]};
@jhardy This is "deeper" than before - can you specify the correct value for this in our new dark-backdrop world?

2020-10-07 21:58 UTC, lukelooker commented on packages/components/src/Dialog/SurfaceBase.tsx
> +}))`
Slightly improve a11y here (to make testing work).

We could definitely do some more work here per WCAG recommendations.

2020-10-07 21:58 UTC, lukelooker commented on packages/components/src/Dialog/SurfaceBase.tsx
> -  }
This is now done in `DialogSurface` to keep it from interfering with `DrawerSurface`

2020-10-07 21:58 UTC, lukelooker commented on packages/components/src/Dialog/stories/Dialog.story.tsx
> +}
This prevents storyshots from "collecting" this story - this story is a closed Dialog (nothing to see except the trigger button) sot it's not really useful for screenshot testing

2020-10-07 21:58 UTC, lukelooker commented on packages/components/src/Dialog/stories/SaveChanges.tsx
> +export const SaveChanges = () => {
Moved this over from Storybook and refactored some.

2020-10-08 11:26 UTC, jhardy commented on packages/components/src/Dialog/Backdrop.tsx
> -  opacity: ${(props) => props.opacity || 0.4};
Parent spec calls for. black at 60% opacity. ui5 @ 60% would work

2020-10-08 11:27 UTC, jhardy commented on packages/components/src/Dialog/Backdrop.tsx
> -  backgroundColor: 'ui2',
Oh now that I look here, I see it is ui5 at 60%. This is 👍

2020-10-08 11:29 UTC, jhardy commented on packages/components/src/Dialog/DialogSurface.tsx
> +  box-shadow: ${({ theme }) => theme.shadows[5]};
Level 5 should work. I plan to take a pass to update our elevation styles, but need to check in with a few teams on impact of those changes

2020-10-08 17:42 UTC, lukelooker commented on packages/components/src/Dialog/DialogRender.tsx
> +
Move to hook. Except className

2020-10-12 04:02 UTC, mdodgelooker requested changes
So much better! 👍👌 Just a few suggestions here and there.

2020-10-12 04:02 UTC, mdodgelooker commented on packages/components/src/Drawer/Drawer.test.tsx
> -
Removed b/c Dialog.test.tsx covers this stuff now?

2020-10-12 04:02 UTC, mdodgelooker commented on packages/components/src/Button/Button.tsx
> +  &[aria-expanded='true'],
🎉

2020-10-12 05:09 UTC, lukelooker commented on packages/components/src/Drawer/Drawer.test.tsx
> -
Yep - with Drawer being just a "pass-through" these tests seemed superfluous.

2020-10-12 05:12 UTC, lukelooker commented on packages/components/src/Dialog/useDialog.tsx
> +    : uncontrolledIsOpen
It sure does! 🤦

2020-10-12 05:17 UTC, lukelooker commented
@mdodgelooker Thanks for your review - incorporated all your suggestion and ready for re-review :)

2020-10-12 05:19 UTC, mdodgelooker approved these changes

2020-10-12 05:44 UTC, merged