Improvements to Storybook
looker-open-source/components pull request #1452
Opened 2020-09-18 08:26 UTC by lukelooker

### :sparkles: Changes

- **Thank you for your contribution to Looker Components!**
- To ensure a successful review, please double check our checklist of requirements below.
- Also including a short description of changes and relevant screenshots will help us more quickly understand the ultimate goal of your work (🗑 replace this introduction with your summary of changes).

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-09-24 06:31 UTC, lukelooker commented on storybook/.storybook/preview-head.html
> +</style>
Remove default padding for very "plain" iframe embed in docs.

2020-09-24 06:31 UTC, lukelooker commented on storybook/.storybook/preview.js
> +  },
See https://storybook.js.org/docs/react/writing-docs/doc-blocks for background

2020-09-24 18:14 UTC, dbchristopher commented on storybook/src/ActionList/ActionList.stories.tsx
> +const Template: Story<DemoProps> = ({
Do we need a ThemeProvider somewhere in here? Weird this story is showing up with serif font, but it doesn't seem to be happening anywhere else

<img width="390" alt="Screen Shot 2020-09-24 at 11 12 40 AM" src="https://user-images.githubusercontent.com/238293/94183278-08b65b80-fe57-11ea-9a27-28d90e52cfab.png">

2020-09-24 18:18 UTC, dbchristopher commented on storybook/src/ActionList/ActionList.stories.tsx
> +
Is it possible to customize the appearance of these toggle buttons? The grey background looks like it's "off" to me, but it's actually the opposite lol

<img width="571" alt="Screen Shot 2020-09-24 at 11 15 51 AM" src="https://user-images.githubusercontent.com/238293/94183596-81b5b300-fe57-11ea-9997-2d3d8127f0ec.png">

2020-09-24 18:19 UTC, dbchristopher commented on storybook/src/ActionList/ActionList.stories.tsx
> +
I.e. Bulk is set to `true`, and isLoading is set to `false`, but it's not apparent to me by looking at those toggle switches

2020-09-24 18:20 UTC, dbchristopher commented on storybook/src/AvatarCombo.stories.tsx
> +}
Not sure if this is a new thing, but it doesn't seem like the icons are able to render in storybook. The secondaryIcon always shows up blank for me:

<img width="98" alt="Screen Shot 2020-09-24 at 11 19 56 AM" src="https://user-images.githubusercontent.com/238293/94183889-fb4da100-fe57-11ea-99bc-79e854b7d9b8.png">

2020-09-24 18:22 UTC, dbchristopher commented on storybook/src/AvatarCombo.stories.tsx
> +}
oh I get it -- it's because the `secondaryColor` and `secondaryBg` are both set to the same color:
<img width="723" alt="Screen Shot 2020-09-24 at 11 21 55 AM" src="https://user-images.githubusercontent.com/238293/94184097-410a6980-fe58-11ea-9fb9-ee0dd01d893c.png">

2020-09-24 18:32 UTC, lukelooker commented on storybook/src/ActionList/ActionList.stories.tsx
> +const Template: Story<DemoProps> = ({
This is due to the font not getting extended on onto ActionList properly. The default font in CORE application solves for this and I've solved this properly in a separate PR.

2020-09-24 18:37 UTC, dbchristopher commented on storybook/src/Tabs/Basic.stories.tsx
> +export const Template: Story<DemoProps> = ({
Is Template actually meant to show up as a sidebar option? 
<img width="215" alt="Screen Shot 2020-09-24 at 11 37 12 AM" src="https://user-images.githubusercontent.com/238293/94185566-4ec0ee80-fe5a-11ea-861e-7e45d0cd2f80.png">

2020-09-24 18:38 UTC, dbchristopher requested changes
All these controls are really cool! The code looks good. Found a few potential QA issues that might be good to resolve

2020-09-24 18:41 UTC, lukelooker commented on storybook/src/ActionList/ActionList.stories.tsx
> +
Yeah - that's "stock" storybook - I'd prefer not mess with it but I admit the rendering is less than ideal. Future improvement ;)

2020-09-24 18:42 UTC, lukelooker commented on storybook/src/AvatarCombo.stories.tsx
> +}
Oh... that's silly, LMK if I can make the defaults be less terrible

2020-09-24 22:28 UTC, lukelooker commented on storybook/src/AvatarCombo.stories.tsx
> +}
Ok, Storybook walks the JSDocs and apparently those were incorrect so it was setting silly defaults. Specifying those better as well as setting a few logical defaults in the stories where the TS Interface introspection got confused has improved things mightly!

2020-09-24 22:30 UTC, lukelooker commented on storybook/src/Tabs/Basic.stories.tsx
> +export const Template: Story<DemoProps> = ({
Nope. Definitely a mistake.

2020-09-24 22:40 UTC, lukelooker commented
@dbchristopher Ready for re-review :)

2020-09-25 16:48 UTC, dbchristopher approved these changes
Looks good! 👍 👍

2020-09-25 16:50 UTC, merged