Make Gatsby neat-o
looker-open-source/components pull request #1454
Opened 2020-09-18 08:48 UTC by lukelooker

### Action Items

- [ ] Add index-page content for /components & /foundations
- [ ] `main` column styling (limit text-character width) (@lukelooker)
- [ ] View Source link is mis-aligned

#### Storybook + Gatsby

- [ ] Storybook iframe URL needs to be dev/prod conditional
- [ ] Use `storybook` key in `frontmatter` to trigger display of Storybook / tab layout
- [ ] Correctly set iframe height (https://github.com/davidjbradshaw/iframe-resizer-react)?

### Possible Improvements

- [ ] Improve home page (better content?)
- [ ] Stretch - Description above TabList
- [ ] Loading state for iframe?

### :sparkles: Changes

- **Thank you for your contribution to Looker Components!**
- To ensure a successful review, please double check our checklist of requirements below.
- Also including a short description of changes and relevant screenshots will help us more quickly understand the ultimate goal of your work (🗑 replace this introduction with your summary of changes).

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-12-04 05:27 UTC, mdodgelooker commented
Hi folks! I tagged a lot of you as reviewers in the hopes I can get at least 2 that have some time to look over the the very long list of changes.

The good news is that there are very minimal changes in `/packages/components` so it should break anything "important". 🙃

@lukelooker I'm not sure what to do for the checklist item above "Move demos/* to storybook" so hopefully it's ok to leave that for a future PR?

2020-12-04 18:58 UTC, mdodgelooker commented
Forgot to call this: To get the Storybook iframe in the "Props & Examples" tab to work, you need to run `yarn storybook-docs` instead of `yarn storybook`. And also `yarn gatsby`. :)

2020-12-04 23:34 UTC, dbchristopher commented on packages/components/src/Spinner/SpinnerWrapper.ts
> +`
I wonder if this could be a generally useful layout component? There is nothing really specific about Spinner functionality here, so I could imagine renaming it to something more descriptive like and moving it to the layouts directory. Maybe `CenterVertically`, or `AbsoluteCenter` since centers children on both X and Y axes? Just a thought, not sure if we'd actually end up using it much

2020-12-04 23:41 UTC, dbchristopher commented on www/gatsby-config.js
> +      resolve: 'gatsby-plugin-local-search',
🙌

2020-12-04 23:59 UTC, dbchristopher requested changes
This is so great! A huge step forward all around for the documentation site. 

I'm not sure if this is a bug, but I see a link to the Theme editor in the top nav. 

<img width="380" alt="Screen_Shot_2020-12-04_at_3_46_32_PM" src="https://user-images.githubusercontent.com/238293/101226408-3d117980-3649-11eb-9255-ebf5648087b0.png">

It opens up a modal with the call to action to "Apply Theme", which would imply it's supposed to theme the gatsby site itself? Doesn't seem to do anything at the moment

<img width="724" alt="Screen Shot 2020-12-04 at 3 59 12 PM" src="https://user-images.githubusercontent.com/238293/101226555-adb89600-3649-11eb-8619-69122d7115e4.png">

2020-12-07 17:53 UTC, mdodgelooker commented on packages/components/src/Spinner/SpinnerWrapper.ts
> +`
On 2nd look I realized center alignment is super easy to accomplish with `Flex` and I agree, it's not really `Spinner`-related and probably wouldn't get used much. Delete! :)

2020-12-07 17:56 UTC, mdodgelooker commented
> It opens up a modal with the call to action to "Apply Theme", which would imply it's supposed to theme the gatsby site itself? Doesn't seem to do anything at the moment

Good catch, definitely a bug, easy fix. (Which should've been caught by lint but the types from `@looker/*` are broken in `./www`. (Which I'll see if I can fix in a separate PR.)

Ready for re-review!

2020-12-07 17:57 UTC, ElliotTheHuman approved these changes
Outside of a few docs nit picks, things look really good to me! 

That being said, I'm a bit hesitant to give a full thumbs up on my own and think getting Daniel's additional approval might be safest.

2020-12-07 17:57 UTC, ElliotTheHuman commented on www/src/documentation/components/actions/button-group.mdx
> +  <Code>ButtonGroup</Code> do not support uncontrolled versions.
```suggestion
  <Code>ButtonGroup</Code> does not support uncontrolled versions.
```

2020-12-07 17:57 UTC, ElliotTheHuman commented on www/src/documentation/components/actions/button-group.mdx
> +  <Code>ButtonGroup</Code> do not support uncontrolled versions.
nit: I could be wrong about the grammar here, but I _think_ it should be "does" (or `ButtonGroup`s)?

2020-12-07 17:57 UTC, ElliotTheHuman commented on www/src/documentation/components/actions/button-toggle.mdx
> +  <Code>ButtonToggle</Code> do not support uncontrolled versions.
Same question as `ButtonGroup`!

2020-12-07 19:46 UTC, mdodgelooker commented on www/src/documentation/components/actions/button-toggle.mdx
> +  <Code>ButtonToggle</Code> do not support uncontrolled versions.
Thanks @ElliotTheHuman , I just pushed the grammar fixes.

2020-12-07 20:24 UTC, mdodgelooker commented
@lukelooker I can't add you as reviewer b/c you're the author on this one, but let the record show I hereby request your review. 😁

2020-12-08 17:59 UTC, dbchristopher approved these changes
This all looks good to me! The theme editor is super cool 💯

2020-12-08 20:06 UTC, lukelooker reviewed
Ok - I made two minor tweaks to the PR:

1. Removed a `Button` story that was conflicting with the correct story
2. Fixed an issue where the Gatsby DOM wasn't allowing the layout component to stretch to the full viewport height.

Everything works well in develop mode. I did notice that when built the Gatsby output doesn't seem to loading the Storybook output but I think it's a minor path issue and we can solve that in a small follow-up PR but I think it's worth landing this to get it shipped :)

2020-12-08 20:30 UTC, mdodgelooker commented
> Everything works well in develop mode. I did notice that when built the Gatsby output doesn't seem to loading the Storybook output but I think it's a minor path issue and we can solve that in a small follow-up PR but I think it's worth landing this to get it shipped :)

Ah yes, this line is the culprit: https://looker.atlassian.net/browse/LENS-1416. Definitely would be good to fix that soon. Thanks!

2020-12-08 20:30 UTC, mdodgelooker approved these changes

2020-12-08 20:35 UTC, merged