Use <table> for ActionList to improve a11y / IE11
looker-open-source/components pull request #1474
Opened 2020-09-24 07:38 UTC by lukelooker

### :sparkles: Changes

- Use <table> for ActionList to improve a11y / IE11
- Remove support for "primaryKey" column type

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-11-05 00:41 UTC, lukelooker commented on packages/components/src/ActionList/ActionList.test.tsx
> -)
No longer supports `header` prop. There is no more BYO header.

2020-11-05 22:41 UTC, mdodgelooker requested changes
I'm blown away. New favorite component!

2020-11-05 22:41 UTC, mdodgelooker commented on packages/components/src/ActionList/Item/ActionListRow.tsx
> +          <ColumnType key="checkbox">
Was `key` here to get rid of a React warning? I think you might not need it anymore.

2020-11-05 22:41 UTC, mdodgelooker commented on packages/components/src/ActionList/Item/ActionListRow.tsx
> +      border-left-color: ${({ theme }) => theme.colors.key};
I know you're working on a fix here
![b83acc3f-ffe2-403e-9f17-7d146bc3069b](https://user-images.githubusercontent.com/53451193/98301676-01af5c80-1f70-11eb-842f-289304e0bf3e.gif)

2020-11-05 22:41 UTC, mdodgelooker commented on www/src/documentation/components/content/action-list.mdx
>        primaryKey: true,
Got some `primaryKey` cleanup to do in this file.

2020-11-05 22:41 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
> +
Can this use `import { filters } from '../../../__mocks__/filters'` instead?

2020-11-05 22:41 UTC, mdodgelooker commented on packages/components/src/ActionList/utils/edgeShadow.ts
> +export const edgeShadow = (placement: 'left' | 'right' = 'left', depth = 4) => {
Such cleverness!

2020-11-05 22:41 UTC, mdodgelooker commented on packages/components/src/Form/Fields/FieldInline.tsx
> +      <Truncate>{label}</Truncate>
👍

2020-11-05 22:41 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFiltersChip.tsx
>        <Chip onDelete={handleDelete} prefix={filter.field} ref={ref} {...props}>
Not related to this PR, but is there a reason the prefix wouldn't be the label?

```suggestion
      <Chip onDelete={handleDelete} prefix={filter.label} ref={ref} {...props}>
```

2020-11-05 22:50 UTC, ElliotTheHuman reviewed
So much good stuff here! 😲 

Had a few nits, but most of the changes make sense to me.

2020-11-05 22:56 UTC, lukelooker commented on packages/components/src/ActionList/ActionListTable.tsx
> +    text-align: right;
Nope - there's a `margin-left: auto` doing the job now 👍 

Removing :)

2020-11-05 22:57 UTC, lukelooker commented on packages/components/src/ActionList/Item/ActionListCheckbox.tsx
> +    event.keyCode === 13 && event.currentTarget.click()
👍

2020-11-05 22:58 UTC, lukelooker commented on packages/components/src/ActionList/ActionList.test.tsx
> +      fireEvent.click(listItemButton[0])
👍

2020-11-05 23:00 UTC, lukelooker commented on packages/components/src/ActionList/Column/columnSize.ts
> +})
"auto" is just "do what a table cell usually does" so no styles are applied in that case. It's admittedly a little weird but I wanted to give clarity to of "auto" (things will _just happen_) vs. carefully made decisions here.

2020-11-05 23:34 UTC, lukelooker commented on packages/components/src/ActionList/Filters/ColumnSelector.test.tsx
> +  })
Whoops. Good catch :)

2020-11-05 23:38 UTC, lukelooker commented on packages/components/src/ActionList/Item/ActionListRow.tsx
>    supportsRaised?: boolean
Good point. Removing.

2020-11-05 23:40 UTC, lukelooker commented on www/src/documentation/components/content/action-list.mdx
>        primaryKey: true,
Done! :)

2020-11-05 23:42 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFiltersChip.tsx
>        <Chip onDelete={handleDelete} prefix={filter.field} ref={ref} {...props}>
That was per the original design – I suspect we might need to get even more specific and have a `filter.prefix` so that the specifier can be super-specific.

2020-11-05 23:50 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
> +
Yep! Fixed :)

2020-11-05 23:54 UTC, lukelooker commented on packages/components/src/ActionList/Item/ActionListRow.tsx
> +          <ColumnType key="checkbox">
Removed. :)

2020-11-05 23:54 UTC, lukelooker commented on packages/components/src/ActionList/Item/ActionListRow.tsx
> +      border-left-color: ${({ theme }) => theme.colors.key};
This should be fixed on the latest version :)

2020-11-06 00:21 UTC, lukelooker commented on packages/components/src/ActionList/Item/ActionListItem.tsx
> +    <ItemTarget style={{ marginLeft: 'auto' }} onClick={handleMenuClick}>
I have future thoughts about `ItemTarget` (it might get used within `List` so I'd like to keep it simple for now) so I went ahead and moved this to the `ActionListTable` styles.

2020-11-06 01:05 UTC, lukelooker commented on packages/components/src/ActionList/ActionList.tsx
> +  )
Good point. I went ahead and refactored a bit with more explicit names and added some comments to clarify the use of each:

```tsx
  /**
   * Extract columns that the user can specify visibility on
   */
  const columnsVisibleDefault = columns
    .filter((c) => c.hide === false)
    .map((c) => c.id)

  /**
   * An array of column IDs that should be displayed to the user
   */
  const [columnsVisible, setColumnsVisible] = useState(columnsVisibleDefault)

  /**
   * Array in which each entry represents the visibility status of every available column
   * NOTE: Columns with `hide===undefined` are always visible
   */
  const columnsDisplayState = columns.map(
    (c) => c.hide === undefined || columnsVisible.includes(c.id)
  )
```

2020-11-06 04:33 UTC, mdodgelooker approved these changes
LGTM!

2020-11-06 04:33 UTC, mdodgelooker commented on packages/components/src/utils/useIsTruncated.ts
> +  }, [handleResize, element, identity])
That'll do it :)

2020-11-06 04:45 UTC, merged