Lara/actin list filter second layer filter
looker-open-source/components pull request #1476
Opened 2020-09-24 20:29 UTC by laraharrow

### :sparkles: Changes

- **Thank you for your contribution to Looker Components!**
- To ensure a successful review, please double check our checklist of requirements below.
- Also including a short description of changes and relevant screenshots will help us more quickly understand the ultimate goal of your work (🗑 replace this introduction with your summary of changes).

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-10-05 16:51 UTC, lukelooker submitted a review, later dismissed
Ran into some issues testing this:

- [x] Deleting an existing Chip causes component to crash `Cannot read property 'options' of undefined`
- [x] When adding a value, after choosing it I can't remove it without choosing a value (user should be able to "click away" from popover and have DraftFilter just disappear
- [ ] Draft label appears the font size is a bit larger than when typing in the `Select`'s `InputText`

![image](https://user-images.githubusercontent.com/34253496/95108564-4b4a2480-06f0-11eb-87d7-19175041cb3d.png)


TODO

- [ ] Make it possible to select several values (use ButtonToggle)
  - Popover should only close when user clicks the Chip itself or anywhere "outside" of the Popover
- [ ] Needs test coverage :)

2020-10-05 17:37 UTC, laraharrow commented
-[ ] Deleting an existing Chip causes component to crash Cannot read property 'options' of undefined
    - This will only happen if you use the old example code because he had the data come in hard coded in a way that doesn't work with the new logic.
    - But there is an error on the console: 
``` 
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Popover (at DraftFilter.tsx:44)
    in DraftFilter (at InputFilters.tsx:129)
``` 

- [ ] When adding a value, after choosing it I can't remove it without choosing a value (user should be able to "click away" from popover and have DraftFilter just disappear
    - 
TODO

- [ ] Draft label appears the font size is a bit larger than when typing in the Select's InputText
- [ ] Make it possible to select several values (use ButtonToggle)
 - Popover should only close when user clicks the Chip itself or anywhere "outside" of the Popover
 - [ ] Needs test coverage :)

2020-10-12 02:36 UTC, lukelooker reviewed
Comments and tweaks in-line. I'd like to see a few more tests:

- [x] Add new filter
- [x] Change filter
- [x] Remove filter single filter
- [x] Remove all filters (have at least two set(

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilterChip.test.tsx
> +describe('InputFilters', () => {
```suggestion
describe('InputFilterChip', () => {
```

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilterChip.test.tsx
> +  test('renders InputFilterChip', () => {
```suggestion
  test('renders', () => {
```

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilterChip.test.tsx
> +  test('InputFilterChip onchange', () => {
```suggestion
  test('onClick', () => {
```

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilterChip.test.tsx
> +  const onDelete = jest.fn()
Probably good to move these inside the specific test they're used within.

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/FilterEditor.tsx
> +export const FilterEditor: FC<FilterEditorProps> = ({
Let's go ahead and call this `InputFiltersChipEditor` to keep it name-spaced on "top" of `InputFilters`

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.story.tsx
> +  filters: filters,
```suggestion
  ...Basic.args,
```

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.story.tsx
>  ]
Pull this out into it's own file `sampleInputFilters.ts`

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
>    ]
Import this from `sampleInputFilters.ts`

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
> +  test('renders InputFilters', () => {
```suggestion
  test('renders', () => {
```

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
> +  test('InputFilter displays list of filters', () => {
```suggestion
  test('Display list of filters', () => {
```

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
> +  test('InputFilter filter clicked gets displayed ', () => {
```suggestion
  test('Clicking filter list displays list of filters ', () => {
```

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
> +  test('InputFilter shows editing options ', () => {
```suggestion
  test('Shows editing options ', () => {
```

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
> +  test('InputFilter shows chip with full filter selected ', () => {
```suggestion
  test('Shows chip with full filter selected ', () => {
```

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
> +  test('InputFilter doest show filter displayed as chip', () => {
```suggestion
  test("Doesn't show filter displayed as chip", () => {
```

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
> +    fireEvent.click(getByText('user'))
I'm wondering why this line is needed?

2020-10-12 02:36 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
> +    expect(queryByText('role')).not.toBeInTheDocument()
```suggestion
    expect(queryByText('role:')).not.toBeInTheDocument()
```

2020-10-12 02:36 UTC, lukelooker commented on storybook/src/ActionList/data.ts
>  ]
Import this from the `sampleFilters.ts` file as well :)

2020-10-12 17:47 UTC, laraharrow commented on packages/components/src/Form/Inputs/InputFilters/InputFilterChip.test.tsx
> +  const onDelete = jest.fn()
I'll do it to onClick, onDelete is required so it will be needed in all tests.

2020-10-12 18:23 UTC, laraharrow commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
> +    fireEvent.click(getByText('user'))
we need to click on those to trigger the new list display.

2020-10-12 18:26 UTC, laraharrow commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
> +    expect(queryByText('role')).not.toBeInTheDocument()
at this point the `role:` should be in displayed, that would be the value inside the chop. I'm looking for the `role` value inside the first list of filter and since `role` is now displayed in a chip it should be out of the first list.

2020-10-12 18:30 UTC, laraharrow commented on storybook/src/ActionList/data.ts
>  ]
I did but this is how it looks fyi: 
`import { filters } from '../../../packages/components/src/Form/Inputs/InputFilters/sampleInputFilters'`

2020-10-14 21:36 UTC, mdodgelooker requested changes
This is cool stuff! I added some comments / suggestions here, but I also created a branch to show how `InputFilters` can be converted to a controlled component for use in `ActionList` and elsewhere (this branch includes my other suggestions as well):
https://github.com/looker-open-source/components/pull/1568
* Filter the `Select` as the user types
* Change `InputFilters` to a controlled component (otherwise the changes from the user can't be applied in `ActionList` or wherever else this component may be used
* Simplify the use of `ButtonGroup`

2020-10-14 21:36 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFiltersChipEditor.tsx
> +    <PopoverContent p="large" width="360px">
Could this be `maxWidth` instead? It looks a bit odd when the buttons don't fill the space 
```suggestion
    <PopoverContent p="large" maxWidth="360px">
```
![image](https://user-images.githubusercontent.com/53451193/96046304-1e042180-0e28-11eb-8b37-8348a5367450.png)

2020-10-14 21:36 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFiltersChipEditor.tsx
> +  }
This could be simplified a bit, along with the suggestion change to `ButtonGroup` below
```suggestion
  const handleChange = (newValues: string[]) => {
    onChange(newValues.sort().join(', '))
  }
```

2020-10-14 21:36 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFiltersChipEditor.tsx
> +        </ButtonGroup>
`ButtonGroup` can take options:

```suggestion
        {options && (
          <ButtonGroup
            value={defaultValue ? defaultValue.split(', ') : []}
            options={options.map((value) => ({ label: value, value }))}
            onChange={handleChange}
          />
        )}
```

2020-10-15 06:11 UTC, mdodgelooker requested changes
Noticed a few more small things (one of which is my bad). :)

2020-10-15 06:11 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
>    const [filterLookupName, setFilterLookupName] = useState('')
I think you can remove this `useState` and the various places `setFilterLookupName` is called, since it's only used on the `Select` but the `Select` actually isn't rendered whenever this has a value.
```suggestion
```

2020-10-15 06:11 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +  )
My bad, my previous suggestion resulted in a funky behavior where the filter tokens would end up in their "original" order, instead of the order the user selects them. This change should fix that:
```suggestion
  const assignedFilters = filters
    .filter((filter) => filter.value || filter.field === fieldEditing)
    .sort((a, b) =>
      a.value === undefined ? 1 : b.value === undefined ? -1 : 0
    )
```

2020-10-15 06:11 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
>      setFilterLookupName('')
```suggestion
```
(See above)

2020-10-15 06:11 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
>        setFilterLookupName('')
```suggestion
```
(See above)

2020-10-15 06:11 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +          const filterIndex = filters.findIndex(
Another fix for the funky filter token order my previous suggestion caused:
```suggestion
          const filterIndex = assignedFilters.findIndex(
```

2020-10-15 06:11 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +          const newFilters = [...filters]
Last funky filter order fix:
```suggestion
          const newFilters = [...assignedFilters, ...unassignedFilters]
```

2020-10-15 06:11 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
>            autoResize
I think `openOnFocus` would be a nice feature for the user – they'll see the options list open when they click anywhere in the input.
```suggestion
          autoResize
          openOnFocus
```

2020-10-15 19:18 UTC, mdodgelooker approved these changes
LGTM! Awesome work 👍

2020-10-16 15:34 UTC, merged