Add visual snapshots for MenuItem and MenuGroup
looker-open-source/components pull request #1503
Opened 2020-10-02 20:37 UTC by jhardy

### :sparkles: Changes

Adds visual snap shots for Menu Items and Menu Groups

### :white_check_mark: Requirements

- [x] Includes test coverage for all changes
- [x] Build and tests are passing
- [ ] Update documentation
- [x] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-10-05 05:43 UTC, lukelooker requested changes
The coverage looks great – I'd just like to heavily leverage the Storybook "args" and Controls pattern more heavily here.

2020-10-05 05:43 UTC, lukelooker commented on packages/components/src/Menu/MenuGroup.story.tsx
> +  children: MenuListExample,
```suggestion
  ...Basic.args,
```

2020-10-05 05:43 UTC, lukelooker commented on packages/components/src/Menu/MenuGroup.story.tsx
> +CompactMenuGroupExample.args = {
```suggestion
export const Compact = ListTemplate.bind({})
Compact.args = {
```

2020-10-05 05:43 UTC, lukelooker commented on packages/components/src/Menu/MenuGroup.story.tsx
> +MenuGroupExample.args = {
There's a convention (admittedly loose at this point) to name the initial example `Basic` (see `Button*` stories for this)

```suggestion
export const Basic = ListTemplate.bind({})
Basic.args = {
```

2020-10-05 05:43 UTC, lukelooker commented on packages/components/src/Menu/MenuItem.story.tsx
> +const ListTemplate: Story<MenuListProps> = (args) => <MenuList {...args} />
I _think_ this should be `MenuItem` here instead:

```suggestion
const Template: Story<MenuItemProps> = (args) => <MenuItem {...args} />
```

2020-10-05 05:43 UTC, lukelooker commented on packages/components/src/Menu/MenuItem.story.tsx
> +}
```suggestion
export const Basic = Template.bind({})
SingleMenuItem.args = {
  children: "Menu Item"
}
```

2020-10-05 05:43 UTC, lukelooker commented on packages/components/src/Menu/MenuItem.story.tsx
> +}
```suggestion
export const Icon = Template.bind({})
Template.args = {
  ...Basic.args,
  icon: 'User'
}
```

2020-10-05 05:43 UTC, lukelooker commented on packages/components/src/Menu/MenuItem.story.tsx
> +
These rest of these should repeat pattern above. You can keep extending args to create more complex examples and this will allow for storybook users to see the args in use via the "Controls" add-on UI.

2020-10-05 20:35 UTC, jhardy commented on packages/components/src/Menu/MenuGroup.story.tsx
> +  children: MenuListExample,
extending basic here kept failing so just passed in children again

2020-10-05 20:36 UTC, jhardy commented on packages/components/src/Menu/MenuItem.story.tsx
> +
Rending outside of a `<MenuList />` kept inserting a `•` bullet in the visual snapshots

2020-10-05 20:37 UTC, jhardy commented on packages/components/src/Menu/MenuItem.story.tsx
> +}
I tried extending like
```
IconAndDetail.args = {
...Icon,
detail: 'A Detail'
}
```

but it would not render all the pieces of the component, so had to keep extending `Basic` for all of these
not sure if I was doing something wrong.

2020-10-06 00:55 UTC, lukelooker approved these changes
I just pushed updates to these tests in this PR. 

Generally we want to keep tests narrowly focused on the component that we're looking at so that changes from outside don't cause unexpected issues.

2020-10-06 00:55 UTC, lukelooker commented on packages/components/src/Menu/MenuItem.story.tsx
> +
Fixed by applying `list-style-type: none;` within `MenuItem`

2020-10-06 00:55 UTC, lukelooker commented on packages/components/src/Menu/MenuGroup.story.tsx
> +}
Lets Storybook expose these as toggles to allow for easy action.

2020-10-06 00:55 UTC, lukelooker commented on packages/components/src/Menu/MenuGroup.story.tsx
> +}
Because the MenuContext doesn't expect for `Icons` to disappear from MenuItems this the `icons: false` only collapses the icon gutter space when the template is loaded with this prop from the get-go.

2020-10-06 15:27 UTC, merged