InputFilter to support multiline filter tokens
looker-open-source/components pull request #1574
Opened 2020-10-16 16:55 UTC by laraharrow

### :sparkles: Changes

- InputFilter to support multiline filter tokens

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

<img width="1354" alt="Screen Shot 2020-10-16 at 9 55 34 AM" src="https://user-images.githubusercontent.com/23616264/96286781-c388d380-0f95-11eb-8b49-6ddea54ed858.png">

2020-10-19 05:47 UTC, mdodgelooker requested changes
This looks good! My only feedback would be to avoid the extra div around each `Chip` by deleting `max-width` in `Chip.tsx`, which should be fine to do. And then just a few small tweaks to match the styling of `InputChips` a little closer.

2020-10-19 05:47 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +  padding-top: ${({ theme: { space } }) => `${space.xsmall}`};
With the removal of the `div` around the `Chip` you'll also need to change the padding here and add `lineHeight="xlarge"` to the `Text`.

```suggestion
  padding: ${({ theme: { space } }) => `${space.xxxsmall} ${space.xxsmall}`}
```

2020-10-19 05:47 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
>    }
With `max-width` removed from `Chip.tsx`, this can also be removed.

2020-10-19 05:47 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +          mt="xxsmall"
Slight change to the margin here, and also add `mt="xxxsmall"` to the filter `Icon` above.
```suggestion
          mt="xxxsmall"
```

2020-10-19 05:47 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +    margin-top: ${({ theme: { space } }) => `-${space.xxsmall}`};
```suggestion
```

2020-10-19 05:47 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFiltersChip.tsx
> +      </div>
I think it should be no problem to remove `max-width` over on `Chip.tsx` and then you can avoid the extra `div` here, which would be good.

```suggestion
        <Chip
          onDelete={handleDelete}
          prefix={filter.field}
          ref={ref}
          {...props}
        >
          {filter.value}
        </Chip>
```

2020-10-20 06:32 UTC, mdodgelooker requested changes
Hi, just noticed a few more super minor things.

2020-10-20 06:32 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +    display: inline;
This can be removed now.

2020-10-20 06:32 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
>    padding: ${({ theme: { space } }) => `${space.xxxsmall} ${space.xxsmall}`};
```suggestion
  padding: ${({ theme: { space } }) => space.xxsmall};
```

2020-10-20 06:32 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
> +    gap: ${({ theme }) => theme.space.xsmall};
```suggestion
    gap: ${({ theme }) => theme.space.xxsmall};
```

2020-10-20 17:07 UTC, dbchristopher approved these changes
this looks great!

2020-10-20 17:09 UTC, merged