Dialog improvements (animation, remove backdrop customization)
looker-open-source/components pull request #1577
Opened 2020-10-16 21:12 UTC by lukelooker

### :sparkles: Changes

- `useDialog` (`Dialog` & `Drawer`) refactored
  - Removed use of `react-transition-group` dependency
  - Added support for `aria-busy`
  - Simplified implementation of `DialogRender` component

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [x] Build and tests are passing
- [ ] Update documentation
- [x] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [x] Checked for a11y impacts
- [x] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [x] PR is ideally < ~400LOC

### :camera: Screenshots

2020-10-18 23:46 UTC, mdodgelooker requested changes
I LOVE this!! Two teensy nits.

2020-10-18 23:46 UTC, mdodgelooker commented on packages/components/src/Dialog/Backdrop.tsx
> +export const Backdrop = styled.div.attrs(() => ({
I think you can just pass the object instead of a callback:
```suggestion
export const Backdrop = styled.div.attrs({
```

2020-10-18 23:46 UTC, mdodgelooker commented on packages/components/src/Dialog/Backdrop.tsx
> +}))`
```suggestion
})`
```

2020-10-18 23:46 UTC, mdodgelooker commented on packages/components/src/Dialog/DialogSurface.tsx
> +  transform: none; */
Delete?

2020-10-19 06:37 UTC, lukelooker commented on packages/components/src/Dialog/Backdrop.tsx
> +export const Backdrop = styled.div.attrs(() => ({
In v5 of Styled Components the sybfunction form is removed (it's deprecated but supported in v4):

https://styled-components.com/docs/faqs 

> Note: The subfunction object-form .attrs({ prop: props => {} }) syntax that was deprecated in v4 is removed in v5. Use function-form attrs instead .attrs(props => ({})) (you should have been seeing console warnings to make this update ahead of time.)

2020-10-19 06:47 UTC, lukelooker commented on packages/components/src/Dialog/DialogSurface.tsx
> +  transform: none; */
Done! :)

2020-10-19 13:30 UTC, mdodgelooker approved these changes

2020-10-19 15:31 UTC, merged