Update InputFilter for value formatting and custom editing
looker-open-source/components pull request #1595
Opened 2020-10-20 23:18 UTC by laraharrow

### :sparkles: Changes

- InputFiltersChipEditor can use CheckboxGroup or RadioGroup.
- InputFiltersChipEditor can be replaced by users editor.

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-10-21 20:04 UTC, laraharrow commented
TODO:
- [ ] draft filter text before becomes a `Chip` needs margin left
- [ ] popover is moving when draft filter text converts to a `Chip`
- [ ] spacing on `Chip` when the closing `Icon` doesn't fit in the screen

2020-10-23 05:36 UTC, lukelooker approved these changes
Reviewed and made a few minor tweaks in a commit I added:

- Remove `inline-table` CSS assignment (didn't appear to be doing anything functional and in-general we avoid using `table` layout types.
- Switched interface for editor prop to use Render Props pattern
- Added autoFocus to search field example

2020-10-23 16:57 UTC, lukelooker approved these changes

2020-10-23 16:57 UTC, lukelooker requested changes
hold please. Needs changelog updates at 0.9.20 has been cut

2020-10-23 16:57 UTC, merged