Select fixes
looker-open-source/components pull request #1597
Opened 2020-10-21 22:15 UTC by mdodgelooker

### :sparkles: Changes

- Fixed: With the Mac touchpad "tap to click" setting enabled, clicking on an option closes & immediately re-opens the list https://looker.atlassian.net/browse/LENS-1249
- Fixed: IE11 can't select option via click https://looker.atlassian.net/browse/LENS-1231
- Fixed: Controlled `Select` losing focus if re-rendered between input blur due to clicking option & value prop update https://looker.atlassian.net/browse/LENS-1284
- Fixed: With windowed options (> 100) and `isFilterable`, deleting input value (filter term) results in incorrect "No options" message https://looker.atlassian.net/browse/LENS-1245

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-10-27 20:09 UTC, mdodgelooker commented on CHANGELOG.md
> -
Noticed this was in the wrong spot during a conflict merge.

2020-10-27 20:10 UTC, mdodgelooker commented on packages/components/src/Form/Fields/FieldSelect/FieldSelect.story.tsx
> +export const DelayUpdate = () => {
Example showing fix for issue #2

2020-10-27 20:29 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/ComboboxMultiInput.tsx
> +    }, [controlledInputValue])
This is a bit of code , tangentially related to the changes above, for handling a controlled `inputValue` (as opposed to `values`, a.k.a. the `Chip`s) that I realized was 1) completely broken, but 2) not being used in `SelectMulti`, which is the only implementation of this component (that I know of).

I had some indecision over whether to fix it or just remove the ability to control `inputValue`. I decided to fix it in the end, since I know implementations of `Combobox` will only get more complex. I could see an email address input needing to control the `inputValue`, for example.
Broken: https://codesandbox.io/s/epic-bush-g3lvl
Fixed: `:3333/?path=/story/combobox--controlled-input-value`

2020-10-27 20:49 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/utils/state.ts
> +  }
This was the fix for the 2nd issue, where a controlled `Select` with any delay b/t `onChange` and an updated `value` was losing focus when clicking an option. This was because the mismatch between the prop `value` and the value from context was triggering a `SELECT_SILENT` – to sync the latter to the former – and the `useFocusManagement` hook that returns focus to the input after a click on an option, is looking for the `lastActionType` to be `SELECT_WITH_CLICK`.

Excluding "SILENT" action types here feels like the right move – they're used only to sync context state to controlled props, not to trigger interactive behavior in the component.

2020-10-27 21:41 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/utils/state.ts
> +    const currentState = stateChart.states[stateRef.current]
Removing the `requestAnimationFrame` delay in `useBlur` to fix the "tap to click" bug caused a bug where the list would fail to close on blur for a `SelectMulti` with `freeInput`. This was caught by "creates value and closes list on blur" in `SelectMulti.test.tsx`! 🎉

2020-10-28 04:47 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/utils/state.ts
> +  const stateRef = useRef(stateChart.initial)
Removing the `requestAnimationFrame` delay in `useBlur` to fix the "tap to click" bug caused a different bug where the list would fail to close on blur for a `SelectMulti` with `freeInput`. 

The issue was that `transition` is called with `BLUR` action, then immediately with `CHANGE_VALUES` action due to the tokenization of the input value on blur. Previously, the `requestAnimationFrame` in `useBlur` put the `BLUR` transition in the next cycle _after_ `CHANGE_VALUES`. 

Because `useState` [batches updates](https://stackoverflow.com/questions/53048495/does-react-batch-state-update-functions-when-using-hooks), the state update from `SUGGESTING` to `IDLE` from the `BLUR` action "loses" to the `CHANGE_VALUES` action, which keeps the state as `SUGGESTING`. Using a ref to capture the intermediate change to `IDLE` gets around this issue.

2020-10-28 04:51 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputChips/InputChips.tsx
> +      event?: FormEvent<HTMLInputElement>
Adding the event here so `ComboboxMultiInput` can distinguish between changes directly from the user typing and "side-effect" changes, like the input value reverting to empty after a value is entered.

2020-10-28 04:53 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputProps.ts
> +  'aria-activedescendant',
Adding this to the list of attributes that get passed down to the inner input as opposed to the wrapper div fixes the screen reader issue.

2020-10-28 04:54 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Select/SelectMulti.test.tsx
> +      screen.getByText('A random button').focus()
This test needed some adjustments after removing the `requestAnimationFrame` in `useBlur`.

2020-10-28 04:59 UTC, mdodgelooker commented
@lukelooker & @dbchristopher this is finally ready for review. The bulk of the changes are for the 1st issue – the "tap to click" re-opening the list – and it's pretty convoluted. Let me know if you'd like chat about it for more clarity. Thank you! 🙏

2020-10-28 16:01 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/utils/useBlur.ts
> +      }
Fixes the tap-to-click list re-opening bug because with tap-to-click there is no delay between blur & click.

With a traditional mouse click there's a tiny delay after blur & before click, so that even with the `requestAnimationFrame`, the `SELECT_WITH_CLICK` action (closes the list) was still coming after the `INTERACT` action (keeps the list open). With tap-to-click, the `requestAnimationFrame` causes `INTERACT` to come after `SELECT_WITH_CLICK`, thus closing then re-opening the list.

The `requestAnimationFrame` was originally in here b/c the `focusInList` check was looking at `document.activeElement`, which gets updated _after_ the blur event. This is no longer the case with `getNextFocusTarget`.

The other thing it was doing was in `SelectMulti` with `freeInput`, making sure the `BLUR` action came after the `CHANGE_VALUES` action that is triggered when the input value gets tokenized on blur. This was tricky to fix but you'll read more about it in my other comments. :)

2020-10-29 17:33 UTC, dbchristopher commented on packages/components/src/Form/Inputs/Combobox/ComboboxMultiInput.tsx
> +        isInputting.current = event !== undefined
smart

2020-10-29 17:37 UTC, dbchristopher commented on packages/components/src/Form/Inputs/Combobox/stories/Combobox.story.tsx
> +}
I think there's a weird bug here I don't quite understand. It seems like once I clear the list, and then add an option again, the "Change Input Value" button no longer works

![combobox-bug](https://user-images.githubusercontent.com/238293/97610893-b545a900-19d2-11eb-91c3-ca1eca3f58cc.gif)

2020-10-29 17:45 UTC, dbchristopher commented on packages/components/src/Form/Inputs/Combobox/utils/state.ts
> +  }
yeah that makes sense to me!

2020-10-29 17:53 UTC, dbchristopher requested changes
Wow, this is some really epic sleuthing and debugging. This component is so dang complicated! I have no feedback on the code changes, but it seems like that controlled combobox bug should probably be looked into before merging. 

But of course, this generally seems _better_ than the current combobox in significant ways, so I'm happy to merge as-is and revisit that issue later if you want

2020-10-30 18:21 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/stories/Combobox.story.tsx
> +}
Great catch! Got a fix in the works now...

2020-10-30 19:59 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/stories/Combobox.story.tsx
> +}
@dbchristopher the issue was that the `inputValue` in `ComboboxContext` changes to `''` when a new option is selected, but `onInputChange` wasn't getting called, so the controlled input value was still on `'bananas'` even though the input showed an empty value. Then clicking the button did nothing b/c it wasn't actually changing the state value (it was already `'bananas'`).

`onInputChange` _should_ be called with the input value is reset to `''` due to an option being selected. I made some updates so that this does happen now, and actually I was able to remove a couple lines of code in `SelectMulti.tsx` as a result. 👍 Thanks again for catching this.

2020-10-30 22:33 UTC, dbchristopher approved these changes
Awesome, I'm glad you were able to get that dialed in!! It all looks great 👍 👍

2020-10-30 23:13 UTC, merged