Select: options-related fixes
looker-open-source/components pull request #1618
Opened 2020-10-26 21:00 UTC by mdodgelooker

### :sparkles: Changes

1. Fixed `Select` alignment of options when some have icons and others do not.
2. `Select` inappropriately shows "No options" when the current value is empty, after filtering a long list down to a single option then deleting the filter text. (Test with the 2nd Select on :3333/?path=/story/fieldselect--select-content)
3. Fixed `Select` remounting its options when the options prop changes due to this fix for a different issue: https://github.com/looker-open-source/components/pull/1240. This causes select via click to fail if the options prop "changes" (same values, new array instance) after a mousedown, e.g. if a parent component contains `usePopover`. (Test with the Open Popover button on :3333/?path=/story/fieldselect--select-demo)

### :white_check_mark: Requirements

- [x] Includes test coverage for all changes (except #3, which I wasn't able to simulate in RTL)
- [x] Build and tests are passing
- [ ] Update documentation
- [x] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [x] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots
#### Issue #1 Before
<img width="250" alt="Screen Shot 2020-10-26 at 1 44 30 PM" src="https://user-images.githubusercontent.com/53451193/97227805-3d3d7000-1793-11eb-93c6-d4f7454a4e35.png">
#### Issue #1 After
<img width="248" alt="Screen Shot 2020-10-26 at 1 47 08 PM" src="https://user-images.githubusercontent.com/53451193/97227756-2d259080-1793-11eb-8977-2fe20ea585b5.png">
#### Issue #2 Before
![2e00cb9a-09d5-4e76-9b62-4194ddfae0e0](https://user-images.githubusercontent.com/53451193/97227915-652cd380-1793-11eb-8ad6-5433bfeceda3.gif)
#### Issue #2 After
![772cfcc2-972e-4f12-9e53-a621a4e617bc](https://user-images.githubusercontent.com/53451193/97227910-6231e300-1793-11eb-8a1d-b4e1a3af5f5d.gif)
#### Issue #3 Before
![d8ed5024-c49c-4897-80ae-6390d070c05d](https://user-images.githubusercontent.com/53451193/97227971-7970d080-1793-11eb-8989-14f4565a328c.gif)
#### Issue #3 After
![fa86b795-3b88-4a08-8ef5-beb36bbe7683](https://user-images.githubusercontent.com/53451193/97228006-87265600-1793-11eb-9407-db34183f9a8b.gif)

2020-10-26 21:14 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Select/SelectOptions.tsx
> +import { IconPlaceholder, ListItemDetail, ListItem } from '../../../List'
Moved `IconPlaceholder` into `/List` from `MenuItem`. More commonality for list-based components! 🎉

2020-10-26 21:14 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Select/SelectOptions.tsx
> +      <ComboboxOption {...rest} py="xxsmall" scrollIntoView={scrollIntoView}>
No longer need a `key` here since I made this a component instead just a function, so that `useContext` would work (the `key` still gets used in `SelectOptions`).

2020-10-26 21:14 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Select/SelectOptions.tsx
> -}
This was the culprit for the overly sensitive options unmount/remount. It was to fix a bug with windowed options + filtering, but the change below (with `useID` and the option length) fixes that issue just as well.

2020-10-26 21:14 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Select/utils/useWindowedOptions.tsx
> +      }
This was the fix for the "No options" but. With an empty value, the `navigationOption` is defined as `{value: ''}` but doesn't match any of the actual options, so the `selectedIndex` is -1, and when starting and ending the options window with -1, you're not gonna get much. 😜

2020-10-26 21:14 UTC, mdodgelooker commented on packages/components/src/List/IconPlaceholder.tsx
> +/*
Moved here from `MenuItem.tsx` in order to share more between list-like components.

2020-10-26 21:39 UTC, lukelooker requested changes
Need to remove react-docgen override but otherwise this looks great. Tested in a bunch of different ways and I wasn't able to see anything amiss the identified problems appear to be gone. :)

2020-10-26 21:39 UTC, lukelooker commented on packages/storybook-config/src/main.js
> +  },
This should get removed as it will break the `storybookMode` logic. We could def look at making a CLI flag to enable `fast` if needed.

2020-10-26 21:42 UTC, mdodgelooker commented on packages/storybook-config/src/main.js
> +  },
Whoops how did that get in there. Thanks!

2020-10-26 21:45 UTC, lukelooker approved these changes

2020-10-26 22:37 UTC, lukelooker commented
Had a build error - I've seen this once or twice before. TS can't infer the type so it requires explicitly specifying the return type to make everything happy.

2020-10-27 04:02 UTC, lukelooker approved these changes
LGTM

2020-10-27 04:19 UTC, merged