Elliot/field checkbox group error state
looker-open-source/components pull request #1622
Opened 2020-10-29 22:57 UTC by ElliotTheHuman

### :sparkles: Changes

- Added `inputTextValidation` css styling to `FieldCheckboxGroup`'s child checkboxes (when `validationMessage.type` === 'error')
- Note: We don't currently have a story for this, so added an example in playground. I think adding a story (and a snapshot test) would make sense here but wanted to get a second opinion before including in this PR!

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots
![Screen Shot 2020-10-29 at 3 55 45 PM](https://user-images.githubusercontent.com/16812885/97641029-3a46b780-19ff-11eb-91af-6f3d5d5b526c.png)

2020-10-30 17:18 UTC, dbchristopher submitted a review, later dismissed
Nice work on the initial draft here! I think it will ultimately be best to take a more direct approach on styling the checkbox though. I left a comment on the Field.tsx changes, let me know if that makes sense at all.

And yeah I think this is totally worth getting some snapshot coverage on FieldCheckboxGroup! It's probably worth moving the entire CheckboxGroup.stories.tsx over to be snapshottable (not sure the right word there lol)

2020-10-30 18:04 UTC, ElliotTheHuman commented on packages/components/src/Form/Fields/Field.tsx
> +  }
I think that makes sense! In retrospect, it seems much cleaner to just make sure the `validationMessage` prop value gets passed down to the internal `CheckboxGroup` rather than doing the style overriding 🤦 

Changes coming in soon!

2020-10-30 20:05 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputText/InputText.tsx
> +    (props.validationMessage && props.validationMessage.type === 'error')
Resolved!

2020-10-30 20:07 UTC, ElliotTheHuman commented on packages/components/src/Form/Fields/Field.tsx
> +  }
Changes are in! Also wanted to note that I implemented Meredith's suggestion of changing the `OptionsGroup`  interface used by `CheckboxGroup` to have `validationType` instead of `validationMessage`. 

Ultimately, `CheckboxGroup` only needs the validation type since the actual validation message text is handled by the internal `Field` element within `FieldCheckboxGroup`, so it made sense to me to only pass the type down from `FieldCheckboxGroup` to `CheckboxGroup`.

2020-10-30 20:08 UTC, ElliotTheHuman commented on packages/components/src/Form/Fields/Field.tsx
> +  }
I liked this suggestions since `CheckboxGroup` only really needed the validation type to affect child `Checkbox` styling. Resolved in 3d885a4!

2020-11-04 17:39 UTC, mdodgelooker requested changes
This looks great! And 👍 on moving the stories and getting them snapshotted. Just a tiny nit in the story file.

2020-11-04 17:39 UTC, mdodgelooker commented on packages/components/src/Form/Fields/FieldCheckboxGroup/FieldCheckboxGroup.story.tsx
>    title: 'Forms/CheckboxGroup',
We've been flattening the navigation as we move stories over to `/packages/components`:
```suggestion
  title: 'CheckboxGroup',
```

2020-11-04 17:48 UTC, ElliotTheHuman commented on packages/components/src/Form/Fields/FieldCheckboxGroup/FieldCheckboxGroup.story.tsx
>    title: 'Forms/CheckboxGroup',
Noted! Resolved in c6191cb.

2020-11-04 17:50 UTC, mdodgelooker approved these changes
🛳!

2020-11-04 18:45 UTC, mdodgelooker approved these changes

2020-11-04 18:51 UTC, merged