first commit
looker-open-source/components pull request #1643
Opened 2020-11-09 19:37 UTC by laraharrow

### :sparkles: Changes

- **Thank you for your contribution to Looker Components!**
- To ensure a successful review, please double check our checklist of requirements below.
- Also including a short description of changes and relevant screenshots will help us more quickly understand the ultimate goal of your work (🗑 replace this introduction with your summary of changes).

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-11-10 01:39 UTC, dbchristopher commented on packages/components/src/DataTable/Item/DataTableRow.tsx
> +        : onClick && onClick(event)
Oh wow, this is way better. TS for the win!

2020-11-10 03:15 UTC, lukelooker requested changes
Awesome! Can you update the PR title to describe the work here and look at adding a test that validates this (mostly so it doesn't break in the future) :)

2020-11-10 17:30 UTC, laraharrow commented on packages/components/src/DataTable/Item/DataTableRow.tsx
> +        : onClick && onClick(event)
🤩 Thanks @lukelooker for the suggestion!

2020-11-11 08:02 UTC, lukelooker approved these changes
LGTM

2020-11-11 08:02 UTC, merged