Focus trap refactor
looker-open-source/components pull request #1644
Opened 2020-11-09 22:52 UTC by mdodgelooker

### :sparkles: Changes

- **Thank you for your contribution to Looker Components!**
- To ensure a successful review, please double check our checklist of requirements below.
- Also including a short description of changes and relevant screenshots will help us more quickly understand the ultimate goal of your work (🗑 replace this introduction with your summary of changes).

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-11-09 23:18 UTC, mdodgelooker commented on packages/components/src/Dialog/SurfaceBase.tsx
> -
I think this was a relic of CSSTransition. Now it works fine to start the focus trap as soon as the designated element is rendered in the dom.

2020-11-09 23:18 UTC, mdodgelooker commented on packages/components/src/Popover/usePopover.tsx
> -  }, [focusTrap, parentFocusTrapRef, isOpen, enableFocusTrap])
We still need to disable any current focus trap directly if `focusTrap` is false (so that the contents of the non-focus-trapped `Popover` can receive focus) but I moved this logic to `useTrapStack` since it should apply to any use of focus trap or scroll lock.

2020-11-09 23:18 UTC, mdodgelooker commented on packages/components/src/Tooltip/useTooltip.tsx
> +  }
If the trigger element has `data-notooltip` (because it was focused due to focus trap's "return focus on deactivate" behavior), don't show the tooltip.

2020-11-09 23:18 UTC, mdodgelooker commented on packages/components-providers/src/FocusTrap/utils.ts
> +      elementToFocus.removeAttribute('data-notooltip')
I needed to make sure this refactor would support the no-tooltip-on-menu-close feature, so I decided to just include it in this PR.

2020-11-09 23:27 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/utils/useInputEvents.ts
> -        input.selectionEnd = input.selectionStart = 0
This was a workaround for https://github.com/focus-trap/focus-trap/issues/114, and no longer needed 🎉

2020-11-10 02:49 UTC, mdodgelooker commented on packages/components/src/Dialog/Prompt/PromptDialog.tsx
> +          my="xxxsmall"
The overflow style on `DialogContent` is chopping off a few pixels of the focus ring shadow.

2020-11-10 23:04 UTC, lukelooker requested changes
This is really cool - works great. Couple of minor nits to address in comments.

2020-11-11 06:34 UTC, mdodgelooker reviewed
Thanks @lukelooker ! Ready a re-review. :)

2020-11-11 06:34 UTC, mdodgelooker commented on packages/components-providers/src/FocusTrap/utils.ts
> +    typeof nodeAsInput.select === 'function' &&
That's in the original `focus-trap` – it's checking that `select` is a function and then it calls `node.select()` down on line 105. As far as I can tell, as long as it's an `input`, `select` will be available, so I think I can remove this line. Think I should?
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

2020-11-11 06:34 UTC, mdodgelooker commented on packages/components/src/Dialog/useDialog.tsx
>          closeModal: handleClose,
I agree, it's obnoxiously named. The only drawback of `close` is that if you somehow try to access `DialogContext` incorrectly, you won't get an error for `close` being undefined, due to `window.close`. (Though calling it in this case would only actually close your window if it was opened via `window.open`).

2020-11-11 06:34 UTC, mdodgelooker commented on playground/src/index.tsx
> +  SelectOptionGroupProps,
Omg that's brilliant.

2020-11-11 07:23 UTC, lukelooker commented on packages/components-providers/src/FocusTrap/utils.ts
> +    typeof nodeAsInput.select === 'function' &&
Out of abundance of caution (basically I'm not sure why they introduced it originally) I think it's fine to keep it in and not possibly introduce a breakage.

2020-11-11 07:26 UTC, lukelooker commented on packages/components/src/Dialog/useDialog.tsx
>          closeModal: handleClose,
🤦  - we've totally had this conversation below and you're still right. I'm just going to wander off now... :)

2020-11-11 07:39 UTC, lukelooker submitted a review, later dismissed
Looks great! 

Let's wait to merge this until we've shipped 0.9.24 and perhaps SC5 upgrade?

2020-11-11 07:40 UTC, lukelooker commented
Oh - just noticed this has a jest snapshot failure (and probably a matching image-snapshot failure) due to the padding change on `DialogContent`

2020-11-17 03:07 UTC, lukelooker approved these changes
LGTM

2020-11-17 22:02 UTC, mdodgelooker commented
@lukelooker just rebased and need another ✅, 🙏. There were a few more image snapshot updates – just from that `xxxsmall` vertical padding I added on the (non-scrolling) `DialogContent` for focus rings.

2020-11-17 22:51 UTC, lukelooker approved these changes
Sold! Ship it :)

2020-11-17 23:23 UTC, merged