FadeIn component
looker-open-source/components pull request #1646
Opened 2020-11-11 21:54 UTC by mdodgelooker

### :sparkles: Changes

- Adds a base component `Animate` and a `FadeIn` component that wraps it with opacity keyframes
- Currently the only use case in the core product is for `FadeIn`
- An "out" transition (e.g. `FadeOut`) could be done with `useAnimationState` but I think that can be left for a future PR / when there's a use case

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [x] Build and tests are passing
- [x] Update documentation
- [x] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [x] PR is ideally < ~400LOC

### :camera: Screenshots
![2818b5dd-f0ae-4b5a-94d0-0f9d2854f454](https://user-images.githubusercontent.com/53451193/98868662-57c74880-2425-11eb-8f25-25a58ba119dc.gif)

2020-11-11 22:36 UTC, mdodgelooker commented on packages/components/src/Animate/Animate.tsx
> +`
This component isn't particularly useful as is... should it even be exported?

2020-11-11 22:36 UTC, mdodgelooker commented on packages/components/src/Animate/Animate.tsx
> +`
I couldn't decide on a testing strategy. An image snapshot won't work, but I hesitate to add more DOM snapshots, though that would capture the relevant CSS, beyond which there's nothing much to test. Thoughts?

2020-11-17 16:56 UTC, lukelooker commented on packages/components/src/Animate/Animate.tsx
> +`
I think a snapshot would at least point at the CSS being stable / the component rendering (not throwing an error) so I'd be good with that for now :)

2020-11-17 16:58 UTC, lukelooker commented on packages/components/src/Animate/Animate.tsx
> +`
I'm not sure... I suppose it gives easy access to the theme.durations if someone wanted to build their own FadeX or other animation component.

I'm ambivalent honestly.

2020-11-17 16:59 UTC, lukelooker requested changes
I think figuring out some kind of test (even if just snapshot is viable) would be the only addition I'd like to see.

2020-11-17 16:59 UTC, lukelooker commented on packages/components/src/Animate/Animate.tsx
> +`
It just occurred to me that you might be able to use the Jest timers to measure opacity at the beginning of the duration, then check that it's resolved at the end. That would "prove" that the animation ends in a good state I think?

2020-11-18 06:08 UTC, mdodgelooker commented on packages/components/src/Animate/Animate.tsx
> +`
I added a couple snapshots (default props & non-default), but sadly the jest timers don't seem to have any affect on the css values.

2020-11-18 08:45 UTC, lukelooker approved these changes

2020-11-18 16:45 UTC, merged