update Select SelectMulti and Combobox replace readOnly with inputReadOnly
looker-open-source/components pull request #1650
Opened 2020-11-13 23:53 UTC by laraharrow

### :sparkles: Changes

- update Select SelectMulti and Combobox replace readOnly with inputReadOnly

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-11-16 18:52 UTC, mdodgelooker requested changes
Just realized the Backspace key still deletes chips with `readOnly` on, added a suggestion for how to disable that.

2020-11-16 18:52 UTC, mdodgelooker commented on CHANGELOG.md
> +- update Select SelectMulti and Combobox replace readOnly with inputReadOnly
No need to update the root `CHANGELOG.md`, just `components/CHANGELOG.md`
```suggestion
```

2020-11-16 18:52 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputChips/InputChipsBase.tsx
> +      readOnly,
One thing I forgot about is you can delete chips via `Backspace` key when the input is focused, or when "select" a chip or chips. Adding `&& !readOnly` below in ln 251 and `if (!readOnly) {` after ln 181 should do the trick.

2020-11-16 18:59 UTC, laraharrow commented on packages/components/src/Form/Inputs/InputChips/InputChipsBase.tsx
> +      readOnly,
@mdodgelooker I don't think I understand the changes. I don't see anything to be changed on line 181. and on 131 I don't think I can add the syntax `if (!readOnly)`.

2020-11-16 19:57 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputChips/InputChipsBase.tsx
> +      readOnly,
Hi @laraharrow I created a mini-PR on top of this branch here https://github.com/looker-open-source/components/pull/1657 to disable deleting of chips via keyboard when `readOnly` is true.

2020-11-16 19:58 UTC, laraharrow commented on packages/components/src/Form/Inputs/InputChips/InputChipsBase.tsx
> +      readOnly,
Great, oh I see yeah now it all make sense! sorry for the confusion!
Thanks

2020-11-16 22:27 UTC, mdodgelooker requested changes
I have a CSS-related suggestion and a docs-related one, and then I made another mini-PR here https://github.com/looker-open-source/components/pull/1661 for the changes needed in the `./Combobox` folder to use `inputReadOnly` for a couple behaviors that were relying on `readOnly` before.

2020-11-16 22:27 UTC, mdodgelooker commented on www/src/documentation/components/forms/input-chips.mdx
> +/>
```suggestion
<SpaceVertical>
  <InputChips disabled values={['disabled']} />
  <InputChips
    placeholder="this is a disabled placeholder"
    disabled
    values={[]}
  />
</SpaceVertical>
```

2020-11-17 23:34 UTC, mdodgelooker commented
The reason all the snapshots are changed is I think due to the styled-components 5 upgrade. If you run `yarn` and then update the image snapshots again, I think they'll mostly revert except for the ones that are affected by this PR.

Also, I just merged my Focus Trap PR and gave you some more conflicts. Sorry!
FYI, in `useInputEvents.ts`, the bit of code that is updated in this PR has now been completely removed, so after rebasing, that file shouldn't show any changes in this PR.

2020-11-18 05:43 UTC, mdodgelooker requested changes
Hey there, found a few things, perhaps due to the merge.

2020-11-18 05:43 UTC, mdodgelooker commented on CHANGELOG.md
> +
No need to update this file, just the one in `./packages/components`
```suggestion
```

2020-11-18 05:43 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputChips/InputChipsBase.tsx
> +        readOnly={readOnly || inputReadOnly}
```suggestion
        readOnly={readOnly || inputReadOnly}
        height="auto"
```

2020-11-18 05:43 UTC, mdodgelooker commented on www/src/documentation/components/forms/input-chips.mdx
> +  <InputChips disabled values={['disbled']} />
```suggestion
  <InputChips disabled values={['disabled']} />
```

2020-11-18 19:17 UTC, mdodgelooker approved these changes
I forgot to mention that a couple snapshots were affected by the `height="auto"` prop in `InputChipsBase` – I just updated and pushed them. This is awesome, great work!

2020-11-18 20:26 UTC, merged