DataTable: Improvements to doDefaultDataTableSort
looker-open-source/components pull request #1665
Opened 2020-11-19 00:05 UTC by ElliotTheHuman

### :sparkles: Changes
- Adds a variety of improvements to `doDefaultDataTableSort` including:
  - Now infers "string" if no type property is present on the corresponding column object
  - Supports default "date" sort
  - Is now a generic (and will set the type of the data property of the return object to match user's data interface)
- Docs + Storybook updates to showcase default "date" sort support
- JIRA Ticket: https://looker.atlassian.net/browse/LENS-1383

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

![2020-11-18_16-04-30 (1)](https://user-images.githubusercontent.com/16812885/99603284-d5f09580-29b7-11eb-84e1-352634d74f11.gif)

2020-11-19 17:06 UTC, lukelooker reviewed
Integrate into "interaction" stories and rename hook with "Default"

2020-11-20 06:52 UTC, lukelooker commented on packages/components/CHANGELOG.md
> +- `doDefaultDataTableSort` improvements
```suggestion
- `doDataTableSort` improvements (formerly `doDefaultDataTableSort`)
```

2020-11-20 08:29 UTC, lukelooker requested changes
Minor name change needed then it's GTG!

2020-11-20 18:38 UTC, ElliotTheHuman commented
Brain farted and didn't push my local branch up before requesting the original review 🤦 

Resolved conflicts with master and pushed the name changes up.

2020-11-20 19:06 UTC, lukelooker approved these changes
LGTM :)

2020-11-20 19:10 UTC, merged