updating FieldInline to support detail and description
looker-open-source/components pull request #1675
Opened 2020-11-23 17:48 UTC by laraharrow

### :sparkles: Changes

- **Thank you for your contribution to Looker Components!**
- To ensure a successful review, please double check our checklist of requirements below.
- Also including a short description of changes and relevant screenshots will help us more quickly understand the ultimate goal of your work (🗑 replace this introduction with your summary of changes).

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-11-23 20:09 UTC, dbchristopher commented on packages/components/src/Form/Fields/FieldInline.tsx
> +    <div className={className}>
Ok I don't actually know what the issue is, where the tests were indicating that expected strings were no longer in the document. But apparently they depend on this wrapper being a `label` rather than a `div`. Reverted this and things pass again 🤷‍♂️ :

<img width="1506" alt="Screen_Shot_2020-11-23_at_12_05_47_PM" src="https://user-images.githubusercontent.com/238293/100010163-b4f7be00-2d84-11eb-97e4-dd76234748a6.png">

2020-11-23 21:03 UTC, laraharrow commented on packages/components/src/Form/Fields/FieldInline.tsx
> +    <div className={className}>
thanks yeah I think that fix the problem. I changed that because my grid wasn't working and I thought maybe it needed a div but then I found the problem and forgot to revert that back. thanks

2020-11-23 23:11 UTC, dbchristopher requested changes
I was inspecting the snapshot changes, and saw that a lot of elements had additional padding added to them. I compared in snapshot on master against this branch, and got the same result:

<img width="458" alt="Screen_Shot_2020-11-23_at_3_00_30_PM" src="https://user-images.githubusercontent.com/238293/100025479-b97ca080-2d9d-11eb-9521-cb326db42d0a.png">

So I think you'll have to track down where that extra space is coming from before we can merge. Also left a note about internet explorer's unfortunate lack of Grid support 😞 

Otherwise, it all looks good to me!

2020-11-23 23:11 UTC, dbchristopher commented on packages/components/src/Form/Fields/FieldInline.tsx
> +  grid-template-columns: auto auto auto auto;
Unfortunately IE11 doesn't support grid areas. And because of inconsistencies of IE11 grid support, autoprefixers don't add in `-ms*` style rules at all. So you'll have to make sure to explicitely write out all IE equivalent grid styles, or find another way to make this layout work without grid 😞 

If you choose to write the IE grid styles, here's a guide that looks pretty decent:

https://medium.com/@elad/supporting-css-grid-in-internet-explorer-b38669e75d66

2020-11-23 23:20 UTC, laraharrow commented on packages/components/src/Form/Fields/FieldInline.tsx
> +
I used the `styled component` because latter on the style part I'm using it to define the area for the `grid`

```
${MessageArea} {
    grid-area: messages;
}
```

2020-11-23 23:55 UTC, dbchristopher commented on packages/components/src/Form/Fields/FieldInline.tsx
> +
Ahh ok. You should define styles directly on the styled component itself!

2020-12-01 19:32 UTC, dbchristopher requested changes
Looks like it reverted to a previous state where a bunch of form elements got extra padding when they shouldn't have 😩 

![onion-skin](https://user-images.githubusercontent.com/238293/100787635-c7977600-33c8-11eb-968d-f09967395031.gif)

2020-12-01 19:34 UTC, dbchristopher commented on packages/components/src/Form/Fields/FieldInline.tsx
> +
These elements should be styled directly!

2020-12-02 23:33 UTC, dbchristopher submitted a review, later dismissed
It all looks good to me! Do we need @mdodgelooker to verify whether the `-ms-grid` stuff works as expected on the IE cloudtop?

2020-12-02 23:37 UTC, mdodgelooker commented
I'll check it out on IE!

2020-12-02 23:43 UTC, laraharrow commented
Thanks!

2020-12-03 16:07 UTC, mdodgelooker commented
The detail is in the wrong spot on IE11 (hiding under the switch). I'll play around with it and try to get it working, but I'm pretty bad at `grid`. @laraharrow any ideas, based on the screenshot?
![image](https://user-images.githubusercontent.com/53451193/101055172-8d4fe500-353e-11eb-94f8-7184a04f8057.png)

2020-12-03 17:12 UTC, mdodgelooker requested changes

2020-12-03 17:12 UTC, mdodgelooker commented on packages/components/src/Form/Fields/FieldInline.tsx
> +const FieldDetail = styled(Span)`
This would fix the IE11 issue. I think IE11 doesn't handle inline elements in a grid.
```suggestion
const FieldDetail = styled.div`
```

2020-12-03 17:23 UTC, mdodgelooker commented on packages/components/src/Form/Fields/FieldInline.tsx
> +const FieldDetail = styled(Span)`
Ah actually `styled(Paragraph)` works better than `styled.div` b/c it includes our default font styles. Updated and pushed!

2020-12-03 17:47 UTC, mdodgelooker approved these changes

2020-12-04 17:53 UTC, mdodgelooker approved these changes

2020-12-04 17:53 UTC, merged