Range Slider Touch Support
looker-open-source/components pull request #1677
Opened 2020-11-25 00:57 UTC by dbchristopher

### :sparkles: Changes

- Adds touch events to range slider and dependencies  

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-12-02 01:19 UTC, dbchristopher commented
@lukelooker this PR is ready for a look whenever you have a chance! I was able to validate this on the iPhone simulator, and I think that should be sufficient to verify that the touch events work. 

@jhardy do you know if there is any good way to test on an actual touch device? I have a feeling that in a real setting, your finger is probably going to obscure the value which would be pretty annoying. Maybe we should make a ticket for future touch-friendly design updates?

2020-12-03 18:07 UTC, dbchristopher commented
@mdodgelooker here's my touch event PR if you have any time to take a look! Obviously no rush, especially while we're blocked by the travis stuff 😵

2020-12-03 23:41 UTC, mdodgelooker requested changes
Looks good! I'd say just add back in the eslint disable comment in `useMouseDragPosition` and it's gtg.

2020-12-03 23:41 UTC, mdodgelooker commented on packages/components/src/utils/useMouseDragPosition.ts
> +    updateMousePos(e)
Just curious what makes the `requestAnimationFrame` necessary now as opposed to how it was before?

2020-12-03 23:41 UTC, mdodgelooker commented on packages/components/src/utils/useMouseDragPosition.ts
> +    }
The `exhaustive-deps` rule still flags a warning here, so might as well keep the disable comment. Alternatively, if you did want to include the 3 handler functions in the deps array, you'd need to protect them from changing every render with `useCallback`. (And I seem to remember it being surprisingly awkward to do this with `throttle`).

2020-12-04 01:11 UTC, dbchristopher commented on packages/components/src/utils/useMouseDragPosition.ts
> +    }
ack ok! VSCode didn't give me the red squiggle or anything so I assumed that meant the rule was disabled altogether 🤦‍♂️  I'll add it back in!

2020-12-04 01:28 UTC, dbchristopher commented on packages/components/src/utils/useMouseDragPosition.ts
> +    updateMousePos(e)
I am honestly not sure why it wasn't necessary before. After implementing the other changes I started getting race conditions between the mouseMove and mouseDown handlers, which caused RangeSlider to act like the mouse was always down. As a result, that caused the RangeSlider to forever try and maintain focus with the first slider thumb you interact with. This gif illustrates the bug, where I'm unable to select the max endpoint:

![bad-focus](https://user-images.githubusercontent.com/238293/101109460-d417fc00-358b-11eb-9e46-d4af20835320.gif)

Let me know if the explanation makes sense, it's kind of hard to explain in text lol. I can take another step through all the changes tomorrow morning to see if I can at least understand why this is happening now when it wasn't before

2020-12-04 17:31 UTC, mdodgelooker commented on packages/components/src/utils/useMouseDragPosition.ts
> +    updateMousePos(e)
Ah, got it. 🙂

2020-12-05 00:59 UTC, dbchristopher commented on packages/components/src/utils/useMouseDragPosition.ts
> +    updateMousePos(e)
Ok after playing around with this a bit more, it turns out it is indeed a race condition issue related to the order that the state updates. So I can make the RangeSlider work correctly with either of these two options:

```
    requestAnimationFrame(() => {
      setIsMouseDown(true)
    })
    updateMousePos(e)
```
or 

```
  updateMousePos(e)
  setIsMouseDown(true)
```
But with the second option I need the additional check of `(isMouseDown && prevMouseDown)` before firing the move event, to prevent mousedown and mousemove listeners from firing simultaneously.

So given that the order of events matter so much I kind of feel like it's going to be less error-prone if we just explicitly delay it with `requestAnimationFrame`. What do you think?

2020-12-07 17:27 UTC, dbchristopher commented
@mdodgelooker this should be ready for final ✅  whenever you get a chance!

2020-12-07 17:29 UTC, mdodgelooker commented on packages/components/src/utils/useMouseDragPosition.ts
> +    updateMousePos(e)
Tricky. I think it's fine as-is. 👍

2020-12-07 17:32 UTC, mdodgelooker approved these changes
Ship it! 👏

2020-12-07 17:38 UTC, merged