Deprecate class components
looker-open-source/components pull request #1678
Opened 2020-11-30 23:58 UTC by lukelooker

### :sparkles: Changes

- Moves 3 demo components from class to functional 

(it's on our tech-debt list to be consistent - this leaves us with just ColorWheel which is a larger project to port)

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-12-01 18:11 UTC, dbchristopher commented on www/src/documentation/components/layout/demos/BoxSpacingRecipeTable.tsx
> +        {types.map((col, i) => ListRender(col.value, col.label, i))}
Getting an error here
<img width="746" alt="Screen Shot 2020-12-01 at 10 10 56 AM" src="https://user-images.githubusercontent.com/238293/100779622-864d9900-33bd-11eb-9118-690243587a56.png">

2020-12-01 18:14 UTC, dbchristopher commented on www/src/documentation/components/layout/demos/BoxSpacingRecipeTable.tsx
> -    }
looks like the class version stored these values in state, but the functional component is expecting to receive them as props. Since the variables are defined in this file, maybe don't do either and just treat them as hard-coded constants?

2020-12-01 18:16 UTC, dbchristopher commented on www/src/documentation/system/demos/BreakpointTable.tsx
> +      <TableRow>{labels.map((label, i) => TableLabel(label, i))}</TableRow>
Same issue in this demo

<img width="860" alt="Screen Shot 2020-12-01 at 10 15 25 AM" src="https://user-images.githubusercontent.com/238293/100780124-37543380-33be-11eb-8706-f09bd322e95c.png">

2020-12-01 18:18 UTC, dbchristopher requested changes
I'm glad we'll be leaving class components behind us for good 😄 Just gotta update a couple of those variables! Really strange that those dummy values were stored in state to begin with 🤔

2020-12-10 07:29 UTC, lukelooker commented
@dbchristopher Apologies for my mistakes here - I thought I'd tried these out in the final state but obviously not (eek!) fixed up (and actually tested) all 3. Ready for re-review.

2020-12-10 18:19 UTC, dbchristopher requested changes
Cool, form validation and box spacing looks good! 

I think there might have been a merge conflict or something with the recent gatsby upgrades though. I'm seeing two directories, `foundations` and `system`, which are basically duplicates of each other.

<img width="346" alt="Screen_Shot_2020-12-10_at_10_15_32_AM" src="https://user-images.githubusercontent.com/238293/101812921-e5ec2880-3ad0-11eb-91e6-c37f80c20c3d.png">

The top search result takes me to `system/breakpoints`, which is still broken

<img width="722" alt="Screen_Shot_2020-12-10_at_10_14_28_AM" src="https://user-images.githubusercontent.com/238293/101813120-2c418780-3ad1-11eb-948b-ca3bdbcdb2b4.png">

I'm guessing that directory just needs to be deleted?

2020-12-10 20:03 UTC, lukelooker commented
@dbchristopher - I went and checked, I think the `system` folder was an artifact on your instance - I looked and it appears to be removed on the branch:

https://github.com/looker-open-source/components/tree/luke/deprecate-class-components/www/src/documentation

2020-12-10 20:05 UTC, dbchristopher approved these changes
👍

2020-12-10 21:41 UTC, merged