InputText - safari color disabled update
looker-open-source/components pull request #1679
Opened 2020-12-03 00:27 UTC by laraharrow

### :sparkles: Changes

- InputText safari color disabled update

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-12-03 00:44 UTC, jhardy requested changes
Disabled state for InputText looks good now.

But issue with the date range input now

![image](https://user-images.githubusercontent.com/170681/100948819-92208480-34bd-11eb-813c-8f033f056d85.png)

2020-12-03 23:01 UTC, dbchristopher commented on packages/components/src/InputDateRange/InputDateRange.tsx
> +  ${({ disabled }) => disabled && inputTextDisabled}
I think you can delete this altogether actually! InputDateRange relies on `InlineInputText` for the text inputs, which also needed a disabled text fix in safari:

<img width="512" alt="Screen Shot 2020-12-03 at 2 55 03 PM" src="https://user-images.githubusercontent.com/238293/101098385-b04abb00-3577-11eb-9a63-4d78aa95e1cf.png">

I think I found a small fix though, which I just pushed onto the branch if you want to double check!

2020-12-03 23:02 UTC, dbchristopher commented on packages/components/src/Form/Inputs/InlineInputText/InlineInputText.tsx
> +    -webkit-text-fill-color: ${(props) => props.theme.colors.text1};
fix for both InlineInputText and InputDateRange

2020-12-04 15:22 UTC, jhardy commented on packages/components/src/InputDateRange/InputDateRange.tsx
> +  span {
is there specific item this is trying to center? Can we reference the item directly instead of a `span` incase the underlying implementation changes?

2020-12-04 17:54 UTC, laraharrow commented on packages/components/src/InputDateRange/InputDateRange.tsx
> +  span {
Good call, this is actually inside `InlineInputText` and I added the style there. Should be good now.

2020-12-07 19:53 UTC, merged