fixing checkbox overflow issue
looker-open-source/components pull request #1680
Opened 2020-12-03 19:58 UTC by laraharrow

### :sparkles: Changes

- fixing checkbox overflow issue

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-12-07 20:14 UTC, mdodgelooker requested changes
This fixes the issue! 🎉 It does appear to slightly affect the visual spacing, as the image snapshots show. I'll defer to to @jhardy on this, but my first thought would be to use pixels instead of ems for the margin.

2020-12-07 20:14 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Checkbox/Checkbox.tsx
> +  margin: 0.19rem;
I think `3px` here would be better, since `0.19rem` could be confusing (and this might make the image snapshots unchanged), but defer to @jhardy if one of our tshirt sizes might be best.

2020-12-08 07:23 UTC, lukelooker requested changes
The position change of the Checkbox should get fixed - it was properly positioned before (but with weird margin of course) so don't want to introduce a regression along with the margin fix :)

2020-12-10 04:12 UTC, lukelooker approved these changes
LGTM

2020-12-10 05:42 UTC, merged