Deprecate variant on TextBase and descendents
looker-open-source/components pull request #1689
Opened 2020-12-08 06:11 UTC by lukelooker

### :sparkles: Changes

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-12-08 18:33 UTC, mdodgelooker requested changes
This is great! My only feedback besides the `Paragraph` test wording is, if possible, to omit `color` from the dom output. But in my brief attempt I couldn't make that happen, so I don't know if it's worth chasing.

2020-12-08 18:33 UTC, mdodgelooker commented on packages/components/src/Text/Paragraph.test.tsx
>  test('A Paragraph component with variant', () => {
```suggestion
test('A Paragraph component with color', () => {
```

2020-12-09 08:34 UTC, lukelooker commented on packages/components/src/Menu/__snapshots__/MenuGroup.test.tsx.snap
> +      color="text"
Yes! Incorporated SC 5.1's "shouldForwardProp" functionality to prevent `color` (and many other spurious attributes) from being pushed down onto DOM elements.

2020-12-09 18:11 UTC, mdodgelooker approved these changes
Awesome!

2020-12-09 18:34 UTC, merged