CopyToClipboard component
looker-open-source/components pull request #1697
Opened 2020-12-10 22:30 UTC by laraharrow

### :sparkles: Changes

- CopyToClipboard component

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-12-11 04:14 UTC, lukelooker requested changes
- [ ] Added comments / code suggestions about the Story and test setup.
- [ ] I have a concern about the "success" `pointerEvents` usage (see comment in source)
- [ ] Needs documentation (Gatsby page)

2020-12-11 04:14 UTC, lukelooker commented on packages/components/src/Button/ButtonCopyToClipboard.story.tsx
> +}
There should only be 1 template per story:

```suggestion
const Template: Story<CopyToClipboardProps> = (args) => <CopyToClipboard {...args} />
```

2020-12-11 04:14 UTC, lukelooker commented on packages/components/src/Button/ButtonCopyToClipboard.story.tsx
> +}
```suggestion
```

2020-12-11 04:14 UTC, lukelooker commented on packages/components/src/Button/ButtonCopyToClipboard.story.tsx
> +export const Basic = Template.bind({})
```suggestion
export const Basic = Template.bind({})
Basic.args = {
  content: 'here is some text to be copied' 
}
```

2020-12-11 04:14 UTC, lukelooker commented on packages/components/src/Button/ButtonCopyToClipboard.story.tsx
> +export const LabelStyled = Template2.bind({})
```suggestion
export const LabelStyled = Template.bind({})
LabelStyled.args = {
  ...Basic.args,
  children: ' 'Copy Something',
  success: 'it was copied'
}
```

2020-12-11 04:14 UTC, lukelooker commented on packages/components/src/Button/ButtonCopyToClipboard.story.tsx
> +
```suggestion
export const ComponentStyled = Template.bind({})
ComponentStyled.args = {
  ...Basic.args,
  children: <Button>Success</Button>,
  success: <Button>Copy stuff</Button>,
}

```

2020-12-11 04:14 UTC, lukelooker commented on packages/components/src/Button/ButtonCopyToClipboard.tsx
> +      })
I think `pointerEvents: 'none'` will cause accessibility and focus issues - simply not having an `onClick` should prevent any user actions while the button is in it's success state.

```suggestion
  success
```

2020-12-11 04:14 UTC, lukelooker commented on packages/components/CHANGELOG.md
> +- CopyToClipboard component
```suggestion
- `CopyToClipboard` component
```

2020-12-11 14:22 UTC, jhardy commented on packages/components/src/Button/ButtonCopyToClipboard.tsx
> +      })
Some of the pointer events changes might be because I gave some feedback that the success state of the button feels strange that it's still clickable.  It might not be that big of a deal in the short term until we can come up with a more holistic approach.

I tested it with voice over, and in either case, with pointer events or not, voice over always puts focus onto the example `textarea` and never put back on the `Button`.  I checked `document.activeElement` after clicking the button and it states that the `<body>` element has focus.

We will probably also need `aria-live="polite"` on the success button here so that we can announce that the copy was successful.

2020-12-11 18:13 UTC, laraharrow commented on packages/components/src/Button/ButtonCopyToClipboard.tsx
> +      })
Ok I remove the `pointerEvents: 'none'` and add `aria-live="polite"` instead. I haven't learned how to test the accessibility yet. But from what i see if we don't have `pointerEvents: 'none'` the success button will be clickable.

2020-12-11 18:18 UTC, laraharrow commented on packages/components/src/Button/ButtonCopyToClipboard.test.tsx
> +    </>
we need the `textarea` for the 2 last tests that are testing the copy itself

2020-12-11 19:49 UTC, lukelooker commented on packages/components/src/Button/ButtonCopyToClipboard.tsx
> +      })
```suggestion
      cloneElement(success, { 'aria-live': 'polite' })
```

2020-12-11 19:50 UTC, lukelooker commented on www/src/documentation/components/actions/button-copy-to-clipboard.mdx
> +}
```suggestion
<CopyToClipboard content='here is some text to be copied' />
```

2020-12-11 19:52 UTC, lukelooker commented on www/src/documentation/components/actions/button-copy-to-clipboard.mdx
> +}
```suggestion
<CopyToClipboard 
  content="here is some text to be copied" 
  success="'it was copied'"
>
  Copy Something'
</CopyToClipboard>
```

2020-12-11 19:53 UTC, lukelooker commented on www/src/documentation/components/actions/button-copy-to-clipboard.mdx
> +}
```suggestion
<CopyToClipboard 
  content="here is some text to be copied" 
  success={<Button>Success</Button>}
>
  <Button>Copy stuff</Button>
</CopyToClipboard>
```

2020-12-11 19:54 UTC, lukelooker commented on www/src/documentation/components/actions/button-copy-to-clipboard.mdx
> +### Add Component
```suggestion
### Customize Components
```

2020-12-11 19:55 UTC, lukelooker commented on www/src/documentation/components/actions/button-copy-to-clipboard.mdx
> +`CopyToClipboard` offers props `children` and `success` both can be used to change the component displayed.
```suggestion
### Customize Components

`CopyToClipboard` `children` and `success` support taking a `JSX.Element` instead of a simple string if you prefer.```

2020-12-11 19:55 UTC, lukelooker commented on www/src/documentation/components/actions/button-copy-to-clipboard.mdx
> +### Change Label
```suggestion
### Label
```

2020-12-11 19:57 UTC, lukelooker requested changes
This is really close! 

I totally missed earlier that file paths of the component. Rather than being nested within `button` this should be in `packages/src/CopyToClipboard` and the component file name should match (e.g.: `CopyToClipboard.tsx`)

2020-12-15 21:05 UTC, lukelooker approved these changes
LGTM

2020-12-15 21:06 UTC, lukelooker requested changes
CHANGELOG needs update then Good-to-go

2020-12-15 21:07 UTC, lukelooker approved these changes
GTG!

2020-12-15 21:10 UTC, lukelooker approved these changes

2020-12-15 21:16 UTC, merged