Mobile Timeframe Filter Components
looker-open-source/components pull request #1699
Opened 2020-12-11 00:06 UTC by dbchristopher

### :sparkles: Changes

- Updates `InputDateRange` with responsive layout adjustments
- Adds a new `Breakpoint` component for toggling different layouts in react
- Updates `Popover` with new props `renderMobileDialog` and `dialogHeader` for rendering mobile friendly UX

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

![mobile-demo](https://user-images.githubusercontent.com/238293/101844501-675baf00-3b01-11eb-8763-c70446f89a55.gif)

2020-12-11 19:09 UTC, dbchristopher commented on packages/components/src/Dialog/Layout/DialogHeader.tsx
> +  z-index: 1;
Had to take the z-index escape hatch 🙈 

This allows use of `position: sticky` on DialogHeader, while ensuring that the header stacks higher than siblings with modified `position` and `display` values

![z-index](https://user-images.githubusercontent.com/238293/101944144-1a2f1a00-3ba1-11eb-9ade-98c440de2bbd.gif)

2020-12-11 19:22 UTC, dbchristopher commented on packages/components/src/Popover/Popover.tsx
> +      )}
Happy to take suggestions on alternate APIs for the Breakpoint component. I went with the props `from` and `to`, as I think it makes sense to say `render this from mobile to tablet`, or `from mobile to xl` for example. 

I can also imagine an alternate version where you pass an array of devices you want it rendered or hidden on. E.G.

```
<Breakpoint hideOn=['mobile`]>...</Breakpoint>
<Breakpoint showOn=['tablet', 'laptop', 'desktop']>...</Breakpoint>
```

@lukelooker @mdodgelooker do you have any preferences or suggestions on what feels the most natural?

2020-12-11 20:21 UTC, lukelooker requested changes

2020-12-11 20:21 UTC, lukelooker commented on packages/components/src/Popover/Popover.tsx
> +        {content}
I'm pretty retiscent to open up lots of new behavior on `DialogHeader` and I think a simple recomposition will allow you to unwind all of the changes to `Dialog*`

```suggestion
  <DialogHeader>{dialogHeader}</DialogHeader>
  <DialogContent>{content}</DialogContent>
```

2020-12-11 20:21 UTC, lukelooker commented on packages/components/src/Popover/Popover.tsx
> +  dialogHeader?: string
I think "label" might be more appropriate here.

```suggestion
  label?: string
```

2020-12-11 20:21 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogHeader.tsx
> +  z-index: 1;
See comment below on Popover. I think these changes can be unwound by using `DialogContent` below

2020-12-11 20:21 UTC, lukelooker commented on packages/components/src/Dialog/DialogSurface.tsx
> +
I think this can be removed with introduction of `DialogContent`

2020-12-11 20:21 UTC, lukelooker commented on packages/components/src/Breakpoint/Breakpoint.tsx
> +]
This is great. We should lift these changes to `@looker/design-tokens` package

2020-12-11 20:21 UTC, lukelooker commented on packages/components/src/Breakpoint/Breakpoint.tsx
> +  to?: NamedBreakpoints
I think this begs for a tuple.

```suggestion
  display: [ NamedBreakpoints, NamedBreakpoints ]
```

I also think it should be required since the component is kinda silly without this.

2020-12-11 20:21 UTC, lukelooker commented on packages/components/src/Breakpoint/Breakpoint.tsx
> +  return rem * parseFloat(getComputedStyle(document.documentElement).fontSize)
Honestly I think it's okay to just use `16` - for better or worse it's a fairly safe assumption throughout our system.

This might be nice to lift into a util from `@looker/design-tokens` since that'll be the source of truth for that.

2020-12-11 20:21 UTC, lukelooker commented on packages/components/src/Breakpoint/Breakpoint.tsx
> +  return rem * parseFloat(getComputedStyle(document.documentElement).fontSize)
Also, we've semi-codified that going forward we prefer arrow functions over `function ...` syntax. 

@mdodgelooker I'm struggling to find where we put that document?

2020-12-11 20:27 UTC, mdodgelooker commented on packages/components/src/Breakpoint/Breakpoint.tsx
> +  return rem * parseFloat(getComputedStyle(document.documentElement).fontSize)
@lukelooker we didn't put it anywhere yet, but I just shared it with the team. I can add it to our internal site if you think it's ready?

2020-12-11 20:28 UTC, lukelooker commented on packages/components/src/Popover/Popover.tsx
> +      )}
`Breakpoint` is super cool - I read through / played with this PR a bit and added some thoughts around this and other pieces.

Now that I'm thinking deeper I wonder if there's a better case for:

```jsx
interface Breakpoint {
  show: [ NamedBreakpoints | undefined, NamedBreakpoints | undefined ]
}

<Breakpoint show={[ undefined, 'large' ]} />
<Breakpoint show={[ 'small', undefined ]} />
<Breakpoint show={[ 'medium', 'xlarge' ]} />

```

2020-12-11 20:33 UTC, lukelooker commented on packages/components/src/Breakpoint/Breakpoint.tsx
> +  return rem * parseFloat(getComputedStyle(document.documentElement).fontSize)
Oh - I'm a dork. It's linked on our "Team Documents" page: https://sites.google.com/corp/google.com/looker-components/team-resources?authuser=0

2020-12-11 21:03 UTC, mdodgelooker commented on packages/components/src/Breakpoint/Breakpoint.tsx
> +  return rem * parseFloat(getComputedStyle(document.documentElement).fontSize)
Oh whoops, I forgot I snuck it up there 😂

2020-12-11 22:21 UTC, dbchristopher commented on packages/components/src/Popover/Popover.tsx
> +        {content}
I can't really use `DialogContent` here though because in this context the `content` is likely already wrapped in `PopoverContent`, so it would be doubling up the whitespace. 

Also, jared specified smaller margins in mobile, and it's REALLY helpful to have the header be sticky on iPhone SE:

![unnamed](https://user-images.githubusercontent.com/238293/101960287-f88f5c00-3bbb-11eb-9842-d22a2fb747d4.png)

Maybe DialogHeader should just be responsive to begin with?

2020-12-11 22:27 UTC, dbchristopher commented on packages/components/src/Popover/Popover.tsx
> +        {content}
Ah ok, I'm following now. So the content would scroll rather than the surface. That makes sense. Maybe I can just strip the padding from `DialogContent`, and then make the header more responsive

2020-12-11 22:28 UTC, dbchristopher commented on packages/components/src/Popover/Popover.tsx
> +  dialogHeader?: string
I'm just not sure if making that prop name more generic would cause confusion, considering 99.9% of popovers wouldn't even use it?

2020-12-11 23:49 UTC, dbchristopher commented on packages/components/src/Popover/Popover.tsx
> +      )}
nice, yeah I like that better!

2020-12-14 19:48 UTC, dbchristopher commented on packages/components/src/Popover/Popover.tsx
> +      )}
@lukelooker should we support a single value tuple? I can imagine if they only passed something like `show={['tablet']}` that could be shorthand for `show={['tablet', 'tablet']}`. Do you think that makes sense, or should we require them to always pass two values?

2020-12-14 19:57 UTC, lukelooker commented on packages/components/src/Popover/Popover.tsx
> +      )}
Hm... I suppose that could make sense (to specify "only display exactly at this breakpoint"

A tuple always has exactly two elements so in that case we could just support giving us 1 breakpoint value as well:

```
interface Breakpoint {
  show: [ NamedBreakpoints | undefined, NamedBreakpoints | undefined ] | NamedBreakpoints
}
```

2020-12-14 20:21 UTC, dbchristopher commented on packages/components/src/Popover/Popover.tsx
> +      )}
oh yeah good call, passing a string value rather than a single-value array makes more sense for that case 👍 

> A tuple always has exactly two elements

That actually is not true! I had to refresh myself on the terminology to make sure the phrase "a single value tuple" even makes sense lol. I found this:

> In mathematics, a tuple is a finite ordered list of elements.

And of course type theory and mathematics don't always correlate in practice, so I double checked the typescript docs:

> Tuple types allow you to express an array with a fixed number of elements whose types are known, but need not be the same.  

So if I'm understanding correctly, a tuple is just an array with a predefined shape, but the lengths can vary

![giphy](https://user-images.githubusercontent.com/238293/102131214-bdcd3400-3e06-11eb-8d98-49c70c38abbd.gif)

2020-12-15 21:30 UTC, lukelooker commented on packages/components/src/Breakpoint/Breakpoint.story.tsx
> +      image="https://placeimg.com/630/480/nature"
This will introduce variance into snapshots (different image can potentially load each time). Let's just use a solid color or something that'll stay stable / not require CI to load resources from the public internet.

2020-12-15 21:53 UTC, lukelooker commented on packages/components/src/Breakpoint/Breakpoint.tsx
> +  children: ReactNode
This is inferred by the `FC` wrapper below

2020-12-15 21:53 UTC, lukelooker commented on packages/components/src/Breakpoint/Breakpoint.tsx
> +  show: NamedBreakpoints | [NamedBreakpoints, NamedBreakpoints]
JSDoc for this prop

2020-12-15 21:53 UTC, lukelooker commented on packages/components/src/Breakpoint/Breakpoint.tsx
> +  )
Does this need to be wrapped in a fragment or would this work?

```suggestion
  return screenWidth > screenMin && screenWidth <= screenMax ? children : null
```

2020-12-15 21:53 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogContent.tsx
> +      {...omit(props, [...paddingProps, 'renderedHeight'])}
I _think_ `pickStyledProps` could do this (wouldn't to `renderedHeight` but that could be done on a separate line explicitly

2020-12-15 21:53 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogContent.tsx
> +
Can the defaultProps be specified on the `DialogContent` itself instead? (Makes them more discoverable for codegen stuff that I've been working on). It's also looking like we're going to need to remove defaultProps altogether for tree-shaking work so moving stuff "up" should make that refactor easier as well

2020-12-15 21:53 UTC, lukelooker commented on packages/design-tokens/src/GlobalStyle/GlobalStyle.tsx
> +export const BASE_FONT_SIZE = 16
Why is this needed?

2020-12-15 21:53 UTC, lukelooker commented on packages/design-tokens/src/tokens/breakpoints.ts
> +]
It seems like `Breakpoints` or `BreakpointRamp` would more internally consistent with other named theme objects.

2020-12-15 21:53 UTC, lukelooker commented on packages/design-tokens/src/tokens/breakpoints.ts
> +  | XL
I'd argue for excluding `undefined` from this because I could see a case where someone might want to specify that the develop _must_ specify a explicit breakpoint and they'd have to alter the type to do so rather than leaving them the choice to mark the type as optional. E.g.:

```ts
interface FauxThing {
  required: NamedBreakpoints
  optional?: NamedBreakpoints
}

interface AltFauxThing {
  required: NamedBreakpoints 
  optional: Exclude<NamedBreakpoints, undefined>
}
```

2020-12-15 21:53 UTC, lukelooker commented on packages/design-tokens/src/tokens/breakpoints.ts
> +}, {})
Since this isn't really relevant to general use of `design-tokens` I'd prefer to see this lifted. Perhaps park it in the `storybook-config` package?

2020-12-15 21:53 UTC, lukelooker commented on packages/design-tokens/src/utils/convertRemToPx.ts
> +import { BASE_FONT_SIZE } from '../GlobalStyle'
I _think_ it'd be ok to just declare `const BASE_FONT_SIZE = 16px`

I don't see a world where we'd expect / design for folks to change that value

2020-12-15 21:53 UTC, lukelooker commented on packages/design-tokens/src/utils/index.ts
> +export { generatePressed, generateInteractive } from './color/stateful'
👍

2020-12-15 22:44 UTC, dbchristopher commented on packages/design-tokens/src/tokens/breakpoints.ts
> +}, {})
Sure sounds good! I definitely wasn't sure where the best place for that would be

2020-12-15 22:45 UTC, dbchristopher commented on packages/components/src/Breakpoint/Breakpoint.story.tsx
> +      image="https://placeimg.com/630/480/nature"
D'oh! Yes of course. No external dependencies in a snapshot test

2020-12-16 00:06 UTC, dbchristopher commented on packages/components/src/Breakpoint/Breakpoint.tsx
> +  )
It depends. Looks like the FC type sets `children` as optional. So if I remove children as a required prop and remove the fragment, it complains that this might return `undefined` which is not a valid react node. 

I think it makes sense to enforce children as required, so I think I'll remove the fragment wrapper but leave the required `children: ReactNode` prop on line 38

2020-12-16 00:10 UTC, dbchristopher commented on packages/components/src/Breakpoint/Breakpoint.tsx
> +  )
oh wait, nevermind. the `ReactNode` definition itself allows for `undefined` 🤦 

I'll remove line 38, but leave the fragment wrapper here. Here's the typescript error I get when I remove the wrapper:

```
const Breakpoint: React.FC<BreakpointProps>
Type '({ children, show }: PropsWithChildren<BreakpointProps>) => string | number | ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)> | null' is not assignable to type 'FC<BreakpointProps>'.
  Type 'string | number | ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)> | null' is not assignable to type 'ReactElement<any, any> | null'.
    Type 'string' is not assignable to type 'ReactElement<any, any> | null'.
```

2020-12-16 00:19 UTC, dbchristopher commented on packages/components/src/Dialog/Layout/DialogContent.tsx
> +
oh yeah, good call!

2020-12-16 17:58 UTC, dbchristopher commented on packages/design-tokens/src/tokens/breakpoints.ts
> +]
Yeah that's a good point. I realized that if I name it `BreakpointRamp` it really needs to be a named hash to be consistent with other ramps. That's a more useful data structure anyways, so went ahead and updated

2020-12-16 18:08 UTC, dbchristopher commented on packages/design-tokens/src/GlobalStyle/GlobalStyle.tsx
> +export const BASE_FONT_SIZE = 16
Just to ensure a consistent value between the global styles and `convertRemToPx`. But I can just hard-code that number in the helper function as you suggested

2020-12-16 19:13 UTC, dbchristopher commented on packages/components/src/utils-storybook/viewportMap.ts
> +)
It really seems like storybook-config is not a friendly place to store helper functions like this. When I try to import anything from there using the relative path, it seems to break all our package dependencies:

<img width="933" alt="Screen Shot 2020-12-16 at 10 49 25 AM" src="https://user-images.githubusercontent.com/238293/102395028-74f4b700-3f8f-11eb-875f-c0b74d3abef0.png">

But I also get that this isn't really isn't useful to people outside our team, and shouldn't be delivered with the design tokens. So I just added this new `utils-storybook` directory within the components src, which won't be exported as part of any package. Does this seem like a good location to you @lukelooker?

2020-12-16 19:14 UTC, lukelooker commented on packages/components/src/utils-storybook/viewportMap.ts
> +)
Ah - that's annoying. Your solve works for me :)

2020-12-22 01:28 UTC, dbchristopher commented on www/src/documentation/components/overlays/popover.mdx
> +
I can't really render an example here because this is what you see when you resize the window to mobile breakpoint:

<img width="484" alt="Screen Shot 2020-12-21 at 3 53 55 PM" src="https://user-images.githubusercontent.com/238293/102837845-98659a80-43b1-11eb-8a9e-cb043bf08dbb.png">

I tried @mdodgelooker's suggestion for rendering the component in an iFrame, but found the breakpoint component still relying on the parent `document.body` to measure the screen size. I think it was because the styled components get injected through a portal, so it maintained the parent context

2020-12-22 18:09 UTC, dbchristopher commented on packages/components/src/Dialog/SurfaceBase.tsx
> +  'aria-labelledby': 'dialog-header',
I wanted to add the aria label as per the [dialog accessibility specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role#Description). 

I feel like there really shouldn't ever be two DialogHeaders on the page at any given time, so hopefully this sort of naive implementation should be sufficient. What do you think @lukelooker?

2020-12-22 18:22 UTC, dbchristopher commented on packages/components/src/Popover/Popover.tsx
> +  label?: string
So just to clarify @lukelooker, do we have plans to render label text on normal popovers in the future?

2020-12-22 18:43 UTC, dbchristopher commented on www/src/documentation/components/dialogs/index.mdx
> +  const { dialog, setOpen } = useDialog({ content: 'My Neat Dialog' })
Previous `useDialog` example was broken in master

2020-12-22 19:23 UTC, dbchristopher commented
Whew ok that was a lot! 😅  @lukelooker this should all be ready for final review

2020-12-23 18:02 UTC, lukelooker commented on packages/components/src/Popover/Popover.tsx
> +  label?: string
I believe so - I think it'll be visually hidden in many / most cases for "Desktop" presentation but it's needed for a11y compliance

2020-12-23 18:02 UTC, lukelooker commented on www/src/documentation/components/dialogs/index.mdx
> +  const { dialog, setOpen } = useDialog({ content: 'My Neat Dialog' })
🤦

2020-12-23 19:14 UTC, lukelooker reviewed
Some nits on a few changes (don't want to add more props to `DialogContent` but in general this is super-close. LMK if anything doesn't make sense.

2020-12-23 19:14 UTC, lukelooker commented on packages/components/src/InputDateRange/InputDateRange.tsx
> +  grid-row-gap: ${({ theme }) => theme.space.medium};
`grid-gap` doesn't have IE11 support. Probably not a particularly tragic rendering in that case?

2020-12-23 19:14 UTC, lukelooker commented on packages/design-tokens/src/system/color/backgroundColor.ts
> +})
Styled-system has a built-in helper for this, you should be able to add it to `packages/design-tokens/src/system/index.ts` and forego adding this.

```suggestion
```

2020-12-23 19:14 UTC, lukelooker commented on packages/design-tokens/src/system/color/index.ts
> +export { backgroundColor } from './backgroundColor'
```suggestion
```

2020-12-23 19:14 UTC, lukelooker commented on packages/design-tokens/src/system/color/index.ts
> +export { backgroundColor } from './backgroundColor'
I'm also completely baffled why I added `textColor` instead of using the built-in type/helper. I think I was playing with "locking" out non-system colors but never actually landed the full change.

Feel free to remove the `textColor` as well if you feel like it.

2020-12-23 19:14 UTC, lukelooker commented on packages/storybook-config/src/storyshotsConfig.ts
> +        }
Neat!

2020-12-23 19:53 UTC, dbchristopher commented on packages/components/src/Dialog/Layout/DialogContent.tsx
> +    PaddingProps,
oh but I do need external control of DialogContent padding for this new case where DialogContent will be wrapped in PopoverContent

<img width="573" alt="Screen Shot 2020-12-23 at 11 51 54 AM" src="https://user-images.githubusercontent.com/238293/103032649-6cfbc080-4515-11eb-84f8-74ce51221a88.png">

2020-12-23 22:01 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogContent.tsx
> +    PaddingProps,
Oh bummer... unwinding all the variations on `DialogHeader` took a lot of time / design negotiation a while back so I'm really reticent to re-open the flood gates on this. 

We also have an existing issue around properly introducing padding to `DialogContent` when it doesn't have adjacent `DialogHeader` / `DialogFooter` and introducing padding as props will make that a lot more complex / brittle. 

Two thoughts occur:

1. What if when `renderMobileDialog` we automatically wrap the `content` in `PopoverContent` when it's in a non-mobile breakpoint. Then we could leave the composition for the mobile-ready Dialog "pure" as it were?
2. On looking at this change to `Popover` in general I'm realizing that we've just made `Popover`'s a lot more expensive to render in all cases (even when they haven't `enabled` the `renderMobileDialog` feature) - I'm thinking that perhaps we want to make these changes into a separate purpose-built component `ResponsivePopover` (name could definitely be better) so that existing use-cases don't end up with a significant complexity boost / bundle-size impact.

2020-12-23 22:56 UTC, dbchristopher commented on packages/components/src/Dialog/Layout/DialogContent.tsx
> +    PaddingProps,
> On looking at this change to Popover in general I'm realizing that we've just made Popover's a lot more expensive to render in all cases (even when they haven't enabled the renderMobileDialog feature)

Hmm, yeah that is a good point. I guess to me it comes down to how much investment we want to make in mobile UX, and how often we'll use this feature. Would you feel comfortable deciding that all popovers should just convert to this new pattern? In that case I think the added complexity would be justified.

But if not, maybe this shouldn't even be a feature of popover. Maybe what we actually deliver is just the Breakpoint component, and then just build this logic at the call site. I.E. it might make sense if it was just a part of the timeframe filter in our internal repo.

What do you think, should I just strip `renderMobileDialog` out altogether from this PR?

2020-12-23 23:17 UTC, dbchristopher commented on packages/components/src/InputDateRange/InputDateRange.tsx
> +  grid-row-gap: ${({ theme }) => theme.space.medium};
yeah that seems like an acceptable level of IE11 jank to me 😄

2020-12-24 00:30 UTC, dbchristopher commented on packages/design-tokens/src/system/color/index.ts
> +export { backgroundColor } from './backgroundColor'
Ok I just tried removing these in favor what styled system provides. Looks like they don't provide specific helpers for specific `textColor` and `backgroundColor` props. They only provide a single `color` helper which consolidates BackgroundColor, TextColor, and Opacity attributes. 

I assume we do want to be able to maintain this level of specificity, yeah?

2020-12-24 00:38 UTC, dbchristopher commented on packages/components/src/Dialog/SurfaceBase.tsx
> +  'aria-labelledby': 'dialog-header',
ah dang, yeah that's tough! that does seem out of scope from this PR, so maybe I'll just revert this change and add a ticket for the Dialog aria changes

2020-12-24 00:42 UTC, dbchristopher commented on packages/components/src/Dialog/Layout/DialogContent.tsx
> +    PaddingProps,
On further reflection, I think this does just feel like a one-off feature we should add to the Timeframe filter itself. I went ahead and reverted those changes, but let me know if you think we should in fact ship that as part of a popover component!

2020-12-28 19:01 UTC, dbchristopher commented on packages/components/src/Dialog/SurfaceBase.tsx
> +  'aria-labelledby': 'dialog-header',
dialog accessibility ticket here: https://looker.atlassian.net/browse/LENS-1448

2021-01-06 17:42 UTC, closed without merging