Field Picker Story Revamp
looker-open-source/components pull request #1700
Opened 2020-12-11 03:19 UTC by ElliotTheHuman

### :sparkles: Changes

- `AccordionDisclosure` added "SimpleLayoutProps"
- Updated `FieldPicker.story` to match Explore team's latest specs
  - https://www.figma.com/file/o8vnoAdtk1fbf99QJDxTFG/Explore-Field-List?node-id=6261%3A133

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots
![image (3)](https://user-images.githubusercontent.com/16812885/101857542-96334e80-3b1c-11eb-8237-3e88fa79dbb5.png)

2020-12-12 00:25 UTC, lukelooker requested changes

2020-12-12 00:25 UTC, lukelooker commented on packages/components/src/Tree/stories/FieldPicker.story.tsx
> +  </TreeStyle>
As discussed make `hoverered` an optional prop

Create this composition as a pattern we export for this specific use case.

With that done would it be possible to stop exporting `TreeStyle` and `TextContext` from the package?

2020-12-12 00:25 UTC, lukelooker commented on packages/components/src/Tree/stories/FieldPicker.story.tsx
> +      </FlexItem>
```suggestion
      <Space between>
        <Text fontSize="xsmall"><Truncate>{label}</Truncate></Text>
        <Badge intent="inform">1</Badge>
      </Space>
```

2020-12-14 20:19 UTC, ElliotTheHuman commented on packages/components/src/Tree/stories/FieldPicker.story.tsx
> +  </TreeStyle>
Yep! Went ahead and removed `TreeContext` from the package exports and replaced it with a `TreeIndentManager` export instead (`TreeStyle` was not being exported originally).

2020-12-14 21:29 UTC, lukelooker reviewed
Haven't had a chance to fully review but had one suggestion (see inline comment)

2020-12-14 21:29 UTC, lukelooker commented on packages/components/src/Tree/stories/FieldPicker.story.tsx
> +    </AccordionDisclosure>
```suggestion
    <AccordionDisclosure px="xxsmall" py="none" fontSize="xsmall">
      <Space between>
        <Truncate>{label}</Truncate>
        <Badge intent="inform">1</Badge>
      </Space>
    </AccordionDisclosure>
```

2020-12-15 00:51 UTC, lukelooker approved these changes
![tree](https://media.giphy.com/media/IeRcJQgDFG5essVj9n/giphy.gif)

2020-12-15 00:54 UTC, merged