Standardize hover and selected states
looker-open-source/components pull request #1704
Opened 2020-12-11 18:31 UTC by ElliotTheHuman

### :sparkles: Changes
Standardized the background colors on various components when in a hovered and/or selected state according to the chart below:
<img width="754" alt="Screen Shot 2020-12-10 at 2 48 23 PM" src="https://user-images.githubusercontent.com/16812885/101839228-da135d00-3af6-11eb-8c86-94b4aab36538.png">

**Always use "keyColor"**
- ComboBox / Select
- ComboboxMulti / SelectMulti
- DataTable

**Default to "standard"**
- TreeItem / Tree

**Always use "standard"**
- Menu (Note: no "selected" state)

Relevant JIRA ticket:
https://looker.atlassian.net/browse/LENS-1293

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [x] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

2020-12-11 21:32 UTC, mdodgelooker requested changes
Aside from the `Combobox` keyboard nav suggestion, the only other thing I see is that `MenuItem` does have sort of a "selected" state if you add the `current` prop – it uses `aria-current="true"` on the dom. And I think that might need a bg color update.

Random thought, am I greyscale colorblind, or are ui1 & ui2 pretty much the same? 
![image](https://user-images.githubusercontent.com/53451193/101956957-5bc9c000-3bb5-11eb-9eff-244aba79a9b9.png)

2020-12-11 21:32 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/ComboboxOption.tsx
> +  } */
Right now keyboard nav doesn't get any feedback on the "active" option. If you make this change, I think it looks good for both keyboard nav and hover, although when you first open a `Select` that has a current value, it'll be `keyAccent` because it is both "active" and "selected". If that's not what we want, we'll probably have to think of something fancy here.
```suggestion
  &[aria-selected='true'] {
    background-color: ${({ isSelected, theme }) =>
      isSelected ? theme.colors.keyAccent : theme.colors.ui1};
  }
```

2020-12-11 21:37 UTC, mdodgelooker commented
Oh and I know we can't do image snapshots of hover state, but what do you think about adding / updating some stories to capture selected/current on `TreeItem` and `MenuItem`?

2020-12-11 22:52 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/Combobox/ComboboxOption.tsx
> +  } */
👍 Good catch. 

Regarding the opening a `Select` with a current value and that value having a `keyAccent` background, I think I'd defer to @jhardy.

2020-12-11 22:55 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/Combobox/ComboboxOption.tsx
> +  } */
Also you're not blind! I imagine those look really similar because of the opacity we apply to `TreeItem` backgrounds. We do this because we don't want to blot out the optional vertical `border`:
<img width="229" alt="Screen Shot 2020-12-11 at 2 55 35 PM" src="https://user-images.githubusercontent.com/16812885/101962404-ef54be00-3bc0-11eb-9834-bdb439e1543b.png">

2020-12-11 22:57 UTC, ElliotTheHuman commented
> Oh and I know we can't do image snapshots of hover state, but what do you think about adding / updating some stories to capture selected/current on `TreeItem` and `MenuItem`?

I think this makes total sense to track that. I'll get some additional stories included in this PR.

2020-12-14 17:33 UTC, mdodgelooker reviewed
The changes look great! On closer look at `TreeItem`, I had a question about the colors there. And I just wanted to make extra sure the new "selected" bg color on `SelectMulti` is cool w/ @jhardy :
![image](https://user-images.githubusercontent.com/53451193/102114757-74bdb580-3def-11eb-9dae-5bcbd7a6cf60.png)

2020-12-14 17:33 UTC, mdodgelooker commented on packages/components/src/Tree/TreeItem.tsx
> +    selected ? uiTransparencyBlend(2) : hovered && uiTransparencyBlend(1)};
I realize now why the `selected` bg color looked too close to the `hovered` bg color. I think `uiTransparencyBlend(2)` is not equivalent to `ui2` – the latter is much darker. Would using `ui2` and `ui1` here break anything?

2020-12-14 18:13 UTC, mdodgelooker commented
FYI the keyboard nav is active on "Friday" in my screenshot above, which is why it's darker.

2020-12-14 18:20 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeItem.tsx
> +    selected ? uiTransparencyBlend(2) : hovered && uiTransparencyBlend(1)};
Ah good call. In taking a closer look, it looks like `uiTransparencyBlend` uses that number arg to alter opacity and the base color is `colors.text`.
```
export const uiTransparencyBlend = (level: UIColorLevels) =>
  css`
    ${({ theme: { colors } }) => blendColorTransparency(colors.text, level)}
  `
```

For context, we couldn't use vanilla ui2 and ui1 because the optional vertical borders would be covered by non-opaque colors. I'm not sure what the most color-math conscious solution is here; @lukelooker any suggestions?

2020-12-14 18:53 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/Combobox/ComboboxOption.tsx
> +  } */
Spoke to @jhardy and he approves of this!

2020-12-14 18:54 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeItem.tsx
> +    selected ? uiTransparencyBlend(2) : hovered && uiTransparencyBlend(1)};
Spoke to @jhardy about this as well. He's cool with using vanilla `ui1` and `ui2` for consistency and revisiting `border`-friendly solutions in the future (specifically when folks in HT land start using the `border` prop).

2020-12-14 22:28 UTC, mdodgelooker approved these changes
LGTM!

2020-12-14 22:59 UTC, merged