update DataTable for accessibility
looker-open-source/components pull request #1709
Opened 2020-12-14 19:59 UTC by laraharrow

### :sparkles: Changes

- update DataTable for accessibility

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-12-23 17:59 UTC, lukelooker requested changes
The icon changes caused tons of snapshot changes. Can you pull that out of this PR and open a separate PR that we can review first / separately to figure out that issue?

2020-12-23 17:59 UTC, lukelooker commented on packages/components/src/Icon/Icon.tsx
> +          {value}
@laraharrow - This changes seems to have caused massive snapshot impacts. Can you pull it out into a separate PR so we can look at it singularly?

2020-12-23 17:59 UTC, lukelooker commented on packages/components/src/Icon/Icon.tsx
> +          aria-hidden={title === undefined && true}
```suggestion
        <div
          aria-label={label} 
          role="img"
          aria-hidden={title === undefined && true}
```

2020-12-24 00:18 UTC, laraharrow commented on packages/components/src/Icon/Icon.tsx
> +          aria-hidden={title === undefined && true}
This idea doesn't work for accessibility. having aria-hidden excludes the aria-label. The aria-hidden needs to be in a different div. that's why I did the double div.

2021-01-06 00:51 UTC, lukelooker requested changes
Couple of small nits and a few concerns around hook-specification of `caption`. With those adjustments this should be GTG! :)

2021-01-06 00:51 UTC, lukelooker commented on packages/components/src/DataTable/Item/DataTableRow.tsx
> +          index === 0
Rather than using `index === 0` use `isHeaderRow` instead:

```suggestion
          isHeaderRow 
```

2021-01-06 00:51 UTC, lukelooker commented on packages/components/src/DataTable/Item/DataTableRow.tsx
> +          <ColumnType>{checkbox}</ColumnType>
```suggestion
          <ColumnType>
            <DataTableCheckbox {...pick(props, checkListProps)} />
          </ColumnType>
```

2021-01-06 00:51 UTC, lukelooker commented on packages/components/src/DataTable/Item/DataTableRow.tsx
> +    ) : undefined
This assignment can be removed altogether with the refactor below in-mind.

2021-01-06 00:51 UTC, lukelooker commented on packages/components/src/DataTable/utils/useDataTable.tsx
> +          <DataTableCell key={column.id} role="foo">
What's `role="foo"` doing here?

2021-01-06 00:51 UTC, lukelooker commented on packages/components/src/DataTable/utils/useDataTable.tsx
> +    <DataTable caption="DataTable useDataTable" columns={columns}>
Seems like `caption` needs to come in as required variable supplied to the `useDataTable` function rather than being statically defined here.

2021-01-06 00:51 UTC, lukelooker commented on packages/components/src/DataTable/utils/useDataTableSortManager.tsx
> +      caption="DataTable Sort Manager"
Again, this needs to dynamic / user-specified.

2021-01-06 00:51 UTC, lukelooker commented on packages/components/src/Icon/Icon.tsx
> +        aria-hidden={title === undefined && true}
👍

2021-01-06 00:54 UTC, lukelooker commented on www/src/documentation/components/actions/pagination.mdx
> +        <DataTable caption="this is the table's caption" columns={columns}>
```suggestion
        <DataTable caption="Example cheeses" columns={columns}>
```

2021-01-06 00:55 UTC, lukelooker commented on www/src/documentation/components/content/data-table.mdx
> +For accessibility `<DataTable>` needs the `caption` prop to be supported with a description of what the table represents.
```suggestion
For accessibility `caption` must be specified to describe the table's contents.
```

2021-01-06 00:55 UTC, lukelooker commented on www/src/documentation/components/content/data-table.mdx
> +    <DataTable caption="this is the table's caption" columns={columns}>
```suggestion
    <DataTable caption="Cheese examples" columns={columns}>
```

2021-01-06 00:56 UTC, lukelooker commented on www/src/documentation/components/content/data-table.mdx
> +    <DataTable caption="this is the table's caption" columns={columns}>
```suggestion
    <DataTable caption="Cheese exampes" columns={columns}>
```

2021-01-06 01:12 UTC, laraharrow commented on www/src/documentation/components/actions/pagination.mdx
> +        <DataTable caption="this is the table's caption" columns={columns}>
not sure what to do here if `caption` is removed the Ts will complain about not having the prop.

2021-01-06 01:13 UTC, laraharrow commented on packages/components/src/DataTable/utils/useDataTableSortManager.tsx
> +      caption="DataTable Sort Manager"
not sure what to do here if caption is removed the Ts will complain about not having the prop.

2021-01-06 01:13 UTC, laraharrow commented on packages/components/src/DataTable/utils/useDataTable.tsx
> +          <DataTableCell key={column.id} role="foo">
oops that was for a test

2021-01-06 16:54 UTC, lukelooker commented on packages/components/src/DataTable/utils/useDataTableSortManager.tsx
> +      caption="DataTable Sort Manager"
Sorry, I meant that the hook itself "useDataTable" should take `caption` as a parameter. 

I pushed a commit that makes the change (and leverages it)

2021-01-06 17:02 UTC, lukelooker commented on packages/components/src/DataTable/Item/DataTableRow.tsx
> +        const cellProps = isHeaderRow
Ack! I apologize - I wasn't reading carefully here - the index=0 was getting the first column to act as the `rowheader` and I misread it to be the table (column) header so your logic was correct. I just pushed a fix to put this back. 

Sorry!

2021-01-06 17:09 UTC, lukelooker approved these changes

2021-01-06 17:42 UTC, closed without merging