Deprecate defaultProps library-wide
looker-open-source/components pull request #1716
Opened 2020-12-18 01:55 UTC by lukelooker

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-12-21 19:19 UTC, ElliotTheHuman reviewed
Things look good! However, we're still hitting a Gatsby error (due to some destructuring shenanigans afaik).

Once that's fixed, I can give a 👍

2020-12-21 19:19 UTC, ElliotTheHuman commented on www/src/Layout/Documentation.tsx
> -          <Status status={status || 'stable'} />
We might still need this. In doing some research, destructuring a property with a false/null value will not lead to the default value replacing said false/null value:
https://stackoverflow.com/questions/39522014/destructuring-falsey-and-null-with-default-parameters

Note: Gatsby is currently failing because it receives "null" here and the `Status` component tries to call `toUpperCase()` on that null.

2020-12-21 19:20 UTC, ElliotTheHuman requested changes
Pressed "Comment" instead of "Request Changes" last time.

2020-12-21 20:15 UTC, lukelooker commented on www/src/Layout/Documentation.tsx
> -          <Status status={status || 'stable'} />
Yeah - that's really annoying - wish I could find the case where it's getting supplied `null` but I made the gate more universal to deal with this now (realized the switch was possibly also suffering from the bad value so moved it up a smidge).

2020-12-21 20:42 UTC, ElliotTheHuman approved these changes
LGTM!

2020-12-21 23:38 UTC, merged

2020-12-28 17:16 UTC, mdodgelooker commented on packages/components/src/Tooltip/TooltipContent.tsx
> +    width: width || '16rem',
This is confusing but I think at some point we decided the width of this `<p>` should always be `'auto'` and if someone was passing in a `width`, it should be set as the `maxWidth` instead. So this should be:
```
    maxWidth: width || '16rem',
    p: 'xsmall',
    textAlign,
    width: 'auto',
```
![image](https://user-images.githubusercontent.com/53451193/103231547-e5cf9380-48ec-11eb-9d20-e95adfccc980.png)
I'll open a PR...

2020-12-28 18:05 UTC, mdodgelooker commented on packages/components/src/Tooltip/TooltipContent.tsx
> +    width: width || '16rem',
Fix merged: https://github.com/looker-open-source/components/pull/1732