Circular progress
looker-open-source/components pull request #1723
Opened 2020-12-22 21:08 UTC by jhardy

### :sparkles: Changes

First pass at a `CircularProgress` component. It has two states, indeterminate and determinate. Here is a few gifs of the interactions though their frame-rate is not the best , but it gets the point across. Looking for early feedback on code.

Indeterminate spins constantly
![2020-12-22_13-00-22 (2)](https://user-images.githubusercontent.com/170681/102932958-285d2000-4456-11eb-962f-c1da1c14e682.gif)

Determinate animates the stroke from 0 to 1 depending on the progress prop
![2020-12-22_13-05-32 (1)](https://user-images.githubusercontent.com/170681/102933109-7a05aa80-4456-11eb-9122-e941ac95cd83.gif)

TODO:
- [ ] Write Tests
- [ ] Write Docs
- [ ] Update Chagelog

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2020-12-23 18:48 UTC, dbchristopher requested changes
This is looking really great! I caught a few small details that could be cleaned up, but nothing major. 

As far as general API design, I think it could be simplified a little bit by removing the `determinate` prop. It seems intuitive to me that if you pass a `progress` value it would automatically switch to the determinate progress bar. At the moment you could pass conflicting props `determinate={false} progress={0.5}` which doesn't really make sense.

And then it would be good to add some gatsby docs for this, and a note on Spinner.mdx pointing people to this new version. 

Solid work!

2020-12-23 18:48 UTC, dbchristopher commented on packages/components/src/ProgressCircular/ProgressCircular.tsx
> +   * If a determaniate progress
spelling -- `determaniate`

If you don't have it, I think a lot of us use the [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) to help with that

```suggestion
  * Render a static progress indicator rather than an animated spinner
  * @default false
```

2020-12-23 18:48 UTC, dbchristopher commented on packages/components/src/ProgressCircular/DeterminateProgress.tsx
> +        <DeterminateTrack cx={half} cy={half} r={radius} strokeWidth={stroke} />
I think it's safe to remove the track since it's just a transparent SVG anyways, right?

2020-12-23 18:48 UTC, dbchristopher commented on packages/components/src/ProgressCircular/ProgessCircular.story.tsx
> +}
I noticed that the default Storybook controls are oriented to whole numbers, which is definitely awkward here: 

![storybook-controls](https://user-images.githubusercontent.com/238293/103026937-c8c04c80-4509-11eb-9ea0-5845126edf6f.gif)
I just looked it up and luckily that can be customized to be a little more helpful 🥳 

```suggestion
export default {
  component: ProgressCircular,
  title: 'ProgressCircular',
  argTypes: {
    progress: {
      control: { type: 'range', min: 0, max: 1, step: 0.1 },
    },
  },
}
```

![slider-controls](https://user-images.githubusercontent.com/238293/103027131-22287b80-450a-11eb-814f-fd22fc26eccb.gif)

2020-12-23 18:48 UTC, dbchristopher commented on packages/components/src/ProgressCircular/IndeterminateProgress.tsx
> +`
white space 
```suggestion
const leftSpin = keyframes`
  from {
    transform: rotate(265deg);
  }
  50% {
    transform: rotate(130deg);
  }
  to {
    transform: rotate(265deg);
  }
`

const rightSpin = keyframes`
  from {
    transform: rotate(-265deg);
  }
  50% {
    transform: rotate(-130deg);
  }
  to {
    transform: rotate(-265deg);
  }
`
```

2020-12-23 18:53 UTC, dbchristopher commented
I'm seeing the CI/Build task failing with an error about missing styled-system types. You might need to just add this to the devDependencies:

https://www.npmjs.com/package/@types/styled-system

No idea why it would be happening now but not before though 🤔

2020-12-29 15:27 UTC, jhardy commented on packages/components/src/ProgressCircular/ProgessCircular.story.tsx
> +}
🥳

2020-12-29 15:28 UTC, jhardy commented on packages/components/src/ProgressCircular/ProgressCircular.tsx
> +   * If a determaniate progress
Thanks! This will help so much.

2020-12-29 15:30 UTC, jhardy commented on packages/components/src/ProgressCircular/size.ts
> +} from '@looker/design-tokens/src'
@dbchristopher just fyi, this was the reason the ci was failing, changed to `@looker/design-tokens` and started working

2020-12-29 16:48 UTC, jhardy commented on packages/components/src/ProgressCircular/DeterminateProgress.tsx
> +        <DeterminateTrack cx={half} cy={half} r={radius} strokeWidth={stroke} />
removed

2020-12-29 16:50 UTC, jhardy commented on packages/components/src/ProgressCircular/DeterminateProgress.tsx
> +  position: absolute;
Absolute positioning is needed in most cases, I believe this should be relatively safe with the `position: relative` on the parent container. I don't think that should cause any z-index issues.

2020-12-29 16:52 UTC, jhardy commented on www/src/documentation/components/content/progress-circular.mdx
> +```
Going to be working on building out some docs for this

2020-12-30 18:37 UTC, dbchristopher requested changes
This is feeling really great! I found a few more small things that could be cleaned up a bit, and after that it should be good to go 👍

2020-12-30 18:37 UTC, dbchristopher commented on packages/components/src/ProgressCircular/IndeterminateProgress.tsx
> +`
Just a small code style/best practices suggestion -- these styles could be rendered declaratively like so:

```suggestion
const spinnerRotateAnimations = () =>
  [...Array(9)].map(
    (_, i) =>
      `${i * 12.5}% {transform: rotate(${
        i * 0.5 * progressCircularConstants.arcSize
      }deg)}`
  )

const spinnerKeyFrames = keyframes`
  ${newSpinnerRotateAnimations().join('\n')}
`
```

2020-12-30 18:37 UTC, dbchristopher commented on packages/components/src/ProgressCircular/ProgressCircular.story.tsx
> +
I just noticed we should probably hide the progress argument altogether from the Indeterminate story.

```suggestion
Indeterminate.args = {
  size: 'large',
}
Indeterminate.argTypes = {
  progress: {
    table: {
      disable: true,
    },
  },
}
```

2020-12-30 18:37 UTC, dbchristopher commented on packages/components/src/ProgressCircular/ProgressCircular.story.tsx
> +}
The Determinate argTypes could be merged with the story default arg types to consolidate that a bit.

```suggestion
export default {
  component: ProgressCircular,
  title: 'ProgressCircular',
  argTypes: {
    size: {
      control: {
        type: 'select',
        options: ['xsmall', 'small', 'medium', 'large'],
      },
    },
    progress: {
      control: { type: 'range', min: 0, max: 1, step: 0.1 },
    },
  },
```

2020-12-30 18:37 UTC, dbchristopher commented on www/src/documentation/components/content/progress-circular.mdx
> +## Showing an unknown wait time
```suggestion
## Showing a generic loading state
```

2020-12-30 18:37 UTC, dbchristopher commented on www/src/documentation/components/content/progress-circular.mdx
> +## Indicating a known wait time
```suggestion
## Rendering defined async progress
```

2020-12-30 18:37 UTC, dbchristopher commented on www/src/documentation/components/content/progress-circular.mdx
> +If the time a process takes can be determined, you can use the `progress` prop to indicate how far along the process has progressed. The `progress` prop accepts a number from `0` to `1`, where `0` is
```suggestion
If the process has known steps to completion, you can use the `progress` prop to indicate a more precise loading state. The `progress` prop accepts a number from `0` to `1`, where `0` is 0% complete and `1` is 100% complete.
```

I think we should remove reference to time from these docs, since it's not actually dealing in seconds or minutes.

2020-12-30 18:37 UTC, dbchristopher commented on www/src/documentation/components/content/progress-circular.mdx
> +```
The fixed ButtonToggle values are a nice solution! If you did still want to render a slider UI, you could just divide the value by 100 to get the decimal:

```suggestion
```jsx
;() => {
  const [progress, setProgress] = useState(50)

  return (
    <SpaceVertical>
      <ProgressCircular progress={progress / 100} />
      <Space>
        <Slider
          min={0}
          max={100}
          value={progress}
          onChange={(e) => {
            setProgress(e.target.value)
          }}
        />
      </Space>
    </SpaceVertical>
  )
}
```

Either way is fine with me though!

2021-01-06 17:42 UTC, closed without merging