Tree: "brand" color prop
looker-open-source/components pull request #1724
Opened 2020-12-23 01:13 UTC by ElliotTheHuman

### :sparkles: Changes

- Created a `getBackgroundColor` util function
- `Tree`, `TreeItem` support `brand` prop to change default state coloring

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots
<img width="736" alt="Screen Shot 2020-12-22 at 5 12 39 PM" src="https://user-images.githubusercontent.com/16812885/102947766-ebeeeb80-4478-11eb-881e-29e23f71614f.png">

2020-12-23 14:18 UTC, jhardy commented on www/src/documentation/components/content/tree.mdx
> +    </Tree>
```suggestion
    </Tree>
    </>
```

Need to close fragment

2020-12-23 14:25 UTC, jhardy commented on www/src/documentation/components/content/tree.mdx
> +    </Tree>
One small think I noticed is the selected color for the top level `Tree` and a `TreeItem` are slightly difference
![image](https://user-images.githubusercontent.com/170681/103007110-afa6a400-44e7-11eb-8fdf-043a6531671d.png)

2020-12-23 14:36 UTC, jhardy commented on www/src/documentation/components/content/tree.mdx
> +    </Tree>
One other small nit is that the hover state when branded switches to a darker color, but it does not do this on the non branded color application. I think we should probably consistent here 
![image](https://user-images.githubusercontent.com/170681/103007830-f8ab2800-44e8-11eb-8e2c-380e80c85529.png)

2020-12-23 14:42 UTC, jhardy commented on www/src/documentation/components/content/tree.mdx
> +    </Tree>
I lied, one other small nit, in this example the nested tree items are disabled, yet you can still toggle them open and close, is that the correct behavior? 

https://user-images.githubusercontent.com/170681/103008370-e1206f00-44e9-11eb-9819-d54ed3cfb7d0.mp4

2020-12-23 18:09 UTC, lukelooker reviewed
Add some nits around function structure (I'll leave design decisions to people like @jhardy who are actually qualified) :)

2020-12-23 18:09 UTC, lukelooker commented on packages/components/src/Tree/TreeItem.tsx
> +  }};
Probably worth pulling this whole thing out as a helper function as the CSS block here is a pretty epic read :)

```
const treeItemBackground = (props: TreeItemLabelProps) => css`background:  ...;`
```

2020-12-23 18:09 UTC, lukelooker commented on packages/components/src/Tree/TreeItem.tsx
> +      Boolean(brand),
`Boolean(brand),` should be handled inside `getBackgroundColor` rather than requiring type-casting in multiple places.

2020-12-23 18:09 UTC, lukelooker commented on packages/components/src/Tree/utils/getBackgroundColor.ts
> +}
Move this up to `Tree` and consume it from there so that this function is leveraging an interface shared across the actual components and this helper function.

2020-12-23 18:48 UTC, mdodgelooker requested changes
Similar thoughts to @lukelooker on the `getBackgroundColor` utility but maybe went a bit further :) and put my suggestions in a PR: https://github.com/looker-open-source/components/pull/1727

2020-12-23 22:51 UTC, ElliotTheHuman commented on www/src/documentation/components/content/tree.mdx
> +    </Tree>
Good calls @jhardy. Tried to organize my responses to each below:

```
One small think I noticed is the selected color for the top 
level Tree and a TreeItem are slightly difference
```
Ah good point. To clarify, I _believe_ we made the compromise with the Explore team to use a lightened version of `ui2` for `Tree`/`TreeItem`. Do we want to use that lightened version (using `itemSelectedColor(props.theme.colors.ui2)`) or just stick with `ui2`?

@lukelooker Might have more insight on the `itemSelectedColor` function we're using here.

```
One other small nit is that the hover state when branded switches to a darker color, 
but it does not do this on the non branded color application. I think we should probably consistent here
```
Understood. Was following the specs laid out in [LENS-1293](https://looker.atlassian.net/browse/LENS-1293) which had a color switch on selected-hovered for keyColor but not for standard.

Thoughts on whether we should remove the color switch from the keyColor suite or add the color switch to the standard suite?

```
another small nit, in this example the nested tree items are disabled, 
yet you can still toggle them open and close, is that the correct behavior?
```
This was intentional. For context (afaik), DiscoNav wants `Tree`s to be selectable like `TreeItem`s. However, there's a world where a folder (represented by a `Tree`) shouldn't be selectable but a child of that folder is, if that makes sense.
![Screen Shot 2020-12-23 at 2 50 17 PM](https://user-images.githubusercontent.com/16812885/103042356-2ebecb00-452e-11eb-824a-7b896ecc029b.png)

2020-12-23 23:18 UTC, ElliotTheHuman commented on www/src/documentation/components/content/tree.mdx
> +    </Tree>
Discussed with Jared over a meet. Here's what we came up with:

```
One small think I noticed is the selected color for the top 
level Tree and a TreeItem are slightly difference
```
`Tree` and `TreeItem` should both use that ui1.5 (itemSelectedColor(ui2))

```
One other small nit is that the hover state when branded switches to a darker color, 
but it does not do this on the non branded color application. I think we should probably consistent here
```
For `Tree` in particular, we'll have keySubtle for both selected and selected+hovered to create consistency with the standard color suite. This might extend to other `keyColor` suite components (i.e. Combobox and Select) but we'll revisit this later.

```
another small nit, in this example the nested tree items are disabled, 
yet you can still toggle them open and close, is that the correct behavior?
```
@jhardy will follow up with the designer on `DiscoNav` to figure out their use case with `disabled`. That should hopefully inform how the prop should act / what it should be named.

2020-12-23 23:34 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeItem.tsx
> +  }};
Resolved in 6f36b33

2020-12-23 23:34 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeItem.tsx
> +      Boolean(brand),
Resolved in 6f36b33

2020-12-23 23:41 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeItem.tsx
> +  const brand = undefinedCoalesce([props.brand, treeContext.brand])
Resolved in 42c1032

2020-12-23 23:56 UTC, ElliotTheHuman commented on packages/components/src/Tree/utils/getBackgroundColor.ts
> +}
Resolved in eed935c

2021-01-05 18:52 UTC, ElliotTheHuman commented
Poking @lukelooker and @mdodgelooker for re-review!

2021-01-05 19:59 UTC, lukelooker submitted a review, later dismissed
LGTM - core logic function is an easy read now. Thank you!

2021-01-05 20:00 UTC, mdodgelooker requested changes
Just a small nit on the `Omit` usage.

2021-01-05 20:00 UTC, mdodgelooker commented on packages/components/src/Tree/Tree.tsx
> +    Omit<TreeBackgroundStyleProps, 'hovered' | 'theme'> {
```suggestion
    Omit<TreeBackgroundStyleProps, 'hovered'> {
```

2021-01-05 20:08 UTC, mdodgelooker reviewed
Also `border` doesn't seem to be working but I can't tell why. Maybe it's not from this PR? Was it an intentional change in a previous PR? I vaguely remember a tree border discussion coming up at some point...

2021-01-05 20:15 UTC, mdodgelooker commented on packages/components/src/Tree/utils/treeBackgroundColor.ts
> +  else renderedColor = colors.background
Aha, my bad. My earlier suggestion to add `colors.background` as the fallback is covering up the border style.

2021-01-05 20:49 UTC, ElliotTheHuman commented on packages/components/src/Tree/utils/treeBackgroundColor.ts
> +  else renderedColor = colors.background
Ah good catch. I'm a bit stumped as to what the ideal solution is here. `colors.background` plays nice with dark backgrounds, but not with border. And "none" plays nice with border but not dark backgrounds.

Would accepting `border` as a part of the parameter object and using `colors.background` or "none" depending on if `border` is true be the right answer? The downside to this is that using border would be unsupported for dark background afaik.

2021-01-05 20:50 UTC, ElliotTheHuman commented on packages/components/src/Tree/utils/treeBackgroundColor.ts
> +  else renderedColor = colors.background
Tagging @lukelooker and @jhardy if interested

2021-01-05 20:56 UTC, mdodgelooker commented on packages/components/src/Tree/utils/treeBackgroundColor.ts
> +  else renderedColor = colors.background
@ElliotTheHuman I'd say for this PR go back to `none` like it was before. Has anyone complained about `Tree` on a dark bg? If/when they do, a new PR can figure it out.

2021-01-05 21:01 UTC, mdodgelooker commented on packages/components/src/Tree/utils/treeBackgroundColor.ts
> +  else renderedColor = colors.background
Random thought – I wonder why the `yarn image-snapshots` didn't complain? It looks like on master, it isn't showing the borders: https://github.com/looker-open-source/components/blob/master/packages/components/snapshots/Tree/Border-snap.png
Perhaps the renderer can't handle the gradient...

2021-01-05 22:28 UTC, ElliotTheHuman commented on packages/components/src/Tree/utils/treeBackgroundColor.ts
> +  else renderedColor = colors.background
Eek. That's a bummer 😞 

For future reference, I will say that one of my monitors has had trouble rendering the `border` unless I zoom in. No issues when it comes to my Macbook Pro's screen, but my external monitor appears as if it isn't rendering the `border` (or does it so faintly that the naked eye can't see it).

2021-01-05 23:09 UTC, lukelooker requested changes
Minor nit on function return (no CSS req'd to do "nothing" in these cases.

2021-01-05 23:09 UTC, lukelooker commented on packages/components/src/Tree/utils/treeBackgroundColor.ts
> +  if (disabled) renderedColor = 'none'
You could just `return` here instead:

```suggestion
  if (disabled) return
```

2021-01-05 23:09 UTC, lukelooker commented on packages/components/src/Tree/utils/treeBackgroundColor.ts
> +  else renderedColor = 'none'
```suggestion
  else return
```

2021-01-05 23:15 UTC, ElliotTheHuman commented on packages/components/src/Tree/utils/treeBackgroundColor.ts
> +  if (disabled) renderedColor = 'none'
👍  Resolved in 7b76233

2021-01-05 23:16 UTC, ElliotTheHuman commented on packages/components/src/Tree/utils/treeBackgroundColor.ts
> +  else renderedColor = 'none'
👍  Resolved in 7b76233

2021-01-05 23:45 UTC, lukelooker approved these changes
LGTM (border works on high and low res monitors now)

2021-01-05 23:52 UTC, merged