DialogLayout improvements
looker-open-source/components pull request #1757
Opened 2021-01-07 20:19 UTC by lukelooker

### :sparkles: Changes

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2021-01-09 00:05 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.tsx
> +  )
If the `Dialog` has a footer we assume the footer includes affordances to close the `Dialog` and remove the "x" in the header (future-proofing for a world where that's no longer a supported pattern)

2021-01-09 00:05 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.tsx
> +        {isLoading ? <DialogLoading /> : children}
Built-in loading pattern :)

2021-01-11 18:07 UTC, mdodgelooker reviewed
I think this might need a rebase from the latest `main`. The sandboxes in gatsby aren't working right:
![image](https://user-images.githubusercontent.com/53451193/104220762-d116f380-53f4-11eb-97ca-58be5ce679a4.png)

2021-01-11 18:44 UTC, mdodgelooker requested changes
Looks great! Just `layout.mdx` needs a lil love.

2021-01-11 18:44 UTC, mdodgelooker commented on packages/components/src/Dialog/Layout/DialogLayout.tsx
> +        {isLoading ? <DialogLoading /> : children}
Right on!

2021-01-11 18:44 UTC, mdodgelooker commented on packages/components/src/Dialog/stories/SaveChanges.tsx
> +          </DialogLayout>
It's nice that you don't need the React Fragment anymore in this kind of composition. 🙂

2021-01-11 18:44 UTC, mdodgelooker commented on www/src/documentation/components/dialogs/layout.mdx
> +  This is a DialogHeader
```suggestion
  This is a DialogLayout
```
Should this section include content on when to use `DialogLayout` vs `DialogContent`?

2021-01-11 19:27 UTC, lukelooker commented on www/src/documentation/components/dialogs/layout.mdx
> +  This is a DialogHeader
Yep! Fixing.

2021-01-11 19:27 UTC, lukelooker commented
@mdodgelooker Broke apart the `Dialog Layout` page into per-component pages and improved the content on them :)

2021-01-11 19:30 UTC, mdodgelooker reviewed
LGTM!

2021-01-11 19:39 UTC, mdodgelooker approved these changes

2021-01-11 20:26 UTC, mdodgelooker approved these changes

2021-01-11 20:39 UTC, merged