Elliot/list
looker-open-source/components pull request #1773
Opened 2021-01-12 21:20 UTC by ElliotTheHuman

### :sparkles: Changes

- **Thank you for your contribution to Looker Components!**
- To ensure a successful review, please double check our checklist of requirements below.
- Also including a short description of changes and relevant screenshots will help us more quickly understand the ultimate goal of your work (🗑 replace this introduction with your summary of changes).

### :white_check_mark: Requirements

- [ ] Includes test coverage for all changes
- [ ] Build and tests are passing
- [ ] Update documentation
- [ ] Updated CHANGELOG
- [ ] Checked for i18n impacts
- [ ] Checked for a11y impacts
- [ ] Check for image-snapshot changes (run `yarn image-snapshots` locally)
- [ ] PR is ideally < ~400LOC

### :camera: Screenshots

2021-01-13 23:11 UTC, ElliotTheHuman commented on packages/components/src/List/utils/dimensions.ts
> +}
Wondering if it's just better to repeat out the specs for each density rather than spread them onto each other.

If we avoid spreading them, we could create an object where keys are density values and values are dimension objects, which could be more elegant!

2021-01-13 23:14 UTC, ElliotTheHuman commented on packages/components/src/List/List.tsx
> +        : 0,
We removed the use of `useMemo` here since we're not supporting 'variable' windowing at the moment. That being said, it could still be worth it to memoize that child height value.

@mdodgelooker @lukelooker Thoughts?

2021-01-13 23:35 UTC, mdodgelooker commented on packages/components/src/List/List.tsx
> +        : 0,
@ElliotTheHuman yep that should be fine – a function (for variable windowing) would be newly instantiated on every render, triggering too many changes downstream, hence the `useMemo` (can't do `useCallback` b/c it might be a number). Since it'll only ever be a number here, no need to memoize.

2021-01-14 20:09 UTC, lukelooker commented on packages/components/src/List/utils/dimensions.ts
> +}
Couldn't you get both by using these to create said object:

```
const densities = {
  1: densityP1,
  0: density0,
 -1: densityN1,
...
}

2021-01-14 20:09 UTC, lukelooker commented on packages/components/src/List/utils/getListItemDimensions.ts
> +}
With the object above this could become a simple object lookup:


```suggestion
export const getListItemDimensions = (
  density: DensityRamp
): ListItemDimensions => densities[density]
```

2021-01-14 22:19 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +          data-testid={`list-item-${renderedIconID}-icon-placeholder`}
We had this here strictly for help testing the ID iirc.

That being said, image snapshotting would probably work even better for testing that the placeholder behavior works on a branch. I'm for scrapping this (and the `useId` call) if you're cool with that.

2021-01-14 22:24 UTC, ElliotTheHuman commented on packages/components/src/List/List.tsx
> +
Resolved in 8ac36fd

2021-01-14 22:25 UTC, ElliotTheHuman commented on packages/components/src/List/List.tsx
> +  border-radius: inherit;
Carry over from `MenuList`. I can scrap it here if it's unneeded.

Resolved in 8ac36fd

2021-01-14 22:25 UTC, ElliotTheHuman commented on packages/components/src/List/List.tsx
> +  user-select: none;
Resolved in 8ac36fd

2021-01-14 22:28 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +  itemRole?: 'link' | 'button'
You are correct :( In this case, would the div w/ role="button" button trick be sufficient to get around this? Or is there a different solution that seems more appropriate?

2021-01-14 22:28 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +  tooltipPlacement?: Placement
Yes we can!

Resolved in 8ac36fd

2021-01-14 22:31 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +          iconGap={itemDimensions.iconGap}
Not that I can think of. We don't currently support just `MarginProps` though in design-tokens so I wasn't sure if bringing all of `SpaceProps` was the call. Is there a more appropriate interface or are we okay with giving it the whole space enchilada?

2021-01-14 22:49 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +      : props.rel
Resolved in 248f502 / 4ae2bb0

2021-01-14 22:54 UTC, ElliotTheHuman commented on packages/components/src/List/ListLabel.tsx
> +}
Good call. Got into a mix up between the remote and my local branch, and the label removal commit got lost in the crossfire.

Resolved in 03f544e

2021-01-14 22:56 UTC, ElliotTheHuman commented on packages/components/src/List/utils/getListItemDimensions.ts
> +}
That works for me! Honestly, my biggest thing with the object route was the naming convention I whipped up, but if it's passable there's definitely no downside afaik to having these available.

2021-01-14 23:04 UTC, ElliotTheHuman commented on packages/components/src/List/utils/getListItemDimensions.ts
> +}
Resolved in ab951f7

2021-01-14 23:05 UTC, ElliotTheHuman commented on packages/components/src/List/List.tsx
> +    WidthProps {
Makes sense for `List` to fill its container. I'm on board with removing these.

2021-01-14 23:08 UTC, ElliotTheHuman commented on packages/components/src/List/List.tsx
> +export const List = styled(ListInternal).attrs(({ minWidth = '12rem' }) => ({
Resolved in a025132

2021-01-14 23:08 UTC, ElliotTheHuman commented on packages/components/src/List/List.tsx
> +    WidthProps {
Resolved in a025132

2021-01-14 23:13 UTC, ElliotTheHuman commented on packages/components/src/List/utils/dimensions.ts
> +}
Resolved in a025132

2021-01-14 23:19 UTC, ElliotTheHuman commented on packages/components/src/List/List.tsx
> +    }
I think children-injection behavior makes sense here since no one outside of the direct `ListItem` children needs the current context info.

That being said, would there be any problems with the children-injection behavior if we introduced a `ListHeader` component that could also be a child of `List`? That's the only potential argument that favors context in my mind (that being said, might not be much of an argument).

2021-01-14 23:21 UTC, ElliotTheHuman commented
Addressed most of the conversations, but some seemed to require more back-and-forth so left those open!

2021-01-15 00:28 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +          data-testid={`list-item-${renderedIconID}-icon-placeholder`}
Will remove useId call here

2021-01-15 00:31 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +  const Component = !disabled && itemRole === 'link' ? 'a' : 'button'
Need "listItem"

2021-01-15 00:34 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +  const Component = !disabled && itemRole === 'link' ? 'a' : 'button'
```suggestion
  const Component = !disabled && itemRole === 'link' ? 'a' : itemRole === 'button' ? 'button' : Fragment
```

2021-01-15 00:41 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +`
Look to combine w/ `ListItemLayout`

2021-01-15 00:47 UTC, lukelooker commented on packages/components/src/List/List.tsx
> +      renderIconPlaceholder,
`iconGutter` instead - explicitly set on `List` default to false

2021-01-15 00:58 UTC, lukelooker commented on packages/components/src/List/utils/dimensions.ts
> +  py: 'xxsmall',
css`calc(${theme.xxsmall} + ${theme.xxxsmall})`

2021-01-15 01:21 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +`
Resolved in bc3c64a

2021-01-15 01:31 UTC, ElliotTheHuman commented on packages/components/src/List/utils/dimensions.ts
> +  py: '0.375rem',
IIRC, the plan was to leave the density objects alone and to leave a comment with this calc for now (in case we wanted to revisit how density worked and make these functions that can accept theme).

2021-01-15 02:12 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +          data-testid={`list-item-${renderedIconID}-icon-placeholder`}
Resolved in f1595fe

2021-01-15 02:13 UTC, ElliotTheHuman commented on packages/components/src/List/List.tsx
> +      renderIconPlaceholder,
Resolved in f1595fe

2021-01-15 02:27 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +          iconGap={itemDimensions.iconGap}
Resolved in 8438ef7

2021-01-15 02:55 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +  const Component = !disabled && itemRole === 'link' ? 'a' : 'button'
Bad news, good news.

Bad news: Setting `Component` to a Fragment breaks the item layout (`ListItemLayout` has selectors that give child `a` / `button` elements the necessary layout CSS)

Good news: If we set `Component` to a `div` and then add that `div` to the necessary selectors, we _should_ get the behavior we want (i.e. a container type that won't bork if the detail includes a button element).

I pushed up a commit b3d77be that shows what this `div` approach looks like. If it doesn't work here, we can definitely revert it and explore other options.

2021-01-15 02:59 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +  const Component = !disabled && itemRole === 'link' ? 'a' : 'button'
Follow-up: Commit 39a3882b removes a test that assumes `ListItem` is a `button` when disabled. With the commit described above, `ListItem` will only be a button if `itemRole` is explicitly "button".

2021-01-15 18:47 UTC, lukelooker requested changes
Ok, sorry, dug deeper and found a few more minor things to add.

We'll also need to add documentation but that can be a follow-up PR.

I did push a commit to change the density story to make cross-comparison easier and add a few variations I wanted to see for comparison as well:

![image](https://user-images.githubusercontent.com/34253496/104766224-130aa700-571f-11eb-964a-f915940ec0f0.png)

2021-01-15 18:47 UTC, lukelooker commented on packages/components/src/Icon/IconPlaceholder.tsx
> +  <div aria-hidden {...omit(props, 'iconGap')} />
Don't need this `omit` any more

2021-01-15 18:47 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +  icon?: IconNames
All props should have JSDoc descriptions

2021-01-15 18:47 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +   * - Use **'none'** for all other items
Thought... do we need `'none'` or is `undefined` basically inferring that already?

Another thought, should assigning `onClick` infer `button` or `link` and if so, which one? (`button` feels right but I'm not 100% sure of that)

2021-01-15 18:47 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +   * @default 'none'
`undefined` doesn't have a default really (see comment above)

2021-01-15 18:47 UTC, lukelooker commented on packages/components/src/Form/Inputs/Select/SelectOptions.tsx
> +        mr="xsmall"
`mr` should be a default value on `IconPlaceholder` I think (both use cases assign it so it seems a safe default)

2021-01-15 18:47 UTC, lukelooker commented on packages/components/src/Icon/IconPlaceholder.tsx
> +  <div aria-hidden {...omit(props, 'iconGap')} />
Also `aria-hidden` could be assigned via `attrs`

This would end up looking something like:

```jsx
export const iconPlaceholder = styled.div.attrs<IconPlaceholderProps>(
  ({ mr = 'xsmall' }) => ({ 'aria-hidden': true, mr })
  )<IconPlaceholderProps>`
  ${size}
  ${space}
`
```

2021-01-15 20:22 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/Select/SelectOptions.tsx
> +        mr="xsmall"
Resolved in 4b86540

2021-01-15 20:22 UTC, ElliotTheHuman commented on packages/components/src/Icon/IconPlaceholder.tsx
> +  <div aria-hidden {...omit(props, 'iconGap')} />
Resolved in 4b86540

2021-01-15 20:26 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +  icon?: IconNames
Resolved in 4b86540

2021-01-15 20:26 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +   * @default 'none'
Resolved in 4b86540

2021-01-15 23:09 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +   * - Use **'none'** for all other items
As discussed, the plan is to do a follow-up PR, bringing in the "detailAccessory" pattern from `Tree` (along with "hover disclosure" and "truncate").

This means that the item label will always be a button / link, but devs can use "detailAccessory" if they want to have a button in the detail element (to get around the button within a button problem).

2021-01-15 23:43 UTC, lukelooker approved these changes
LGTM.

2021-01-16 00:00 UTC, merged