feat: List & ListItem detail props
looker-open-source/components pull request #1800
Opened 2021-01-21 19:46 UTC by ElliotTheHuman

- Added detailAccessory and detailHoverDisclosure props to `List` and `ListItem`
- Added truncate prop to `ListItem`
- Added detailAccessory and detailHoverDisclosure-related tests 
- Added typography and textColor styled functions to `Truncate`

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] Includes test coverage for all changes
- [ ] Documentation updated
- [ ] i18n impacts
- [ ] a11y impacts
- [ ] :rotating_light: Check for image-snapshot changes (run `yarn image-snapshots` locally)

2021-01-21 19:55 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemLayout.tsx
> +    description ? height + 16 : height}px;
Debating whether this should be min-height or height.

min-height would mean that the item container could expand vertically to properly fit content, but that would throw off the specific measurements we had for each density value.

height would keep density values mapped to specific heights, but putting taller items as content / detail could lead to weirdness.

This choice could affect Explore's Field Picker since we're currently using no vertical padding on `TreeItem`, which allows them to cleanly fit a 24px Icon into a 24px TreeItem.

![image](https://user-images.githubusercontent.com/16812885/105404800-3d58da80-5bdf-11eb-92c9-c56cc3546eda.png)


@jhardy

2021-01-21 20:02 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemLayout.tsx
> +  & > a {
Adding a button or link element in the detail was affected by these selectors previously. Making them more specific should solve that.

2021-01-21 20:04 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemLayout.tsx
> +    /* stylelint-disable */
Hit an odd stylelint issue involving space before the bang operator. Definitely open to suggestions on this one if the disabling isn't ideal.

2021-01-21 20:06 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemDetail.tsx
> +  ${padding}
I needed to be able to have padding on the `ListItemDetail` when detailAccessory === true, but NOT when it was false (i.e. the parent layout container takes care of padding if false).

Giving this padding props seemed like the best solution, but could be wrong.

2021-01-21 20:07 UTC, ElliotTheHuman commented on packages/components/src/Truncate/Truncate.tsx
> +    CompatibleHTMLProps<HTMLSpanElement> {
Felt like `Truncate` could use TypographyProps. My thought was that since it was used in place of Paragraph depending on X prop, it should have similar props to Paragraph.

2021-01-22 01:27 UTC, lukelooker reviewed
When `ListItem` has a `detail` & is `selected` with `detailAccesssory` the hover behavior doesn't look quite as-expected:

![image](https://user-images.githubusercontent.com/34253496/105431724-0ac4d700-5c0b-11eb-9918-22f72a2a9fc3.png)

2021-01-22 01:27 UTC, lukelooker commented on packages/components/src/List/List.tsx
> +  detailHoverDisclosure?: boolean
I'm _tempted_ to say that we shouldn't support these on list and only support them directly on `listItem`

2021-01-22 01:27 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +  detailHoverDisclosure?: boolean
Crazy idea... what if `detail` took one of two type signatures:

```tsx
interface DetailOptions {
  /**
   * If true, child ListItems' detail will appear outside of the item's grey background on hover
   * In addition, if true, events will not propagate from the detail container
   * @default false
   */
  accessory?: boolean
  /**
   * If true, child ListItems' detail will only appear on hover
   * @default false
   */
  hoverDisclosure?: boolean
}

interface ListItem {
  ...
  detail: ReactNode | { content: ReactNode, options: DetailOptions }
}
```

2021-01-22 01:27 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +      )
Use dynamic component reference to simplify this some...

```
     const Component = truncate ? Truncate : Paragraph

     (<Component
        fontSize={itemDimensions.labelFontSize}
        lineHeight={itemDimensions.labelLineHeight}
      >
        {children}
      </Component>
      )
```

2021-01-22 01:27 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +        </Paragraph>
Dynamic JSX can be used here too.

2021-01-22 01:27 UTC, lukelooker commented on packages/components/src/List/ListItemDetail.tsx
> +  ${padding}
I'd be tempted to make the solution narrower by having an `accessory` prop that just toggles the padding value as needed instead of making `PaddingProps` available any upstream `ListItemDetail` consumers.

2021-01-22 01:27 UTC, lukelooker commented on packages/components/src/List/ListItemLayout.tsx
> +    description ? height + 16 : height}px;
Hmmm...

2021-01-22 01:27 UTC, lukelooker commented on packages/components/src/List/ListItemLayout.tsx
> +    }};
Probably worth lifting this out into a separate function given the level of complexity within.

2021-01-22 01:27 UTC, lukelooker commented on packages/components/src/List/ListItemLayout.tsx
> +    /* stylelint-disable */
I wonder if you could do something like `detailAccessory === false && colors.ui1` to not upset stylelint?

2021-01-22 01:27 UTC, lukelooker commented on packages/components/src/Truncate/Truncate.tsx
> +    CompatibleHTMLProps<HTMLSpanElement> {
Probably fair. It's worth noting that `Truncate` uses a `span` underneath but also has `display: block` so it's an odd fit but I can live with it.

2021-01-22 23:23 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemLayout.tsx
> +    description ? height + 16 : height}px;
Discussed over Meet, but the plan is to try a css grid implementation that allows detail children to be as big as their parent container.

2021-01-22 23:29 UTC, ElliotTheHuman commented on packages/components/src/List/List.tsx
> +  detailHoverDisclosure?: boolean
Resolved in c82b064

2021-01-22 23:30 UTC, ElliotTheHuman commented on packages/components/src/Truncate/Truncate.tsx
> +    CompatibleHTMLProps<HTMLSpanElement> {
Resolved in 49909b9

2021-01-22 23:45 UTC, ElliotTheHuman commented on packages/components/src/Truncate/Truncate.tsx
> +    CompatibleHTMLProps<HTMLSpanElement> {
Resolved in 49909b9

2021-01-23 01:06 UTC, ElliotTheHuman commented on packages/components/src/List/utils/getItemBackgroundColor.ts
> +  else renderedColor = 'transparent'
disabled and else needed to output a valid "background-color" CSS value. Otherwise, the browser's default button CSS takes over in `ListItemLayout`.

2021-01-23 01:09 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemLayout.tsx
> +    /* stylelint-disable */
Resolved in 66bbd9c

2021-01-25 19:57 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +        </Paragraph>
Resolved in f838b1b

2021-01-25 19:57 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +      )
Resolved in f838b1b

2021-01-27 00:07 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemLayout.tsx
> +    }};
Resolved in 66d4330

2021-01-27 00:07 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +  detailHoverDisclosure?: boolean
Resolved in eaa1187

2021-01-27 00:08 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemLayout.tsx
> +    description ? height + 16 : height}px;
Resolved in 66d4330

2021-01-27 00:16 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemDetail.tsx
> +  ${padding}
The one problem is that a `ListItem`'s density determines the size of the conditional "padding-right" on `ListItemDetail`. In which case we need two props (i.e. "density" and "accessory") to replace `PaddingProps` props.

I can do that if that's preferable here!

2021-01-27 00:20 UTC, ElliotTheHuman commented
Hey Luke! Got the first round of List & ListItem feedback done. Everything was straightforward except the potential grid implementation (see commit 66d4330).

TLDR is that I couldn't get grid to solve for a lot of the confusing pieces, like the conditional padding on the `ListItemDetail` or having the detail sit within or outside of the internal "button" / "a" element. Apologies ahead of time I'm ignorant to any grid-related properties / magic :( It did help organize some of the JSX structure in the `ListItem` component (but did require the addition of more containers within).

2021-01-27 06:51 UTC, lukelooker reviewed
Let's chat tomorrow morning about grid challenges here - overall this is looking really great and I think I have an idea or two about how we can perhaps make managing the "accessory" implementation less painful.

2021-01-27 06:51 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +  selected?: boolean
`current` and `selected` may need to both exist as `current` has a specific ARIA meaning (current page) vs. `selected` - not exactly sure the right answer here but we should discuss / research what the best practice here needs to be. It may be the case that `selected` and/or `current` needs to either-or perhaps? Anyway, topic to ponder a bit.

2021-01-27 06:51 UTC, lukelooker commented on packages/components/src/List/types.ts
> +   * If true, the Tree/TreeItem will have a darker background color
```suggestion
   * If true, the ListItem will have a darker background color
```

2021-01-27 06:51 UTC, lukelooker commented on packages/components/src/List/types.ts
> +   * If true, the Tree/TreeItem will have a light background color
```suggestion
   * If true, the ListItem will have a light background color
```

2021-01-27 06:51 UTC, lukelooker commented on packages/components/src/List/types.ts
> +   * If true, the Tree/TreeItem will have a "disabled" presentation.
```suggestion
   * If true, the ListItem will have a "disabled" presentation.
```

2021-01-27 06:51 UTC, lukelooker commented on packages/components/src/List/types.ts
> +  brand?: boolean
It occurs to me that `brand` isn't used anywhere else but `keyColor` is supported by `Link` so it'd be more consistent to use that and create an association the the `theme.colors.key`

```suggestion
  /**
   * Replace the normal uiX color for selected and selected + hovered color with key colors
   * @default false
   */
  keyColor?: boolean
```

2021-01-27 06:51 UTC, lukelooker commented on packages/components/src/List/utils/getItemBackgroundColor.ts
> +import { ItemBackgroundColorProps } from '../types'
Admittedly, it's annoyingly long but I think for consistency's sake we should title this file and it's interface/functions `ListItemBackgroundColorProps`

2021-01-27 06:51 UTC, lukelooker commented on packages/components/src/List/ListItem.story.tsx
> +
Would be good to add an example of `truncate` + `detail` & `icons` to make sure layout plays nice in a worst-case scenario.

2021-01-27 21:02 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.story.tsx
> +
Resolved in c886cb4!

2021-01-27 21:21 UTC, ElliotTheHuman commented on packages/components/src/List/types.ts
> +  brand?: boolean
Resolved in 4b6f7ad

2021-01-27 21:21 UTC, ElliotTheHuman commented on packages/components/src/List/types.ts
> +   * If true, the Tree/TreeItem will have a "disabled" presentation.
Resolved in c6c8885

2021-01-27 21:22 UTC, ElliotTheHuman commented on packages/components/src/List/types.ts
> +   * If true, the Tree/TreeItem will have a light background color
Resolved in c6c8885

2021-01-27 21:22 UTC, ElliotTheHuman commented on packages/components/src/List/types.ts
> +   * If true, the Tree/TreeItem will have a darker background color
Resolved in c6c8885

2021-01-27 23:26 UTC, ElliotTheHuman commented on packages/components/src/List/utils/getItemBackgroundColor.ts
> +import { ItemBackgroundColorProps } from '../types'
👍  7b0516b

2021-01-28 00:01 UTC, ElliotTheHuman commented on packages/components/src/List/utils/getItemBackgroundColor.ts
> +import { ItemBackgroundColorProps } from '../types'
Resolved in 0a34bfa!

However, what do you think of the name `ListItemStateProps`? I know that set of props functionally exists to determine the background color of the `ListItem`, but they are reflective of the "state" of the `ListItem` (outside of `keyColor`).

2021-01-28 00:25 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemDetail.tsx
> +  ${padding}
Accidentally minimized Luke's previous comment (thought it was a dupe). Added it back here:
```
I'd be tempted to make the solution narrower by having an accessory prop that just toggles the 
padding value as needed instead of making PaddingProps available any upstream ListItemDetail consumers.
```

2021-01-28 18:58 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +  selected?: boolean
Resolved in 9352c1e

2021-01-28 19:07 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +    )
Ended up going with `Paragraph` and conditionally toggling it's `truncate` prop (didn't realize `Paragraph` had a truncate prop in retrospect 🤦 ).

Considering we check the type of the child / description, it felt like wrapping it in a `Paragraph` was the simplest way to get the right dimensions / truncation behavior.

2021-01-29 00:10 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemLayout.tsx
> +  ${(props) => listItemPadding({ accessory: false, ...props })}
I thought having the Layout components handle the padding  made the most readability sense (i.e. packaging the conditional padding with the different JSX layouts).

That being said, I could see an argument for moving this up to the `ListItemWrapper` component so that we're a bit more DRY.

2021-01-29 00:13 UTC, ElliotTheHuman commented
Summary of the layout changes!

- Added `ListItemWrapper` which is essentially the same as the old `ListItemLayout` (i.e. renders the `li` and handles (most of the) list styling 
- Added `ListItemLayout` and `ListItemLayoutAccessory` which represent the different layout options when accessory is off or on, respectively.
- `ListItem`'s primary purpose to distribute props to either `Layout` or `Wrapper` and also construct the "rendered" children (i.e. icon, children, description, detail)

2021-01-29 18:02 UTC, lukelooker requested changes
Ok - a small pile of what I think is mostly minor nits.

If `codecov` complaints look tricky we can go ahead and defer those for later.

Super excited to enable `Tree`/`TreeItem` density support soon! :)

2021-01-29 19:15 UTC, ElliotTheHuman commented on packages/components/src/List/types.ts
> +export interface ListItemBackgroundColorProps {
Resolved in 0a279378e!

2021-01-29 19:15 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +    />
Resolved in 0a279378e

2021-01-29 19:15 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeItem.tsx
> +  extends ListItemBackgroundColorProps,
Resolved in 0a279378e!

2021-01-29 20:08 UTC, ElliotTheHuman commented on packages/components/src/List/types.ts
> +}
I don't love this name, but can't come up with anything more concise.

I _could_ do something like `ListItemFullStateful` but figured being explicit was probably more important. This component _should_ only be used by things like `TreeStyle` and the `listItemBackground` util since nothing that devs should touch should have a "hovered" prop.

2021-01-29 20:08 UTC, ElliotTheHuman commented on packages/components/src/Tree/Tree.tsx
> +        keyColor={hasKeyColoring}
Resolved in 8861783

2021-01-29 20:08 UTC, ElliotTheHuman commented on packages/components/src/Tree/Tree.tsx
> +        keyColor: hasKeyColoring,
Resolved in 8861783

2021-01-29 20:09 UTC, ElliotTheHuman commented on packages/components/src/List/types.ts
> +  hovered?: boolean
Ended up creating another interface since `hovered` is necessary in >1 spots.

Don't love the name I came up with though. Added a comment covering the new interface below.

2021-01-29 23:18 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +      <Paragraph
Should be resolved in b1eb581

2021-01-29 23:19 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemWrapper.tsx
> +    `&:focus-within button:after,
Left a note about an attempted test at this behavior. See comment below.

2021-01-29 23:21 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.test.tsx
> +    )
Based on the [RTL docs](https://testing-library.com/docs/dom-testing-library/api-configuration/#computedstylesupportspseudoelements), the pseudo-selector parameter in getComputedStyle is not supported by JSDom. Afaik, I don't think there's another way to test the ":after" pseudo-element that creates the purple border when focusVisible === true to make codecov happy.

Could be wrong though (hopefully)! For now, leaving an xtest for future development felt like the right call.

2021-01-30 00:26 UTC, lukelooker commented on packages/components/src/List/ListItem.test.tsx
> +    )
Ah... yes, this is a case where we need to use `jest-image-snapshot` to drive a `puppeteer` instance, move focus and then take a picture. 

Suffice it to say a problem for another day :)

2021-01-30 00:27 UTC, lukelooker commented on packages/components/src/List/types.ts
> +}
👍  - Perhaps someday the perfect name will pop into my head but I can live with this as-is for now :)

2021-01-30 00:29 UTC, lukelooker approved these changes
Such `List`, much wow!

![List](https://media.giphy.com/media/B7o99rIuystY4/giphy-downsized.gif)

2021-01-30 00:32 UTC, merged