feat:Lara/panel
looker-open-source/components pull request #1815
Opened 2021-01-25 17:31 UTC by laraharrow

Thank so much for contributing to @looker/components!

The CI & [README](https://github.com/looker-open-source/components/blob/main/README.md) should help to make most of our code standards clear

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] Includes test coverage for all changes
- [ ] Documentation updated
- [ ] i18n impacts
- [ ] a11y impacts
- [ ] :rotating_light: Check for image-snapshot changes (run `yarn image-snapshots` locally)

2021-01-27 01:33 UTC, lukelooker reviewed
Preliminary feedback - still need to run / test locally

2021-01-27 01:33 UTC, lukelooker commented on packages/components/CHANGELOG.md
> +- Properly build ems/cjs/ts for easy deep-imports ([#1804](https://github.com/looker-open-source/components/issues/1804)) ([2a523cd](https://github.com/looker-open-source/components/commit/2a523cd70b
Remove change here

2021-01-27 01:33 UTC, lukelooker commented on packages/components/CHANGELOG.md
> +- updated allComponents.ts to have Aside, Footer, Header, Layout, Page, Section
Remove this change

2021-01-27 01:33 UTC, lukelooker commented on packages/components/src/Panel/HeaderPanel.tsx
> +   * @default 'left'
Needs explanation beyond default value :)

What's this do?

2021-01-27 01:33 UTC, lukelooker commented on packages/components/src/Panel/HeaderPanel.tsx
> +  cursor: pointer;
Only the IconButton should have a specialized cursor (which it already does)

```suggestion
```

2021-01-27 01:33 UTC, lukelooker commented on packages/components/src/Panel/HeaderPanel.tsx
> +  display: inline-flex;
```suggestion
  display: flex;
```

2021-01-27 01:33 UTC, lukelooker commented on packages/components/src/Panel/Panel.test.tsx
> +        </MenuList>
Simplify composition here to not have cross-component test

```suggestion
        <ul>
            <li><button onClick={open} icon="Check">Option A</button></li>
            <li icon="Check">Option B</li>
        </ul>
```

2021-01-27 01:33 UTC, lukelooker commented on www/src/documentation/components/layout/panel.mdx
> +
Simplify to `List` rather than `Menu`, don't use in-product language (cheese only please)

2021-01-27 01:33 UTC, lukelooker commented on packages/components/src/Panel/Panel.story.tsx
> +          </MenuList>
We should use `List` / `ListItem` instead of `Menu*` and switch to cheeses instead of using in-product examples:

```suggestion
         <Heading size="small" color="neutral">Cheese Selections</Heading>
          <List>
            <ListItem onClick={toggleExplore} icon="ExploreOutline">
              Cheddar
            </ListItem>
            <Panel content={'content from display...'} title="Develop">
                <ListItem icon="Code">Gouda</ListItem>
            </Panel>
            <ListItem icon="Group">Provolone</ListItem>
          </List>
```

2021-01-27 02:50 UTC, laraharrow commented
Hey @lukelooker, ok so I think I change all the suggestions you asked somehow the docs are not quite working after I made the change.

2021-02-01 19:55 UTC, lukelooker requested changes
I know this is still waiting for final design-specs but I went ahead and did a pass on the code side of things. 

I found a few minor issues on the code/docs and also noticed that the animation is backwards and doesn't act properly when `placement="right"` is specified.

2021-02-01 19:55 UTC, lukelooker commented on packages/components/CHANGELOG.md
>  ## [0.10.2](https://github.com/looker-open-source/components/compare/v0.10.1...v0.10.2) (2021-01-22)
Undo all changes to CHANGELOG

2021-02-01 19:55 UTC, lukelooker commented on packages/components/src/Panel/PanelHeader.tsx
> +  direction?: 'left'
Panel enters / exits backwards. `left` means the `Panel` is attached to the left edge of the screen and should appear to enter and exit from the left. Currently when `direction="left"` the `Panel` enters and exits from the right instead.

2021-02-01 19:55 UTC, lukelooker commented on packages/components/src/Panel/PanelHeader.tsx
> +        label={`Close ${title} navigation`}
This will break if the user specifies a `ReactNode` for title. Probably need to check if `typeof title === 'string'` and only do this if that's true. Otherwise just say `Close`. Probably needs an optional prop for `closeLabel` that the developer can specify if they're sending a `ReactNode`

```suggestion
        label={`Close ${title}`}
```

2021-02-01 19:55 UTC, lukelooker commented on packages/components/src/Panel/PanelSurface.tsx
> +    transform: translateX(100%);
This needs to change if `direction='right'`

2021-02-01 19:55 UTC, lukelooker commented on www/src/documentation/components/layout/panel.mdx
> +
Need to add explanation of `Panels` in here somewhere.

2021-02-03 19:18 UTC, laraharrow commented
I think I fix the stuff you suggested, there is still the lines not tested from `codecov` some of them I'm not sure I know how to test.

2021-02-03 20:55 UTC, lukelooker commented
https://codecov.io/gh/looker-open-source/components/pull/1815/diff?src=pr&el=tree#diff-cGFja2FnZXMvY29tcG9uZW50cy9zcmMvUGFuZWwvUGFuZWxIZWFkZXIudHN4

`codecov` feedback:

![image](https://user-images.githubusercontent.com/34253496/106807861-7ef57680-661e-11eb-8645-6a8aaf494217.png)

Tests need to "exercise" each of these branches. I'd say for now go ahead and limit to just `left` & `right` since those are the only known use cases we currently have in mind. With that change you'd need to go ahead and add a test that sets `direction="right"` and `direction="left"` and then verify that the icon is being properly specified.


![image](https://user-images.githubusercontent.com/34253496/106808175-e7445800-661e-11eb-8c86-b8742977388c.png)

Add a test that uses the render prop form of `Panel`

![image](https://user-images.githubusercontent.com/34253496/106808221-f7f4ce00-661e-11eb-9874-31afc6cb5d6b.png)

Build a test that verifies that this throws an exception :)

2021-02-03 20:56 UTC, lukelooker requested changes
Added a comment with details regarding code coverage

2021-02-06 00:24 UTC, laraharrow commented
```        <Panel>
          <li>empty</li>
        </Panel>
        ```

2021-02-08 21:58 UTC, lukelooker requested changes
Really close - just some minor design nits.

2021-02-08 21:58 UTC, lukelooker commented on packages/components/src/Panel/index.ts
> +export * from './PanelHeader'
For now I don't think we need to export this

```suggestion
```

2021-02-08 21:58 UTC, lukelooker commented on packages/components/src/Panel/PanelSurface.tsx
> +    opacity: 0.01;
@jhardy Do we want a opacity fade with `Panel` or just a slide in?

2021-02-08 21:58 UTC, lukelooker commented on packages/components/src/Panel/PanelHeader.tsx
> +      mt="small"
In general we're trying to avoid using margin `m` but I'm not seeing a straightforward way to use it here for the `y` (vertical) values without giving more thought to how `Panel` is going to get used in general so I'm okay with it for now.

`height` can get pulled out of space tokens via `import { space } from '@looker/design-tokens/src/tokens/space'`

`px` can be used for the horizontal white-space.

`gap` defaults to medium but is spec'd for `small` in design

```suggestion
      height={space.xxlarge}
      px="large"
      gap="small"
      mt="small"
      mb="1.5rem"
```

2021-02-08 22:57 UTC, jhardy commented on packages/components/src/Panel/PanelSurface.tsx
> +    opacity: 0.01;
I think we should start with just sliding in now, we can look at refining transition down the road

2021-02-08 23:00 UTC, laraharrow commented on packages/components/src/Panel/PanelSurface.tsx
> +    opacity: 0.01;
great thanks I'l remove it

2021-02-10 10:43 UTC, lukelooker requested changes
Rebased branch to deal with a couple of minor merge conflicts.

I should've caught on earlier review but this doesn't have an image-snapshots. You can take a look at what we do for `Dialog` or `Drawer` for examples of how we capture this kind of component.  

I'd say a example for each "placement"  (right & left) of the `Panel` while open would do the trick

2021-02-11 06:20 UTC, lukelooker approved these changes
Rebased to pull out unrelated commits and snapshot changes. 

Ready to ship! :)

2021-02-11 17:29 UTC, merged