Elliot/tree refactor
looker-open-source/components pull request #1846
Opened 2021-02-02 02:20 UTC by ElliotTheHuman

Thank so much for contributing to @looker/components!

The CI & [README](https://github.com/looker-open-source/components/blob/main/README.md) should help to make most of our code standards clear

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] Includes test coverage for all changes
- [ ] Documentation updated
- [ ] i18n impacts
- [ ] a11y impacts
- [ ] :rotating_light: Check for image-snapshot changes (run `yarn image-snapshots` locally)

2021-02-02 19:03 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemContext.tsx
>    iconGutter: boolean
Because `ListItem` now accepts `density` directly, I thought it'd make sense to have the `ListItemContext` provide the density value instead of the `ItemDimensions` object (which was previously looked up in a parent `List` but now is looked up in each item).

Code readability-wise, I think this is cleaner (since the `ListItem` code reads as "If you gave me a density, use that density. Otherwise, use the context density"). However, we might not like the performance hit of each item doing its own dimension lookup.

Thoughts? Happy to retool `ListItemContext` to hold an itemDimensions object if that's the better route.

2021-02-03 01:07 UTC, ElliotTheHuman commented on packages/components/src/Tree/Tree.tsx
> +  }
All this dark magic is used to prevent the Accordion from opening when clicking a `Tree`'s detail element and `accessory === true`.

There's an argument to have this behavior baked into `List`, but I figure that this is specifically a `Tree` problem and so any dark magic belongs within `Tree`'s implementation.

2021-02-04 00:05 UTC, ElliotTheHuman commented on packages/components/src/Tree/stories/Tree.story.tsx
> -export * from './Flat.story'
Will create a `List` story with a header since that seems more appropriate than "Flat" `Tree`.

2021-02-04 01:33 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeHeading.tsx
> +      lineHeight="xsmall"
While it's possible to derive `fontSize` and `lineHeight` from the `Tree`'s density, the Explore team had specific desires about the sizing of the `Tree` group headers.

Keeping this set in stone for now made sense, or at least until someone requests for these to be scalable with density / customizable.

2021-02-04 01:34 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeStyle.tsx
> +      }
`font-weight` was being clobbered by the browser's default button CSS, so making this selector more specific does the trick (Note: this may not be the ideal solution, happy to discuss better alternatives).

2021-02-04 01:35 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeStyle.tsx
> +  & > ${Accordion} > ${AccordionContent} > ${List} > ${ListItem} > a {
These selectors (and the ones below) boil down to "Indent my direct child `TreeHeadings` and `ListItem`s

2021-02-04 17:18 UTC, lukelooker reviewed
Some minor questions and comments but overall this looks really great!

2021-02-04 17:18 UTC, lukelooker commented on packages/components/src/Tree/TreeHeading.tsx
> +    </Paragraph>
Does this need to be a `li` underneath to keep DOM happy? (immediate descendants of `<ul>` / `<ol>` is usually a `li`)

2021-02-04 17:18 UTC, lukelooker commented on packages/components/src/Tree/TreeHeading.tsx
> +    </Paragraph>
Ok - poked around, appears to not be a problem.

2021-02-04 17:18 UTC, lukelooker commented on packages/components/src/Tree/TreeItem.tsx
> +    </ListItem>
This file refactor is awesome 😃

2021-02-04 17:18 UTC, lukelooker commented on packages/components/src/Tree/TreeStyle.tsx
> +  & > ${Accordion} > ${AccordionContent} > ${List} > ${ListItem} > a {
Nesting could help make this easier to read:


```suggestion
  & > ${Accordion} > ${AccordionContent} > ${List} {
    & > ${TreeHeading}, & > ${ListItem} > button, ${ListItem} > a {
```

2021-02-04 17:18 UTC, lukelooker commented on packages/components/src/Tree/stories/BorderRadius.story.tsx
> +  ${Accordion} > ${AccordionContent} > ${List} > ${ListItem} > button {
Would be nice to find a way to make the old CSS work so upstream changes aren't needed / provide a stable styling "contract"

2021-02-04 17:18 UTC, lukelooker commented on packages/components/src/Tree/types.ts
> -  label: ReactNode
woohoo!

2021-02-04 17:18 UTC, lukelooker commented on packages/components/src/Tree/types.ts
> +  density?: DensityRamp
I wonder if we should just add this to `ListItem` since I could see cases where folks want / need to specify explicitly instead of at the `List` / `Tree` level?

2021-02-04 17:18 UTC, lukelooker commented on packages/components/src/Tree/TreeStyle.tsx
> +  & > ${Accordion} > ${AccordionContent} > ${List} > ${ListItem} > a {
Honestly I'm not sure my refactor here really helps - seems more complex if anything. AKA: Ignore me.

2021-02-04 19:56 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeHeading.tsx
> +    </Paragraph>
Good call. Technically speaking, this should probably be an `li` based on MDN:
![Screen Shot 2021-02-04 at 11 35 17 AM](https://user-images.githubusercontent.com/16812885/106945762-0f928c00-66dd-11eb-91f1-a3b0891a6647.png)

I read on an SO post that browsers can handle it, but it's pretty simple to get this wrapped in an `li` (Note: it does slightly change the selectors in `TreeStyle` but only by a smidge).

2021-02-04 20:25 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeHeading.tsx
> +    </Paragraph>
Resolved in d581d9b

2021-02-04 20:29 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +    color,
In this case, the default is just for `icon` (i.e. if given a color, use that color, otherwise, use "text1" for the icon). It does make sense though to not have the color logic sit in the prop where it's hard to parse out. I tried to make things a little more readable (as well as make the color prop work on `Tree`s in [this commit](d581d9b)).

Let me know what you think / how I can make this better!

2021-02-04 20:29 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +        color={color || 'text1'}
See comment above for additional thoughts

2021-02-04 20:35 UTC, ElliotTheHuman commented on packages/components/src/Tree/types.ts
> +  density?: DensityRamp
We did actually! We needed a way to pass the density value to the parent-most `Tree`'s inner item, and adding the prop onto `ListItem` made the most sense (but it's a @private so hopefully shouldn't be out in the wild too much).

2021-02-04 20:39 UTC, ElliotTheHuman commented on packages/components/src/Tree/stories/BorderRadius.story.tsx
> +  ${Accordion} > ${AccordionContent} > ${List} > ${ListItem} > button {
That would be ideal... would making it a prop be a viable option? Then it could just be on us to manage the border-radius'ing.

Alternatively, we _could_ try exporting the entire selector 😝  Haven't played around with it much, but in that world, users would just have to worry about importing the "direct child item selector + disclosure selector" and not have to maintain it in anyway.

2021-02-04 20:54 UTC, ElliotTheHuman commented
Note: did some reworking of how colors are distributed from Tree and TreeItem / ListItem.

Some of the logic gets hairy, but it's (mostly) all managed via props and not within the styled selectors which seems a little easier to follow. Default color "text5" of `Tree` structures is still set by a selector though.

2021-02-04 22:01 UTC, lukelooker commented on packages/components/src/Tree/TreeHeading.tsx
> +  color?: string
Probably ideal to use `TextColorProps`

2021-02-04 22:17 UTC, lukelooker commented on packages/components/src/Tree/stories/BorderRadius.story.tsx
> +  ${Accordion} > ${AccordionContent} > ${List} > ${ListItem} > button {
`ListItemLabel`

2021-02-05 01:14 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +  }))<ListItemLabelProps>``
This _should_ keep `itemRole` from getting down to the actual `div` element, correct? I'm not seeing any errors in the console, but wanted to make sure I was using "shouldForwardProp" properly here.

2021-02-05 01:14 UTC, ElliotTheHuman commented on packages/components/src/Tree/stories/BorderRadius.story.tsx
> +  ${Accordion} > ${AccordionContent} > ${List} > ${ListItem} > button {
Resolved in 8e727fb

2021-02-05 01:16 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeHeading.tsx
> +  color?: string
As discussed, we cut `TreeHeading` down to its bare bones (i.e. so that it's only role is to get proper indentation from parent `Tree` and contain children). Now known as `TreeBranch`.

Resolved in a8838ce

2021-02-05 21:32 UTC, ElliotTheHuman commented on packages/components/src/Truncate/Truncate.tsx
> +const TruncateLayout: FC<TruncateProps> = ({
I needed to be able to change line height on the `Truncate` container in `ListItem` since default button browser styling was clobbering / increasing `ListItem` height by 1px. 

However, couldn't change it directly on `Truncate`'s CSS because that would change the layout on existing `Truncate` use cases (i.e. `FieldCheckboxGroup`).

Decided that exporting `Truncate` as a styled component made sense, but let me know if that's something we totally do not want and I can rethink how we get the proper line-height for `ListItem` here.

2021-02-05 21:34 UTC, ElliotTheHuman commented on packages/components/src/List/utils/listItemPadding.ts
> +  const pr = space[propsPx]
We want that inner button / a to always have right padding (afaik). If the button content / label stretches to the edge in the `accessory` case, it would make sense for it to have some right padding rather than reach the edge of the button.

2021-02-05 21:38 UTC, ElliotTheHuman commented
Changes since last time:
- `Truncate` is now exported as a styled component for styling purposes within `ListItem`
- Added `ListItemLabel` styled component for easy border radius targeting
- Fixed some minor CSS issues (i.e. border on `TreeArtifical` being weird, `Truncate` + `accessory` not playing nicely because flex)
- `listItemPadding` always has right padding since  properly aligns unhovered, hoverDisclosure, accessory items

2021-02-05 21:39 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +  }))<ListItemLabelProps>``
Yep - that should swat it away :)

2021-02-05 21:44 UTC, ElliotTheHuman commented on packages/components/src/List/utils/listItemPadding.ts
> +  const pr = space[propsPx]
Previous implementation:
`const pr = accessory ? '0' : space[propsPx]`

2021-02-06 00:57 UTC, lukelooker approved these changes

2021-02-06 00:57 UTC, lukelooker commented on packages/components/src/List/ListItemLayoutAccessory.tsx
> +  labelCreator,
What's the reason to do this as a function instead of as a component?

2021-02-06 00:57 UTC, lukelooker commented on packages/components/src/List/ListItemLayoutAccessory.tsx
> +      {labelCreator({
Same as above - but why not do this as `<LabelCreator className={className}>content</LabelCreator>`?

2021-02-06 00:57 UTC, lukelooker commented on packages/components/src/Truncate/Truncate.tsx
> +  const className = join([domProps.className, propsClassName], ' ')
I'd just use built-in join here. 

```suggestion
  const { className, otherDomProps } = domProps
  const className = [className, propsClassName].join(' ')
```

2021-02-06 00:57 UTC, lukelooker commented on packages/components/src/Truncate/Truncate.tsx
> +        {...omit(domProps, 'className')}
```suggestion
        {...otherDomProps}
```

2021-02-06 00:57 UTC, lukelooker commented on packages/components/src/Truncate/Truncate.tsx
> +import omit from 'lodash/omit'
Down with `lodash` (see below)

2021-02-06 00:57 UTC, lukelooker commented on packages/components/src/Truncate/Truncate.tsx
> +const TruncateLayout: FC<TruncateProps> = ({
I'm cool with exporting this but we should log a ticket to eventually fix `Truncate` to have `line-height: 1` (fixing the locations that depend on that) because it really does seem more "correct" that way and then we could unwind `Tree`'s need to reach-in as it were.

2021-02-06 01:01 UTC, lukelooker commented on packages/components/src/List/ListItemLayoutAccessory.tsx
const LabelCreator = labelCreator

2021-02-06 01:43 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemLayoutAccessory.tsx
> +      {labelCreator({
Discussed over meet, but because `LabelCreator` needs to wrap around the content in the `XLayout` components, we would need to pass in the component via a prop, then set it to a variable with a capital name so that we can create JSX elements off of it.

IIRC, the plan is to keep things as they are for now, but might be worth revisiting this assuming there's no performance loss from passing in a component vs. a vanilla function.

2021-02-06 01:49 UTC, ElliotTheHuman commented
Excuse the latest commit name 🤦  I set the density to -3 by default, the commit was just named incorrectly by yours truly.

2021-02-06 02:12 UTC, lukelooker requested changes
Push density down so we can do one last careful comparison of snapshot changes :)

2021-02-06 02:12 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +    density: propsDensity,
```suggestion
    density: propsDensity = -3,
```

2021-02-06 02:12 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +    density: propsDensity,
Can you switch the default density back down to match the previous setup so we can compare screenshots?

2021-02-06 03:27 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +    density: propsDensity,
Ah I set the default density back to `-3` on `Tree` in particular since those stories were at that small "Developer" density.

`ListItem` and `List` default to `0` on main, but I can bump those down to `0` as well if you'd like! Just wanted to make sure.

2021-02-06 04:02 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +    density: propsDensity,
Oh - I'm a dork and misread here. Ignore me!

2021-02-06 04:12 UTC, lukelooker approved these changes
Looking at `File Tree Closed` is appears the icon size and spacing changed a little bit:

![image](https://user-images.githubusercontent.com/34253496/107108593-ff1e0680-67ed-11eb-9f54-69228f1f51ef.png)

![image](https://user-images.githubusercontent.com/34253496/107108599-080ed800-67ee-11eb-82a9-56cb9517f518.png)

That said the Field Picker appears to be rock-solid so I think we're good to go!

2021-02-06 04:41 UTC, merged