fix: Radio validation error
looker-open-source/components pull request #1850
Opened 2021-02-02 22:29 UTC by laraharrow

Thank so much for contributing to @looker/components!

The CI & [README](https://github.com/looker-open-source/components/blob/main/README.md) should help to make most of our code standards clear

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] Includes test coverage for all changes
- [ ] Documentation updated
- [ ] i18n impacts
- [ ] a11y impacts

2021-02-03 06:11 UTC, lukelooker requested changes
New appearance looks good.

I think the CSS can be simplified a bit (specifically `border-color` assignment)

Since we're making changes here in general this would be a good chance to remove Jest snapshot tests. Instead we should be using jest to verify behavior – [Checkbox.test.tsx](https://github.com/looker-open-source/components/blob/main/packages/components/src/Form/Inputs/Checkbox/Checkbox.test.tsx) is a really good template for what the `Radio.test.tsx` should look more like (basically testing every prop and in so doing exercising all the code within the component).

Specifically, the complaints from codecov can be seen at  [code coverage report for Radio.txt](https://codecov.io/gh/looker-open-source/components/pull/1850/diff?src=pr&el=tree#diff-cGFja2FnZXMvY29tcG9uZW50cy9zcmMvRm9ybS9JbnB1dHMvUmFkaW8vUmFkaW8udHN4) – basically what it's complaining about is that coverage % has gone down - this is because there are new, un-tested lines (the lines red-blocks next to them - 87 & 97)

![image](https://user-images.githubusercontent.com/34253496/106704825-98a4a880-65a1-11eb-9ef7-4b058f2ec4dd.png)

2021-02-03 06:11 UTC, lukelooker commented on packages/components/src/Form/Inputs/Radio/Radio.tsx
> +          ref={ref}
Since we don't want the spread `...` to overwrite any of the key settings on the radio input it should be done before those attributes get assigned explicitly.

```suggestion
          {...pickInputProps(restProps)}
          type="radio"
          aria-invalid={validationType === 'error' ? 'true' : undefined}
          ref={ref}
```

2021-02-03 06:11 UTC, lukelooker commented on packages/components/src/Form/Inputs/Radio/Radio.tsx
> +        ? theme.colors.criticalBorder
Codedov notes for this line - basically a specific test is needed that puts `Radio` into an error state and then verifies that the `border-color` is set as-expected.

2021-02-03 06:11 UTC, lukelooker commented on packages/components/src/Form/Inputs/Radio/Radio.tsx
> +        ? theme.colors.criticalBorder
Same as above here.

2021-02-03 06:11 UTC, lukelooker commented on packages/components/src/Form/Inputs/Radio/Radio.tsx
> +    border-color: ${({ theme, validationType }) =>
I believe `border-color: ...` can be specified on the core selector `input + ${FauxRadio} {` just once and then not repeated for all the different states.

2021-02-03 06:11 UTC, lukelooker commented on packages/components/src/Form/Inputs/Radio/Radio.tsx
> +        : theme.colors.ui2};
I believe this can be removed and replaced with a specification on the default (non-pseudo state) as noted above

2021-02-03 06:11 UTC, lukelooker commented on packages/components/src/Form/Inputs/Radio/Radio.tsx
> +    border-color: ${({ theme }) => theme.colors.ui2};
See note above.

```suggestion
```

2021-02-03 06:11 UTC, lukelooker commented on packages/components/src/Form/Inputs/Radio/Radio.tsx
> +    border-color: ${({ theme }) => theme.colors.ui2};
See note above.

```suggestion
```

2021-02-03 06:12 UTC, lukelooker commented
Also, the Ci has opened up a pull request against this pull request with snapshot updates: https://github.com/looker-open-source/components/pull/1851

2021-02-03 23:08 UTC, laraharrow commented on packages/components/src/Form/Inputs/Radio/Radio.tsx
> +    border-color: ${({ theme, validationType }) =>
That was my first solution too. But some how it didn't quite work for radio. So I ended up finding this way around to get the error color to show up.

2021-02-03 23:10 UTC, laraharrow commented on packages/components/src/Form/Inputs/Radio/Radio.tsx
> +        ? theme.colors.criticalBorder
I can't really test the `border-color` given that it is not available on tests. instead I tried testing `area-invalid` that also gets triggered by the `validationType`

2021-02-04 08:43 UTC, lukelooker reviewed
Really minor feedback on code style patterns within tests but functionally this looks great.

2021-02-04 08:43 UTC, lukelooker commented on packages/components/src/Form/Inputs/Radio/Radio.test.tsx
> +  const RadioInput = getByRole('radio')
Typically `PascalCase` is reserved for component and class names

```suggestion
  const radioInput = getByRole('radio')
```

2021-02-04 08:43 UTC, lukelooker commented on packages/components/src/Form/Inputs/Radio/Radio.test.tsx
> +  const RadioInput = getByRole('radio')
```suggestion
  const radioInput = getByRole('radio')
```

2021-02-04 08:43 UTC, lukelooker commented on packages/components/src/Form/Fields/FieldRadio/FieldRadio.test.tsx
> +  expect(RadioInput as HTMLInputElement).toBeDisabled()
The `as HTMLInputElement` shouldn't be needed (and doesn't appear to be). In general the test can be made more terse like so:

```suggestion
  renderWithTheme(
    <FieldRadio disabled id="FieldRadioID" label="FM" name="thumbsUp" />
  )

  expect(screen.getByRole('radio')).toBeDisabled()
```

2021-02-04 08:43 UTC, lukelooker commented on packages/components/src/Form/Fields/FieldRadio/FieldRadio.test.tsx
> +  expect(RadioInput as HTMLInputElement).toBeDisabled()
We've also tried to switch to using `screen.X` instead of destrucuring helpers from RTL's `render` method.

2021-02-04 08:43 UTC, lukelooker commented on packages/components/src/Form/Inputs/Radio/Radio.test.tsx
> +  expect(RadioInput as HTMLInputElement).toBeInTheDocument()
All of the tests here-in can be made a lot more terse :)

```suggestion
  renderWithTheme(<Radio defaultChecked />)
  expect(screen.getByRole('radio')).toBeInTheDocument()
```

Also would be good to wrap all of the tests inside a `describe('Radio', () => { ...` to keep them all grouped together in the output.

2021-02-04 08:43 UTC, lukelooker commented on packages/components/src/Form/Fields/FieldRadio/FieldRadio.test.tsx
> +  const { getByRole } = renderWithTheme(
All of the `FieldRadio` tests should be wrapped in a top-level

```describe('FieldRadio', () => {``` 

To group all of the tests together when output

2021-02-05 21:04 UTC, lukelooker approved these changes
LGTM

2021-02-05 21:45 UTC, merged