fix: DataTable onClick behavior
looker-open-source/components pull request #1865
Opened 2021-02-04 18:03 UTC by laraharrow

Thank so much for contributing to @looker/components!

The CI & [README](https://github.com/looker-open-source/components/blob/main/README.md) should help to make most of our code standards clear

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] Includes test coverage for all changes
- [ ] Documentation updated
- [ ] i18n impacts
- [ ] a11y impacts

2021-02-04 18:04 UTC, laraharrow commented
[ ] DataTableItem should only have a “hover” behavior (color or cursor change) when on onClick callback handler is specified
- line 136 of DataTableRow.tsx
```
  &:hover {
    cursor: ${({ onClick }) => onClick && 'pointer'};
    outline: none;
```
    
[x] Remove support for onClickRowSelect - developers can use onClick to emulate this behavior themselves and simplify usage / implementation

[ ] Clicking select Checkbox within DataTableRow should not trigger the onClick assigned to the full row (it should only toggle the checkbox)
- where can I find this behavior?

2021-02-04 21:51 UTC, lukelooker commented
> [ ] DataTableItem should only have a “hover” behavior (color or cursor change) when on onClick callback handler is specified
> 
> * line 136 of DataTableRow.tsx
> 
> ```
>   &:hover {
>     cursor: ${({ onClick }) => onClick && 'pointer'};
>     outline: none;
> ```

The row also gets a grey background color on hover - that shouldn't happen unless `onClick` is assigned

> [ ] Clicking select Checkbox within DataTableRow should not trigger the onClick assigned to the full row (it should only toggle the checkbox)
> 
> * where can I find this behavior?

Here's an example of the DataTableRow w/ `onClick`: https://codesandbox.io/s/datatable-example-ypeh5?file=/src/index.tsx - the "alert" shouldn't happen when you click on the checkbox, only on the remainder of the row.

2021-02-04 23:43 UTC, lukelooker requested changes
Added a comment on specific questions you asked. 

Also noticed that Jest and Lint CI checks have failures.

2021-02-05 20:17 UTC, laraharrow commented on packages/components/src/DataTable/stories/items.tsx
> +        onClick={() => alert("This shouldn't happen when clicking checkbox")}
so adding this here, my assumption is that we would repeat the bug behavior as in: https://codesandbox.io/s/datatable-example-ypeh5?file=/src/index.tsx:985-1003
But actually the behavior on storybook is:
* on Basic: clicking anywhere on the row triggers the `onClick`
* on (any) Select: clicking anywhere on the row just triggers the checkbox but not the `onClick`

2021-02-05 21:36 UTC, lukelooker requested changes
Tried this out and found the following issues:

- [x] Only the `checkbox` should trigger selection. Clicking else anywhere in the row should not toggle the checkbox value
- [ ] Rows with `onClick` assigned are now missing `:hover` effect (the row should darken when the user hovers and the `DataTableItem` has an `onClick` callback assigned)

These changes are done: (✅ )

- [x] The `checkbox` is not trigger `DataTableItem` onClick

2021-02-05 23:19 UTC, laraharrow commented on packages/components/src/DataTable/Item/DataTableItem.tsx
> +  const handleClick = disabled ? undefined : onClick || undefined
this removes the checkbox selecting when clicking anywhere in the row unless it is specific to the checkbox itself.

2021-02-05 23:22 UTC, laraharrow commented on packages/components/src/DataTable/Item/DataTableRow.tsx
> +        event.target.nodeName === 'INPUT'
Not sure if this is the correct solution. That adds `nodeName` to a file that I'm not familiar with `lib.dom.d.ts`. Basically we need to confirm that event.target is not a checkbox this will prevent the `onClick` to propagate iself to the checkbox

2021-02-05 23:24 UTC, laraharrow commented on packages/components/src/DataTable/Item/DataTableRow.tsx
> +
somehow the hasOnClick is returning undefined even when the row has the prop. I compared with line 151 that also uses onClick in that instance the behavior is as expected.

2021-02-05 23:51 UTC, laraharrow commented on packages/components/src/DataTable/Item/DataTableRow.tsx
> +        event.target.nodeName === 'INPUT'
this is causing lint errors

2021-02-06 02:10 UTC, lukelooker requested changes
Added some notes about the challenging spots.

2021-02-06 02:10 UTC, lukelooker commented on packages/components/src/DataTable/Item/DataTableRow.tsx
> +  theme: DefaultTheme,
Use `Theme` from `@looker/design-tokens`

```suggestion
  theme: Theme,
```

2021-02-06 02:10 UTC, lukelooker commented on packages/components/src/DataTable/Item/DataTableRow.tsx
> +  if (!isHeader || !hasOnClick) return undefined
Logic for `isHeader` here is backwards :) 


```suggestion
  if (isHeader || !hasOnClick) return undefined
```

2021-02-06 02:10 UTC, lukelooker commented on packages/components/src/DataTable/Item/DataTableRow.tsx
> +        getRowHoverColor(theme, onClick !== undefined, isHeaderRow, checked)};
You can tighten up the function parameters by casting everything exactly here:

```suggestion
        getRowHoverColor(theme, Boolean(onClick), Boolean(isHeaderRow), Boolean(checked))};
```

2021-02-06 02:10 UTC, lukelooker commented on packages/components/src/DataTable/Item/DataTableRow.tsx
> +  isSelected: boolean | 'mixed' | undefined
See note below about tightening up inputs, it's a lot easier to test when a functions parameters are all required:

```suggestion
  isHeader: boolean,
  isSelected: boolean
```

2021-02-08 22:07 UTC, lukelooker requested changes
Looks great - just need to remove the `alert(...` added for testing and then it'll be GTG! :)

2021-02-08 22:07 UTC, lukelooker commented on packages/components/src/DataTable/stories/items.tsx
> +        onClick={() => alert("This shouldn't happen when clicking checkbox")}
This should get removed now :)

2021-02-08 22:33 UTC, lukelooker approved these changes
LGTM

2021-02-08 22:39 UTC, merged