docs: Add List docs and update Tree docs
looker-open-source/components pull request #1879
Opened 2021-02-08 22:53 UTC by ElliotTheHuman

- Added `List` and `ListItem` docs
- Updated `Tree` docs to align with `List` / `ListItem` refactor

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] Includes test coverage for all changes
- [ ] Documentation updated
- [ ] i18n impacts
- [ ] a11y impacts

2021-02-08 23:01 UTC, ElliotTheHuman commented
Tagging @mariebeau for visibility

2021-02-09 18:19 UTC, dbchristopher requested changes
This looks good @ElliotTheHuman! The only real issue I found is that the `keyColor` prop in the prop table doesn't seem to do anything, so maybe it was included by mistake?

2021-02-09 18:19 UTC, dbchristopher commented on www/src/documentation/components/content/demos/ListItemPropTable.tsx
> +              color of the child element and icon, if present.
SUPER minor nitpick: I notice that a few of these descriptions end in period, but most don't. So maybe just for consistency's sake treat them as full grammatical sentences?

2021-02-09 18:19 UTC, dbchristopher commented on www/src/documentation/components/content/demos/ListItemPropTable.tsx
> +          </TableRow>
Maybe I'm not putting it in the right place, but it doesn't seem like the `keyColor` prop does anything? It also seems weird that there would be both `color` and `keyColor` props anyways

2021-02-09 18:32 UTC, ElliotTheHuman commented on www/src/documentation/components/content/demos/ListItemPropTable.tsx
> +              color of the child element and icon, if present.
Ah the need for consistency makes total sense here. Good call.

2021-02-09 18:47 UTC, ElliotTheHuman commented on www/src/documentation/components/content/demos/ListItemPropTable.tsx
> +          </TableRow>
The `keyColor` prop doesn't really do anything unless the item is selected or hovered + selected. It's here as a result of this ticket a while back where we unified the hovered and selected states of a various list-like components:
https://looker.atlassian.net/browse/LENS-1293

Screenshot:
![Screen Shot 2021-02-09 at 10 41 08 AM](https://user-images.githubusercontent.com/16812885/107411406-53add400-6ac3-11eb-953d-ac18ab179c36.png)

It definitely is odd to have `color` and `keyColor` since they sound so similar. I could add a note on `keyColor` that directs people to `color` if they're looking to change text color! Changing `color` to a different name might be an option too.

Thoughts?

2021-02-09 18:48 UTC, ElliotTheHuman commented on www/src/documentation/components/content/demos/ListItemPropTable.tsx
> +          </TableRow>
Also, I noticed that adding `keyColor` to a parent `List` doesn't actually spread it down to child props like `Tree` does 🤦 I can patch that up since it's a pretty easy context fix.

2021-02-09 19:08 UTC, ElliotTheHuman commented on www/src/documentation/components/content/demos/ListItemPropTable.tsx
> +              color of the child element and icon, if present.
Resolved in 383b79b

2021-02-09 19:28 UTC, dbchristopher approved these changes
Awesome, looks good @ElliotTheHuman!

2021-02-09 19:30 UTC, merged