fix: add test to ProgressCircular
looker-open-source/components pull request #1882
Opened 2021-02-09 18:42 UTC by laraharrow

Thank so much for contributing to @looker/components!

The CI & [README](https://github.com/looker-open-source/components/blob/main/README.md) should help to make most of our code standards clear

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] Includes test coverage for all changes
- [ ] Documentation updated
- [ ] i18n impacts
- [ ] a11y impacts

2021-02-09 23:11 UTC, mdodgelooker approved these changes
LGTM

2021-02-10 00:25 UTC, mdodgelooker requested changes
Ok I'm stumped on where the 88.89% on `DeterminateProgress.tsx` is coming from. The only tiny piece that's not being tested is the `progress = 0` default value. In reality, `progress` is never undefined, so I think you could remove the ` = 0` as the `?` in `progress?: number` in the props.

2021-02-10 01:32 UTC, laraharrow commented on packages/components/src/ProgressCircular/ProgressCircular.test.tsx
> +  test('renders progress of 0', () => {
@mdodgelooker here is the test I wrote for testing when progress = 0

2021-02-10 02:48 UTC, mdodgelooker approved these changes
@laraharrow because the progress prop is never undefined by the time it renders DeterminateProgess, the default in that component is never used. That's the only place I can see that isn't covered but I don't think it really matters anyway.

2021-02-10 17:53 UTC, merged