feat: adding i18n to our components
looker-open-source/components pull request #1883
Opened 2021-02-09 20:49 UTC by laraharrow

Thank so much for contributing to @looker/components!

The CI & [README](https://github.com/looker-open-source/components/blob/main/README.md) should help to make most of our code standards clear

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] Includes test coverage for all changes
- [ ] Documentation updated
- [ ] i18n impacts
- [ ] a11y impacts

2021-02-10 21:53 UTC, mdodgelooker requested changes
Making so much progress! 🎉 Are you able to change the PR to compare against my `mdodge/i18n` branch so I can keep making updates in there to the setup code (`useI18n`, etc)?

2021-02-10 21:53 UTC, mdodgelooker commented on packages/components-providers/src/I18n/resources.ts
> +      Label: 'Clear Field',
Ah looks like you're mostly calling `t()` with in the value, like `t('Clear Field')` in `AdvancedInputControls.tsx`, but using a different name as the key here in resources ("Label" in this case). For all translations except ones that contain `{{}}`, you can use the value as the key, which is how it's done in the core product, so might as well keep it consistent for sanity's sake. You need to add single quotes if the key contains spaces, so this would be:
```suggestion
      'Clear Field': 'Clear Field',
```
Anytime `t` is called with a key that's not found, an error is thrown and you'll see something like the screenshot below, so to check if everything is properly translated, you can just go to a story or docs page containing that component.
![image](https://user-images.githubusercontent.com/53451193/107575775-22a5d000-6ba5-11eb-8a56-3f739c1e25c5.png)

2021-02-10 21:53 UTC, mdodgelooker commented on packages/components-providers/src/I18n/resources.ts
> +        'Date {{formatDateString(new Date(Date.now())}}, {{dateStringLocale}}',
I think this one can break the rule we chatted about earlier of not breaking up phrases because of languages like Japanese – since it's not really a phrase, more like a label (see suggestion part 2 in `InputDate.tsx`):
```suggestion
      Date: 'Date',
```
![image](https://user-images.githubusercontent.com/53451193/107576436-fb9bce00-6ba5-11eb-8b21-52f17cd22ed6.png)

2021-02-10 21:53 UTC, mdodgelooker commented on packages/components/src/InputDate/InputDate.tsx
> +          })}
Suggestion part 2:
```suggestion
          placeholder={`${t('Date')} (${formatDateString(
            new Date(Date.now()),
            dateStringLocale
          )})`}
```

2021-02-10 23:55 UTC, laraharrow commented
ok @mdodgelooker  I looked at every file that got `i18ned` and everything seems to be working properly now. Except for `MessageBar.tsx` the error that I'm getting is that `t` is not a function but also on VCCode its complaining that `intent` on line 135 could be undefined and `Type 'undefined' is not assignable to type 'TFunction'` but I'm not using the `t` method on `intent`. Very confusing.

2021-02-11 04:24 UTC, mdodgelooker commented
@laraharrow this is awesome! I've merged your `lara/i18n` branch into my `mdodge/i18n`– I'll take a look at `MessageBar` and then add some more features like eslint, context utilities, etc.

2021-02-11 04:24 UTC, closed without merging