fix(MessageBar): Use intent accent colors for MessageBar background
looker-open-source/components pull request #1901
Opened 2021-02-11 23:13 UTC by jhardy

Thank so much for contributing to @looker/components!

The CI & [README](https://github.com/looker-open-source/components/blob/main/README.md) should help to make most of our code standards clear

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] Includes test coverage for all changes
- [ ] Documentation updated
- [ ] i18n impacts
- [x] a11y impacts

2021-02-12 17:21 UTC, lukelooker requested changes
Functionality looks great, minor suggestions around Styled Components usage

2021-02-12 17:21 UTC, lukelooker commented on packages/components/src/MessageBar/MessageBar.tsx
> +    intent ? backgroundColor : `background: ${colors.informAccent};`}
Rather than having the default fallback here we should do it in `attrs` above:

```suggestion
  ${background}
```

2021-02-12 17:21 UTC, lukelooker commented on packages/components/src/MessageBar/MessageBar.tsx
>      px,
You can use Styled Components `attrs` method to inject default `intent` value:

```suggestion
  ({ intent = 'inform', px = 'medium', py = 'small', width = '100%' }) => ({
    intent,
    px,
```

2021-02-12 17:21 UTC, lukelooker commented on packages/components/src/MessageBar/MessageBar.tsx
> +})
I've been tending towards using `background` over `background-color`. No huge argument for it besides that it's slightly more terse and if other CSS specifices `background` it can be confusing to have interactions between `background` and `backgroundColor`

```suggestion
const background = variant({
  prop: 'intent',
  variants: {
    critical: {
      background: 'criticalAccent',
    },
    inform: {
      background: 'informAccent',
    },
    positive: {
      background: 'positiveAccent',
    },
    warn: {
      background: 'warnAccent',
    },
  },
})
```

2021-02-12 17:21 UTC, lukelooker commented on packages/components/src/MessageBar/MessageBar.test.tsx
> +        'background-color',
See comment below

```suggestion
        'background',
```

2021-02-13 08:49 UTC, lukelooker requested changes
One more note to address a nearby issue.

2021-02-13 08:49 UTC, lukelooker commented on packages/components/src/MessageBar/MessageBar.tsx
>    border-radius: ${({ theme: { radii } }) => radii.medium};
Since you're working here anyway it'd be great to fix another problem I've seen:

```suggestion
  border-radius: ${({ theme: { radii } }) => radii.medium};
  color: ${({ theme }) => theme.color.text };
```

Currently color is inherited instead of explicit so when themes are inverted things look sad.

2021-02-16 13:58 UTC, jhardy commented on packages/components/src/MessageBar/MessageBar.tsx
> +})
I originally tried background, but the color does not get applied.  The theme values name is set as the value of `background`. Any thoughts?
![image](https://user-images.githubusercontent.com/170681/108072514-d8e13d80-701b-11eb-892a-3828da9b26c2.png)

2021-02-16 14:06 UTC, jhardy commented on packages/components/src/MessageBar/MessageBar.tsx
>    border-radius: ${({ theme: { radii } }) => radii.medium};
![image](https://user-images.githubusercontent.com/170681/108073584-12667880-701d-11eb-9c25-3e4f0b625f79.png)

2021-02-16 17:09 UTC, lukelooker commented on packages/components/src/MessageBar/MessageBar.tsx
> +})
Oh - weird, I forgot that `variant` is doing `styled-system` magic here. In testing it turns out that `bg` works too but also outputs `backgroundColor` so 🤷

2021-02-16 17:09 UTC, lukelooker approved these changes

2021-02-16 17:37 UTC, merged