feat(Menu): Menu Refactor
looker-open-source/components pull request #1906
Opened 2021-02-12 01:37 UTC by ElliotTheHuman

Thank so much for contributing to @looker/components!

The CI & [README](https://github.com/looker-open-source/components/blob/main/README.md) should help to make most of our code standards clear

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] Includes test coverage for all changes
- [ ] Documentation updated
- [ ] i18n impacts
- [ ] a11y impacts

2021-02-12 01:43 UTC, ElliotTheHuman commented on packages/components/src/Menu/MenuGroup.test.tsx
> -})
The plan is to remove `MenuGroup` so preemptively removing test suite.

Also, these tests check for icon placeholder behavior, which is more suitably tested by visual snapshotting (I think).

2021-02-12 01:43 UTC, ElliotTheHuman commented on packages/components/src/Menu/MenuList.test.tsx
> -
Tested via visual snapshotting.

2021-02-12 01:44 UTC, ElliotTheHuman commented on packages/components/src/Menu/Menu.tsx
> +    const listProps = omit(props, popoverPropKeys)
Note to self: Should use vanilla JS here instead of lodash.

2021-02-12 20:22 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> -const ListItemInternal: FC<ListItemProps> = (props) => {
A lot of these changes are from introducing `forwardRef` into `ListItemInternal`. The `mouseEnter` / `mouseLeave` handlers + the new state to track hover state is new to this PR though!

2021-02-17 05:56 UTC, mdodgelooker requested changes
Great work @ElliotTheHuman ! And thanks for your patience with my slow reviewing. 😉

2021-02-17 05:56 UTC, mdodgelooker commented on packages/components/src/Menu/Menu.tsx
> +    const listProps = omit(props, popoverPropKeys)
Is there a reason you switched from destructuring to pick/omit (other than fewer total lines of code)? I think the latter is less performant, and also will need to be vanilla-JS-ified.

2021-02-17 05:56 UTC, mdodgelooker commented on packages/components/src/Menu/MenuGroup.test.tsx
> -})
👍 And actually icon placeholder behavior no longer works on a standalone `MenuGroup` – it relies on a `MenuList`.

2021-02-17 05:56 UTC, mdodgelooker commented on packages/components/src/Menu/MenuItem.tsx
> +const MenuItemInternal: FC<MenuItemProps> = forwardRef(
Remove this `MenuItemProps` here and add it below...
```suggestion
const MenuItemInternal = forwardRef(
```

2021-02-17 05:56 UTC, mdodgelooker commented on packages/components/src/Menu/MenuItem.tsx
> +    },
...here
```suggestion
    }: MenuItemProps,
```

2021-02-17 05:56 UTC, mdodgelooker commented on packages/components/src/Menu/MenuItem.tsx
> +    const { iconSize } = listItemDimensions(density)
Nice!

2021-02-17 05:56 UTC, mdodgelooker commented on packages/components/src/Menu/MenuItem.tsx
>         due to React Portal event bubbling */}
```suggestion
        {/* Keep nestedMenu popover outside of ListItem to prevent its events
       from bubbling up (especially onClick) due to React Portal event bubbling */}
```

2021-02-17 05:56 UTC, mdodgelooker commented on packages/components/src/Menu/MenuList.tsx
> -    WidthProps {
The core product does use `width` and occasionally `minWidth` props on `Menu` (which previously was coming from here). Should we add support in `List`, or just not support it, and you get the width that you get? @lukelooker thoughts?

2021-02-17 05:56 UTC, mdodgelooker commented on packages/components/src/utils/useHovered.ts
> + * Get the current hover / focus state of a element of which component has no control
Thank you so much for adding this. 🙏 Such a confusing hook.
```suggestion
 * Get the hover / focus state of an element over which the current component has no control
```

2021-02-17 05:56 UTC, mdodgelooker commented on www/src/documentation/components/overlays/menuitem.mdx
> +  <Tooltip content="It is gouda!">
Should we use `"left"` in the example b/c that usually looks good? Feel free to disregard though.
```suggestion
  <Tooltip content="It is gouda!" placement="left">
```

2021-02-17 17:50 UTC, ElliotTheHuman commented on packages/components/src/Menu/Menu.tsx
> +    const listProps = omit(props, popoverPropKeys)
The props object that was spread onto `MenuList` included props from `PopoverProps` like "portalElement" and "scrollLock" and so giving those props to `Menu` could result in some "React does not recognize X prop on a DOM element" errors.

Having a pick / omit here seemed a bit sturdier since `Menu` wouldn't require its props to be updated if `PopoverProps` was every updated (the `popoverPropKeys` array would just need to be updated instead). That being said, if the performance gain from destructuring the props matters more, I could definitely go that route instead and include the unaccounted for `Popover` props.

2021-02-17 17:55 UTC, lukelooker commented on packages/components/src/Menu/Menu.story.tsx
> -        tooltip="Some tooltip"
If I'm reading this right we removed the the `tooltip` prop on `MenuItem` specifically bit it can still be accomplished via composition. E.g.:

```<Tooltip ...><MenuItem>Stuff</MenuItem></Tooltip>```

2021-02-17 17:58 UTC, lukelooker commented on packages/components/src/Menu/MenuList.tsx
> -    WidthProps {
I'm _tempted_ to say you get what you get. Which is to say we specify a `minWidth: 12rem` of on `MenuItem`s themselves and otherwise things just grow to fit.

2021-02-17 18:11 UTC, ElliotTheHuman commented on packages/components/src/Menu/Menu.story.tsx
> -        tooltip="Some tooltip"
Correct, we removed the `tooltip` prop on `MenuItem` and instead support that pattern using composition.

I'm not too sure on what the right call is here, but doing this keeps `ListItem` from taking on `tooltip`-related props and keeps it simple.

It _shouldn't_ be hard to add a `tooltip`-related props to `ListItem`, so happy to do that if the convenience to the user outweighs any potential tech debt here.

2021-02-17 18:17 UTC, ElliotTheHuman commented on packages/components/src/Menu/Menu.tsx
> +  escapeWithReference?: boolean
Resolved in 4c6420e

2021-02-17 18:23 UTC, ElliotTheHuman commented on packages/components/src/Menu/MenuItem.tsx
> +const MenuItemInternal: FC<MenuItemProps> = forwardRef(
Ah I figured I was doing something wrong with Props here since the typing of `ref` on `ListItem` kept erroring out.

Good call! Resolved in af3e87fdf.

2021-02-17 18:23 UTC, ElliotTheHuman commented on packages/components/src/Menu/MenuItem.tsx
> +    },
Resolved in af3e87fdf

2021-02-17 18:23 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +  ref?: Ref<HTMLLIElement>
Resolved in af3e87f

2021-02-17 18:23 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +  (props, ref: Ref<HTMLLIElement>) => {
Resolved in af3e87f

2021-02-17 18:54 UTC, mdodgelooker commented on packages/components/src/Menu/Menu.story.tsx
> -        tooltip="Some tooltip"
Oh whoops, I added this comment and then later realized what the change was. Meant to delete it. 🙂

2021-02-17 18:57 UTC, mdodgelooker commented on packages/components/src/Menu/MenuList.tsx
> -    WidthProps {
Works for me... anyone wanna do an audit to see if any menus will look just terrible without being able to specify the width? 😉

2021-02-17 20:25 UTC, ElliotTheHuman commented on packages/components/src/Menu/MenuList.tsx
> -    WidthProps {
I'll poke around HT to see if anything looks broken by not being able to set the width. Stay tuned!

2021-02-17 20:44 UTC, mdodgelooker commented on packages/components/src/Menu/Menu.tsx
> +    const listProps = omit(props, popoverPropKeys)
Oh interesting! I neglected to destructure those props, and I blame typescript. 😉 Apparently it doesn't complain if you spread extra props that are not valid. Then I think it is safer to do what you've done, but to add a type on the array. I'll add an inline suggestion.

2021-02-17 20:52 UTC, mdodgelooker requested changes

2021-02-17 20:52 UTC, mdodgelooker commented on packages/components/src/Popover/Popover.tsx
> +export const popoverPropKeys = [
If you move this array down below `PopoverProps` and add this type, it'll be slightly safer, though it could still be missing props. I've asked for help on deriving a type that's an exhaustive array, but it's tricky so this I think is good enough for now.

Also I think `escapeWithReference` should be there. My bad I missed it in my `Menu` restructure, but I could think of a situation where you'd want to use it.
```suggestion
export const popoverPropKeys: Array<keyof PopoverProps> = [
  'escapeWithReference',
```

2021-02-17 20:52 UTC, mdodgelooker commented on www/src/documentation/components/overlays/menu.mdx
> -  escapeWithReference
I think we should add `escapeWithReference` back in – my oversight for removing it.

2021-02-17 22:18 UTC, ElliotTheHuman commented on www/src/documentation/components/overlays/menu.mdx
> -  escapeWithReference
Discussed over chat, but it looks like `escapeWithReference` was deprecated from `Popover`. Keeping it deleted from `MenuProps` seems like the right call.

2021-02-17 22:20 UTC, ElliotTheHuman commented on packages/components/src/Popover/Popover.tsx
> +export const popoverPropKeys = [
Discussed over chat, but it looks like `escapeWithReference` was deprecated from `Popover`. Keeping it deleted from `MenuProps` seems like the right call.

Did move down the keys array though to make use of the interface + keyof!

Resolved in ef164e1

2021-02-17 23:20 UTC, ElliotTheHuman commented on packages/components/src/Menu/Menu.tsx
> +    const listProps = omitPopoverProps(props, popoverPropKeys)
Vanilla JS-ifying `popoverProps` was pretty straightforward, but getting `listProps` was a bit trickier. I'm definitely not beholden to my current `omitPopoverProps` implementation so open to any cleaner approaches out there!

2021-02-17 23:21 UTC, ElliotTheHuman commented on packages/components/src/Menu/Menu.tsx
> +    const listProps = omit(props, popoverPropKeys)
Cool cool! I left a comment on my recent vanilla JS-ifying attempt. It probably could be better, but couldn't think of anything cleaner for `omitPopoverProps` 🤷 

https://github.com/looker-open-source/components/pull/1906#discussion_r578013729

2021-02-18 18:29 UTC, ElliotTheHuman commented on packages/components/src/Menu/MenuList.tsx
> -    WidthProps {
Discussed over Meet, but adding a `min-width: 12rem` to `MenuList` in particular and removing width-related props was the call iirc.

Resolved in 974aaf7.

2021-02-18 19:08 UTC, mdodgelooker approved these changes
🚢!!!

2021-02-18 19:08 UTC, mdodgelooker commented on packages/components/src/Menu/Menu.tsx
> +}
Nice. I think when we do more work on removing/minimizing lodash we'll want to make this a util. I can think of at least all the `Field-` components that would need it (or similar). 🙂

2021-02-18 19:09 UTC, ElliotTheHuman commented on packages/components/src/Menu/Menu.tsx
> +
I really wanted to be able to produce the listProps and popoverProps simultaneously since they're mutually exclusive, so whipped up a function to do so. 

Note: There's technically no reason I need to copy the props object, but it just feels weird to me to delete properties on the `props` object (or mutate it in general) 🤷  I could just be paranoid though.

2021-02-18 19:12 UTC, merged