feat: Add label to Dialog
looker-open-source/components pull request #1924
Opened 2021-02-17 20:47 UTC by kvrmd

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [x] Includes test coverage for all changes
- [x] Documentation updated
- [x] i18n impacts
- [x] a11y impacts

Storybook DialogHeader inherits Dialog id:
![image](https://user-images.githubusercontent.com/24406097/108261664-cac51700-7118-11eb-9c5d-f887be434c4f.png)

Screen reader reads labelled Dialog:
![image](https://user-images.githubusercontent.com/24406097/108261630-bf71eb80-7118-11eb-8933-dfac8f42de72.png)

2021-02-17 20:47 UTC, kvrmd commented on packages/components/src/Dialog/Layout/DialogHeader.tsx
> +    <div {...omitStyledProps(props)}>
Changed `header` to be `div` here, because the screen reader was using this element as the title of the dialog. Alternatively, I could keep the `header` tag and refer to the `Heading` for the `header`'s label:

```tsx
<Dialog aria-labelledby={`${dialogId}-header`} />

<header
  id={dialogId ? `${dialogId}-header` : ''}
  aria-labelledby={id ? `${id}-header-heading` : ''}
>
  <Heading id={id ? `${id}-header-heading` : ''} />
</header>
```

2021-02-17 20:47 UTC, kvrmd commented on packages/components/src/Dialog/DialogContext.ts
> +  dialogId: '',
Should I use `id` or `dialogId`?

2021-02-18 00:37 UTC, kvrmd commented on packages/components/src/Dialog/Layout/DialogHeader.tsx
> +    <div {...omitStyledProps(props)}>
I updated this to keep the `header` element for semantics.

2021-02-19 19:33 UTC, lukelooker requested changes
Very minor change about `dialogId` to `id` and then this is good to go.

My apologies on being slow to review this - I'll be pushing through lots of reviews today!

2021-02-19 19:33 UTC, lukelooker commented on packages/components/src/Dialog/DialogContext.ts
> +  dialogId: '',
I think I'd prefer `id` since the context consumer can alias if name collisions are a concern and the terse version is nice

2021-02-19 19:33 UTC, lukelooker commented on packages/components/src/Dialog/DialogContext.ts
> +  dialogId: '',
We haven't been super consistent about prop-docs but we're _trying_ to get better. I'd also like to mark this as `@private` since I don't (at this point at least) want to encourage more use of this outside this since use-case.

```suggestion
  /**
   * Used to connect the DialogHeader's title to the Dialog's `aria-labelledby`
   * @private
   */
  id: string
```

2021-02-19 20:41 UTC, lukelooker approved these changes
LGTM!

2021-02-19 20:56 UTC, merged