WIP
looker-open-source/components pull request #1925
Opened 2021-02-17 22:54 UTC by lukelooker

Refactor icon-leveraging components

@looker/icons needs to export static collection if Icon components

Components:

- [ ] Avatar*
- [ ] Button*
- [ ] ListItem (includes: MenuItem, TreeItem)
- [ ] IconButton
- [ ] InputSearch
- [ ] InputText
- [ ] SelectOption
- [ ] Status

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] Includes test coverage for all changes
- [ ] Documentation updated
- [ ] i18n impacts
- [ ] a11y impacts

2021-03-15 05:43 UTC, lukelooker commented on packages/components/src/Form/Inputs/Select/Select.tsx
> +          iconBefore={<SelectInputIcon options={options} />}
Icon styling is _currently_ only applied to content injected via `iconBefore` / `iconAfter`- when injected via `before` the icon has no explicit sizing information and ends up huuuge. :)

2021-03-18 19:53 UTC, lukelooker commented
@mdodgelooker / @jhardy - Apologies for the massive size of this PR. I still need to fix-up the Gatsby side of things but everything else should be functional and ready for review. I tried to consolidate commits to make it easier to review / understand what happens here but please let me know if I can do anything to assist your review.

2021-03-19 01:38 UTC, lukelooker commented
@mdodgelooker Got Gatsby up and running so I think this is fully-ready for review :)

2021-03-19 04:20 UTC, mdodgelooker requested changes
This is so great. 👏👏👏
I haven't gotten to any of the gatsby changes yet but my computer is about to die so I'll send the feedback I have so far and look at gatsby in the morning.

2021-03-19 04:20 UTC, mdodgelooker commented on packages/components/src/List/ListItemLayout.tsx
> +  }
Not sure if something in here is the culprit but the pivot icon looks small in the `Tree` Field Picker example:
![image](https://user-images.githubusercontent.com/53451193/111730112-f1689180-882d-11eb-85c3-7ecca1e39003.png)

2021-03-19 04:20 UTC, mdodgelooker commented on packages/components/src/Pagination/Pagination.tsx
> +import { ChevronLeft, ChevronRight } from '@styled-icons/material-rounded'
Something's off: 
![image](https://user-images.githubusercontent.com/53451193/111730544-e4986d80-882e-11eb-96af-a15dfa413b5c.png)

2021-03-19 20:51 UTC, lukelooker commented on packages/components/src/Button/IconButton.tsx
>            aria-hidden={true}
Is sure doesn't! :)

2021-03-19 20:54 UTC, lukelooker commented on packages/components/src/Form/Inputs/Select/stories/Select.story.tsx
> +
I think so, yes. This image snapshot isn't very useful since the Select is close and looks like the rest (I think?)

2021-03-19 20:58 UTC, lukelooker commented on packages/components/src/Icon/Icon.tsx
>     */
Oops! :)

2021-03-19 20:59 UTC, lukelooker commented on packages/components/src/Form/Inputs/Select/stories/SelectOptions.story.tsx
> +    icon: <Create />,
Same!

2021-03-19 21:06 UTC, lukelooker commented on packages/components/src/List/ListItemLayout.tsx
> +  }
So mine looks fine... 
![image](https://user-images.githubusercontent.com/34253496/111842050-24f1fd00-88bc-11eb-9efd-2f5fd78d0888.png)

I'm wondering your instance was in a weird state perhaps `yarn prebuild` messed up perhaps? Would you rebuild and see if it repeats (definitely want to track down what did happen)

2021-03-19 21:07 UTC, lukelooker commented on packages/components/src/Pagination/Pagination.tsx
> +import { ChevronLeft, ChevronRight } from '@styled-icons/material-rounded'
So the tiny icon on the left looks related to the build error I was pondering above. The `DoubleArrow` does seem like a bad replacement so I went ahead and restore `DoubleChevonRight` to get things back to "sane" on my instance.

2021-03-19 21:09 UTC, lukelooker commented on packages/components/src/Form/Inputs/Select/SelectInputIcon.tsx
> +  return getOptionIcon(option.value, options)
Need to ponder on this... 🤔

2021-03-22 04:55 UTC, lukelooker commented on packages/components/src/Pagination/Pagination.tsx
> +import { ChevronLeft, ChevronRight } from '@styled-icons/material-rounded'
![image](https://user-images.githubusercontent.com/34253496/111942244-283de200-8a90-11eb-871a-573a78b76bbb.png)

2021-03-22 05:07 UTC, lukelooker commented on packages/components/src/Icon/Icon.tsx
> -    width: 100%;
I think it's ideal to just keep the current behavior (re-add height/width here) - see notes above

2021-03-22 05:11 UTC, lukelooker commented on packages/components/src/Form/Inputs/Select/SelectInputIcon.tsx
> +  return getOptionIcon(option.value, options)
Restoring height & width to `svg` selector within `Icon` solves this well - for better or worse the Styled Icon spec pre-supposes that SVGs have an specified size but it's safest if we bound them to the size we expect.

2021-03-22 05:13 UTC, lukelooker commented on packages/components/src/Form/Inputs/Select/stories/Select.story.tsx
> +
Doh - should've _actually_ looked at the file. No, this is a dumb test. Removed. :)

2021-03-22 17:36 UTC, jhardy commented
![image](https://user-images.githubusercontent.com/170681/112033168-6374fb00-8afa-11eb-9311-e1c7d07dfbdc.png)
Secondary Icon example on Avatar in gatsby broken

2021-03-22 18:39 UTC, lukelooker commented
Fixed Avatar MDX bug (jez I wish our mdx could be TS-checked) :)

2021-03-22 21:54 UTC, mdodgelooker requested changes
Just found one thing in www, otherwise, gtg!

2021-03-22 21:54 UTC, mdodgelooker commented on packages/components/src/Pagination/Pagination.tsx
> +import { ChevronLeft, ChevronRight } from '@styled-icons/material-rounded'
1) You're right, 2) looks good

2021-03-22 21:54 UTC, mdodgelooker commented on www/src/MDX/Pre/CodeSandbox.tsx
> +                        <Icon name={<Warning />} size={24} />
```suggestion
                        <Icon icon={<Warning />} size={24} />
```

2021-03-22 21:54 UTC, mdodgelooker commented on www/src/documentation/components/forms/input-select.mdx
> +      { icon: <BarChart />, label: 'Column', value: 'column' },
Haha we need to come up with the equivalent of "L is for Left" to keep these 2 straight. 😉

2021-03-22 22:01 UTC, lukelooker commented on www/src/documentation/components/forms/input-select.mdx
> +      { icon: <BarChart />, label: 'Column', value: 'column' },
Yes we do :) 

I think the plan is to actually go ahead and rename the "looker-specific" icons to follow Material conventions in the not-too-distant future :)

2021-03-22 22:02 UTC, mdodgelooker approved these changes
LGTM! 🚢 🎉 🚢 🎉 🚢 🎉

2021-03-22 22:27 UTC, merged