feat: Focus on first tabbable node when Dialog opens
looker-open-source/components pull request #1927
Opened 2021-02-18 01:27 UTC by kvrmd

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] Includes test coverage for all changes
- [ ] Documentation updated
- [ ] i18n impacts
- [ ] a11y impacts

In this PR, I update FocusTrap utils to focus on the first tabbable element, instead of the dialog element.

Few things to note:
1. VoiceOver default arrow-key navigation gets stuck when the dialog element is focused. This seems to be because dialog element is treated as the last focusable element -> you'd have to navigate backwards to read the dialog content.
2. w3c specs says to focus on the first focusable element when the Dialog is opened, with some exceptions. It's worth mentioning that there are conflicting opinions on when the exceptions apply.

For 2, I'm thinking we could add a `initialFocusStrategy` prop to `Dialog` to specify the fallback-logic when determining what element to focus when the Dialog opens. By default it could be: `['autofocus', 'firstTabbableNode', 'header', 'dialog']`.

```
  initialFocusStrategy: Array<'autofocus' | 'firstTabbableNode' | 'header' | 'dialog'>
```

2021-02-18 01:32 UTC, kvrmd commented on packages/components/src/Portal/Portal.tsx
> -    const content = <InvisiBox ref={ref} tabIndex={-1} {...props} />
@lukelooker Is there a reason we add `tabIndex={-1}` to this component? This is causing VoiceOver to navigate to this element.
![2021-02-17_17-30-54 (1)](https://user-images.githubusercontent.com/24406097/108290864-13df9000-7146-11eb-8e10-96abba16aa1b.gif)

2021-02-19 20:40 UTC, lukelooker requested changes
Wrote up notes on the `firstTabbableNode` strategy

2021-02-19 20:40 UTC, lukelooker commented on packages/components/src/Portal/Portal.tsx
> -    const content = <InvisiBox ref={ref} tabIndex={-1} {...props} />
👍  This was a legacy thing (pre-`*Surface` and should go away)

2021-02-19 20:40 UTC, lukelooker commented on packages/components-providers/src/FocusTrap/utils.ts
> +      const tabbableNodes = tabbable(element)
So @mdodgelooker discussed this some. We _used_ to have a strategy very much like this and it led to some angst when things were unexpectedly or annoyingly focused. We've mitigated many of the key issues there (introducing `:focus-visible` pattern, making `DialogHeader`'s close icon `tabIndex={-1]}` etc...

That said we want to avoid focusing on a button within the DialogContent unless it's our only option so we want to go with a slightly more complex strategy here. `firstTabbableNode` should be (in this order)

1. `inputs[0]` (`input, textarea, select`) - find the first input
2. `footer > tabbable[0]` - if that fails, find the first tabbable item in the footer
3. `tabbable[0]` - if all else fails, find the first tabbable thing

2021-02-19 21:44 UTC, kvrmd reviewed
I couldn't find any docs to update. Please let me know if I missed it 🙏

2021-02-19 21:44 UTC, kvrmd commented on packages/components-providers/src/FocusTrap/utils.ts
> +        firstInputElement || firstTabbableFooterElement || firstTabbableElement
@lukelooker + @mdodgelooker Here's the meat of the initial focus logic change.

2021-02-19 21:44 UTC, kvrmd commented on packages/components/src/utils/useFocusTrap.test.tsx
> +        <FocusTrapComponent hideClose>
Added `hideClose` to prevent the close button from being initially focused. Alternatively, I could update the test to `expect` the close button being focused as opposed to the surface.

2021-02-19 21:44 UTC, kvrmd commented on packages/components/src/utils/useFocusTrap.test.tsx
> +            <FieldText label="Text field B" autoFocus />
Added a 2nd input to ensure `autoFocus` overrides the initial tabbable element logic.

2021-02-19 22:47 UTC, lukelooker requested changes
I think there's a fairly straightforward performance optimization that could be done on the `prioritizedTabbableElement` assignment and some thoughts on the associated test.

2021-02-19 22:47 UTC, lukelooker commented on packages/components-providers/src/FocusTrap/utils.ts
> +      const firstTabbableElement = tabbable(element)[0]
To otimize performance we probably want to check if a condition before has returned a result and only keep querying if a tabbable element hasn't already been found.

2021-02-19 22:47 UTC, lukelooker commented on packages/components/src/utils/useFocusTrap.test.tsx
> +        <FocusTrapComponent hideClose>
I think this actually points out a minor defect in the `FocusTrapComponent` where it doesn't emulate the structure of our Dialog layout components

I'd actually propose restructuring the `Inner` to like the example below - basically introducing `tabIndex={-1}` to the "early" close option and introducing a `footer` wrapper.

```
const Inner: FC<TestProps> = ({ children, clickOutsideDeactivates }) => {
  const [, ref] = useFocusTrap({ options: { clickOutsideDeactivates } })
  const { value, setOff, toggle } = useToggle()
  return (
    <>
      {value && (
        <div ref={ref}>
          {children}
          <button tabIndex={-1} onClick={setOff}>
            Close
          </button>
        </div>
      )}
      <footer>
        <button onClick={toggle}>toggle</button>
        <button onClick={setOff}>Another button</button>
      </footer>
    </>
  )
}
```

2021-02-20 00:33 UTC, kvrmd commented on packages/components-providers/src/FocusTrap/utils.ts
> +    const node = getInitialFocusNodeByPriority()
I refactored this a bit to call a helper function that does early-returns to avoid unnecessary queries.

2021-02-20 00:35 UTC, kvrmd commented on packages/components/src/utils/useFocusTrap.test.tsx
> +          </button>
@lukelooker fyi I didn't add a tabbable button here, so the test for focusing the surface would still work.

2021-02-20 00:55 UTC, lukelooker approved these changes
Thanks so much for taking this on - this updated behavior is a really nice improvement. :)

Ship it!

2021-02-20 01:02 UTC, merged