feat: customize icon label for localization
looker-open-source/components pull request #1932
Opened 2021-02-18 23:28 UTC by laraharrow

Thank so much for contributing to @looker/components!

The CI & [README](https://github.com/looker-open-source/components/blob/main/README.md) should help to make most of our code standards clear

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [ ] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [ ] not applicable

2021-02-19 01:04 UTC, mdodgelooker requested changes
Use `...rest` instead of `...props` in the components where props are being now destructured differently now because of i18n.

2021-02-22 22:52 UTC, mdodgelooker requested changes
Sorry for the delay – this looks great! Just some super minor feedback.

2021-02-22 22:52 UTC, mdodgelooker commented on packages/components/src/Chip/Chip.tsx
> +  chipIconLabel?: string
I think this one can just be named `iconLabel`.

2021-02-22 22:52 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/AdvancedInputControls.tsx
> +   * customize the tooltip on the closing icon
```suggestion
   * customize the tooltip on the clear icon
```

2021-02-22 22:52 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/types.ts
> +  chipIconLabel?: string
You can remove this here since it's only used in `ComboboxMultiInput` and will get into `ComboobxMultiInputProps` via `InputChipsCommonProps`.
```suggestion
```

2021-02-22 22:52 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/types.ts
> +   * customize the tooltip on the closing icon
```suggestion
   * customize the tooltip on the clear icon
```

2021-02-22 22:52 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/InputSearch/InputSearch.tsx
> +   * customize the tooltip on the closing icon
```suggestion
   * customize the tooltip on the clear icon
```

2021-02-22 23:27 UTC, mdodgelooker commented
Ah sorry if it wasn't clear - I was just suggesting to use iconLabel in Chip.tsx itself but keep chipIconLabel elsewhere.

2021-02-23 21:56 UTC, mdodgelooker requested changes

2021-02-23 21:56 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/ComboboxMultiInput.tsx
> +      iconLabel: iconLabel,
Sorry, I thought everywhere you had `chipIconLabel` before looked good, just the one inside `Chip` itself I thought should be `iconLabel`.

2021-02-23 23:50 UTC, laraharrow commented on packages/components/src/Form/Inputs/Combobox/ComboboxMultiInput.tsx
> +      iconLabel: iconLabel,
oh lol ok fixing it now

2021-02-24 19:55 UTC, mdodgelooker approved these changes

2021-02-24 20:01 UTC, merged