feat: MenuHeading and MenuDivider
looker-open-source/components pull request #1948
Opened 2021-02-22 20:10 UTC by ElliotTheHuman

Added `MenuHeading` and `MenuDivider` to replace `MenuGroup` existing behaviors

### 🔧  TODO (Follow-up PRs)
- Create docs for `MenuDivider` + `MenuHeading`
- Delete `MenuGroup` and replace usage in storybook and docs with `MenuDivider` + `MenuHeading`
- Update `Menu`-related docs to use `MenuDivider` + `MenuHeading`

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [ ] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [ ] not applicable

2021-02-22 20:12 UTC, ElliotTheHuman commented on packages/components/src/Menu/MenuHeading.tsx
> +  )
Aside from the fact that `MenuHeading` respects parent `Menu` / `MenuList`'s "density" value, this file is a copy of `MenuGroupLabel`

2021-02-23 23:25 UTC, ElliotTheHuman commented on packages/components/src/Menu/MenuHeading.tsx
> +        py="xsmall"
These specs were from the design maestro, Jared!
https://www.figma.com/file/zd6MjUXIIstvG7gTJWaX2Y/Looker-Components?node-id=11194%3A93767

2021-02-24 00:02 UTC, mdodgelooker requested changes
Very cool! Had some suggestions on `MenuDivider` styling, and I think codecov is complaining.

2021-02-24 18:55 UTC, ElliotTheHuman commented on packages/components/src/Menu/MenuDivider.tsx
> +`
The & + & is awesome! Thanks for the suggestion :) 

Regarding divider's spacing, I took another look at [Jared's design specs](https://www.figma.com/file/zd6MjUXIIstvG7gTJWaX2Y/Looker-Components?node-id=1861%3A0) and it looks like it's calling for 8px margin above and below the divider, in which case I can push that change up.

That being said, I'm cool with using density to determine spacing as well though if we like that approach better!

@jhardy Thoughts on whether a constant margin-y or using density for margin-y is a better design call here?

2021-02-24 19:09 UTC, ElliotTheHuman commented on packages/components/src/Menu/MenuDivider.tsx
> +`
(Wanted to note that we're not scaling `MenuHeader` with density, so wondering if that tips the scale in favor of not scaling `MenuDivider` as well 🤔 )

2021-02-24 19:19 UTC, ElliotTheHuman commented on packages/components/src/Menu/Menu.story.tsx
> -        </Menu>
I didn't even know Menu had sticky headers. They look real slick 😍 

My fault for removing this in the first place.

2021-02-24 19:20 UTC, ElliotTheHuman commented on packages/components/src/Menu/MenuList.story.tsx
> +      {key < groupsArray.length - 1 && <MenuDivider />}
Resolved in 4dbdb2b

2021-02-24 19:20 UTC, ElliotTheHuman commented on packages/components/src/Menu/Menu.story.tsx
> -        </Menu>
Added back in 4dbdb2b

2021-02-24 19:21 UTC, ElliotTheHuman commented
First round of feedback implemented! (Note: left some thoughts regarding `MenuDivider` margin-y. TLDR is that Jared's design specs call for 8px constant across densities, but I pinged him to see if it's better to have it scale)

2021-02-24 20:21 UTC, ElliotTheHuman commented on packages/components/src/Menu/MenuDivider.tsx
> +`
Spoke to Jared, and he suggested we start simple for now and have 8px for margin-y across the board.

2021-02-24 20:24 UTC, mdodgelooker commented on packages/components/src/Menu/MenuDivider.tsx
> +`
Sounds good! Now I'm just trying to remember what we do about new styled components that bring coverage down... Just ignore? Smoke test by rendering once in Jest?
![image](https://user-images.githubusercontent.com/53451193/109061227-408e2d00-769b-11eb-8213-7a8715f3ac56.png)

2021-02-24 20:28 UTC, mdodgelooker commented on packages/components/src/Menu/MenuDivider.tsx
> +`
Ah sounds like a jest smoke test is in order. Maybe just add a super simple render test with `MenuDivider` and `MenuHeading` in `MenuList.test.tsx`?

2021-02-24 22:15 UTC, ElliotTheHuman commented on packages/components/src/Menu/MenuDivider.tsx
> +`
Good call. Done!

62d32dd

2021-02-24 23:05 UTC, mdodgelooker approved these changes
LGTM!

2021-02-24 23:10 UTC, merged