feat(MultiFunctionButton): component
looker-open-source/components pull request #1955
Opened 2021-02-23 17:25 UTC by laraharrow

Thank so much for contributing to @looker/components!

The CI & [README](https://github.com/looker-open-source/components/blob/main/README.md) should help to make most of our code standards clear

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [ ] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [ ] not applicable

2021-02-23 20:57 UTC, laraharrow commented
TODO

- [ ] keep focus on MultiFunctionButton container
- [ ] keep size (width & height) based on the larger button
    - what if on button is larger on width and the other is larger in height?
    - should we pass the dimensions as props guarantee precision?

2021-02-24 22:14 UTC, lukelooker requested changes
Initial notes on the focus-hold portion of the problem

2021-02-24 22:18 UTC, lukelooker commented on packages/components/src/Button/MultiFunctionButton.tsx
> +    <div aria-live="polite" ref={parent}>
Could put `onClick` handler here if needed.

2021-03-03 00:27 UTC, lukelooker requested changes
Noticed a couple of issues when trying this out (see inline notes).

Codecov notes a few lines missing coverage:

![image](https://user-images.githubusercontent.com/34253496/109733449-f530be80-7b73-11eb-9e65-d08847d16d2c.png)

Can you also look at using this component within the existing `CopyToClipboard` component as well? Should work as an excellent proof-of-concept :)

I think when I pulled the branch I accidently removed you Typescript fix for the ref on `alternate` - can you re-push to get that change included?

2021-03-03 00:27 UTC, lukelooker commented on packages/components/src/Button/MultiFunctionButton.tsx
> +  border: 1px solid ${({ theme }) => theme.colors.key};
This border shouldn't be needed?

```suggestion
```

2021-03-03 00:27 UTC, lukelooker commented on packages/components/src/Button/MultiFunctionButton.story.tsx
> +  alternate: <ButtonTransparent size="large">Copied!</ButtonTransparent>,
Since this is proportedly the inverse of the the "CopyToClipboard" story it'd be ideal to assign `alternate` and `children` to `consts` and share across the two stories to make it easier to see re-use across the two.

2021-03-03 00:27 UTC, lukelooker commented on packages/components/src/Button/MultiFunctionButton.story.tsx
> +      alternate={<ButtonTransparent size="large">Copied!</ButtonTransparent>}
Changing this to include an `iconBefore="Check"` (matching the early design) exposes a bug in the CSS implementation - see note below.

```

const alternate = (
  <ButtonTransparent iconBefore="Check" size="small">
    Copied!
  </ButtonTransparent>
)
```

2021-03-03 00:27 UTC, lukelooker commented on packages/components/src/Button/MultiFunctionButton.tsx
> +      ? `*:first-child {
Needs to only assign style to immediate descendents or causes problems with sub-elements.

```suggestion
      ? `> *:first-child {
```

2021-03-03 00:27 UTC, lukelooker commented on packages/components/src/Button/MultiFunctionButton.tsx
> +      : `*:last-child {
```suggestion
      : `> *:last-child {
```

2021-03-04 19:36 UTC, mdodgelooker requested changes
Great stuff! Added some suggestions for using `useForkedRef` that will make it a bit simpler to use for developers.

2021-03-04 19:36 UTC, mdodgelooker commented on packages/components/src/Button/MultiFunctionButton.tsx
> +}) => {
This will require `displayName` – see suggestion below.
```suggestion
export const MultiFunctionButton = forwardRef(
  (
    {
      alternate,
      children,
      alternateRef,
      swap = false,
    }: MultiFunctionButtonProps,
    forwardedRef: Ref<HTMLButtonElement>
  ) => {
```

2021-03-04 19:36 UTC, mdodgelooker commented on packages/components/src/Button/MultiFunctionButton.tsx
> +}
```suggestion
  }
)

MultiFunctionButton.displayName = 'MultiFunctionButton'
```

2021-03-04 19:36 UTC, mdodgelooker commented on packages/components/src/Button/MultiFunctionButton.tsx
> +  setAlternateRef?: any
Use `RefAttributes` to make `children` & `alternate` accept refs.

`setChildrenRef` can be removed after adding `forwardRef` below, which will make the most common ref use (like what `CopyToClipboard` does) super easy.

As for `alternateRef`, when using `useForkedRef`, it can be either a ref object or a state setter, so we don't need to name it specifically with "set".
```suggestion
  alternate: ReactElement<
    (ButtonProps | IconButtonProps) & RefAttributes<HTMLButtonElement>
  >
  children: ReactElement<
    (ButtonProps | IconButtonProps) & RefAttributes<HTMLButtonElement>
  >
  alternateRef?: Ref<HTMLButtonElement>
```

2021-03-04 19:36 UTC, mdodgelooker commented on packages/components/src/Button/MultiFunctionButton.tsx
> +  FC,
`forwardRef` instead of `FC` (see below).

```suggestion
  forwardRef,
```

2021-03-04 19:36 UTC, mdodgelooker commented on packages/components/src/Button/MultiFunctionButton.tsx
> +  RefObject,
`RefAttributes` will be a slightly simpler way to make `children` and `alternate` accept refs in `cloneElement`.
```suggestion
  Ref,
  RefAttributes,
```

2021-03-04 19:36 UTC, mdodgelooker commented on packages/components/src/Button/MultiFunctionButton.tsx
> +        },
```suggestion
          ref: useForkedRef(aRef, forwardedRef),
```

2021-03-04 19:36 UTC, mdodgelooker commented on packages/components/src/Button/MultiFunctionButton.tsx
> +        },
```suggestion
          ref: useForkedRef(bRef, alternateRef),
```

2021-03-04 19:36 UTC, mdodgelooker commented on packages/components/src/Button/MultiFunctionButton.tsx
> +import styled from 'styled-components'
The hook for combining refs:
```suggestion
import styled from 'styled-components'
import { useForkedRef } from '../utils'
```

2021-03-04 19:36 UTC, mdodgelooker commented on packages/components/src/CopyToClipboard/CopyToClipboard.tsx
> +  const [buttonRef, setButtonRef] = useState<HTMLButtonElement>()
With `useForkedRef` in `MultiFunctionButton` this can go back to how it was before, which is a bit more performant:
```suggestion
  const buttonRef = useRef<HTMLButtonElement>(null)
```

2021-03-04 19:36 UTC, mdodgelooker commented on packages/components/src/CopyToClipboard/CopyToClipboard.tsx
> +      buttonRef.appendChild(textField)
```suggestion
    if (buttonRef.current) {
      buttonRef.current.appendChild(textField)
```

2021-03-04 19:36 UTC, mdodgelooker commented on packages/components/src/CopyToClipboard/CopyToClipboard.tsx
> +        ref={setButtonRef}
We can just add ref once to `<MultiFunctionButton/>` since that component now uses `forwardRef`.
```suggestion
```

2021-03-04 19:36 UTC, mdodgelooker commented on packages/components/src/CopyToClipboard/CopyToClipboard.tsx
> +        ref: setButtonRef,
```suggestion
```

2021-03-04 19:36 UTC, mdodgelooker commented on packages/components/src/CopyToClipboard/CopyToClipboard.tsx
> +      setChildrenRef={setButtonRef}
```suggestion
      ref={buttonRef}
```

2021-03-05 00:25 UTC, mdodgelooker submitted a review, later dismissed
LGTM!

2021-03-05 16:57 UTC, mdodgelooker approved these changes

2021-03-05 16:58 UTC, merged