fix(DataTable): Firefox border-bottom bug
looker-open-source/components pull request #1961
Opened 2021-02-24 20:09 UTC by laraharrow

Thank so much for contributing to @looker/components!

The CI & [README](https://github.com/looker-open-source/components/blob/main/README.md) should help to make most of our code standards clear

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [ ] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [ ] not applicable

2021-02-24 22:04 UTC, laraharrow commented
Here is the fix:
https://user-images.githubusercontent.com/23616264/109071940-3a9f4880-76a9-11eb-8ae5-d8451a904a34.mov

2021-02-25 16:50 UTC, lukelooker requested changes

2021-02-25 16:50 UTC, lukelooker commented on packages/components/src/DataTable/Table.tsx
> -  height: initial;
This is related to the Safari fix (#1965), correct? If so, can it get moved over there to keep git-history linked up correctly?

2021-02-25 17:46 UTC, laraharrow commented on packages/components/src/DataTable/Table.tsx
> -  height: initial;
this is out of date

2021-02-25 18:42 UTC, lukelooker approved these changes
LGTM! Ship it!

2021-02-25 20:42 UTC, merged