refactor(Tree): Replaced useHovered with simpleHandlers
looker-open-source/components pull request #1962
Opened 2021-02-24 23:13 UTC by ElliotTheHuman

`useHovered` was designed specifically for the "hidden element revealed when hovering over some other element" pattern. In `Tree`'s case, we just need simple mouseEnter and mouseLeave handlers to track hover state for styling purposes.

**Note:** Needed to update some code in `AccordionDisclosure` since it had CompatibleHTMLProps in its interface, but didn't actually pass those down to underlying DOM elements.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [ ] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [ ] not applicable

2021-02-25 17:01 UTC, lukelooker reviewed
Two questions but behavior / code looks good overall.

2021-02-25 17:01 UTC, lukelooker commented on packages/components/src/Accordion/AccordionDisclosure.tsx
>      }
Could `useWrapEvent` be used here with? E.g.:

```
const handleKeyDown = (event: KeyboardEvent<HTMLElement>) => 
  useWrapEvent((event) => { event.key === 'Enter' && handleToggle() }, onKeyDown)
```

2021-02-25 17:03 UTC, lukelooker commented on packages/components/src/Accordion/AccordionDisclosure.tsx
> +      onKeyUp && onKeyUp(event)
Would be good to have a test that assigns `onKeyUp` & onClick` and `onBlur` and verifies that the passed in callbacks are getting called properly.kj

2021-02-25 17:04 UTC, lukelooker requested changes
Realized this begs for a quick test coverage pass of `on*` handlers getting passed through.

2021-02-25 19:38 UTC, ElliotTheHuman commented on packages/components/src/Accordion/AccordionDisclosure.tsx
> +        {...props}
All of the CompatibleHTMLProps land on the `AccordionDisclosureStyle` div, so (iiuc) using `pickStyledProps` here will keep HTML props from reaching the an underlying div.

That being said, I could see an argument for renaming `AccordionDisclosureStyle` to `AccordionDisclosureWrapper` since it's technically doing more than styled. Thoughts?

2021-02-25 19:51 UTC, ElliotTheHuman commented
Future TODO for myself: Add CompatibleHTMLProps to `Accordion` during the `AccordionDisclosure` refactor since disclosure will no longer be exposed to users.

They'll have to pass any HTML props for the underlying disclosure div to `Accordion`, who then passes it to the internal `AccordionDisclosure.

2021-02-25 19:56 UTC, ElliotTheHuman commented on packages/components/src/Accordion/AccordionDisclosure.tsx
> +      onKeyUp && onKeyUp(event)
Good call. Resolved in 8779501.

2021-02-25 19:57 UTC, ElliotTheHuman commented on packages/components/src/Accordion/AccordionDisclosure.tsx
>      }
We could! And should.

Resolved in 8779501.

2021-02-26 17:31 UTC, lukelooker commented on packages/components/src/Accordion/AccordionDisclosure.tsx
> +        {...props}
👍  That makes sense. I guess this change has the possibility of introducing breakage downstream if a developer was assigning a prop that we previously ignored but in general I think that's acceptable since the previous behavior (ignoring domProps) wasn't intuitive and the typing made it look like it _should_ work to assign those.

As to renaming - we're not super consistent with our internal component names so I wouldn't worry about it within this PR. It probably would be worth doing an audit of our naming conventions and seeing if we can come up with some better conventions standards at some point (I'll make a note on our tech-debt log)

2021-02-26 17:31 UTC, lukelooker approved these changes
LGTM! 

Great work :)

2021-02-26 17:46 UTC, merged