docs: Added MenuDivider and MenuHeading docs
looker-open-source/components pull request #1968
Opened 2021-02-25 19:17 UTC by ElliotTheHuman

- Added `MenuDivider` and `MenuHeading` doc mentions in Menu docs
- Removed `MenuGroup` doc portion from MenuList docs
- Added note about `density` prop to Menu docs

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [ ] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [ ] not applicable

2021-02-25 19:19 UTC, ElliotTheHuman commented on www/src/documentation/components/overlays/menuitem.mdx
> -```
Icon placeholder behavior is no longer automatically handled by `MenuContext` and is instead provided by the user using the `iconGutter` prop on a parent `Menu` / `MenuList`. This is described in the `Menu` docs.

2021-02-26 06:14 UTC, mdodgelooker requested changes
Looks good! Just a couple minor suggestions.

2021-02-26 06:14 UTC, mdodgelooker commented on www/src/documentation/components/overlays/menu.mdx
> +    <Button>Icon Gutter</Button>
```suggestion
    <Button>No Icon Gutter</Button>
```

2021-02-26 06:14 UTC, mdodgelooker commented on www/src/documentation/components/overlays/menu.mdx
> +    <Button>No icon Gutter</Button>
```suggestion
    <Button>Icon Gutter</Button>
```

2021-02-26 06:14 UTC, mdodgelooker commented on www/src/documentation/components/overlays/menulist.mdx
>  This is the most efficient mode, but scrolling will be distorted if the list is grouped.
Might as well delete these too – they're not that helpful now that we don't do groups & variable windowing.
```suggestion
```

2021-02-27 00:33 UTC, mdodgelooker approved these changes
LGTM!

2021-02-27 00:59 UTC, merged