fix: Slider & RangeSlider properly support floating step
looker-open-source/components pull request #1974
Opened 2021-02-27 00:22 UTC by lukelooker

Corrects behavior in `Slider` to treat steps as floats.
Corrects incrementPoint / decrementPoint in `RangeSlider` to address JS floating point eccentricities

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [ ] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [ ] not applicable

2021-02-27 00:29 UTC, lukelooker commented
@dbchristopher - I suspect the `RangeSlider` fix I did could be done in a more clever way perhaps leveraging other helpers already within that code so before I chase down codecov's complaint (needs a smidge more test-coverage) I figured I'd wait to see your general feedback here.

2021-03-01 19:04 UTC, dbchristopher requested changes
This looks good to me! I think you picked the best place to handle the floating point math. I did see this when I was testing in storybook, but it was after trying to tweak a couple of things on my end. So I'm not sure if it's a real issue or not, but my cloudtop has suddenly become so mind bogglingly slow that I can't even back out of my changes and try again 😳 

<img width="307" alt="Screen Shot 2021-03-01 at 10 57 06 AM" src="https://user-images.githubusercontent.com/238293/109545305-8cffb100-7a7d-11eb-9829-aff024c560d3.png">

So anyways, just want to make sure you can double check that it's working well! And then I suggested a couple of more readable approaches to those precision utility functions

2021-03-01 19:56 UTC, dbchristopher commented
Oh actually, the incrementPoint/decrementPoint helpers are only part of the keyboard navigation ux 🤦‍♂️  That was why I was still seeing the floating point issue in the UI. I think it could go in the roundToStep helper. I think I have an idea of how it could be integrated more thoroughly..

2021-03-01 20:07 UTC, dbchristopher commented on packages/components/src/Form/Inputs/RangeSlider/RangeSlider.tsx
> +  newPoint: number
swapped this argument order to make it easier to partially apply those first three values which shouldn't change over the life of this component

2021-03-01 20:08 UTC, dbchristopher commented on packages/components/src/Form/Inputs/RangeSlider/RangeSlider.tsx
> +      point - step * stepMultiplier
Remove math.min and math.max because that happens in `roundToStep` now

2021-03-01 20:09 UTC, dbchristopher commented on packages/components/src/Form/Inputs/RangeSlider/RangeSlider.tsx
> +          )
now both keyboard and mouse events use the same `roundToStep` helper which makes more sense anyways

2021-03-01 20:12 UTC, dbchristopher approved these changes
Ok this looks good to me! While I almost always prioritize readability over performance optimizations, I'm ok with leaving those precision helpers in their mathematical forms. 

I did some testing at https://jsbench.me/ and found your versions to be ~80% faster. In this case there are potentially so many mouse event updates that it would be nice to squeeze out a few more ms to keep things snappy

2021-03-01 20:14 UTC, dbchristopher commented on packages/components/src/Form/Fields/FieldRangeSlider/FieldRangeSlider.story.tsx
> +Floating.args = { max: 3.7, min: 0.1, step: 0.1 }
added a larger slider range to more easily test the shift+arrow interactions (for skipping 10x steps per keypress)

2021-03-01 20:47 UTC, merged