fix(List): Fixed List / Menu windowing
looker-open-source/components pull request #1997
Opened 2021-03-04 01:21 UTC by ElliotTheHuman

I noticed that scrolling in a long `Menu` seemed to have a bounce / rubber band effect on `main`.

Turns out, I had forgotten to pass the `ref` returned from `useWindow` to `List`'s underlying `ul` element 🤦 . From what I can tell, this meant that the scroll position event handlers produced by `useScrollPosition` weren't attaching to the container `ul`, which meant that scroll position wasn't being calculated properly on scroll (which caused the bounce effect).

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [ ] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [ ] not applicable

2021-03-04 04:36 UTC, mdodgelooker requested changes
Good catch on the bounce, but `navProps` contains a `ref`, merged with the one used for arrow key navigation. This change would break the navigation, but it does fix the bounce. So I think there must be something in `useArrowKeyNav` causing this. I'll look into it too.

2021-03-04 04:49 UTC, mdodgelooker commented
Looks like the bounce is being caused by repeated calls to `placeInitialFocus` inside `useArrowKeyNav` as the focused element keeps getting removed from the dom as you scroll – and then moving focus to the top rendered item makes the browser try to scroll that into view, I think. Somehow we need to disable that behavior until after scrolling has stopped. Let's chat about it mañana?

2021-03-04 20:10 UTC, ElliotTheHuman commented
Heads up! This PR ended up covering two separate issues related to windowing. The two broad areas of code change are:
1. Created a `getFallbackElement` function that returns the first visible fallback element (if possible)
2. The `LongList` story in `MenuList` and `List` did not have a container with explicit height, which led to all child items trying to render. I added a `Box` container to each and left a note in the `Windowing` sections of both respective docs.

2021-03-04 20:15 UTC, ElliotTheHuman commented on packages/components/src/utils/getNextFocus.ts
> +    else fallback = tabStops[0]
I don't know exactly what case you'd want this else, but...
1. Having it prevents the return type from including "undefined"
2. It probably makes sense to return the first tabbable element should anything weird happen

2021-03-05 03:02 UTC, mdodgelooker approved these changes
Great fix @ElliotTheHuman ! As long as you're feeling good about `height: 100%` on list, I say ship it.

2021-03-05 03:02 UTC, mdodgelooker commented on packages/components/src/List/List.tsx
> +  height: 100%;
Hopefully this won't have any unintended consequences? I can't think of any, and I know it's a good way to make sure windowing is easy to accomplish – otherwise you have to do a bunch of flex-y styles on the container – but I wouldn't want it to give us any fun surprises...

2021-03-05 18:23 UTC, ElliotTheHuman commented on packages/components/src/List/List.tsx
> +  height: 100%;
Yeah, this seemed like the simplest way to prevent `List` from growing outside the confines of its parent. Definitely open to revisiting this solution should we run into a fun surprise with an edge case.

2021-03-05 18:24 UTC, merged