refactor(InputColor): Created new ColorPicker base component
looker-open-source/components pull request #2013
Opened 2021-03-09 23:58 UTC by ElliotTheHuman

- Added a new `ColorPicker` component, a composition of the new `HueSlider` and `LightSaturationPreview` components
- Refactored `InputColor` to use new `ColorPicker` foundation
- Updated `InputColor` test suite

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [ ] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [ ] not applicable

2021-03-10 19:06 UTC, lukelooker commented on packages/components/src/Form/Inputs/InputColor/HueSlider/HueSlider.tsx
> +const sliderHeight = 12
```suggestion
const SLIDER_HEIGHT = 12
```

2021-03-10 22:36 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/HueSlider/HueSlider.tsx
> +  width: ${SLIDER_WIDTH}px;
We discussed being able to set this to 100% since the `ColorPicker` `SpaceVertical` container can take a hardcoded width so that we can remove `SLIDER_WIDTH` from the code here (and from `LightSaturationPreview`).

However, in both `LightSaturationPreview` and `HueSlider` we use `SLIDER_WIDTH` in the drag and click handlers, so I figured because we needed it there, it makes sense to keep it in the CSS-in-JS for readable.

2021-03-10 22:38 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/HueSlider/HueSlider.tsx
> +const sliderHeight = 12
Resolved in 6378918

2021-03-10 22:38 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/utils/color_utils.ts
> +}
Resolved in 6378918

2021-03-10 23:47 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/utils/color_format_utils.test.tsx
> -})
As far as I can tell, the `color_format_util` functions we use in the new `InputColor` have unit tests in this file (i.e. the ones that have an individual file and were NOT deleted).

In which case, I _believe_ the right answer is to just delete this file outright since any functions being tested here have been deleted.

2021-03-10 23:50 UTC, ElliotTheHuman commented
Went ahead and pulled out all the `color_format_util` functions we use in the new `InputColor` into their own files.

**Note:** I saw some naming inconsistencies (i.e. some functions were named `X to Y` format while others were just `to Y` format). Went ahead and standardized all the named to be A) Camel Case and B) Follow the `X to Y` naming scheme.

2021-03-10 23:51 UTC, ElliotTheHuman commented
Another note, but the pulled out `color_format_util` functions do NOT have any existing coverage afaik. Happy to include that in this PR, but figure it might be better to leave for a follow-up since the line count is already pretty high here.

2021-03-12 06:12 UTC, lukelooker requested changes
Ok - took a little while to get through this. 

Synopsis of my feedback is:

- I think consolidate the control of `width` into `InputColor` would make sense (basically having `InputColor` specifically codify `200px` as the width for the `ColorPicker` and then having `ColorPicker` forward the value "down" to the subcomponents would leave future flexibility.
- I think `handle` can be DRY'd up in code a bit - I also think it'd be worth pulling those out into their own respective files.
- Currently the handle for the `HueSlider` is changing when `LightSaturation` adjustments are made. It should reflect just the hue and not light/saturation values (take a look at how Chrome's native `input type="color"` implementation works for an example (let me know if this isn't clear)
- Code coverage for "drag" behaviors is low - I have no idea how feasible it is to test within Jest / RTL but it'd be worth pondering a bit.

In looking at the `simpleHsvToFormattedColorString` I noticed that only the first argument was used - this meant effectively that the vast majority of the logic in the function wasn't in play. I went ahead pushed in a commit (https://github.com/looker-open-source/components/pull/2013/commits/f60600d0d9a68d390c0e50cd7ee24e2e0ea10bde) that reduced the function to the portion _actually_ in use and deleting all the unused helpers.

I added some notes about how we can probably completely remove our dependency on D3 but I think we can hold off on that until a later piece of work - was mostly just pondering how feasible that would be so feel free to ignore those comments.

2021-03-12 22:30 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/LightSaturationPreview/LightSaturationPreview.tsx
> +`
Good call. Resolved in ae9c5da

2021-03-12 22:37 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/utils/simpleHsvToFormattedColorString.ts
> +      return rgbToRgbpString(rgbColor)
Believe this was done in f60600d0d9a68d390c0e50cd7ee24e2e0ea10bde! Thank you for removing those.

2021-03-12 22:37 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/utils/simpleHsvToFormattedColorString.ts
> +      return rgbToHslString(rgbColor)
Same as above.

2021-03-12 22:41 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/HueSlider/HueSlider.tsx
> +const SLIDER_HEIGHT = 12
👍  Resolved in 45b2a96

2021-03-12 22:43 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/InputColor.tsx
>        <PopoverContent display="flex" flexDirection="column">
👍

2021-03-12 22:46 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/LightSaturationPreview/LightSaturationPreview.tsx
> +const HANDLE_WIDTH = theme.sizes.small
Resolved in 24fdaadde!

2021-03-12 22:47 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/Swatch/Swatch.test.tsx
> +  })
![image](https://user-images.githubusercontent.com/16812885/111006573-e3a0a100-8341-11eb-9dbd-3941fd533905.png)

2021-03-12 23:28 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/InputColor.tsx
> +          setHsv={setColorState}
Done in 24fdaad!

2021-03-12 23:28 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/LightSaturationPreview/LightSaturationPreview.tsx
> +const PREVIEW_HEIGHT = 150
Done in 24fdaad!

2021-03-12 23:29 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/HueSlider/HueSlider.tsx
> +const SLIDER_WIDTH = COLOR_PICKER_WIDTH
Done in 24fdaad!

2021-03-12 23:54 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/InputColor/HueSlider/HueSlider.tsx
> +`
Done in 0334dc8! Moved the bulk of the CSS into a css`` styled helper function call that's shared between both 1d and 2d.

Also moved both `Handle` files into their own subdirectory.

2021-03-12 23:58 UTC, ElliotTheHuman commented
Feedback implemented! Thanks for reviewing; the code feels way more organized / sensibly laid out now.

**Note:** Haven't included any test-related changes yet. Did you want to leave those for a follow-up PR or include those here (I'm happy to do either).

2021-03-17 04:26 UTC, lukelooker approved these changes
LGTM

2021-03-17 16:16 UTC, merged