feat(Layout): add position fixed to Header and Footer
looker-open-source/components pull request #2028
Opened 2021-03-11 02:24 UTC by laraharrow

Thank so much for contributing to @looker/components!

The CI & [README](https://github.com/looker-open-source/components/blob/main/README.md) should help to make most of our code standards clear

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [ ] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [ ] not applicable

2021-03-12 06:47 UTC, lukelooker requested changes
Let's chat about this tomorrow - I think we should come up with a few specific examples so we can have a "test suite" as it were for possible solutions :)

2021-03-12 06:47 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Header.tsx
> +      position: sticky;
`position: sticky` isn't supported in IE11 :/

2021-03-12 06:47 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Layout.tsx
> +  max-height: 100vh;
This may not work in some scenarios - `100vh` applies to the viewport so if the `Layout` isn't the full viewport height this will mix-calculate.

2021-03-19 17:19 UTC, dbchristopher requested changes
Looks good! Just caught a couple really tiny issues

2021-03-19 17:19 UTC, dbchristopher commented on packages/components/src/Layout/Semantics/Semantics.test.tsx
> +  test('has Header and Footer positions fixed when passifn prop fixed', () => {
```suggestion
  test('has Header and Footer positions fixed when passing prop fixed', () => {
```

2021-03-19 17:19 UTC, dbchristopher commented on packages/components/src/Layout/Semantics/Semantics.test.tsx
> +    )
judging by the test description, you probably want to validate the `position: fixed` style rule instead?

2021-03-19 20:26 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Layout.tsx
> +    `}
Moving the overflow out of the interpolation saves the need for the `css` helper:

```
overflow:  ${({ fixed }) => fixed ? 'hidden' : 'auto'};
```

2021-03-19 21:47 UTC, laraharrow commented on packages/components/src/Layout/Semantics/Semantics.test.tsx
> +    )
Because of the way we are implementing the fixed position we actually does not have `position: fixed` we are using `flex` and all the logic is all on the `Layout` layer and doesn't ever trigger any change on `Header` or `Footer`

2021-03-19 22:06 UTC, dbchristopher approved these changes

2021-03-19 22:13 UTC, merged