fix(Space): Remove snapshot tests, add justify support, default DataTable to 100% width
looker-open-source/components pull request #2050
Opened 2021-03-15 22:53 UTC by lukelooker

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [ ] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [ ] not applicable

2021-03-15 23:32 UTC, ElliotTheHuman requested changes
Mostly minor requests! One thing I will say is that it might be worth replacing the `spaceCSS` styled function with `simpleLayoutCSS` (which doesn't include the `flexbox` styled function) and removing `FlexboxProps` outright.

As it stands, you can still add a `justifyContent` content prop that works properly. It's not a problem per say, but it could be confusing to have both the traditional flex-related props and our more targeted suite of flex props (i.e. `justifyContent` vs `justify`).
![Screen Shot 2021-03-15 at 4 25 52 PM](https://user-images.githubusercontent.com/16812885/111234135-1f8a6f00-85ab-11eb-9554-5c6fa0a49d30.png)

I'm cool with supporting both the traditional flex props and our own flex-related props if it's not a huge deal though!

2021-03-15 23:32 UTC, ElliotTheHuman commented on packages/components/src/Layout/Space/Space.test.tsx
> +  })
I think we're already "testing" space with image snapshots.

It might make sense to check the `margin-right` on one of the child divs, but image snapshots probably do a good enough job of covering this. In which case, maybe we should just delete the xtests?

2021-03-15 23:32 UTC, ElliotTheHuman commented on packages/components/src/Layout/Space/Space.tsx
> +   * NOTE: Justifcation is based on flex-direction so if `reverse=true` this will be "backwards"
```suggestion
   * NOTE: Justification is based on flex-direction so if `reverse=true` this will be "backwards"
```

2021-03-15 23:32 UTC, ElliotTheHuman commented on packages/components/src/Layout/Space/Space.tsx
> +import { justifyContent, variant } from 'styled-system'
I don't _think_ this `justifyContent` function is being used anywhere (the only other place the text `justifyContent` is seen is seen is in the variant call below, but it's just as a property name, i.e. not the styled system function).

2021-03-15 23:43 UTC, lukelooker commented on packages/components/src/Layout/Space/Space.test.tsx
> +  })
Yeah - i'm down with that :)

2021-03-15 23:44 UTC, lukelooker commented on packages/components/src/Layout/Space/Space.tsx
> +import { justifyContent, variant } from 'styled-system'
Oops... accidentally imported this :)

2021-03-15 23:50 UTC, lukelooker commented
Your point about `justifyContent` _also_ being available is apt but I _think_ there's value in being explicit about the preferred way to justify content (I've seen folks frequently mixing up flex attributes so providing a "happy path" seems worthwhile. 

I did update the JSDoc to be more explicit about what will conflict with the `justify` setting. Let me know your thoughts.

2021-03-16 16:57 UTC, ElliotTheHuman approved these changes
LGTM! Thanks for adding that note about the `justify` prop.

2021-03-16 17:01 UTC, merged