fix(DataTable): update gap space between content and indicator
looker-open-source/components pull request #2065
Opened 2021-03-17 17:33 UTC by laraharrow

Thank so much for contributing to @looker/components!

The CI & [README](https://github.com/looker-open-source/components/blob/main/README.md) should help to make most of our code standards clear

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [ ] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [ ] not applicable

2021-03-17 21:24 UTC, dbchristopher requested changes
The code looks good! I just left a comment about naming convention that I think would be good to update so as not to cause any confusion in the future

2021-03-17 21:24 UTC, dbchristopher commented on packages/components/src/DataTable/stories/useIndicator.tsx
> +UseIndicator.args = {
Just for the sake of preventing future confusion, I'd probably just rename the story and filename to simply `Indicator`. The convention for `use...` usually indicates a custom hook. But I think in this case it's simply indicating that the indicator prop is being used?

2021-03-17 21:28 UTC, laraharrow commented on packages/components/src/DataTable/stories/useIndicator.tsx
> +UseIndicator.args = {
oh good point!

2021-03-17 21:37 UTC, dbchristopher submitted a review, later dismissed
Looks good! 👍

2021-03-18 16:18 UTC, dbchristopher approved these changes

2021-03-18 16:20 UTC, merged