feat(Select): Support windowing for grouped options
looker-open-source/components pull request #2071
Opened 2021-03-17 22:59 UTC by mdodgelooker

Thank so much for contributing to @looker/components!

The CI & [README](https://github.com/looker-open-source/components/blob/main/README.md) should help to make most of our code standards clear

Before requesting review from another developer please delete the lines above and summarize your change.

### Requirements

Please check the following items are addressed in your pull request (or are not applicable)

- [ ] a11y impact (FUTURE: Make aXe pass req'd for CI ✅)

#### Image snapshots (choose one)

  - [ ] yes
  - [ ] not applicable

#### Documentation updated (choose one)

  - [ ] yes
  - [ ] not applicable

2021-03-24 18:27 UTC, ElliotTheHuman commented on packages/components/src/List/utils/listPadding.ts
> +export const listPadding = (ItemComponent: StyledComponent<any, any>) => css`
I think leaving a comment here could be helpful since there's no actual padding in the CSS. Something like...

```
This CSS gives collection component (i.e. Menu, Select) spacing above the first item, below the last item, and before and after `ListDivider`s.
```

2021-03-24 21:09 UTC, ElliotTheHuman requested changes
Some minor feedback and questions about the codebase in general, but nothing major.

Looks really, really great 😃

2021-03-24 21:09 UTC, ElliotTheHuman commented on packages/components/src/Form/Inputs/Select/utils/useWindowedOptions.tsx
>      // But we can't use windowedOptions if there are groups
I could be wrong, but this comment can be removed now right? Since there technically aren't any groups anymore?

2021-03-25 16:53 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/ComboboxList.tsx
> +          // scrollIntoView()
Close. It's a little hard to describe, but basically when your mouse is resting over the list and you're scrolling, you keep firing `mouseenter` on the options as they go by. If you're scrolling fast enough, the option may already be scrolle out of the visible window by the time `useOptionScroll` is called. This hook sees that the currently highlighted option is not visible, so it calls `scrollIntoView()` on it, forcing the browser to scroll in reverse till that option becomes visible again. The effect is a scroll jitter. The fix is to not highlight a `mouseenter`ed option if the user is currently scrolling, which `isScrollingRef.current` tells us.

2021-03-25 16:58 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/ComboboxList.tsx
> +          // scrollIntoView()
This also applies to keyboard navigating. If you arrow key down until you hit the bottom of the visible area, when you get to the first "not visible" option, `scrollIntoView()` gets called, the list scrolls just enough to make it visible, and if your mouse happens to be resting over the list, a `mouseenter` is triggered. Without the check for `isScrollingRef.current`, it would end up being a battle between keyboard nav and mouse over which option should be highlighted. This was already fixed previously because `isAutoScrollingRef` was set to true right before `scrollIntoView()` was called. But I moved it to the scroll event listener (and changed the name) to make it apply to either "auto" scroll, or user scroll (the issue above).

2021-03-25 18:06 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/utils/useOptionEvents.ts
> +    isScrollingRef,
See long-winded comments above, but it's not an element ref, it's a mutable value ref for tracking scrolling without forcing a re-render like `useState` does: https://reactjs.org/docs/hooks-faq.html#is-there-something-like-instance-variables

2021-03-25 18:08 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Select/utils/useFlatOptions.ts
> + * 2) navigationOptions that only includes options with values
Exactly. `navigationOptions` are guaranteed to have a `value` which is used for navigation, getting the current display value for the input, and other stuff like that. `flatOptions` may not have a value (like dividers & headers) and are just used for windowing & rendering.

2021-03-25 18:12 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Select/utils/useWindowedOptions.tsx
>      // But we can't use windowedOptions if there are groups
Haha nope you're not wrong. Removing this comment pretty much sums up the whole point of this PR 😅

2021-03-30 19:36 UTC, lukelooker approved these changes
Change looks really solid - I think it makes sense to move forward unless @ElliotTheHuman has any remaining concerns. 

It looks like the snapshot change is because jest-image-snapshot "trims" the leading margin which is a little funny but definitely not tragic.

2021-03-30 20:35 UTC, merged