feat(List): NavList
looker-open-source/components pull request #2115
Opened 2021-03-24 05:37 UTC by laraharrow

Created NavList component to support Lists

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested

2021-03-25 06:18 UTC, lukelooker requested changes

2021-03-25 06:18 UTC, lukelooker commented on packages/components/src/List/List.story.tsx
> +import { NavList } from './NavList'
This should get parked in it's own `NavList.story` file.

Also probably ideal to make `NavList` a top-level directory `/components/src/NavList`

2021-03-25 06:18 UTC, lukelooker commented on packages/components/src/List/NavList.tsx
> +  ${AccordionDisclosureStyle}, ${ListItemLabel} {
@ElliotTheHuman Is this likely to break with your changes or will this continue to work? `NavList` "presumes" that items will be `role="link"|"button"` in my mind.

2021-03-25 06:18 UTC, lukelooker commented on packages/components/src/List/NavList.tsx
> +export const NavList = styled(List)`
This should have JSDoc block explaining how to use this.

Also (new thing)... let's put this in the doc block:

```
  @status: EXPERIMENTAL
  This component is in active development and may see significant change in it's behavior, interface & presentation. It may also be deprecated without SemVer major version change. _It is not recommended to use this component at this time._
```

2021-03-25 22:21 UTC, ElliotTheHuman commented on packages/components/src/List/NavList.tsx
> +  ${AccordionDisclosureStyle}, ${ListItemLabel} {
Think we're good! Since the styled override ends up passing a class to whatever actual DOM element gets rendered (be it div, a or button). Tested these exact style overrides on my dev branch and things look good:
![Screen Shot 2021-03-25 at 3 19 56 PM](https://user-images.githubusercontent.com/16812885/112551156-c3c79f00-8d7d-11eb-8702-e9812470c9d4.png)

2021-03-31 18:03 UTC, lukelooker requested changes
See comments inline. 

NavList also needs to be exported from the root `components/src/index.ts` file so folks can import it

2021-03-31 18:03 UTC, lukelooker commented on packages/components/src/NavList/NavList.tsx
> + */
Needs a space here and the comment should break lines at ~80 characters generally:


```suggestion
 * @status: EXPERIMENTAL
 * This component is in active development and may see significant change in 
 * it's behavior, interface & presentation. It may also be deprecated without 
 * SemVer major version change. _It is not recommended to use this component 
 * at this time.
 */
```

2021-03-31 23:38 UTC, lukelooker requested changes

2021-03-31 23:38 UTC, lukelooker commented on packages/components/src/NavList/NavList.tsx
> +    color: ${({ theme }) => theme.colors.key};
This is causing trouble :/ (no purple text when the ListItem is "resting")

```suggestion
```

2021-04-01 00:51 UTC, lukelooker requested changes
![image](https://user-images.githubusercontent.com/34253496/113228397-a6954380-9249-11eb-90e0-91e2132ad4e5.png)

Snapshot still appears to reflect the `key` color text for the inactive item

2021-04-01 22:49 UTC, lukelooker approved these changes
LGTM!

2021-04-01 22:49 UTC, merged