feat(Layout): scroll use cases
looker-open-source/components pull request #2186
Opened 2021-04-13 22:22 UTC by laraharrow

## 👋👋 Thank you for contributing to Looker Components (⚡️🍣)

📺 Watch a quick video on how to you make your pull requests fast and easy for you and your reviewer(s):
https://threadit.app/thread/k45nyrqugoinw6xub9vf/message/fl8m57exhqg4r0a4hg01eebn

- 👆 Make sure your pull request title follows [Pull Request Title Guidelines](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#title-guidelines) from our [Contribution guide](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md)
- 👉 Don't forget to replace these instructions with your _✨awesome✨_ description of what this change _actually does_. Additionally it's great to include context on how it works and why the change was needed.
- 👇 Edit "Developer Checklist" to reflect items relevant to this PR (and try to make sure to check everything off before asking for review)

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-04-15 22:37 UTC, dbchristopher requested changes
This works well! Clever use of `fit-content` to accomplish the task, I don't think I would have ever thought of that. I suggested a couple small tweaks to the code as is, but also offered up an alternate approach to structure the API in hopes of keeping the components pure. Let me know what you think!

2021-04-15 22:37 UTC, dbchristopher commented on packages/components/src/Layout/Semantics/Layout.tsx
> +   *  independently | x number of areas together | all together
this seems to describe three different options, when in reality it's just a boolean. Maybe just lose that middle one

```suggestion
   *  independently | all together
```

2021-04-15 22:37 UTC, dbchristopher commented on packages/components/src/Layout/Semantics/Layout.tsx
> +  scrollChildren?: boolean
I wonder if `scrollGroup` or `scrollTogether` would be any more clear about the behavior this prop controls? I'm just thinking that when `scrollChildren` is false the children _do_ still scroll, they just scroll independently. 🤔  That's definitely a subtle distinction though and I might be overthinking it.

2021-04-15 22:37 UTC, dbchristopher commented on packages/components/src/Layout/Semantics/Layout.tsx
> +      main {
I will always be nervous when components start overwriting each other's styles. It makes them impure, which makes css harder to debug because you can't just look at one file and know where the styles are coming from. Do you think it would make sense to flip the approach, and add a prop like `scrollWithin` to the `Aside` and `Section` components instead? I imagine something like this:

```
<Layout hasAside>
  <Aside>...</Aside>
  <Section scrollWithin={false}>...</Section>
  <Aside scrollWithin={false}>...</Aside>
</Layout>
```

`scrollWithin` would toggle `height: fit-content;` as you've done here, but default to `true` so as not to break current implementations. And with this approach _I believe_ you could accomplish all three of these new stories with identical markup, without having to create nested Layout groups.

Let me know what you think!

2021-04-16 16:37 UTC, laraharrow commented on packages/components/src/Layout/Semantics/Layout.tsx
> +        overflow: auto;
yep you are right!

2021-04-16 16:41 UTC, laraharrow commented on packages/components/src/Layout/Semantics/Layout.tsx
> +  scrollChildren?: boolean
yeah I agree, that was just the name on the example Luke gave me but `scrollTogether` is more appropriated for sure

2021-04-16 17:06 UTC, laraharrow commented on packages/components/src/Layout/Semantics/Layout.tsx
> +      main {
Oh yeah I do like this a lot. I think you bring up a good point I'm updating the code now to follow your logic!

2021-04-16 18:36 UTC, dbchristopher requested changes
This is really close! Thanks for the updates. 

I'm sorry I suggested another name change for that prop lol 🙈  That's a tough one to describe succinctly!

2021-04-16 18:36 UTC, dbchristopher commented on packages/components/src/Layout/Semantics/Layout.tsx
> +//     `}
can be removed now!

2021-04-16 18:36 UTC, dbchristopher commented on packages/components/src/Layout/Semantics/Semantics.test.tsx
> +    })
this passes if you change to `toHaveStyleRule`

```suggestion
    expect(screen.getByText("I'm the Aside before")).not.toHaveStyleRule(
      'height'
    )
```

2021-04-16 18:36 UTC, dbchristopher commented on packages/components/src/Layout/Semantics/semanticStyledBase.ts
> +  scrollWithin?: boolean
Naming is so hard 😩 I know this was my suggestion, but seeing it now I think it still isn't quite clear what behavior this controls. What about `scrollWithLayoutGroup`?

2021-04-16 18:36 UTC, dbchristopher commented on packages/components/src/Layout/Semantics/semanticStyledBase.ts
> +   */
Oh that's a good callout that it's meant to be used within a `<Page fixed>`! I think that could be a little more explicit about _which_ fixed prop you're referring to since that's a different component entirely. Maybe this?

```suggestion
  /**
   * To be used within the context of <Page fixed> container. 
   * When true, this removes the inner overflow-y scrolling
   * and allows content within a Layout group to scroll together.
   * @default false
   */
```

2021-04-16 18:36 UTC, dbchristopher commented on packages/components/src/Layout/Semantics/Header.tsx
> +    Omit<SemanticLayoutBase, 'scrollWithin'>,
I think that the fact that this prop can't be used on Header means the prop shouldn't be defined on the shared `SemanticLayoutBase` interface. It's one of those cases where [some duplication is better than DRY code](https://sandimetz.com/blog/2016/1/20/the-wrong-abstraction).  I'd copy it over over to both `AsideProps` and `SectionProps` instead

2021-04-16 20:21 UTC, laraharrow commented on packages/components/src/Layout/Semantics/semanticStyledBase.ts
> +   */
thanks, naming things and explaining  use cases are so hard some times.

2021-04-16 21:06 UTC, dbchristopher approved these changes
Looks good!

2021-04-16 21:07 UTC, merged

2021-04-19 16:30 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Section.tsx
> +  ${({ scrollWithin }) => scrollWithin && 'height: fit-content;'}
@laraharrow  - `fit-content` isn't supported in IE11