fix(TreeItem): Clicks on padding trigger onClick when parent Tree labelBackgroundColor is true
looker-open-source/components pull request #2189
Opened 2021-04-13 23:33 UTC by ElliotTheHuman

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-04-13 23:34 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +    const handleMouseLeave = useWrapEvent(() => setHovered(false), onMouseLeave)
Wasn't sure if we wanted the `handleOnX` or `handleX` nomenclature, but going with the latter option meant these handlers were one-liners 🤷 

Happy to change these back if we prefer the former.

2021-04-13 23:36 UTC, ElliotTheHuman commented on packages/components/src/Tree/stories/FieldPicker.story.tsx
> +            }}
The onClick callbacks in the Pivot / Filter icons (both of which live within the item label container)  need a `stopPropagation` call regardless of this PR's other changes.

2021-04-15 08:18 UTC, lukelooker requested changes

2021-04-15 08:18 UTC, lukelooker commented on packages/components/src/Tree/stories/FieldPicker.story.tsx
> +            }}
This seems awkward to me - it feels like it should "just work" or not work at all - this seems to sort-of split the difference (at least in my head) but I think I'd be more confused by this middle track than just saying it's "batteries not included" if you go the `itemRole="none"` route.

I think in an `itemRole="none"` the `onClick` specified on the `ListItem` shouldn't apply to label and we should leave it to the developer to apply it manually to the parts of the label they want it to be activated `onClick` (in this case `<FlexItem flex={1}>{children}</FlexItem>`?)

You could be _very_ explicit and add a `onClickWhitespace` handler that uses a type-gate (see Daniel's clever TS scheme from earlier this week) to gate that callback to only be available when `itemRole="none"`. Along those same lines you could also prevent `onClick` in that case as well to further reduce the potential for mis-steps.

2021-04-15 22:43 UTC, ElliotTheHuman commented on packages/components/src/Tree/stories/FieldPicker.story.tsx
> +            }}
Makes sense. I went ahead and got those changes in via 44771eb.

Note: I tried getting the type-gating in, but for whatever reason I couldn't get an error to pop up when using `onClick` and `itemRole="none"` 😟 

For reference, I used these types below:
```
type ListItemRoleOther = {
  itemRole?: 'button' | 'link'
  onClick?: (event: React.MouseEvent<HTMLElement>) => void
  onClickWhitespace?: never
}

type ListItemRoleNone = {
  itemRole: 'none'
  onClick?: never
  onClickWhitespace?: (event: React.MouseEvent<HTMLElement>) => void
}

type ListItemRoleProps = ListItemRoleOther | ListItemRoleNone
```

2021-04-15 22:44 UTC, ElliotTheHuman commented on packages/components/src/Tree/stories/FieldPicker.story.tsx
> +            }}
In the meantime, I added `onClickWhitespace` as just an optional prop on `ListItemProps` and added a `console.warn` when trying to use `itemRole="none"` and `onClick` at the same time.

2021-04-19 21:13 UTC, lukelooker requested changes

2021-04-19 22:03 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +    }
Technically speaking, it's possible to have a `Tree` with `labelBackgroundOnly` enabled and items that have `itemRole="button"` (or "link"). In which case, clicking the whitespace wouldn't do anything without an `onClickWhitespace` passed in.

Ideally, we could disable this by checking if `labelBackgroundOnly` is enabled, but that's strictly a `Tree` prop (i.e. not a `TreeItem` / `ListItem` prop) since `Tree` is the one that manages the indent logic.

I could try pulling from `TreeContext` to see if `labelBackgroundOnly` is enabled, but tying `ListItem` and `Tree` together in that way seems a bit invasive for `ListItem`.

2021-04-19 22:11 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +    }
It's definitely discouraged to use `onClickWhitespace` without `labelBackgroundOnly`, but I don't _think_ there's anything wrong with using `onClickWhitespace` when `itemRole` is "link" or "button" (i.e. you'd need an `onClickWhitespace` in that scenario so that anything left of the link / button is clickable).

The problem is that `labelBackgroundOnly` is a `Tree` prop and thus we'd have to use `useContext(TreeItemContext)` within `ListItem` to figure out if `labelBackgroundOnly` is enabled. Not the end of the world, but my gut seems odd to tie those two together. I could wrong about that though.

2021-04-20 17:37 UTC, ElliotTheHuman commented
Jest tests are failing on GH, but tests passing locally 👍 
![Screen Shot 2021-04-20 at 10 37 05 AM](https://user-images.githubusercontent.com/16812885/115440222-5b28e200-a1c4-11eb-95f5-e667f51059a9.png)

2021-04-20 17:52 UTC, lukelooker reviewed
Pushed a commit to _hopefully_ straighten out Codecov error

2021-04-20 17:52 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +   * @private
```suggestion
   * Callback to specify onClick handler on item's whitespace.
   * @private May only be passed via TreeItem. This feature may be removed without a breaking change, we STRONGLY discourage the direct use of this property
```

2021-04-20 19:00 UTC, lukelooker approved these changes
Ship it. :)

2021-04-20 20:09 UTC, merged