feat(Accordion) - Refactored Accordion interface and composition
looker-open-source/components pull request #2199
Opened 2021-04-14 22:40 UTC by ElliotTheHuman

- Accordion accepts a "content" prop (i.e. content that is hidden and shown based on open state)
- Accordion child gets placed into an `AccordionDisclosure` internally

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-04-15 02:17 UTC, lukelooker reviewed
I think you're going the right direction with this - continue on with my blessings!

Also, I have an couple of ideas about how we can solve for the "old" composition style - conversation for tomorrow :)

2021-04-15 02:17 UTC, lukelooker commented on packages/components/src/Accordion/Accordion.story.tsx
>  )
My brain was having a hard-time groking this - came up with a (I think) simpler to read version:

```jsx
const Branch: FC = ({ children }) => (
  <Accordion
    indicatorPosition="left"
    defaultOpen
    pl="medium"
    content={
      <UnorderedList>
        <li>Cheddar</li>
        <li>Gouda</li>
        <li>Swiss</li>
        {children}
      </UnorderedList>
    }
  >
    Hello World
  </Accordion>
)

export const Nested = () => (
  <Branch>
    <Branch>
      <Branch>
        <Branch />
      </Branch>
    </Branch>
  </Branch>
)
```

2021-04-15 22:53 UTC, ElliotTheHuman commented on packages/components/src/Accordion/Accordion.story.tsx
>  )
This is 100000% more readable. Sick composition.

2021-04-19 17:31 UTC, ElliotTheHuman commented on packages/components/src/Accordion/Accordion.tsx
> +        {...props}
I needed a way to provide HTML props (and things like text color) to the underlying `AccordionDisclosure` since the user can't do it themselves in the new/ideal composition.

My proposed solution is to add the necessary props to `Accordion` and then pass any props that are HTML compatible down to the internal `AccordionDisclosure`.

2021-04-19 19:28 UTC, ElliotTheHuman commented
Got the rest of the codebase (i.e. docs and stories and tests) refactored to the new composition!

2021-04-20 23:39 UTC, ElliotTheHuman commented on www/src/documentation/components/content/list.mdx
> +  <ListItem icon={<LogoRings />} detail="Switzerland">
`<Account />` was causing an error on the docs page so swapped to an icon that wouldn't error out.

2021-04-20 23:47 UTC, ElliotTheHuman commented on packages/components/src/Accordion/AccordionContent.tsx
> +  accordionDisclosureId?: string
Ideally these would be required since the only place `AccordionContent` would be used is within `Accordion`, but to support legacy compositions we make them optional.

2021-04-20 23:48 UTC, ElliotTheHuman commented on packages/components/src/Accordion/AccordionDisclosure.tsx
> +            indicatorIcons || accordionContextDefaults.indicatorIcons
It's a bit janky, because we changed the interface around to support the legacy composition, we need to add these fallbacks so that `AccordionDisclosureLayout` is happy (since the indicator related props and `isOpen` are required on the layout component).

2021-04-20 23:49 UTC, ElliotTheHuman commented on packages/components/src/Form/Fieldset/Fieldset.tsx
> +    } = props
Seemed like a good time to get rid of the `omit` and `pick` usage I added to `Fieldset` way back when.

2021-04-21 00:03 UTC, lukelooker requested changes
Few minor nits on documentation and one adjustment to Styled System usage.

2021-04-21 00:03 UTC, lukelooker commented on packages/components/src/Accordion/AccordionDisclosure.tsx
> +            indicatorIcons || accordionContextDefaults.indicatorIcons
Maybe add a `@todo` above this to note that the fallbacks should be removed in `2.x`?

2021-04-21 21:11 UTC, lukelooker approved these changes
Failing due to a snapshot difference but otherwise this LGTM. Once CI is green I'm happy to do a fresh 👍

2021-04-21 21:24 UTC, ElliotTheHuman commented
🤦  I used the `Accordion > Basic` story to test some weirdness with `Fieldset`. Changed it back. Will re-request review once snapshots are updated / merged into this PR.

2021-04-21 21:43 UTC, lukelooker approved these changes
Approved :)

2021-04-21 21:55 UTC, merged