update List to support fontFamily as prop
looker-open-source/components pull request #2216
Opened 2021-04-19 22:24 UTC by laraharrow

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-04-19 23:40 UTC, lukelooker requested changes

2021-04-19 23:40 UTC, lukelooker commented on packages/components/src/List/List.story.tsx
> +
Needs a screenshot to be added manually :)

2021-04-19 23:40 UTC, lukelooker commented on packages/components/src/List/List.tsx
> +  fontFamily?: FontFamilies
Needs JSDoc explanation.

2021-04-19 23:40 UTC, lukelooker commented on www/src/documentation/components/content/list.mdx
> +<List fontFamily="Impact">
I'd prefer showing folks a `theme` reference here. Even though they _can_ specify an explicit font-face I'd prefer them to think in a theme world :)

```suggestion
<List fontFamily="code">
```

2021-04-19 23:41 UTC, dbchristopher commented on packages/components/src/List/List.tsx
> +  }
I wonder if this selector is actually too narrow in this case? It seems like users could potentially render any form element in a list which might not inherit the type settings as expected. Maybe it makes sense to use the `*` selector instead?

```suggestion
  * {
    font-family: inherit;
  }
```

What do you think?

2021-04-20 03:59 UTC, lukelooker requested changes

2021-04-20 03:59 UTC, lukelooker commented on packages/components/src/List/List.tsx
> +  }
This shouldn't be needed if the branch is off the latest `main` - `ListItem` _should_ just inherit the `List` font-family correctly.

2021-04-20 17:51 UTC, laraharrow commented on packages/components/src/List/List.story.tsx
> +
if you look at the files on gitHub you will see the snapshot file. Not sure if I'm missing something here.

2021-04-20 17:56 UTC, lukelooker commented on packages/components/src/List/List.story.tsx
> +
The PR: https://github.com/looker-open-source/components/pull/2217 needs to get merged into this one so that the snapshot PNG is included.

2021-04-20 17:57 UTC, laraharrow commented on packages/components/src/List/List.tsx
> +  }
I updated to use `*` instead of `button` great suggestion thanks. As far as removing the code all together I just updated to be in the same place as main but if I remove it the font does not get updated. Not sure if I'm missing something here.

2021-04-20 18:11 UTC, laraharrow commented on packages/components/src/List/List.story.tsx
> +
I did add the snapshot thou. I see the same file here just a little lower in this page.

2021-04-20 18:13 UTC, lukelooker commented on packages/components/src/List/List.tsx
> +  }
I'm not a big fan of having a component reach into another component like this - with the refactor of the `reset` behavior it _should_ be possible to simply leverage CSS inheritance to get this to work.

Checking out branch locally to see if I can understand why it doesn't work without the specific selector here.

2021-04-20 18:16 UTC, laraharrow commented on packages/components/src/List/List.tsx
> +  }
I updated to use * instead of button great suggestion thanks. As far as removing the code all together I just updated to be in the same place as main but if I remove it the font does not get updated. Not sure if I'm missing something here.

2021-04-20 18:58 UTC, lukelooker requested changes

2021-04-20 18:58 UTC, lukelooker commented on packages/components/src/List/List.tsx
>    ${reset}
`reset` is overriding `fontFamily` because it specifies `font-family: inherit` _after_ `fontFamily` helper emits its preferred font-family.

I'd recommend re-working `ListStyle` like so:

```jsx
const ListStyle = styled.ul
  .withConfig({ shouldForwardProp })
  .attrs<ListProps>(({ fontFamily = 'inherit' }) => ({
    fontFamily,
  }))<ListProps>`
  ${fontFamily}
  ${height}
  ${width}

  list-style: none;
  margin: 0;
  overflow: auto;
  padding: 0;
`
```

This directly injects the "reset" behaviors into the style block (`margin: 0` & `padding: 0` and leverages a default value on `fontFamily` so that the existing behavior stays intact.

2021-04-20 18:58 UTC, lukelooker commented on packages/components/src/List/List.tsx
> +   * Use this prop to specify themed fonts for the List text.
```suggestion
   * Specify font-family. Generally will end up inheriting `theme.fonts.body` but can be specified as `brand`, `code` or `body` to explicitly specify theme-controlled font-family
   * default inherit
```

2021-04-22 00:45 UTC, lukelooker approved these changes
LGTM! :)

2021-04-22 15:57 UTC, merged