feat(Layout): add width t-shirt size to Aside
looker-open-source/components pull request #2227
Opened 2021-04-20 20:35 UTC by laraharrow

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-04-21 06:18 UTC, lukelooker requested changes
As you pointed out on chat we'll need to rationalize the sizes a bit to match-up with `Aside`'s existing default.

Since `Aside` (and all of the layout components for that matter) are marked as "experimental" I think we can change the default safely so I'd probably just go with `xsmall` for now and we can iterate from there.

2021-04-21 06:18 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Aside.tsx
> +  width?: ResponsiveValue<DialogSizeRamp | string>
`DialogSizeRamp` should be lifted out of `Dialog` and renamed to something like `LayoutWidthRamp` and placed in the `/Layout` folder.

Then `dialogWidth` should be updated to reference that central, more generic version.

2021-04-21 06:18 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Aside.tsx
> +  ${dialogWidth}
Seems really odd to have `dialogWidth` specifying the `aside`'s width. Perhaps create a `layoutWidth` helper that can be used in both places?

2021-04-21 06:18 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Semantics.test.tsx
> +      </Layout>
Example can be narrowed down to just the `Aside` itself.

```suggestion
      <Aside width="medium">Aside content</Aside>
```

2021-04-21 06:18 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Story/ExamplePage.story.tsx
> +  </Highlighter>
Narrow to just the `Aside` and make this an `arg` that the Storybook user can play with. See Dialog story at https://looker-open-source.github.io/components/latest/storybook/?path=/docs/dialog--basic

https://github.com/looker-open-source/components/blob/main/packages/components/src/Dialog/stories/Dialog.story.tsx#L169-L186

![image](https://user-images.githubusercontent.com/34253496/115505348-29e4fc00-a22e-11eb-8005-743dc140e35e.png)

2021-04-21 06:18 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Aside.tsx
> +
`attrs` above should default `width = 'xsmall`` I guess?

Also `max-width` and `min-width` should probably be removed to not conflict with `dialogWidth` (to be renamed)

2021-04-21 16:21 UTC, laraharrow commented
@lukelooker I was wondering if it make sense to lift `dialogWidth` just because maybe we will want to use other sizes then what is set for `Dialog` and `Drawer` for instance right now Aside width is set to `12rem` and the smaller size on that file is `xxsmall` and it is set as `16rem`

2021-04-21 20:48 UTC, lukelooker commented
@laraharrow - I definitely think we'll want to *add* a "LayoutWidths" - I'm admittedly not sure if we could use that same collection of sizes in Drawer & Dialog or not so perhaps that's a good reason to keep them seperate for now. I'd say you could just copy the existing values for DialogWidths and then @jhardy & I can audit usage within Helltool and come up with an ideal list.

2021-04-21 22:41 UTC, laraharrow commented on packages/components/src/Layout/Semantics/Story/ExamplePage.story.tsx
> +  </Highlighter>
Hey @lukelooker I added `width` to the argument list on Storybook. But changing the values doesn't change the `Aside`'s width - Same seemed true to me in Dialog.

2021-04-21 22:48 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Story/ExamplePage.story.tsx
> +  </Highlighter>
Ah - weird, yeah it looks like that example isn't working. 

Drawer (https://looker-open-source.github.io/components/latest/storybook/?path=/story/drawer--basic) does appear to work so hopefully you can borrow from there and perhaps take on getting `Dialog` working properly as well?

2021-04-21 23:45 UTC, laraharrow commented on packages/components/src/Layout/Semantics/Story/ExamplePage.story.tsx
> +  </Highlighter>
sure thing!

2021-04-27 01:08 UTC, lukelooker requested changes
See notes in Buganizer about next steps.

2021-04-29 17:35 UTC, lukelooker commented on packages/components/src/Layout/Semantics/LayoutWidth.ts
> +  xsmall: '12rem',
Set back to `21rem`

2021-05-03 20:09 UTC, mdodgelooker approved these changes
LGTM!

2021-05-03 23:49 UTC, jhardy commented on packages/components/src/Layout/Semantics/LayoutWidth.ts
> +export const layoutSizes: LayoutSizeRamp = {
I have mixed feelings about combining t-shirt sizes with named values like `navigation` and `rail`.  One idea Luke and I had talked about was naming these items like `size="rail"` instead of width as the prop. 

I'm questioning if we even need the t-shirt sizes here? Should width just be `'rail' | 'navigation' | 'sidebar' | number`?

2021-05-03 23:50 UTC, jhardy commented on packages/components/src/Layout/Semantics/Story/ExamplePage.story.tsx
> +    width: {
having these width controls be apart of the default makes it Look like they are available on every layout story. Is there a way to limit them just to the `Aside` stories?

2021-05-03 23:52 UTC, jhardy commented on packages/components/src/Layout/Semantics/LayoutWidth.ts
> +export const layoutSizes: LayoutSizeRamp = {
the name here `layoutSizes` seems again like it would apply to all layout pieces, but `rail`, `navigation`, and `sidebar` apply to just `Aside`

2021-05-12 21:47 UTC, closed without merging