feat(TreeCollection): Added TreeCollection component
looker-open-source/components pull request #2271
Opened 2021-04-29 18:03 UTC by ElliotTheHuman

- Added `TreeCollection` component
- Updated `Tree` tests and docs to have a `TreeCollection` parent

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-04-29 23:48 UTC, lukelooker requested changes
Comments in source.

- Minor code structure changes
- Needs test coverage
- Needs documentation coverage (explain `TreeCollection`) :)

2021-04-29 23:48 UTC, lukelooker commented on packages/components/src/Tree/TreeCollection.tsx
> +`
Needs test coverage :)

This can be consolidated into a single component (at least for now).

```suggestion
export const TreeCollection = styled.ul.attrs(({ role = 'tree' }) => ({
  role,
}))<TreeCollectionProps>`
  margin: 0;
  padding: 0;
`
```

2021-04-29 23:48 UTC, lukelooker commented on packages/components/src/Tree/TreeCollection.tsx
> +type TreeCollectionProps = CompatibleHTMLProps<HTMLUListElement>
Should be exported if the component using it is exported:

```suggestion
export type TreeCollectionProps = CompatibleHTMLProps<HTMLUListElement>
```

2021-04-29 23:48 UTC, lukelooker commented on packages/components/src/Tree/TreeStyle.tsx
> +// Ideally, this would be an li, but the problem is the internal ListItem is also an li so we get an "li can't be a child of an li" error
```suggestion
/**
 * @todo refactor `div` to `li`
 * Complex because nested ListItem is also an `li` breaking HTML nesting rules
 **/
```

2021-04-29 23:48 UTC, lukelooker commented on packages/components/src/Tree/stories/Density.story.tsx
> +    <TreeCollection>
Outer fragment (`<>`) can be removed

2021-04-29 23:48 UTC, lukelooker commented on www/src/documentation/components/content/tree.mdx
> +<TreeCollection>
Would be good to mention the need to use `TreeCollection` as the top-level element of a tree

2021-04-30 17:24 UTC, ElliotTheHuman commented
Note to self: I might need to change the base branch to `release-1.2`

2021-04-30 18:58 UTC, ElliotTheHuman commented on www/src/documentation/components/content/tree.mdx
> +<TreeCollection>
👍  I included a subsection in the `Tree` docs. It's pretty bare-bones so let me know if more elaboration is needed.

2021-04-30 18:58 UTC, ElliotTheHuman commented on packages/components/src/Tree/stories/Density.story.tsx
> +    <TreeCollection>
Resolved in 4b874a1

2021-04-30 18:58 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeStyle.tsx
> +// Ideally, this would be an li, but the problem is the internal ListItem is also an li so we get an "li can't be a child of an li" error
Resolved in 4b874a1

2021-04-30 18:59 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeCollection.tsx
> +type TreeCollectionProps = CompatibleHTMLProps<HTMLUListElement>
Resolved in 4b874a1

2021-04-30 19:09 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeCollection.tsx
> +`
👍  Added a test file for `TreeCollection` in 8aa464247

It only checks that children are rendered by `TreeCollection` since it's just a styled `ul` at the moment, but we can add tests for `Tree` windowing behavior once that's implemented.

2021-04-30 20:13 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeStyle.tsx
> + **/
Discussed over chat, but this refactor is _not_ imminent, so converting `TreeCollection` to a `div` and adding another `@todo` makes sense to me!

2021-04-30 21:18 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeStyle.tsx
> + **/
Resolved in 3ae0c15

2021-04-30 21:34 UTC, mdodgelooker approved these changes
LGTM! 🚢

2021-04-30 22:33 UTC, merged