feat(Accordion): Toggle on spacebar key
looker-open-source/components pull request #2281
Opened 2021-05-01 02:41 UTC by mdodgelooker

_Preliminary work for focus visible refactor._

As I was pulling out the focus visible logic in here to replace with the upcoming `useFocusVisible` hook, I realized `AccordionDisclosure` is actually a great use case for `useClickable`. This hook is aimed at accessibility for non-buttons that are being used in a button-y way. It adds keyup handlers for enter and spacebar keys, and it has focus visible behavior built-in. The enter key was already triggering the accordion toggle, so the only change from `useClickable` is toggling on the spacebar key.

Doing this change in a separate PR helps make the focus visible refactor more sane. 

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [x] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [x] 👾 Browsers tested
  - [x] Chrome
  - [x] Firefox
  - [x] Safari
  - [x] IE11

2021-05-01 03:06 UTC, mdodgelooker commented on packages/components/src/Accordion/AccordionDisclosure.tsx
> -  focusVisible?: boolean
This prop should be internal only – I moved it into `AccordionDisclosureStyleProps` using `FocusVisibleProps`.

2021-05-01 03:06 UTC, mdodgelooker commented on packages/components/src/Tree/Tree.tsx
> -  onClick,
Was this left unused for a reason? By not destructuring it here, it goes onto `Accordion` along with `...restProps` – would there be any issue with that?

2021-05-01 03:06 UTC, mdodgelooker commented on packages/components/src/Tree/types.ts
> +  Omit<ListItemProps, 'onClick'> & {
Using `GenericClickProps` in `AccordionProps` caused a TS conflict with the `onClick` from `ListProps` (because of the whole `KeyboardEvent` thing). Now it's going onto `Accordion` (see comment above) so it should get the onClick type from there.

2021-05-03 17:35 UTC, ElliotTheHuman requested changes
`AccordionDisclosure` looks way better with `useClickable`. Thank you for implementing that!

I had one suggestion about `Tree` and one clarifying question about `AccordionDisclosure`'s `onKeyUp` behavior.

2021-05-03 17:35 UTC, ElliotTheHuman commented on packages/components/src/Tree/Tree.tsx
> -  onClick,
No reason that I can think of. I think that was an accident. Thanks for catching that!

In that case, I _believe_ `onKeyUp` should be removed from the destructuring as well since it should be passed down to the `Accordion` like `onClick`.

2021-05-03 17:35 UTC, ElliotTheHuman commented on packages/components/src/Accordion/AccordionDisclosure.tsx
> +    })
One consequence of using `useClickable` instead of the old `handleKeyUp` is that if you're focused on a `Tree` and press any key, the focus visible border appears (before it was just on tab and any other key press would remove the border).

That being said, if that behavior is standard for other components / we're okay with that, I think using `useClickable` is a huge improvement here!

2021-05-03 21:32 UTC, mdodgelooker commented on packages/components/src/Accordion/AccordionDisclosure.tsx
> +    })
Great question – I think that's how _most_ of the other focus visible components are working now and that's how it'll be after my refactor. I'm going off of the not-yet-universally-supported `:focus-visible` pseudo-selector behavior that does go on for any key: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

2021-05-03 21:33 UTC, mdodgelooker commented on packages/components/src/Tree/Tree.tsx
> -  onClick,
Ooh thanks for catching that. Removed [here](https://github.com/looker-open-source/components/pull/2281/commits/55b220c35d17b843dee78f3bd01910d0ca3b6aa6)

2021-05-03 22:03 UTC, ElliotTheHuman approved these changes
👍

2021-05-03 22:50 UTC, merged