fix(IconButton): Match focus ring to toggleColor
looker-open-source/components pull request #2282
Opened 2021-05-01 03:41 UTC by mdodgelooker

_Preliminary work for focus visible refactor._

Updates `IconButton` focus visible styling to match focus ring color to `toggleColor`.

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-05-01 03:55 UTC, mdodgelooker commented on packages/components/src/Button/ButtonBase.tsx
> +const ButtonLayout = forwardRef(
Just changing for consistency with how we usually name these.

2021-05-01 03:55 UTC, mdodgelooker commented on packages/components/src/Button/ButtonBase.tsx
> +const buttonCSS = css<ButtonColorProps & ToggleColorProps & FocusVisibleProps>`
Did some type refactoring to smooth things a bit, and the focus visible refactor will benefit from that.

2021-05-01 03:55 UTC, mdodgelooker commented on packages/components/src/Button/ButtonBase.tsx
> +    focusVisible && buttonShadow(toggleColor || color)}
Use `toggleColor` to generate the focus ring color, if it exists, otherwise `color`.

2021-05-01 03:55 UTC, mdodgelooker commented on packages/components/src/Button/iconButtonTypes.ts
> -  focusVisible?: boolean
Moving this prop to `ButtonOuterProps` (see above) since it should only be used internally.

2021-05-01 03:55 UTC, mdodgelooker commented on packages/design-tokens/src/utils/helpers.ts
> +export const buttonShadow = (color: ExtendedStatefulColor = 'key') =>
Includes dimension, measure, etc (using this in order to support `toggleColor`).

2021-05-03 18:08 UTC, dbchristopher commented on packages/components/src/Button/ButtonBase.tsx
> +  (props: ButtonLayoutProps, ref: Ref<HTMLButtonElement>) => {
Any idea how to raise this limit? 33 lines of code hardly seems excessive for a react component lol

2021-05-03 18:21 UTC, dbchristopher requested changes
This looks good! I left a note about the "toggle color" terminology, which seems a little unclear to me on first impression. And do you think we need a new snapshot where `focusVisible={true}` to better track this behavior through future changes?

2021-05-03 18:21 UTC, dbchristopher commented on packages/components/src/Button/iconButtonTypes.ts
> +}
I'm not sure I'm totally following this terminology. Maybe `focusColor` would be more descriptive?

2021-05-03 21:38 UTC, mdodgelooker commented on packages/components/src/Button/ButtonBase.tsx
> +  (props: ButtonLayoutProps, ref: Ref<HTMLButtonElement>) => {
Haha I wish I knew. Codeclimate seems really neat but still a bit of a mystery to me.

2021-05-03 22:59 UTC, mdodgelooker commented on packages/components/src/Button/iconButtonTypes.ts
> +}
`toggleColor` is actually a new prop Luke added in this PR to, I believe, support `IconButton`s used in the core product field picker to toggle states like filter-by, etc: https://github.com/looker-open-source/components/pull/2263

But I noticed during my focus visible refactor that the focus ring was looking funky with the `dimension`/`calculation`/`measure` colors: https://looker-open-source.github.io/components/canary/storybook/?path=/story/iconbutton--toggle-color

2021-05-03 23:01 UTC, mdodgelooker commented
@dbchristopher really good point about image snapshot. As of yet we haven't captured focus (or other interactive) styles in any snapshots because there hasn't been an obvious way to do it in storyshots, but we've talked about it, and it seems possible. I'm gonna spend the rest of the day seeing if I can finally make this happen. 🙂

2021-05-04 20:48 UTC, mdodgelooker reviewed
@dbchristopher looks like CI is happy with the interaction+snapshot change! Let me know if the `beforeScreenshot` stuff isn't making sense.

2021-05-04 20:48 UTC, mdodgelooker commented on packages/components/src/Button/IconButton.story.tsx
> +  beforeScreenshot: async (page: any) => {
See comment below in `storyshotsConfig.ts`...

2021-05-04 20:48 UTC, mdodgelooker commented on storybook/src/setup/storyshotsConfig.ts
> +        }
Here I'm leveraging `beforeScreenshot` to look for a story-specific one that would trigger any necessary events to get the component into a state where we want to take the snapshot.

I'm passing in [`page`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#class-page) as the argument which can be used in the story to get an element and interact with it

It's a bit buried in the [Storybook docs](https://storybook.js.org/addons/@storybook/addon-storyshots-puppeteer) but apparently this is indeed the way you're supposed to trigger events:
> beforeScreenshot is part of the promise chain and is called after the browser navigation is completed but before the screenshot is taken. It allows for triggering events on the page elements and delaying the screenshot and can be used avoid regressions due to mounting animations.

2021-05-04 20:48 UTC, mdodgelooker commented on packages/components/src/Button/IconButton.story.tsx
> +  },
See comment in `storyshotsConfig.ts` below.

2021-05-04 20:48 UTC, mdodgelooker commented on packages/components/package.json
> +    "puppeteer": "^9.1.0",
Adding this to `devDependencies` to get access to the `Page` interface (see below) since `@storybook/addon-storyshots-puppeteer` doesn't export it.

2021-05-04 23:49 UTC, dbchristopher commented on storybook/src/setup/storyshotsConfig.ts
> +        }
wow that is super cool! Nice work getting that set up

2021-05-04 23:49 UTC, dbchristopher approved these changes

2021-05-04 23:50 UTC, merged