FEAT: Vis components release
looker-open-source/components pull request #2286
Opened 2021-05-03 23:51 UTC by dbchristopher

2021-05-03 23:55 UTC, dbchristopher commented on tsconfig.common.json
> +    "lib": ["es6", "es2019.object", "es2019.array", "dom"],
Resolves object and array method errors:

> packages/visualizations-nivo/src/Bar/barUtils.ts:33:29 - error TS2550: Property 'fromEntries' does not exist on type 'ObjectConstructor'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2019' or later.

> packages/visualizations-nivo/src/Bar/Bar.tsx:65:14 - error TS2550: Property 'flatMap' does not exist on type 'BarDatum[]'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2019' or later.

2021-05-06 00:14 UTC, dbchristopher commented on packages/eslint-config/index.js
> +    camelcase: 'off',
I figured that nobody was that attached to this rule, so it's easier to just assume support of all the sdk response keys

2021-05-14 04:21 UTC, mdodgelooker submitted a review, later dismissed

2021-05-14 04:21 UTC, mdodgelooker commented on packages/visualizations-nivo/package.json
> +  "@looker/components-test-utils": "1.1.5",
I left a comment about this over in the core product release script PR, but it looks like the `@looker/*` packages aren't getting the right version.

2021-05-24 03:50 UTC, lukelooker commented
@dbchristopher Is this PR still a going concern or are you planning to re-open later on? (just checking as it's on my review list but looks like it's parked) :)

2021-05-24 16:26 UTC, dbchristopher commented
@lukelooker I was planning to request review as part of the general release process. Not urgent now, but more updates will be forthcoming!

2021-05-27 18:00 UTC, dbchristopher commented on packages/eslint-config/index.js
> +    camelcase: 'off',
thanks @mdodgelooker! Just getting back to this side of the release process now. I don't think we'll need to disable `order/properties-alphabetical-order` -- that's easily autofixable and should not get out-of-sync anymore with the packages in helltool extending our eslint config.

I also think it's probably worth keeping the `no-explicit-any` turned on! I've resolved some instances of that in vis packages, and manually disabled the rule where `any` really is as specific as I can be for now

2021-06-01 22:15 UTC, dbchristopher commented on packages/components/src/Form/Inputs/Combobox/ComboboxList.tsx
> +      let t: ReturnType<typeof setTimeout>
Running `yarn lint` I'd get this error:

```
Type 'number' is not assignable to type 'Timeout'.
```

But then if I set `let t: number`, when running `yarn build` I'd get this error:

```
Type 'Timeout' is not assignable to type 'number'.
```

So going with `ReturnType` was a compromise to keep all build environments happy relative to their own definitions.

2021-06-11 23:24 UTC, dbchristopher commented
Not sure why all the build stuff is failing suddenly 🤔  I'll have to take more of a look at this on monday

2021-06-13 21:40 UTC, lukelooker requested changes
Overall this PR looks good to me. Ran into a specific issues:

- The local packages references in the root `package.json` seem to break `yarn install` in some interesting ways. See note on that file for more detail but I think those local references need to be removed.
- Made notes about `visualizations-nivo/package.json` but same questions apply to all of the new package.json added here:
  - Local package refs in `devDeps` are all `*` except `"@looker/components-test-utils"` - seems like these should be consistent. All `*`?
  - Remove `typescript` ref (it's provided by the monorepo and isn't declared per package elsewhere in the monorepo except `eslint-config` (that's a special case)
- Please run `yarn deduplicate` on this PR so can keep the `yarn.lock` as narrow as possible :)

2021-06-13 21:40 UTC, lukelooker commented on package.json
> +    "@looker/stylelint-config": "*",
I think this will break Lerna publishing. 

Is there a reason the central package.json should need these (they should get inferred by the `workspaces` above?

NOTE: `@looker/sdk` is okay here - just meant the local references.

2021-06-13 21:40 UTC, lukelooker commented on packages/visualizations-nivo/package.json
> +  "typescript": "4.2.4"
Other packages within the monorepo don't specify `@typescript` so I'd probably forego it here.

2021-06-13 21:40 UTC, lukelooker commented on packages/visualizations-nivo/package.json
> +  "@looker/components": "1.x",
This needs to bump to 2.x shortly. Perhaps make it a range of 1.x or 2.x (or just make the bump to 2.x)

2021-06-13 21:40 UTC, lukelooker commented on packages/visualizations-nivo/package.json
> +  "@looker/eslint-config": "*",
Since these are both local I'm thinking they should both be `*` or version specific?

Not _exactly_ sure if this is going to cause concerns publishing (some security scanning tools want an explicit range so they can calculate full dep tree). That said we could probably just strip all of the `devDeps` out during publishing step.

2021-06-13 21:40 UTC, lukelooker commented on packages/visualizations-nivo/tsconfig.build.json
> +{
NOTE TO SELF: TS4.2 or 4.3 add a feature (name I'm spacing) that _should_ make all of these sub-extends moot – investigate how so we can don't have to keep copying these around. :)

2021-06-13 21:40 UTC, lukelooker commented on package.json
> +    "@looker/stylelint-config": "*",
Ok - just checked this out and I'm pretty sure this leads to `yarn` install failures as well (at least it did on my instance)

2021-06-14 19:22 UTC, dbchristopher commented on package.json
> +    "@looker/stylelint-config": "*",
[Lerna list](https://www.npmjs.com/package/@lerna/list) is a much better way to track local deps. I can safely remove the starred versions from here!

2021-06-15 20:37 UTC, dbchristopher commented on packages/components/package.json
> +    "@types/styled-components": "5.1.9",
Pinned this to 5.1.9. I changed the `components-providers` to a starred version to ensure there would only ever be one version of `types/styled-components` in the monorepo

2021-06-15 20:51 UTC, lukelooker approved these changes
Ship all the things! :)

2021-06-15 21:33 UTC, merged