feat(Aside): adding prop collapse
looker-open-source/components pull request #2288
Opened 2021-05-04 17:57 UTC by laraharrow

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-05-10 22:20 UTC, lukelooker requested changes

2021-05-10 22:20 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Aside.tsx
> +   * To be used when desiring the Aside to be collapsible
```suggestion
   * Prevent `Aside` from being rendered.
```

2021-05-10 22:20 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Aside.tsx
> +  ${({ collapse }) => collapse && 'display: none;'}
Rather than using CSS I _think_ this should actually prevent the JSX from being rendered at all - that way if there's any cost to the underlying rendering (complex `Tree` for instance) there will be no performance impact of rendering this hidden element.

I suspect to do this `Aside` will need to have an underling component like:

```

const AsideLayout: FC<AsideProps> = ({ collapse, ...props }) => 
  collapse ? null : <aside {...props} />

export const Aside = styled(AsideLayout)  ...

```

2021-05-10 22:20 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Semantics.test.tsx
> +    expect(screen.getByText('Aside content')).toHaveStyleRule('display: none;')
This will need to get refactored since `Aside content` will no longer be on the page.

2021-05-10 22:20 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Story/ExamplePage.story.tsx
> +        </AsideAlt>
Can we use a simpler example here so it's easier to "see" what's being tested here:

```suggestion
        <Aside collapse>Aside</Aside>
        <Section as="main">Section</Section>
```

2021-05-12 21:43 UTC, lukelooker requested changes
I went ahead and fixed this up (took me a bit of poking to understand what had gone awry). 

This needs test coverage and then it should be good-to-go.

2021-05-12 21:43 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Aside.tsx
> +    shouldForwardProp: (prop) => prop === 'collapse' || shouldForwardProp(prop),
@laraharrow - the problem was the `shouldForwardProp` was filtering out `collapse` and therefore not forwarding it on the the underlying `AsideLayout` component.

This change makes it work as it should

2021-05-12 21:43 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Story/ExamplePage.story.tsx
> +  )
Made this interactive so it's easier to understand what it does.

2021-05-12 21:43 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Story/ExamplePage.story.tsx
> +    disable: true,
Screenshot is of pretty limited use since a simple Jest test of whether or not the `Aside` content is visible will give the same quality of coverage.

2021-05-12 22:41 UTC, lukelooker requested changes
Let's move `Aside` tests into their own file so that it easier for reviewers to find related tests :)

2021-05-12 22:41 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Semantics.test.tsx
> +  })
This test file is getting pretty huge - can we go ahead and move this (as well as any other `Aside`-specific tests) into `Aside.test.tsx` to follow along with our other component file-layouts?

2021-05-12 23:38 UTC, laraharrow commented on packages/components/src/Layout/Semantics/Semantics.test.tsx
> +  })
Should I do this here or wait until we have all the Aside/Layout work done and I can organize the test separated then?
I'm aware that other PR's that I'm working now also have test that could be subdivided

2021-05-13 00:53 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Semantics.test.tsx
> +  })
I suppose it's fine if it gets done in a follow-up PR. 👍

2021-05-13 00:53 UTC, lukelooker approved these changes

2021-05-13 01:28 UTC, merged