feat(Tree): Keyboard Navigation
looker-open-source/components pull request #2295
Opened 2021-05-05 00:05 UTC by ElliotTheHuman

## 👋👋 Thank you for contributing to Looker Components (⚡️🍣)

📺 Watch a quick video on how to you make your pull requests fast and easy for you and your reviewer(s):
https://threadit.app/thread/k45nyrqugoinw6xub9vf/message/fl8m57exhqg4r0a4hg01eebn

- 👆 Make sure your pull request title follows [Pull Request Title Guidelines](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#title-guidelines) from our [Contribution guide](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md)
- 👉 Don't forget to replace these instructions with your _✨awesome✨_ description of what this change _actually does_. Additionally it's great to include context on how it works and why the change was needed.
- 👇 Edit "Developer Checklist" to reflect items relevant to this PR (and try to make sure to check everything off before asking for review)

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-05-05 00:07 UTC, ElliotTheHuman commented on packages/components/src/Tree/types.ts
> +  > & {
Unrelated change: `Tree` accepted `ListItem` props, but funneled anything that wasn't one of these props to the nested `Accordion` (which is a no-go).

Getting `Tree` to support all `ListItem` props is possible but I'd like to keep those changes separate from all the keyboard nav business. For now, restricting props down to only the ones that are needed `Tree`'s nested `TreeItem` / `ListItem` seemed like a decent temp solution.

2021-05-05 19:32 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +    })
In an ideal world, I'd put this `useEffect` call in `TreeItem`. But two points:
1. Putting this in `TreeItem` leads to the `querySelectorAll` call failing to find child focusable elements. I _think_ this has to do with the fact that `ListItem` (which is nested within `TreeItem`) is the one being rerendered, and so hovering / keyboard navigating rerenders the `ListItem` and calls the `useEffect` again with hover disclosure icons present. Placing in `TreeItem` means this `useEffect` call doesn't get re-called when hovering / keyboard navigating. Not sure on this 100%, but TLDR the child elements don't get their auto `tabIndex=-1` when this code lives in `TreeItem`.
2. It's might be nice for actual `List`s elements to include focusable child elements in their keyboard nav flow.

2021-05-06 01:04 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +    }
For the record, I don't love this. Buuuuut I needed a way for state to exist up in the `TreeItem` so that `TreeItem` could know when it's being hovered or not. It needs to know hovered state because it needs to know when to call its `useEffect` which adds `tabIndex=-1` to child button / a / input elements.

Alternatives to this:
- Move the `useEffect` into `ListItem.tsx` (but this couples `ListItem` and `TreeItem` because the `querySelectorAll` call references Tree-related classes)
- Move the `useEffect` call into `ListItemLabel` and `ListItemDetail`
  - I actually think this might be the call...

2021-05-06 17:56 UTC, ElliotTheHuman commented on packages/components/src/List/ListItem.tsx
> +    }
Update: Now that we've forced `TreeItemInner` (i.e. `Tree`'s internal item used to keep code DRY), we _should_ be free to apply `tabIndex=-1` to all links / buttons / inputs present within a `TreeItem` / `ListItem`. In which case, keeping the `useEffect` in `ListItem.tsx` creates the least amount of tech debt afaik.

Follow-up work: Update `List` keyboard navigation to support similar keyboard nav behavior as `Tree` (i.e. up / down arrow traverses items, left / right traverses buttons within the item / item detail container).

2021-05-13 22:19 UTC, ElliotTheHuman commented on packages/components/src/Tree/stories/FieldPicker.story.tsx
> +        px="xxsmall"
Minor visual adjustment to get field type headings to line up with field labels

2021-05-13 23:43 UTC, mdodgelooker requested changes
Looking pretty good! I have a few comments & questions here & there.

2021-05-13 23:43 UTC, mdodgelooker commented on packages/components/src/utils/useArrowKeyNav.ts
>   */
Now that this hook has a different result if disabled, can you define the result type here, and add it as the return type on the function definition below?
```
export type UseArrowKeyNavResult<E extends HTMLElement> = Pick<
  UseArrowKeyNavProps<E>,
  'ref' | 'onBlur' | 'onFocus' | 'onKeyDown'
> & {
  tabIndex?: number
}
```

2021-05-13 23:43 UTC, mdodgelooker commented on packages/components/src/utils/useArrowKeyNav.ts
> +  return disabled ? null : navProps
```suggestion
  return disabled ? {} : navProps
```

2021-05-13 23:43 UTC, mdodgelooker commented on packages/components/src/List/ListItem.tsx
> +    }
This change is good but I think it's causing `AccordionDisclosure` on the field picker to look funky when focused:
![image](https://user-images.githubusercontent.com/53451193/118198484-d8332a00-b405-11eb-8274-dcbf337eaa2c.png)

2021-05-13 23:43 UTC, mdodgelooker commented on packages/components/src/List/ListItemLabel.tsx
> +
Is the focus ring supposed to always show on `ListItem` now, not just for focus via keyboard? If so, we should remove `useFocusVisible`.

2021-05-13 23:43 UTC, mdodgelooker commented on packages/components/src/Tree/Tree.tsx
> +      itemRole={treeItemInnerRole}
I guess this is causing the snapshot diffs? Not sure if that's a real issue or not...

2021-05-14 22:55 UTC, mdodgelooker commented on packages/components/src/utils/useArrowKeyNav.ts
>   */
Whoops, it looks like my requested change caused some TS errors. You can fix those by passing the element type like:
```
const navProps = useArrowKeyNav<HTMLTableElement>({
```

2021-05-18 05:21 UTC, mdodgelooker requested changes
This is looking really slick! A few more suggestions.

2021-05-18 05:21 UTC, mdodgelooker commented on packages/components/src/Tree/TreeStyle.tsx
> +      &:focus::after {
Shouldn't the focus ring only be for keyboard nav? If so, it might work to update `Accordion` with something like
```
className={ `${clickableProps.focusVisible ? 'focusVisible ' : ''}${className}`}
```
and then here you could do `.focusVisible:after`.

2021-05-18 05:21 UTC, mdodgelooker commented on packages/components/src/Tree/TreeStyle.tsx
> +      }
This won't work for Safari or IE11. But if you end up using my suggestion above, you could include this with that.

2021-05-18 05:21 UTC, mdodgelooker commented on packages/components/src/Tree/utils/getNextTreeFocus.ts
> +const getFallbackElement = (
Oh good point codeclimate. You could export the one in `utils/getNextFocus.ts` and then just use that here.

2021-05-18 16:40 UTC, ElliotTheHuman commented on packages/components/src/List/ListItemLabel.tsx
> +    focusVisible: boolean
👍  Good call.

And (iirc) I moved `focusVisible` from the wrapper to the label because the label container is the one that actually takes focus (i.e. has `tabIndex=-1`). The wrapper is just a layout container / li stand-in while the label is the button / a usually (in Explore's instance it's a div with an onClick / onKeyDown because buttons inside of buttons).

2021-05-18 18:12 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeStyle.tsx
> +      &:focus::after {
Good catch. With the previous styling you could click on the indicator and that would trigger the focus visible ring 🤦 .

Went ahead and used the `useFocusVisible` hook, using the returned `focusVisible` prop to conditionally pass the `focusVisible` class name to `TreeStyle`.

2021-05-18 18:54 UTC, ElliotTheHuman commented
GH Actions is stalling, but the code should be ready for another look!

2021-05-18 19:39 UTC, mdodgelooker commented on packages/components/src/Tree/TreeStyle.tsx
> +      &:focus::after {
I think you should be able to just add the `className` in `AccordionDisclosure` where `useFocusVisible` is already in place. Would this work? https://github.com/looker-open-source/components/pull/2372

2021-05-18 21:31 UTC, mdodgelooker approved these changes
Gorgeous. Ship it! 🚢

2021-05-18 21:32 UTC, merged