feat(Header Footer): add shadow to sticky items
looker-open-source/components pull request #2300
Opened 2021-05-05 20:42 UTC by laraharrow

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-05-12 23:39 UTC, laraharrow commented
@lukelooker any suggestions here?

2021-05-13 19:01 UTC, laraharrow commented
hey @lukelooker, as soon as I make `Layout` into a FC it breaks the display. When you have a sec would you look into this?

2021-05-14 00:44 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Layout.tsx
> +)
The `InnerLayout` needs to "know" about `hasAside` & `fixed` to properly specify the CSS:

```suggestion
export const Layout: FC<LayoutProps> = ({ children, fixed, hasAside }) => (
  <InnerLayout hasAside={hasAside} fixed={fixed}>{children}</InnerLayout>
)
```

2021-05-14 22:09 UTC, mdodgelooker reviewed
`Layout` needs to pass through the rest of `props`.

2021-05-14 22:09 UTC, mdodgelooker commented on packages/components/src/Layout/Semantics/Layout.tsx
> +export const Layout: FC<LayoutProps> = ({ children, fixed, hasAside }) => {
```suggestion
export const Layout: FC<LayoutProps> = ({ children, fixed, hasAside, ...props }) => {
```

2021-05-14 22:09 UTC, mdodgelooker commented on packages/components/src/Layout/Semantics/Layout.tsx
> +      ref={internalRef}
```suggestion
      ref={internalRef}
      {...props}
```

2021-05-18 02:20 UTC, laraharrow commented
@lukelooker  Here is my first attempt on making the hooks for overflow into `useOverflow` - its not quite working 🤦🏽‍♀️
I saw it working when I had the logic inside each component ( `Layout` `Aside` `Section` ) once I created `useOverflow` and tried adding it to the 3 components it's not working anymore. Also`shouldForwardProp` is causing a bug on `collapse`.

2021-05-19 04:43 UTC, lukelooker requested changes
Most of my comments are focused around consolidating some duplicate code across Aside, Layout & Section (I made comments on `Aside` but refactors applied there should get applied to the other `useOverflow` components as well)

2021-05-19 04:43 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Aside.tsx
> +    <InnerAside hasOverflow={hasOverflow} ref={internalRef} {...props}>
Create a single component that be used in all the components (see mention of `OverflowShadow` below:

```suggestion
    <OverflowShadow as="aside" hasOverflow={hasOverflow} ref={internalRef} {...props}>
```

2021-05-19 04:43 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Semantics.test.tsx
> +)
Can you pull the text block here from a variable in `__mock__` file so the test itself is easy to read? (I believe the `Constitution.tsx` file has some big chunks of text)

```suggestion
```

2021-05-19 04:43 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Story/ExamplePage.story.tsx
> +  aside {
Ideally we should never target HTML selectors and instead use Styled Component references to ensure we're targeting just our own components.

2021-05-19 04:43 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Story/ExamplePage.story.tsx
> -          <Section p="xxlarge" as="main">
Why did you remove the `as="main"` throughout this file? (it does add semantic meaning and helps screen readers so there will probably be real-world use cases for it)

2021-05-19 04:43 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Story/ExamplePage.story.tsx
> +)
This file is getting too large to read. Can we look at breaking it up in this PR or doing a follow-up to do so?

2021-05-19 04:43 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Story/Semantics.story.tsx
> +    <Layout height="100%">
We should not need to explicitly style `Layout` like this (if it's need we probably have a bug that needs to be addressed)

2021-05-19 05:10 UTC, mdodgelooker commented on packages/components/src/Layout/Semantics/Aside.tsx
> +export const Aside: FC<AsideProps> = ({ collapse, children, ...props }) => {
@lukelooker yeah, we probably should use `forwardRef` – I could see people wanting to measure these elements, get their scroll position, stuff like that.
@laraharrow let's chat tomorrow about how to modify `useOverflow` to support that change.

2021-05-19 17:36 UTC, laraharrow commented on packages/components/src/Layout/Semantics/Story/ExamplePage.story.tsx
> +)
yes I'll add that to the PR that I'll separate the tests.

2021-05-20 23:23 UTC, lukelooker requested changes

2021-05-20 23:23 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Section.tsx
>  `
This repeats in all `Aside`, `Layout` & here (`Section`).

How about renaming it as `OverflowShadow` and placing it centrally (perhaps with the `useOverflow` hook) and then using it for all of the usages?

2021-05-20 23:23 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Story/Semantics.story.tsx
> +    <Layout height="100%">
Still worried about this change. Why was it needed?

2021-05-20 23:28 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Story/Semantics.story.tsx
> +    <Layout height="100%">
Still worried about this change. Why was it needed?

2021-05-20 23:31 UTC, laraharrow commented on packages/components/src/Layout/Semantics/Section.tsx
>  `
The only things about that is that we use `aside` and `div` as the styled element. Also the specific component prop is part of the interface. I could just add the 3 props: `SectionProps` `AsideProps` `LayoutProps` what to do about the fact that `Aside` uses `aside` as its element on `styled` and the other two use `div`.

2021-05-21 00:12 UTC, laraharrow commented on packages/components/src/Layout/Semantics/Story/Semantics.story.tsx
> +    <Layout height="100%">
oops forgot to remove it, I fixed the issue before just forgot to remove it on story. fixed now

2021-05-21 21:21 UTC, lukelooker approved these changes
Awesome! `useOverflow` & `OverflowShadow` look great.

Ignore test / storybook structure since they're a bit of a mess but that's going to be addressed shortly.

2021-05-21 21:22 UTC, merged