feat(Aside): standardized width size
looker-open-source/components pull request #2348
Opened 2021-05-12 23:34 UTC by laraharrow

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-05-14 00:14 UTC, lukelooker requested changes
Need to add `AsideSizes` to the sizes supported by `Drawer` so that folks can move between the two seamlessly then this is totally good to go!

2021-05-14 00:55 UTC, lukelooker requested changes
Seeing some test failures and the `DrawerWidth` is going to need to be an extension of `DialogWidth` so there's only a single helper in the CSS block.

2021-05-14 00:55 UTC, lukelooker commented on packages/components/src/Drawer/DrawerSurface.tsx
> +  ${asideWidth}
This will output `width` twice in the CSS.

There should be a new `drawerWidth` function that combines the two Ramps and then allows a single use here.

2021-05-14 21:52 UTC, mdodgelooker commented on packages/components/src/Drawer/DrawerSurface.tsx
> +  width?: ResponsiveValue<DialogSizeRamp | AsideSizeRamp | string>
If you make this a new type...
```
export type DrawerWidth = ResponsiveValue<DialogSizeRamp | AsideSizeRamp | string>
...
width?: DrawerWidth
```
You can then add it to `UseDialogPropsInternal` in `useDialog.tsx`:
```
export interface UseDialogPropsInternal
  extends Omit<UseDialogProps, 'placement' | 'width'> {
  placement?: DialogPlacements | DrawerPlacements
  width?: DialogWidth | DrawerWidth
}
```

2021-05-17 16:08 UTC, lukelooker requested changes
Appears that sine `Drawer` stuff snuck in `Dialog` and I see one spot where a change to `width` on `Drawer` could/would be a breaking change for folks.

2021-05-17 16:08 UTC, lukelooker commented on packages/components/src/Dialog/DialogSurface.tsx
> +  width?: DrawerWidth
?

```suggestion
  width?: DialogWidth
```

2021-05-17 16:08 UTC, lukelooker commented on packages/components/src/Drawer/DrawerSurface.tsx
> +  width?: DrawerWidth
This needs to support `string` still as folks may want to use "off standard" sizes:

```suggestion
  width?: DrawerWidth | string
```

Also removing `ResponsiveValue` will act as a breaking change for anybody using that so we need to put it back so as not to break folks who might be using responsive drawer sizes (not sure if anyone is but it's hard to know for sure since extension developers use stuff in new ways).

2021-05-17 16:08 UTC, lukelooker commented on packages/components/src/Dialog/DialogSurface.tsx
> +import { DrawerWidth } from '../Drawer/DrawerSurface'
I'm thinking the `DrawerWidth` shouldn't be pulled into `DialogSurface`?

2021-05-17 18:18 UTC, laraharrow commented
Hey Luke, I'm not sure I follow your suggestions here. I was getting errors by using `DialogWidth` within `Drawer` and `Dialog ` so to fix it I updated that value to include the new `Aside` values. Nothings should have changed to `Dialog` as we still support all the value expected by it. I just added the values that `Aside` is adding. I was a bit skeptical of adding `DrawerWidth` inside `DialogSurface` but it seemed to be needed to avoid a bug since `Drawer` is actually using `Dialog` underneath.

2021-05-17 18:51 UTC, lukelooker commented on packages/components/src/Dialog/DialogSurface.tsx
> +import { DrawerWidth } from '../Drawer/DrawerSurface'
`DialogDrawerWidth`

2021-05-17 19:45 UTC, lukelooker approved these changes
Ship it! :)

2021-05-17 19:55 UTC, merged