feat(TabPanel): Added tabIndex prop to TabPanel
looker-open-source/components pull request #2413
Opened 2021-05-21 23:49 UTC by ElliotTheHuman

In the new Field Picker experience, a keyboard user has to tab from the `Tab` to the `TabPanel` to the first `Tree` in order to focus on the `Tree` items and begin field keyboard traversal. Ideally, I think it'd be cleaner to just tab from the `Tab` directly to the `TreeCollection` since it is the only element in the `TabPanel`.

Adding `tabIndex` as a prop allows devs to pass a non-zero value to `TabPanel`'s `tabIndex` prop and thus remove it from the tab flow.

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-05-24 17:16 UTC, ElliotTheHuman commented
There's an argument to add `CompatibleHTMLProps<HTMLDivElement>` to `Tab` but I wasn't sure if that was excluded here purposefully.

2021-05-24 21:05 UTC, lukelooker requested changes
I'd prefer not to ask developers to understand `tabIndex` and instead offer a more semantic prop. See proposed change.

2021-05-24 21:05 UTC, lukelooker commented on packages/components/src/Tabs/TabPanel.tsx
> +  tabIndex?: number
```suggestion
  /**
   * Set to `true` if you would like TabPanel to be reached via tab-key.
   * Generally this is _only_ the case when the TabPanel contains no tab-stopping items (a, button, etc.)
   * @default false
   */
  tabStop?: boolean
```

2021-05-24 21:56 UTC, lukelooker submitted a review, later dismissed
Assuming @jhardy's research supports this I'm happy with it :)

2021-05-25 13:55 UTC, jhardy commented
I dug in a bit more and this seems to align closely with some [updated guidance from the w3c aria best practices.](https://github.com/w3c/aria-practices/issues/1164) This is not published on their official docs just yet, but the new guidance is for the `tab` key is 

> - When focus moves into the tab list, places focus on the active tab element.
> - When the tab list contains the focus, moves focus to the next element in the page tab sequence outside the tablist, which is the tabpanel unless the first element containing meaningful content inside the tabpanel is focusable. 

I am wondering about the prop name `tabStop`, that feels a bit too generic as first glance. I don't dislike it enough to block the PR. I am wondering if a more descriptive prop name but could be something we reuse elsewhere if we need to give the option to programmatically add focus.

`<TabPanel makeFocusable>` 
`<TabPanel includeInTabSequence>`
`<TabPanel addAsTabStop>`
`<TabPanel canReceiveFocus>`

Not sure if those are any better or too verbose, but just a few early morning thoughts.

2021-05-25 16:41 UTC, lukelooker commented
Great point on naming... what about `isTabStop`? (fits with our other `isX` conventions)

2021-05-25 16:56 UTC, jhardy commented
that works for me!

2021-05-25 18:47 UTC, lukelooker approved these changes
LGTM!

2021-05-25 18:48 UTC, merged