fix(Semantics): updated and organized stories and tests
looker-open-source/components pull request #2414
Opened 2021-05-22 03:11 UTC by laraharrow

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-05-22 03:51 UTC, laraharrow commented
Organized and added test and test files inside `Semantics` 
Separating and cleaned up tests and stories for  `Aside` `Layout` and `Section`. 
`DrawerSurface` uses `asideWidth` had to be updated once the file got moved
Updated `__mock__/Constitution.tsx` to have more reusable components

2021-05-22 05:04 UTC, lukelooker requested changes

2021-05-22 05:04 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Aside/Aside.test.tsx
> +  test('renders.', () => {
```suggestion
  test('default', () => {
```

2021-05-24 18:26 UTC, lukelooker requested changes
Looks like some comment from the previous review weren't addressed yet. Add "bump" to the areas I'd still like to see addressed.

2021-05-24 18:26 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Layout.tsx
> +import { Section } from './Section/Section'
Should import from `import { Section } from './Section'` for consistency's sake (probably need to add an `index.ts` to the "Section" folder.

2021-05-24 18:26 UTC, lukelooker commented on packages/components/src/Layout/Semantics/index.ts
> +export * from './Aside/Aside'
Bump

2021-05-24 18:26 UTC, lukelooker commented on packages/components/src/Layout/Semantics/index.ts
> +export * from './Section/Section'
Bump

2021-05-24 18:26 UTC, lukelooker commented on packages/components/src/__mocks__/Constitution.tsx
> +import { ViewColumn } from '@styled-icons/material/ViewColumn/ViewColumn'
Bump

2021-05-24 18:26 UTC, lukelooker commented on packages/components/src/__mocks__/Constitution.tsx
> +)
Bump

2021-05-24 23:40 UTC, lukelooker requested changes
Really close! Found a few issues:

- [x] `Footer.tsx` got erroneously duplicated
- [ ]  Rename "Semantics" story
- [x] Move `ItemsFiller` into it's own mock file separate from Constitution since they're unrelated 
- [x] Delete the "snapshots" folder on your local instance and then re-run `yarn test:image-test-snapshots` - commit any deleted snapshots so that we don't keep tracking images for snapshots that have since been renamed (I'm sure the `Aside` ones are in this group, not if there's anything else)

2021-05-24 23:40 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Layout/Footer.tsx
> + Permission is hereby granted, free of charge, to any person obtaining a copy
This appears to duplicate the file in `packages/components/src/Layout/Semantics/Footer.tsx` - I think this version should simply get removed?

2021-05-24 23:40 UTC, lukelooker commented on packages/components/src/Layout/Semantics/Semantics.story.tsx
> +  title: 'Semantics',
To avoid confusion with other Looker use of the word "semantics" (in reference to LookML) let's be more specific with the title here :)

```suggestion
  title: 'Semantic Layout',
```

2021-05-24 23:40 UTC, lukelooker commented on packages/components/src/__mocks__/Constitution.tsx
> +)
This should probably move into its own file within `__mocks__` since it doesn't have anything to do with the `Constitution` content below. Perhaps "ListHelper.tsx`?

2021-05-25 00:47 UTC, lukelooker approved these changes
LGTM! Much improved :)

2021-05-25 00:48 UTC, merged