feat(Footer): create updated Popover, Modal, Dialog
looker-open-source/components pull request #2434
Opened 2021-05-25 22:48 UTC by laraharrow

This PR, created a top component ModalHeader that holds the structure for Header for Dialog and Popover
DialogHeader was updated to use ModalHeader
PopoverHeader was created also using ModalHeader

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-05-26 15:28 UTC, lukelooker requested changes

2021-05-26 15:28 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverHeader.story.tsx
> +)
I would merge this together:

```suggestion
export const Detail = () => (
  <Box bg="ui1" width="248px">
    <PopoverHeader detail={<button>close</button>}>Header Text</PopoverHeader>
  </Box>
)
```

2021-05-26 15:28 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverHeader.test.tsx
> +  })
These two tests can be unified.

2021-05-26 15:28 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverHeader.tsx
> +  font-weight: ${({ theme }) => theme.fontWeights.medium};
These shouldn't be needed I think.

2021-05-26 15:28 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverHeader.tsx
> +  })
These values should be assigned as props to `ModalHeader`

2021-05-26 15:28 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogHeader.tsx
> +export interface DialogHeaderProps extends ModalHeaderProps {
Per ticket this should leverage a type union:

> Add a discriminated type union to prevent setting hideClose={true} && detail at the same time (these are mutually exclusive states)

See https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types & https://basarat.gitbook.io/typescript/type-system/discriminated-unions

2021-05-26 15:28 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverHeader.tsx
> +}
Should leverage discriminated type union as noted above on `DialogHeader`

2021-05-26 15:28 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverHeader.story.tsx
> +  <Box bg="ui1" width="248px">
I'd go ahead and skip the `Box` on all of these actually:

```suggestion
    <PopoverHeader>Header Text</PopoverHeader>
```

2021-05-26 15:28 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverHeader.test.tsx
> +    renderWithTheme(<PopoverHeader>Heading</PopoverHeader>)
Import examples from Storybook to allow easy visual checking of test cases:

In import block:

```
import { Basic } from './PopoverHeader.story.tsx`
```

```suggestion
    renderWithTheme(<Basic />)
```

2021-05-26 21:58 UTC, laraharrow commented on packages/components/src/Dialog/Layout/DialogHeader.test.tsx
>    })
Because that is a `ModalHeader` prop I was testing it there.

2021-05-26 23:19 UTC, laraharrow commented
The `lint:ts` bug I think was created by using the `union type` for `detail` and `hideClose` I created a problem on `DialogHeader` inside `DialogLayout` I'm not sure what the best approach to salve this is. Do you have a suggestion?

2021-05-27 04:38 UTC, lukelooker reviewed
Just added two comments in this review pointing out how to type things to work correctly.

The type changes will reveal a "bug" in `DialogLayout` where `detail` & `hideClose` _could_ be assigned to `DialogHeader` at the same time - that code will need to be slightly restructured so that's not possible - a great proof-case that the type change here is working as-intended :)

2021-05-27 04:38 UTC, lukelooker commented on packages/components/src/Modal/ModalHeader.tsx
> +}
This needs to get converted to a type so that when the types get merged in DialogHeader & PopoverHeader they're compatible:

```suggestion
export type ModalHeaderProps = SpaceProps &
  CompatibleHTMLProps<HTMLElement> &
  FontSizeProps &
  FontWeightProps & {
    children: ReactNode
    /**
     * Usually used as a closing button this element is displayed on the right side of the component
     */
    detail?: ReactNode | string
    /**
     * use to support aria-labelledby
     */
    id?: string
  }
```

2021-05-27 04:38 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogHeader.tsx
> +export type DialogHeaderProps = WithDetail | WithHideClose
This needs to extended the type for `ModalHeader`:

```suggestion
export type DetailUnion = WithDetail | WithHideClose

export type DialogHeaderProps = DetailUnion & Omit<ModalHeaderProps, 'detail'>
```

2021-05-27 21:42 UTC, lukelooker requested changes
Minor comments on naming and code style but pretty close to ready.

2021-05-27 21:42 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.test.tsx
> +    expect(screen.queryByText('Close')).toBeInTheDocument()
```suggestion
    expect(screen.getByText('Close')).toBeInTheDocument()
```

2021-05-27 21:42 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.test.tsx
> +    expect(screen.queryByText('Heading')).toBeInTheDocument()
```suggestion
    expect(screen.getByText('Heading')).toBeInTheDocument()
```

2021-05-27 21:42 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.test.tsx
>      expect(screen.queryByLabelText('Close')).not.toBeInTheDocument()
```suggestion
    expect(screen.getByLabelText('Close')).not.toBeInTheDocument()
```

2021-05-27 21:42 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.tsx
> +export type DialogHeaderProps = DetailUnion & Omit<ModalHeaderProps, 'detail'>
I know I had suggested the names here originally but in reading this I think it would be improved by better naming:

```suggestion
export type DetailOptions = WithDetail | WithHideClose
export type DialogHeaderProps = DetailOptions & Omit<ModalHeaderProps, 'detail'>
```

2021-05-27 21:42 UTC, lukelooker commented on packages/components/src/Modal/CloseHeaderButton.tsx
> +export interface CloseHeaderButtonProps {
Propose name change to `ModalHeaderCloseButton` to keep this within the "Modal" name-space.

2021-05-27 21:42 UTC, lukelooker commented on packages/components/src/Modal/CloseHeaderButton.tsx
> +const CloseHeaderButtonLayout: FC<CloseHeaderButtonProps> = ({
See name suggestion above.

2021-05-27 21:42 UTC, lukelooker commented on packages/components/src/Modal/CloseHeaderButton.tsx
> +)<CloseHeaderButtonProps>``
See name suggestion above again. Also, I don't think the `CloseHeaderButtonProps` needs to be specified because Styled Components _should_ infer it automatically.

```suggestion
export const ModalHeaderCloseButton = 
  styled(ModalHeaderCloseButtonLayout)``
```

2021-05-27 21:42 UTC, lukelooker commented on packages/components/src/Modal/ModalHeader/ModalHeader.test.tsx
> +    renderWithTheme(<ModalHeader detail={button}>Header</ModalHeader>)
Prefer seeing these collapsed since `button` const is never used again :)

```suggestion
    renderWithTheme(<ModalHeader detail={<button>x</button>}>Header</ModalHeader>)
```

2021-05-27 21:42 UTC, lukelooker commented on packages/components/src/Modal/ModalHeader/ModalHeader.tsx
> +    children: ReactNode
Can this get narrowed to `ReactChild`?

```suggestion
    children: ReactChild
```

2021-05-27 21:42 UTC, lukelooker commented on packages/components/src/Modal/ModalHeader/ModalHeader.tsx
> +    id?: string
I think the `HTMLElement` extension above should bring this in automatically?

Perhaps that needs to be `HTMLDivElement` instead to get `id`?

2021-05-27 21:42 UTC, lukelooker commented on packages/components/src/Modal/ModalHeader/ModalHeader.tsx
> +  id = undefined,
```suggestion
  id,
```

2021-05-27 21:42 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverHeader/PopoverHeader.tsx
> +      detail={!hideClose && finalDetail}
This can be done with an implicit return:

```suggestion
}) => (
    <ModalHeader
      detail={detail || !hideClose && <CloseHeaderButton size="small" />}
```

2021-05-27 23:19 UTC, laraharrow commented on packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.test.tsx
>      expect(screen.queryByLabelText('Close')).not.toBeInTheDocument()
This one needs to be query to test correctly 
`queryBy`: returns null when element is not found (what we want)
`getBy`: throws an error

2021-05-27 23:28 UTC, laraharrow commented on packages/components/src/Modal/ModalHeader/ModalHeader.tsx
> +    children: ReactNode
This breaks `PopoverHeader`

2021-06-01 16:21 UTC, lukelooker reviewed
Found a few minor things - pushing a commit momentarily with patches (had to pull branch to validate if my feedback was useful anyway so I figured I'd just push up the changes to help get things rolling)

2021-06-01 16:21 UTC, lukelooker commented on packages/components/src/Modal/ModalHeader/ModalHeader.tsx
> +    children: ReactNode
Ok - poked around a bit and figured out what was happening here - the `PopoverHeader` needs to explicitly specify `children: ReactChild` rather than _just_ using `FC<...>` because `FC` (FunctionalComponent) adds `children?: ReactNode` by default if it's not already specified.

2021-06-01 16:22 UTC, lukelooker approved these changes
Just pushed a few small fixes in (https://github.com/looker-open-source/components/pull/2434/commits/ebc42e629e9bfbe79cd18e716fc1716741ea0cbe) that address final feedback issues.

Please self-review the changes I made so you can see what I noticed (and make sure I didn't miss anything).

Assuming CI passes LGTM.

2021-06-01 16:35 UTC, merged