fix(Tree): Updated Tree icon / indicator alignment
looker-open-source/components pull request #2449
Opened 2021-06-01 21:21 UTC by ElliotTheHuman

**Changes:**
- Removed iconGapAdjuster
- Set consistent iconGap across densities (xxsmall)
- Scaled indicator icon according to density
- Added `iconSpacing` prop to align labels of `Tree`s with icons and labels of child `Tree`s without icons

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-06-01 21:22 UTC, ElliotTheHuman commented on packages/components/src/List/utils/index.ts
> +export * from './partitionAriaProps'
Unrelated: Correcting the file name on this to reflect the actual function name of `partitionAriaProps`

2021-06-01 21:22 UTC, ElliotTheHuman commented on packages/components/src/Tree/TreeArtificial.tsx
> +    >
I plan on deprecating `TreeArtificial` as soon as this update gets merged.

For now, I needed to make some minor changes to get TS from complaining.

2021-06-02 16:56 UTC, lukelooker requested changes
Some questions inline regarding deprecation strategy / plan.

The big question I have is about indicator alignment: 

![image](https://user-images.githubusercontent.com/34253496/120520505-ba177480-c388-11eb-82a8-214ffc6959fe.png)


It _appears_ like the indicator is no longer centered in the space it occupies? I think that's incorrect?

2021-06-02 16:56 UTC, lukelooker commented on packages/components/src/Tree/Tree.tsx
> +      {...restProps}
Any concerns about breaking previous behavior that might've depended on overriding values "late"?

2021-06-02 16:56 UTC, lukelooker commented on packages/components/src/Tree/Tree.tsx
> +
Since this is used exactly once is there a reason to pull it out into a separate variable?

2021-06-02 16:56 UTC, lukelooker commented on packages/components/src/Tree/types.ts
> +     * @deprecated Use `iconSpacing` prop instead
Are we sure it makes sense to drop this in 2.x or perhaps wait for 3.x?

Asked another way, what's the overhead if we don't remove this immediately? Generally we try to indicate deprecations for at least a few releases before removing.

2021-06-02 16:56 UTC, lukelooker commented on packages/components/src/Tree/types.ts
> +     * @deprecated Use `iconSpacing` prop instead
Alternatively, could we be "cute" and make this a proxy for `iconSpacing` in 2.x?

2021-06-02 17:46 UTC, ElliotTheHuman commented on packages/components/src/Tree/Tree.tsx
> +      {...restProps}
I don't have any concerns, but this might not be the best change in retrospect. The reason I moved this up was because I wanted my explicit `indicatorGap` to be applied  (which conditionally applies the density-respective `iconGap` or the default `indicatorGap` based on the `iconSpacing` prop).

In c3fd26e, I moved the `restProps` destructure back to the bottom of the props, and destructured `indicatorDefaults` before the `Accordion` JSX (i.e. manually passing in the properties of `indicatorDefaults`).

This adds some lines, but I think it's a little easier to follow since I need to access that `indicatorDefault.indicatorGap` value anyhow 🤷

2021-06-02 17:51 UTC, ElliotTheHuman commented on packages/components/src/Tree/Tree.tsx
> +
It wouldn't ideally! But I'm getting a lint error when passing a literal string value:
![Screen Shot 2021-06-02 at 10 46 51 AM](https://user-images.githubusercontent.com/16812885/120528028-d8cd3980-c38f-11eb-89b5-d3dea3f33f13.png)

That being said, considering the comment above, it might make sense to pass the  `indicatorDefaults.indicatorGap (gets renamed to defaultGap)`  variable since I'm destructuring `indicatorDefaults` outside of the `Accordion` JSX.

2021-06-02 17:55 UTC, ElliotTheHuman commented on packages/components/src/Tree/types.ts
> +     * @deprecated Use `iconSpacing` prop instead
We can probably do either!

1) The engineering overhead for keeping `forceLabelPadding` doesn't seem costly (it's just another variable that gets received by `Tree` and funneled into `TreeStyle` and `generateIndent`). However, supporting it and making sure it plays nice with any future alignment changes could be a nuisance.

2) It shouldn't be hard to make this a proxy for `iconSpacing` in 2.x. The only change we'd need to make would be within `generateIndent`. Happy to change the JSDoc to reflect this upcoming change if you'd like.

2021-06-02 18:00 UTC, ElliotTheHuman commented
> Some questions inline regarding deprecation strategy / plan.
> 
> The big question I have is about indicator alignment:
> 
> ![image](https://user-images.githubusercontent.com/34253496/120520505-ba177480-c388-11eb-82a8-214ffc6959fe.png)
> 
> It _appears_ like the indicator is no longer centered in the space it occupies? I think that's incorrect?

The reason the indicator is no longer centered is because it has a "4px" gutter (in the form of `margin-right`). I _think_ that's the right way to apply that gutter (note: the optional `icon` on `ListItem`s also has a gutter, but this gutter is "4px + x" where x is some amount of minor label faux-padding Jared outlined in this spec:
https://www.figma.com/file/ADmrXwJUbKG0eVAhco8X10/LGM2-Transition?node-id=1495%3A222438

2021-06-02 18:38 UTC, lukelooker commented on packages/components/src/Tree/types.ts
> +     * @deprecated Use `iconSpacing` prop instead
Ok, yes, I'd say go ahead and make it a "proxy" and mark it as `@deprecated` we can go ahead and remove it in the 3.x series.

2021-06-02 18:59 UTC, jhardy commented
> Some questions inline regarding deprecation strategy / plan.
> 
> The big question I have is about indicator alignment:
> 
> ![image](https://user-images.githubusercontent.com/34253496/120520505-ba177480-c388-11eb-82a8-214ffc6959fe.png)
> 
> It _appears_ like the indicator is no longer centered in the space it occupies? I think that's incorrect?

I think this ok, as Elliot mentioned above its the artifact of the gutter, we could use `padding-left` on the label instead, but not sure if there is a down side to that. 

Either way I think the alignment is working pretty nicely

2021-06-02 19:01 UTC, lukelooker commented
> I think this ok, as Elliot mentioned above its the artifact of the gutter, we could use `padding-left` on the label instead, but not sure if there is a down side to that.
> 
> Either way I think the alignment is working pretty nicely

Comparing screenshots makes it look like a really big change but if the design-guy says it's okay I'm cool with it. 👍 

Reading remainder of feedback now. :)

2021-06-02 19:02 UTC, ElliotTheHuman commented on packages/components/src/Tree/types.ts
> +     * @deprecated Use `iconSpacing` prop instead
Done in 38c0325

2021-06-02 19:54 UTC, jhardy commented
> > I think this ok, as Elliot mentioned above its the artifact of the gutter, we could use `padding-left` on the label instead, but not sure if there is a down side to that.
> > Either way I think the alignment is working pretty nicely
> 
> Comparing screenshots makes it look like a really big change but if the design-guy says it's okay I'm cool with it. 👍
> 
> Reading remainder of feedback now. :)

Just to compare side

> > I think this ok, as Elliot mentioned above its the artifact of the gutter, we could use `padding-left` on the label instead, but not sure if there is a down side to that.
> > Either way I think the alignment is working pretty nicely
> 
> Comparing screenshots makes it look like a really big change but if the design-guy says it's okay I'm cool with it. 👍
> 
> Reading remainder of feedback now. :)

Just to close the loop here, previously nested trees did not align with the parent icon, here is a visual side-by-side
![image](https://user-images.githubusercontent.com/170681/120543519-3b7b0100-c3a1-11eb-8ec7-aa5775ea39ea.png)

In new spec we also slightly changed the spacing between the label and the icon, previously we were subtracting two pixels to save for some optical space, but I felt that was over complicated it, so now we stick with the default `ListItem` spacing, hopefully, to keep it a bit simpler. (@ElliotTheHuman can keep me honest here)

2021-06-02 20:24 UTC, ElliotTheHuman commented
> Just to close the loop here, previously nested trees did not align with the parent icon, here is a visual side-by-side
> ![image](https://user-images.githubusercontent.com/170681/120543519-3b7b0100-c3a1-11eb-8ec7-aa5775ea39ea.png)
> 
> In new spec we also slightly changed the spacing between the label and the icon, previously we were subtracting two pixels to save for some optical space, but I felt that was over complicated it, so now we stick with the default `ListItem` spacing, hopefully, to keep it a bit simpler. (@ElliotTheHuman can keep me honest here)

Correctamundo! This PR pulls out the `iconGapAdjuster` (i.e. the -2px to save for optical space). Now we use the exact   `iconGap` values from the density scale.

2021-06-02 21:59 UTC, lukelooker submitted a review, later dismissed
Awesome-sauce. 🚢

2021-06-02 22:43 UTC, lukelooker approved these changes
👍

2021-06-02 22:44 UTC, merged