fix PopoverContent double file
looker-open-source/components pull request #2472
Opened 2021-06-04 20:14 UTC by laraharrow

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-06-15 01:09 UTC, laraharrow commented
Ok I think this is ready for review!
A few notes here:
1. I made a few changes to the snapshots based on the new code that was added. @lukelooker maybe we can chat about what is the best way to have every option well represented but with no repetition?
2. I don't think that the `DialogFooter` storybook examples are exactly relatable to the use cases we have in helltool, not sure if we want to update that.

2021-06-16 15:53 UTC, lukelooker requested changes
Needs rebase :)

2021-06-16 16:31 UTC, laraharrow commented on packages/components/src/__mocks__/DialogExampleLayout.tsx
> -      footer={
@lukelooker this is what I was mentioning about the stories

2021-06-16 16:43 UTC, lukelooker requested changes
Haven't dug into the `Popover` specific changes as of yet - I'd like to start with just having `Dialog*` snapshots stay identical (no changes). Additional snapshots is fine but I'd expect to see no changes to the existing "known good" snapshots.

2021-06-16 16:43 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.story.tsx
> -)
Can we revert this change?

2021-06-16 16:43 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.test.tsx
> -
Let's revert this change and the one below (effectively just moves around the test and I'd prefer to limit the amount of change since we've had "jitter" on these components recently)

2021-06-16 16:43 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +)
Can this set of stories be restore to how they were used before so that we can verify that no of the associated image snapshots were altered unexpectedly?

2021-06-16 16:43 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +)
This is a net-new test and can be kept.

2021-06-16 16:43 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +)
This is a net-new test and can be kept.

2021-06-16 16:43 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
>  )
I'm okay with this change.

2021-06-16 16:43 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +)
Specifically `DialogLayoutExampleProps`, `Template`, `Basic`, `Header` & `Footer`

2021-06-16 16:43 UTC, lukelooker commented on packages/components/src/Modal/ModalFooter/ModalFooter.tsx
> +  </Flex>
This will break the existing `DialogFooter` layout for "secondary" I think – "secondary" is supposed to go on the left-hand side of the `DialogFooter`

```
[secondary]                                                   [children]
```

e.g.:

```
[Add Another]                                                       [ Cancel,  Save Changes ]
```

2021-06-16 16:43 UTC, lukelooker commented on packages/components/src/Modal/ModalHeader/ModalHeader.tsx
> +  width: 100%;
I'm not remember why we needed to add this (I think it's fine but always great to see a note on the PR noting why a change to a component was needed

2021-06-16 16:43 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverFooter/PopoverFooter.story.tsx
> +export const Basic = () => <PopoverFooter />
Pretty sure this still needs to have a child `Footer Text` ?

2021-06-16 16:43 UTC, lukelooker commented on packages/components/src/__mocks__/DialogExampleLayout.tsx
> +        </ButtonTransparent>
This change needs to be reversed as it alters the result of a lot of image snapshots. The previous version was the expected design (no use of `footerSecondary` in these)

2021-06-16 16:58 UTC, laraharrow commented on packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.story.tsx
> -)
I updated this change but as of right now its set as `storyshots: { disable: true },` so it shouldn't affect snapshots.

2021-06-16 18:06 UTC, laraharrow commented on packages/components/src/Modal/ModalFooter/ModalFooter.tsx
> +  </Flex>
That's one of the problems with my understanding of the `figma` the was that the component is displayed there there is no example with `secondary` so I assumed the `cancel` word there was the `secondary` prop. 
https://www.figma.com/file/zd6MjUXIIstvG7gTJWaX2Y/Looker-Components?node-id=3%3A569
So I actually change the code to accommodate that🤦🏽‍♀️.

2021-06-16 18:09 UTC, laraharrow commented on packages/components/src/Modal/ModalHeader/ModalHeader.tsx
> +  width: 100%;
My bed, when we chat last there was a bug I was trying to fix. You had suggested adding that would maybe solve the problem. I added thinking I would go back and check and after solving the bug I forgot it that was there.

2021-06-16 18:11 UTC, laraharrow commented on packages/components/src/Popover/Layout/PopoverFooter/PopoverFooter.story.tsx
> +export const Basic = () => <PopoverFooter />
Because when nothing is passed we would still have the `Done` available there is a chance that nothing needs to be passed. Am I missing something here?

2021-06-16 18:34 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverFooter/PopoverFooter.story.tsx
> +export const Basic = () => <PopoverFooter />
Ah! My bad - that makes sense.

2021-06-17 05:41 UTC, lukelooker requested changes
Hey Lara - 

With the work to prepare 2.0 to launch we found quite a few spots where we had regressions in Dialog layouts (as well as the existing `PopoverContent` behavior so I'd like to be a bit more cautious moving forward so we don't accidentally cause any new issues. 

With that in mind I'd like to break this PR into two seperate PRs:

1. refactor: Extract new `ModalLayout` from `DialogLayout`
2. feat: Add new `PopoverLayout` component

Ideally the initial PR would be able to leave all existing stories and tests for `DialogLayout` intact (adding new ones is totally fine of course). 

I've made a bunch of additional comments as well as unresolving some unaddressed comments from my previous review that should help get the first PR ready to go (the "refactor" portion). 

If you need help with doing the git-magic to pull this apart into a couple of separate PRs I'd be happy to jump on a call with you and walk you through doing so.

2021-06-17 05:41 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +    <DialogLayout header="Header" headerDetail={extraButton} footer="Footer">
```suggestion
    <DialogLayout header="Header" headerDetail="Detail text" footer="Footer">
```

2021-06-17 05:41 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +)
```suggestion
```

2021-06-17 05:41 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +  <Box bg="ui1">
I worry that folks previewing these components might come to the false assumption that they have a `ui1` background if they don't look at the source.

So i'd prefer not to wrap see these in a box with background color since it's not something we expect to see in real implementations.

2021-06-17 05:41 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +      }
`DialogLayout` already wraps content output in `footer` within another `DialogFooter` so it's not needed here. Should instead be:

```suggestion
      footer={<Button>Primary</Button>
      footerSecondary="Secondary text"
```

2021-06-17 05:41 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +    <DialogLayout header="Header" headerCloseButton={true} footer="Footer">
```suggestion
    <DialogLayout header="Header" headerCloseButton footer="Footer">
```

2021-06-17 05:41 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +  <Box bg="ui1">
NOTE: Please remove from all of these stories for consistency unless you see a specific benefit to keeping the background color (let me know if so - happy to discuss)

2021-06-17 05:41 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +Content.args = {}
Any specific reason to rename this story? Most of our `.story` files start with a story named "Basic" so it'd be nice to keep with that convention unless there's a specific reason not to do so.

Also the `length` option made it easier to compose the stories below - wondering why you choose to remove that functionality and hard-code it instead?

```suggestion
export const Basic = Template.bind({})
Basic.args = {
  length: 'short'
}
```

2021-06-17 05:41 UTC, lukelooker commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +export const HeaderDetail = () => (
This story could leverage the standard `Template` above by being rewritten as:

```suggestion
export const HeaderDetail = Template.bind({})
HeaderDetail.args = {
  ...Content.args,
  header: 'Header',
  headerDetail: 'Header detail text',
}
```

If you need to leverage the complete story in a Jest test you can do so by following this article: https://storybook.js.org/docs/react/workflows/unit-testing

TLDR: 

```
it('renders the button in the primary state', () => {
  render(<HeaderDetail {...HeaderDetail.args} />);
  expect(screen.getByText('Header detail text');
});
```

Note the `{...HeaderDetail.args} ` that spreads the args onto the component is a key piece here.

2021-06-17 05:41 UTC, lukelooker commented on packages/components/src/__mocks__/DialogExampleLayout.tsx
> -      footer={
This story should be restored to the way it was before - the intention (in this example) is to have the two buttons both on the left-side and not to have anything in the  `secondary`  (left) position.

2021-06-17 17:23 UTC, laraharrow commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +Content.args = {}
the length option is not used anywhere as `long` so I didn't see the point of having it.

2021-06-17 17:24 UTC, laraharrow commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +  <Box bg="ui1">
yeah I totally see that I was going off a different example that was already there that had that in place. I'm happy to remove it.

2021-06-17 17:24 UTC, laraharrow commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +      }
oops yep, that totally make sense, my bad!

2021-06-17 17:28 UTC, laraharrow commented on packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.test.tsx
> -
I think this is done!

2021-06-17 17:31 UTC, laraharrow commented on packages/components/src/Dialog/Layout/DialogLayout.story.tsx
> +export const HeaderDetail = () => (
Why should we do this change?

2021-06-26 05:50 UTC, closed without merging