feat(PopoverLayout): new component for laying out for popover
looker-open-source/components pull request #2516
Opened 2021-06-17 19:31 UTC by laraharrow

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-06-21 20:19 UTC, lukelooker requested changes
Some small nits as well as I'd like the `PopoverLayout` stories to be written as CSF (Common Storybook Format) to make them consistent with `DialogLayout`

2021-06-21 20:19 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverFooter/PopoverFooter.story.tsx
> +      cancel
Would be nice to capitalize this so it matches `done`

```suggestion
      Cancel
```

2021-06-21 20:19 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverFooter/PopoverFooter.test.tsx
> +    expect(screen.getByText('cancel')).toBeInTheDocument()
```suggestion
    expect(screen.getByText('Cancel')).toBeInTheDocument()
```

2021-06-21 20:19 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverFooter/PopoverFooter.tsx
> +  align-items: center;
Why is this needed?

2021-06-21 20:19 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.story.tsx
> +  </Box>
Since these are brand new can we not include the `Box` here?
```suggestion
  <PopoverLayout header="Header Text" footer>
    <ConstitutionShort />
  </PopoverLayout>
```

2021-06-21 20:19 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.story.tsx
> +  </Box>
Oh , actually these should all be converted to CSF like `DialogLayout`

https://storybook.js.org/docs/react/api/csf

2021-06-21 20:19 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.tsx
> +  header?: never
Currently this excludes `header` entirely but we want to only support `string` if `hideHeading=true`

>  - `heading` must be a `string` if `hideHeading=true` (use type-union to enforce)

2021-06-21 20:19 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.tsx
> +type WithoutHeader = {
```suggestion
type WithHiddenHeader = {
```

2021-06-22 01:12 UTC, lukelooker requested changes
Few nits on code-style things (sorry, missed these on first pass) as well as a larger question about defaults in how things are presented.

Also, I'd like to see #2515 merged so I can see if there are any unexpected visual snapshot test changes.

2021-06-22 01:12 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.story.tsx
> +  headerCloseButton: true,
This composition shouldn't be possible. 

We don't want a case where users see both the "x" at the top and the "Done" at the bottom. I think just removing `headerCloseButton` support should prevent that possibility as specifying any `footer` should automatically force the `PopoverHeader` to remove the `x` icon

2021-06-22 01:12 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.story.tsx
> +  header: 'Header text',
```suggestion
  ...Header.args,
  footer: true,
```

2021-06-22 01:12 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.story.tsx
> +  hideHeading: true,
```suggestion
  ...Full.args,
  hideHeading: true,
```

2021-06-22 01:12 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.story.tsx
> +  header: 'Header text',
```suggestion
  ...header.Args,
  footer: extraButton,
```

2021-06-22 01:12 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.story.tsx
> +Basic.args = {}
The screenshot for this test indicates that the component defaults are off - there needs to be some way for the user to close the `Popover` - I think with this composition the `footer` should be displayed with a "Done" button to allow the user to close the `Popover`?

2021-06-22 01:12 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.story.tsx
> +}
I'm thinking that in this case the PopoverLayout should display the "x" in the header and no footer? 

![image](https://user-images.githubusercontent.com/34253496/122847018-e6554f80-d2bb-11eb-8382-4b3fe10e6f8d.png)

2021-06-22 01:12 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.story.tsx
> +Basic.args = {}
![image](https://user-images.githubusercontent.com/34253496/122847046-f4a36b80-d2bb-11eb-8d2d-e83830c714f0.png)

2021-06-22 15:03 UTC, laraharrow commented on packages/components/src/Popover/Layout/PopoverLayout.story.tsx
> +  footer: true,
I fix the logic to always have `PopoverFooter unless its specified `footer = false`

2021-06-22 15:30 UTC, laraharrow commented on packages/components/src/Popover/Layout/PopoverLayout.story.tsx
> +  headerCloseButton: true,
I kept `headerCloseButton` but made a type-union for `footer` and `headerCloseButton`.  I also added some logic into `PopoverHeader` to avoid adding the close button if `footer = true`.
That seems to have salved the issue.

2021-06-22 15:35 UTC, laraharrow commented on packages/components/src/Popover/Layout/PopoverLayout.story.tsx
> +  hideHeading: true,
on the `HeaderHideHeading` example if I don't add the header value explicitly: `header: 'Header text',` I get an error that says: 
```
Types of property 'header' are incompatible.
Type 'ReactNode' is not assignable to type '(string & (boolean | ReactChild | ReactFragment | ReactPortal | null)) | undefined'.
Type 'null' is not assignable to type '(string & (boolean | ReactChild | ReactFragment | ReactPortal | null)) | undefined'.
```

2021-06-22 15:37 UTC, laraharrow commented on packages/components/src/Popover/Layout/PopoverLayout.story.tsx
> +Basic.args = {}
I don't really understand what the exactly you need done here.

2021-06-22 15:58 UTC, laraharrow commented on packages/components/src/Popover/Layout/PopoverLayout.story.tsx
> +  hideHeading: true,
Types of property 'header' are incompatible.
Type 'ReactNode' is not assignable to type '(string & (boolean | ReactChild | ReactFragment | ReactPortal | null)) | undefined'.
Type 'null' is not assignable to type '(string & (boolean | ReactChild | ReactFragment | ReactPortal | null)) | undefined'.

2021-06-22 19:58 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.test.tsx
> +    expect(screen.queryByText('Header Text')).not.toBeInTheDocument()
The text should still be in the document (for screen-readers) but not visible - the `VisuallyHidden` should be doing this for us.

```suggestion
    expect(screen.queryByText('Header Text')).not.toBeVisible()
    expect(screen.queryByText('Header Text')).toBeIntheDocument()
```

2021-06-22 19:59 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.test.tsx
> +  test('Footer and no Header has no closing button', () => {
```suggestion
  test('With header & footer display only "Done" button', () => {
```

2021-06-23 22:35 UTC, laraharrow commented
I looked into the DialogLayout snapshots that got changed on the PopoverLayout PR.
I'm a bit confused about what happened there:
here is what I see that got pushed (and merged) from the DialogLayout PR:
export const Header = Template.bind({})
Header.args = {
  header: 'Header text',
}

export const Footer = Template.bind({})
Footer.args = {
  footer: 'Footer text',
}

export const Full = Template.bind({})
Full.args = {
  ...Footer.args,
  ...Header.args,
}

export const HeaderDetail = Template.bind({})
HeaderDetail.args = {
  ...Full.args,
  headerDetail: 'Cancel',
}

export const HeaderCloseButton = Template.bind({})
HeaderCloseButton.args = {
  ...Full.args,
  headerCloseButton: true,
}
My understanding is that all 5 stories would have the same header and footer values and those are: header: 'Header text' and footer: 'Footer text'.

...BUT...

Also on the `DialogLayout PR:

the snapshots for:
1. DialogLayout/Header Close Button the values are: header: 'Header' and footer: 'Footer.
2.DialogLayout/Header Detail the values are: header: 'Header' and footer: 'Footer.

on the other hand on the same PR the story referent to this code:
export const FooterSecondary = Template.bind({})
FooterSecondary.args = {
  ...Full.args,
  footerSecondary: 'Cancel',
}
exactly the same as the 2 above returns the snapshot of: header: 'Header' and footer: 'Footer

That is what I would expect for all of them. 
As a secondary issue, the same 2 problem snapshots: Header Close Button and Header Detail are yet again different then the expected after I updated it, now presenting as I would expect
1. DialogLayout/Header Close Button the values are: header: 'Header text' and footer: 'Footer text.
2.DialogLayout/Header Detail the values are: header: 'Header text' and footer: 'Footer text.

Sorry this is a long message. Not sure if it's clear.
What I did was update the snapshots on the PopoverLayout pr and the way that it is presented seems to make sense to me. I know its not idea to mix the 2 separated component work. So let me know what you think the best approach is for that

2021-06-24 09:06 UTC, lukelooker approved these changes
Ok - I'm not exactly sure how the `DialogLayout` examples passed previously but it appears that they match what's `main` should have (the copies in `main` appear to be slightly out-of-date. 

We do still need to connect with @jhardy about figuring out how to align the horizontal padding values for `PopoverContent` with the header and footer versions but I'm ok with doing that in a follow-up PR (I've created a ticket to track that fix)

2021-06-24 16:32 UTC, merged