refactor(ListItem): DO NOT MERGE, useListItemPartitions
looker-open-source/components pull request #2526
Opened 2021-06-22 23:38 UTC by ElliotTheHuman

# **DO NOT MERGE**
We are currently exploring ways to make more granular `ListItem` pieces available to other components like `Tree`. This is a quick attempt at that.

I put this PR up so that I can check to see if any image-snapshots break from these changes.

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-06-25 17:38 UTC, ElliotTheHuman commented
Hey @dbchristopher! Tagging you in this PR as well to try and get a reviewer that was further away from these changes. Cheers.

2021-06-25 21:33 UTC, lukelooker requested changes
Ok - overall this looks great!

Suggestions on how to clean-up the readability of the hook and one open question that I'd like to do via 1:1

2021-06-25 21:33 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +      icon: icon || (iconGutter ? <IconPlaceholder /> : undefined),
```suggestion
      icon: icon || (iconGutter && <IconPlaceholder />),
```

2021-06-25 21:33 UTC, lukelooker commented on packages/components/src/List/ListItemLabel.tsx
> +  ${(props) => listItemPadding({ ...props })}
I have questions... I think.

2021-06-25 21:33 UTC, lukelooker commented on packages/components/src/List/TruncateWrapper.tsx
> +  </Text>
I wonder if we should just admit defeat and support those props on `Truncate`?

2021-06-25 21:33 UTC, lukelooker commented on packages/components/src/List/utils/useListItemPartitions.tsx
> +  icon?: ReactNode
```suggestion
  icon?: IconType | ReactElement<IconPlaceholderProps>
```

2021-06-25 21:33 UTC, lukelooker commented on packages/components/src/List/utils/useListItemPartitions.tsx
> +  )
If the hook is too long to read easily why not extract these as functions unto themselves:

```suggestion
  const renderedIcon = generateIcon(...)
```

```
const generateIcon = (icon, color, disabled, dimensions) => icon ? (
    <ListItemIcon
      color={listItemIconColor(color, disabled)}
      disabled={disabled}
      iconGap={dimensions.iconGap}
      iconSize={dimensions.iconSize}
    >
      {icon}
    </ListItemIcon>
  ) : null

2021-06-25 21:33 UTC, lukelooker commented on packages/components/src/List/utils/useListItemPartitions.tsx
> +  )
Extract into function :)

2021-06-25 21:33 UTC, lukelooker commented on packages/components/src/List/utils/useListItemPartitions.tsx
> +      {renderedIcon}
Use extracted functions directly here:

```suggestion
      {generateIcon(icon, color, disabled, dimensions)}
```

2021-06-25 23:38 UTC, lukelooker commented on packages/components/src/List/TruncateWrapper.tsx
> +  </Text>
Working on this now.

2021-06-25 23:38 UTC, lukelooker commented on packages/components/src/List/ListItem.tsx
> +      icon: icon || (iconGutter ? <IconPlaceholder /> : undefined),
Nevermind. I'm wrong.

2021-06-28 18:57 UTC, ElliotTheHuman commented on packages/components/src/List/TruncateWrapper.tsx
> +  </Text>
🎉 🎉 🎉

2021-06-28 18:59 UTC, ElliotTheHuman commented on packages/components/src/List/utils/useListItemPartitions.tsx
> +  icon?: ReactNode
That's what I was looking for! Couldn't figure out the best way to do "React Component with X specific shape".

2021-06-29 21:27 UTC, closed without merging