feat(Accordion2): New improved & simpler accordion component
looker-open-source/components pull request #2527
Opened 2021-06-23 15:41 UTC by lukelooker

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-06-23 18:28 UTC, heyelic commented on packages/components/src/Accordion2/Accordion2.test.tsx
> +      <Accordion2 label="My Accordion Label">My Accordion Content</Accordion2>
Does it make sense to pull out `My Accordion Content` and `My Accordion Label` as constants to prevent multiple hardcoded strings?

2021-06-24 06:26 UTC, lukelooker commented
@heyelic For reasons I don't really grok Github doesn't want me to reply to your comment (I think underlying file changed and so it's no longer valid to respond?)

> Does it make sense to pull out My Accordion Content and My Accordion Label as constants to prevent multiple hardcoded strings?

Yes, it makes sense! (I just copied the `Accordion` test file across but that's a nice clean-up to turn those to variables used across the test suite. ✅

2021-06-25 19:16 UTC, lukelooker commented on packages/components/src/Tree/Tree.test.tsx
> +  xdescribe('aria roles', () => {
Need to leverage `useAccordion2` to resolve this. Follow-up PR to come.

2021-06-26 05:28 UTC, lukelooker commented on packages/components/src/Accordion2/Accordion2.test.tsx
> +      <Accordion2 label="My Accordion Label">My Accordion Content</Accordion2>
Yes, it makes sense!  ✅

(I just copied the Accordion test file across but that's a nice clean-up to turn those to variables used across the test).

2021-06-28 17:59 UTC, ElliotTheHuman requested changes
Overall looks good. There a few nits and questions I had, but nothing alarming.

2021-06-28 17:59 UTC, ElliotTheHuman commented on packages/components/src/Tree/Tree.tsx
> +      {...ariaProps}
I _think_ these `ariaProps` might need to live on the `AccordionDisclosure` when `labelToggle === false`. The inner `TreeItem` shouldn't be focusable in that case (I _think_).

To clarify, we'd just pass those into a `useAccordion2` call after we get around to refactoring `Tree` right?

2021-06-28 17:59 UTC, ElliotTheHuman commented on packages/components/src/Tree/Tree.tsx
> +  }
nit: Is there any harm with just putting `isOpen` and `toggleOpen` on `accordionProps` and making `accordionProps` a const? IIUC, `accordionProps` is passed to `Accordion2` (eventually `useAccordion2`) and if `Accordion2` will figure out what to do if those are undefined.

I only ask because it's just one less `if` statement to worry about in `Tree` 🤷

2021-06-28 17:59 UTC, ElliotTheHuman commented on packages/components/src/Tree/utils/indicatorDefaults.tsx
> +  Omit<AccordionIndicatorProps, 'disabled' | 'indicatorSize'>
We included `disabled` on `AccordionIndicatorProps` in preparation for `labelToggle` only, right?

2021-06-28 20:13 UTC, lukelooker commented on packages/components/src/Tree/Tree.tsx
> +      {...ariaProps}
Yep - I expect a fairly large restructuring of this code when we refactor with `useListItemPartition` & `useAccordion2`

2021-06-28 20:17 UTC, lukelooker commented on packages/components/src/Tree/Tree.tsx
> +  }
It's needed because the discriminated type union on `Accordion2` gets angry if it's _possible_ that only one of `isOpen` or `toggleOpen` is assigned.

`TreeItem2` will ideally have the same discriminated type union so that we won't have to have a "gate" like this to keep TS happy.

2021-06-28 20:23 UTC, lukelooker commented on packages/components/src/Tree/utils/indicatorDefaults.tsx
> +  Omit<AccordionIndicatorProps, 'disabled' | 'indicatorSize'>
Woops... This was actually a mis-step on my part. 

The `Accordion2` supports `disabled` and sets it's internal color based on that here: https://github.com/looker-open-source/components/pull/2527/files#diff-2cb2a0fda00b17d099d28146f5973ecd7ca09be2a9d56e169bf2226c2d2e3275R100

The `AccordionIndicator` just absorbs its color from the accordion itself so it doesn't need to be told about the `disabled` state.

2021-06-28 20:26 UTC, lukelooker commented on www/src/documentation/components/content/accordion.mdx
> +The `children` determines what content is hidden or shownby the accordion.
Fixed!

2021-06-28 20:26 UTC, lukelooker commented on packages/components/src/Accordion2/accordionDefaults.tsx
> +export interface AccordionDefaultProps {
Fixed!

2021-06-28 20:26 UTC, lukelooker commented on packages/components/src/Accordion2/Accordion2Disclosure.tsx
> +  width: 100%;
Fixed!

2021-06-28 20:26 UTC, lukelooker commented on packages/components/src/Accordion2/Accordion2.tsx
> + * interface as well as
Fixed!

2021-06-28 20:41 UTC, lukelooker commented
@ElliotTheHuman I think this is ready for re-review. Thanks!

2021-06-28 22:04 UTC, ElliotTheHuman approved these changes
:shipit:

2021-06-28 22:06 UTC, merged