fix(PopoverContent): update padding
looker-open-source/components pull request #2530
Opened 2021-06-24 21:57 UTC by laraharrow

- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-06-24 23:58 UTC, lukelooker requested changes
Can you add a Storybook / image snapshot for the "Custom padding" case. 

I'd like to have that to verify that the browser is acting as-intended in case some future refactor makes the CSS output different in a way the assertions below might miss.

2021-06-24 23:58 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverContent/PopoverContent.test.tsx
>        </PopoverContent>
Can you add a Storybook / image snapshot example of this as well. I'd like to have that to verify that the browser is acting as-intended in case some future refactor makes the CSS output different in a way the assertions below might miss.

2021-06-25 05:44 UTC, laraharrow commented on packages/components/src/Popover/Layout/PopoverContent/PopoverContent.test.tsx
>        </PopoverContent>
oh sorry about that I added the story but with the `snapshot { disable: true }` fixing it now.

2021-06-25 16:51 UTC, lukelooker approved these changes
Looks great! :)

2021-06-25 18:35 UTC, merged