Update Vis Components directory structure and package files
looker-open-source/components pull request #2543
Opened 2021-06-28 20:58 UTC by dbchristopher

- Add directory and build files for new vis-adapter package
- Run release scripts on package.json to reflect new non-circular dependency graph

2021-06-28 21:42 UTC, dbchristopher commented
@lukelooker here is the updated dependency graph that matches the changes in our internal repo

2021-06-30 17:27 UTC, dbchristopher commented
@lukelooker do you think this is worth merging for now just to resolve those build errors?

2021-07-02 17:31 UTC, mdodgelooker approved these changes
LGTM!

2021-07-02 17:31 UTC, mdodgelooker commented on packages/visualizations-nivo/package.json
> + },
I'm not familiar with how this is treated differently from `"private": true,` but trusting it's what we need for these packages. 🙂

2021-07-02 17:31 UTC, mdodgelooker commented on packages/visualizations-nivo/package.json
> + },
Side note, should this config be added to the "Facilitating Pre-Launch Packages" doc?

2021-07-02 17:35 UTC, lukelooker requested changes

2021-07-02 17:35 UTC, lukelooker commented on packages/visualizations-nivo/package.json
> + },
This is going to cause trouble with publishing all the other packages. Within the OSS repo we need to keep "private": true in place so we can not publish these.

2021-07-02 17:39 UTC, mdodgelooker commented on packages/visualizations-nivo/package.json
> + },
Oh good to know, thanks @lukelooker !

2021-07-02 17:40 UTC, lukelooker commented
I'm wondering if we should just pull all of these packages out of the OSS repo for right now? It seems like keeping all of that within a `launch-vis` branch in the prerelease repo would leave this more "self-serve" for now and reduce the number of "hops" needed to make an update.

2021-07-02 21:36 UTC, dbchristopher commented on packages/visualizations-nivo/package.json
> + },
oh thanks for flagging that! I think I misunderstood some feedback from a previous PR

2021-07-02 21:46 UTC, dbchristopher commented
Closing in favor of #2570

2021-07-02 21:46 UTC, closed without merging