feat(Popover): updated aria-labelledby and role for A11Y
looker-open-source/components pull request #2544
Opened 2021-06-28 22:00 UTC by laraharrow

- [ ] ♿️ Accessibility addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-06-28 22:40 UTC, lukelooker requested changes
Added inline comments about the missing pieces here.

- [x] Needs Storybook example that shows the full composition of `Popover` + `PopoverLayout`
- [x] Needs test coverage: Visible Header
- [x] Needs test coverage: Hidden Header

### Rough test steps:

1. Open Popover w/ PopoverLayout
2. getByRole('dialog') 
3. get `aria-labelledby` attribute
3. Verify that element with `id` = `aria-labelledby` exists and matches expected text

2021-06-28 22:40 UTC, lukelooker commented on packages/components/src/Dialog/useDialog.tsx
> +          role="dialog"
This is not needed. It's pushed in by `...surfaceProps` below.

2021-06-28 22:40 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverHeader/PopoverHeader.tsx
> +  headerVisuallyHidden?: boolean
Given that this is in the context of `PopoverHeader` already this could be shortened a good bit.

```suggestion
  hidden?: boolean
```

Make sure to add a JSDoc explaining the use-case.

2021-06-28 22:40 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverHeader/PopoverHeader.tsx
> +  ) : (
```suggestion
  return hidden ? (
    <VisuallyHidden id={headingId}>{children}</VisuallyHidden>
  ) : (
```

2021-06-28 22:40 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverHeader/PopoverHeader.tsx
> +  const headingId = dialogId || undefined
The `heading` needs to have `-heading` prepended to it so that the `labelledby` on the "surface" can target it.

```suggestion
    const { id } = useContext(DialogContext)
    const headingId = id ? `${id}-heading` : undefined

```

2021-06-28 22:40 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.tsx
> +
```suggestion

```

2021-06-28 22:40 UTC, lukelooker commented on packages/components/src/Popover/Layout/PopoverLayout.tsx
> +      {header && popoverHeader}
```suggestion
      {header && (
        <PopoverHeader hidden={hideHeader} hideClose={!!footer}>
          {header}
        </PopoverHeader>
      )}
```

2021-06-28 22:40 UTC, lukelooker commented on packages/components/src/Popover/usePopover.tsx
> +          aria-labelledby={dialogId}
```suggestion
          aria-labelledby={`${dialogId}-heading`}
```

2021-06-29 22:23 UTC, lukelooker approved these changes
A few small nits on test and ancillary clean-ups than I think this should be good-to-go.

2021-06-29 22:23 UTC, lukelooker commented on packages/components/src/Popover/Popover.test.tsx
> +    )
We want to verify that the id specified in `aria-labelledby` exists.

```suggestion
    )
    expect(screen.getByText('Header text')).toHaveAttribute('id', 'a11y-heading')
```

2021-06-29 22:23 UTC, lukelooker commented on packages/components/src/Popover/usePopover.tsx
> +            aria-labelledby={`${dialogId}-heading`}
The `dialog` usage here is making me :eye-twitch:

Can you change the spot where we instanient this to:

```
  id = useID(id)
```

And then the various spots using it can go from ~`dialogId`~ to just `id` (I'm guessing it was my bad choice when copying things around from `dialog` but it'd be nice to get this rationalized since it's getting tweaked here anyway.

2021-06-29 22:23 UTC, lukelooker commented on packages/components/src/Popover/usePopover.tsx
> +            data-testid="content-container"
This is used in exactly one spot `Select.test.tsx` - can you remove it and then update the test there to use `selectByRole('dialog')` instead of ~`selectByTestId('content-container')`~

```suggestion
```

2021-06-29 22:23 UTC, lukelooker requested changes
A few small nits on test and ancillary clean-ups than I think this should be good-to-go.

2021-06-29 23:50 UTC, laraharrow commented on packages/components/src/Popover/usePopover.tsx
> +            aria-labelledby={`${dialogId}-heading`}
hey @lukelooker I agree with the change of dialogId into something else. But it can't be id it will have a conflict with the prop id
how about something like a11yId?
not sure I'm really bad at naming things

2021-06-30 00:01 UTC, lukelooker commented on packages/components/src/Popover/usePopover.tsx
> +  const popoverId = useID(id)
```suggestion
 id = useID(id)
```

2021-06-30 21:31 UTC, lukelooker approved these changes
Awesome-sauce! This looks great! :)

2021-07-01 14:12 UTC, merged