feat(PopoverLayout): create documentation for component
looker-open-source/components pull request #2547
Opened 2021-06-29 22:32 UTC by laraharrow

- [ ] 📚 Documentation updated

2021-06-30 16:09 UTC, lukelooker requested changes
PopoverHeader, PopoverContent & PopoverFooter should each have their own separate mdx files (see Dialog equivalents)

Added some inline comments as well

2021-06-30 16:09 UTC, lukelooker commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +`PopoverLayout` is a container that has:
I'd take a look at `DialogLayout` for an example of the docs here:

```suggestion
The `PopoverLayout` component manages the popover layout components below to easily meet design-system expectations.

This component composes `PopoverHeader`, `PopoverContent` and `PopverFooter` as needed.
```

2021-06-30 16:09 UTC, lukelooker commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +`Header`: can be used as a label, scrolling inside a popover and with the ability to hava a close button. By default `Header` will display the closing button if `Fooret` is set to false.
`PopoverHeader`, `PopoverContent` & `PopoverFooter` should each have their own separate `mdx` files (see `Dialog` equivalents)

This section should get moved to `PopoverHeader` and so and so forth for the other sections.

```suggestion
`Header` can be used as a label, scrolling inside a popover and with the ability to have a a close button. By default `Header` will display the closing button if `Footer` is set to false.
```

2021-06-30 16:09 UTC, lukelooker commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +</PopoverLayout>
I think the "Basic" example should probably show with a visible header as that's the recommended pratice.

```suggestion
<PopoverLayout header="Example Popover">
  PopoverLayout content
</PopoverLayout>
```

2021-06-30 16:09 UTC, lukelooker commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +
This needs an explanation... e.g.: "Use the `hidden` prop to hide the visible header text but still provide context for screen readers"

2021-06-30 16:09 UTC, lukelooker commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +## PopoverLayout Footer extra content
Need to explain that `Done` is included by default and how to change the word "Done" to something else.

2021-06-30 18:49 UTC, laraharrow commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +## PopoverLayout Footer extra content
we actually don't have this as an option right now. As of now you can only pass `footer` and that is a `ReactNode` so we are not specifying the close prop on `PopoverLayout` that may have to be an extra ticket if that should be included.

2021-06-30 19:03 UTC, lukelooker commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +## PopoverLayout Footer extra content
🤦 . Yeah we should make that possible.

2021-06-30 19:24 UTC, lukelooker commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +## PopoverLayout Footer extra content
PR at #2557

2021-07-01 00:18 UTC, mdodgelooker requested changes
Very thorough! Got some suggestions here and there. 🙂

2021-07-01 00:18 UTC, mdodgelooker commented on www/src/documentation/components/overlays/popovercontent.mdx
> +storybookPath: PopoverContent
This needs a github path since it doesn't match the `src/[Name]/[Name].tsx` pattern. Also when you remove the space in the title, the `storybookPath` is unnecessary.
```suggestion
title: PopoverContent
github: components/src/Popover/PopoverContent.tsx
storybook: true
```

2021-07-01 00:18 UTC, mdodgelooker commented on www/src/documentation/components/overlays/popoverfooter.mdx
> +storybookPath: PopoverFooter
```suggestion
title: PopoverFooter
github: components/src/Popover/PopoverFooter.tsx
storybook: true
```

2021-07-01 00:18 UTC, mdodgelooker commented on www/src/documentation/components/overlays/popoverheader.mdx
> +storybookPath: PopoverHeader
```suggestion
title: PopoverHeader
github: components/src/Popover/PopoverHeader.tsx
storybook: true
```

2021-07-01 00:18 UTC, mdodgelooker commented on www/src/documentation/components/overlays/popoverheader.mdx
> +`PopoverHeader` can be attached to the top of Popover and provides a button to close the containing Popover. Uses the `PopoverContext` to get access to the `close` callback.
I would say either remove the 2nd sentence since it might be too much info for normal usage. Or if you'd like to keep it, `close` should be `closeModal`.

2021-07-01 00:18 UTC, mdodgelooker commented on www/src/documentation/components/overlays/popoverheader.mdx
> +- `hideClose` property remove the "close" `IconButton`
```suggestion
- `hideClose` removes the "close" `IconButton`
```

2021-07-01 00:18 UTC, mdodgelooker commented on www/src/documentation/components/overlays/popoverheader.mdx
> +- `detail` property allows the developer to specify a ReactNode that will replace the "close" `IconButton`
```suggestion
- `detail` allows the developer to specify a ReactNode that will replace the "close" `IconButton`
```

2021-07-01 00:18 UTC, mdodgelooker commented on www/src/documentation/components/overlays/popoverheader.mdx
> +NOTE: don't use `hideClose` and `detail. together
```suggestion
NOTE: don't use `hideClose` and `detail` together
```

2021-07-01 00:18 UTC, mdodgelooker commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +title: PopoverLayout
Add github path:
```
github: components/src/Popover/PopoverLayout.tsx
```

2021-07-01 00:18 UTC, mdodgelooker commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +`Header` will display the closing button if `Footer` is set to false.
```suggestion
`PopoverHeader` will display the closing button if `footer` is set to false.
```

2021-07-01 00:18 UTC, mdodgelooker commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +`Footer`: By default `Footer` will dispaly the work `Done` but that value can be changed to another string or component.
```suggestion
By default `PopoverFooter` will contain a dismissal button with the text "Done", but that value can be changed to another string or component.
```

2021-07-01 00:18 UTC, mdodgelooker commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +## Basic PopoverLayout
I think this header is unnecessary.
```suggestion
```

2021-07-01 00:18 UTC, mdodgelooker commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +## PopoverLayout Header hidden
```suggestion
## Header hidden
```

2021-07-01 00:18 UTC, mdodgelooker commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +## PopoverLayout Footer extra content
```suggestion
## Footer extra content
```

2021-07-01 00:18 UTC, mdodgelooker commented on www/src/documentation/components/overlays/popoverlayout.mdx
> +## PopoverLayout no Footer
```suggestion
## No footer
```

2021-07-01 20:30 UTC, mdodgelooker commented
I think you forgot to push changes?

But I also noticed a couple more things:
1. Can you update `popover.mdx` to use `PopoverLayout` instead of `PopoverContent`
2. The header close button isn't aligning properly inside `Popover` (I got this screenshot by updating `PopoverLayout.tsx` to wrap the template in a `Popover`):
![image](https://user-images.githubusercontent.com/53451193/124185960-7b043e00-da70-11eb-9292-e04c27fe94b9.png)

2021-07-01 21:48 UTC, laraharrow commented
Hey Meredith, sorry i didn't push the changes earlier. Here it is. I didn't see the error you were seeing in `header` on popover.

2021-07-02 16:45 UTC, mdodgelooker submitted a review, later dismissed
I filed a separate ticket for the close button alignment since it's not really related to docs: https://b.corp.google.com/issues/192662704

But I think `popover.mdx` should be updated with `PopoverLayout` replacing `PopoverContent` before this PR ships.

Everything else looks great!

2021-07-02 20:40 UTC, lukelooker approved these changes
LGTM

2021-07-02 21:49 UTC, merged