fix(Panel): Avoid focusing elements underneath
looker-open-source/components pull request #2611
Opened 2021-07-15 21:27 UTC by mdodgelooker

## 👋👋 Thank you for contributing to Looker Components (⚡️🍣)

📺 Watch a quick video on how to you make your pull requests fast and easy for you and your reviewer(s):
https://threadit.app/thread/k45nyrqugoinw6xub9vf/message/fl8m57exhqg4r0a4hg01eebn

- 👆 Make sure your pull request title follows [Pull Request Title Guidelines](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#title-guidelines) from our [Contribution guide](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md)
- 👉 Don't forget to replace these instructions with your _✨awesome✨_ description of what this change _actually does_. Additionally it's great to include context on how it works and why the change was needed.
- 👇 Edit "Developer Checklist" to reflect items relevant to this PR (and try to make sure to check everything off before asking for review)

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-07-19 18:56 UTC, mdodgelooker reviewed
@lukelooker here's my idea for the focus issue with `Panel`. Let me know if you think it's on the right track.

2021-07-19 18:56 UTC, mdodgelooker commented on packages/components/src/Panel/Panel.story.tsx
> +      <Button>Before</Button>
Adding a couple focusable elements to test the flow.

2021-07-19 18:56 UTC, mdodgelooker commented on packages/components/src/Panel/Panels.tsx
> +import { CompatibleHTMLProps } from '@looker/design-tokens'
The basic gist of the changes in this file are:
1. When focus lands inside `Panels`, check if it's in the panel, if there is one (or the top panel if there are multiple).
2. If it's not, we can't let focus stay there, because nothing else inside `Panels` would be visible. So we bump focus to:
    a. The (top) panel itself, unless focus was previously inside that panel, in which case move it to:
    b. The first tabbable element before or after `Panels`, depending on where it landed relative to the panel

2021-07-19 18:56 UTC, mdodgelooker commented on packages/components/src/Panel/usePanel.tsx
> +  }, [])
This is very unsophisticated. At the very least we should move focus from the button that opened the panel onto something inside the panel, but probably not to the close icon button – so this just focuses the panel itself.

To improve the UX, we could implement something similar to what `useFocusTrap` does, where it picks what to focus by priority – first any input, then any footer button, then the 1st focusable element, then the surface itself.

2021-07-19 18:56 UTC, mdodgelooker commented on packages/components/src/Panel/usePanel.tsx
> +        tabIndex={-1}
Without this, there's a bug when used inside a `List` where if you click somewhere inside the panel but not specifically on a focusable element, focus lands on the `List` and the focus handler from `useKeyboardNav` battles with that in `Panels`, creating an infinite loop.

Also, it provides a "fallback" focusable element other than the close button (see comment above).

2021-07-19 18:56 UTC, mdodgelooker commented on packages/components/src/Panel/usePanel.tsx
> +        data-panel
This is here so that `Panels` can find all its children panels. My first thought was to use an aria role, but the closest I could find was `tabpanel`, which isn't quite right... is it?

2021-07-22 15:07 UTC, lukelooker requested changes
Sorry for the delay getting feedback to you on this! Anyway...

It's funny how hard it is to keep tabs off of things :)

I really wish there was a way to make this "just work" via DOM and/or removing elements but I still haven't come up with anything that works well / doesn't get more complicated than what you've got here. 

Overall this seems the best bet to move forward – the implementation makes sense to me and reads clearly. 

- [ ] I think adding inline comments similar to your PR comment regarding changes would be good to make sure future developers have good context on what's going on and the intent.
- [ ] Needs some test coverage to validate that it suppresses things as expected
- [ ] Does this suppress screen-readers successfully too – I know they can be uniquely aggressive about finding DOM targets at times but sometimes don't seem to trigger "real" focus events)

2021-07-22 15:07 UTC, lukelooker commented on packages/components/src/Panel/Panels.tsx
> +export const Panels = styled(PanelsInternal)`
Minor nit - I've been moving to wrapping the `*Internal` components inside the `styled` block unless there's a case where the `styled` needs to get props "back" from the React component:

```export const Panels = styled(props) => {
  /* do react stuff here */
})`
  height: 100%;
  position: relative;
  width: 100%;
`

2021-07-22 18:34 UTC, mdodgelooker commented
@lukelooker thanks for the feedback! Navigating via screenreader is definitely still an issue: VoiceOver ctrl+option+left-arrow can get you into the hidden content underneath an open panel. I'm hoping that some combination of aria & role can help with that. 🤞 

Do you think that this PR should tackle "smart" initial focus on opening a `Panel`, similar to what focus trap now does? Or just focus the panel surface for now and add improvements in a future PR?

2021-07-22 19:17 UTC, mdodgelooker commented
Actually I'm gonna explore putting `visibility: hidden' on `Panels` and then `visibility: visible` on the active `Panel`. Oddly that works (visually) – we'll see what it does for tab nav and screenreaders.

2021-07-23 15:13 UTC, mdodgelooker commented
@lukelooker I think the `visibility: hidden` on `Panels` and overridden with `visibility: visible` on the topmost `Panel` will do the trick. The only challenge is making sure that _only_ the topmost `Panel` has `visibility: visible`, which is a very similar problem to focus trap and scroll lock. So I'm using the `TrapStack` infrastructure here, which sounds a little funny, because we're not really trapping anything. I could rename it to something even more generic...

Still working on the test.

2021-07-23 15:18 UTC, lukelooker commented on packages/components/src/Panel/Panels.tsx
> +    <TrapStackProvider activate={activatePanel} context={PanelsContext}>
This does feel _way_ better :)

I don't mind `TrapStack` here since we're "trapping" the visibility using a stack :)

2021-07-23 15:39 UTC, lukelooker commented on packages/components/src/Panel/usePanel.tsx
> +        data-panel
Yeah  reading up on `tabpanel` it doesn't seem quite right for this. I'm cool with your solve here.

2021-07-23 23:03 UTC, mdodgelooker commented on packages/components/src/Panel/usePanel.tsx
> +        tabIndex={-1}
The first paragraph is no longer relevant after switching to the `visibility` strategy, but the 2nd still is.

2021-07-23 23:03 UTC, mdodgelooker commented on packages/components/src/utils/useAnimationState.ts
> +  className: 'entering' | 'entered' | 'exiting' | 'exited'
Felt like this needed a bit more type safety.

2021-08-03 23:39 UTC, mdodgelooker commented
@lukelooker ready for re-review when you've got time. 🙂

2021-08-04 21:39 UTC, lukelooker approved these changes
Works great!

2021-08-05 16:55 UTC, merged