fix(DataTable): Make first column sortable again
looker-open-source/components pull request #2638
Opened 2021-07-22 20:33 UTC by lukelooker

2021-07-22 22:17 UTC, ElliotTheHuman requested changes
There's a minor "bug" where vanilla `id` doesn't get passed down to `DataTableHeaderCell`'s actual DOM element. Whether we want to do that (or not) though is up to you!

2021-07-22 22:17 UTC, ElliotTheHuman commented on packages/components/src/DataTable/Header/DataTableHeaderCell.tsx
>        type,
Vanilla `id` currently isn't being passed down to the DOM element so we'll need to add that prop assignment to the `FocusableCell` element below (I _think_)

2021-07-22 22:17 UTC, ElliotTheHuman commented on packages/components/src/DataTable/Header/DataTableHeaderCell.tsx
>        type,
Fixing this, though, will mean that the first header cell will receive the `{ id: `rowheader-${id}`, role: 'rowheader' }` from the `cloneElement` call in `DataTableRow.tsx`.

I think it makes sense to add an additional condition on `DataTableRow.tsx > Line 82` using the `isHeaderRow` prop, like this:
![Screen Shot 2021-07-22 at 3 14 00 PM](https://user-images.githubusercontent.com/16812885/126716135-b6a16635-12ed-410e-b41d-5f7b2665f52c.png)

2021-07-22 22:17 UTC, ElliotTheHuman commented on packages/components/src/DataTable/Header/DataTableHeaderCell.tsx
>        type,
Alternatively, we can just remove vanilla `id` as a prop on `DataTableHeaderCell` but I'm unsure of whether that's a problem or not 🤷 . Considering it isn't being passed down to the DOM element on `main` this seems like a reasonable option instead of the changes listed above.

2021-07-23 16:30 UTC, lukelooker commented on packages/components/src/DataTable/Header/DataTableHeaderCell.tsx
>        type,
It's actually completely fine to just remove support for `id` altogether (there's no need to attach the "Select All" checkbox to a cell as it leverages `aria-label` for it's label.

2021-07-23 17:00 UTC, dbchristopher submitted a review, later dismissed
This looks good! I was a little bit thrown off at first because I saw the `canSort` attribute, but then noticed other stories toggling this behavior using the `sort` property:

<img width="688" alt="Screen Shot 2021-07-23 at 9 57 05 AM" src="https://user-images.githubusercontent.com/238293/126816116-2c38ae04-1139-4844-8de5-110c6ff1709d.png">

After a bit of digging I saw that `sort` was just specific to the Template component used for those stories. Not sure if we care to have those storybook controls match up with the real prop names exactly or not 🤷‍♂️  If so it would be a quick update!

2021-07-23 17:38 UTC, lukelooker commented
@dbchristopher Renamed `sort` to `canSort` in story example prop.

2021-07-23 17:49 UTC, dbchristopher approved these changes

2021-07-23 18:24 UTC, merged