First pass at density documentation
looker-open-source/components pull request #2647
Opened 2021-07-23 22:35 UTC by jhardy

First iteration around documenting our current density scale

![image](https://user-images.githubusercontent.com/170681/126847605-4ece15a9-ee3f-44d9-9765-d8ef984f85a4.png)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-07-23 22:35 UTC, jhardy commented on www/src/Layout/Default.tsx
> +      <Heading as="h1" fontSize="xxxxlarge" mb="xlarge">
Added some default margin here to give a bit more spacing on `<h1>`s

2021-07-23 22:36 UTC, jhardy commented on www/src/documentation/foundations/demos/RadiusList.tsx
> +        <TableRow>
Small change here just to resolve console error around incorrect nesting of `<th>`s inside a `<thead>`

2021-07-23 22:38 UTC, jhardy commented on www/src/documentation/foundations/color.mdx
> -<p>&nbsp;</p>
removing this now that `<h1>` has some default bottom margin

2021-08-05 19:52 UTC, lukelooker requested changes
I pushed a commit with a few minor code structure changes and I added one comment regarding the documentation itself.

Pushing this through as a "request changes" so my change is visible, then I'll merge the suggestion and approve. If you're happy with the changes feel free to merge as-is

2021-08-05 19:52 UTC, lukelooker commented on www/src/documentation/foundations/density.mdx
> +In general Looker Components that support density adjustments start at a medium density and offer the ability to increase or decrease density depending on the context and needs of the experience.
I went back and forth on the "right" way to describe density (because the numbers confuse me when paired with "increase" and "decrease" - that said, I think what you landed on is correct and adding some in-context examples reinforces things well.

```suggestion
In general Looker Components that support density adjustments start at a medium density (e.g.: `0`) and offer the ability to increase (e.g.: '-1, -2. -3`) or decrease (e.g.: `1`) density depending on the context and needs of the experience.
```

2021-08-05 19:53 UTC, lukelooker approved these changes
LGTM

2021-08-09 22:23 UTC, merged