Lara/tab2
looker-open-source/components pull request #2659
Opened 2021-07-29 19:53 UTC by laraharrow

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-08-09 23:57 UTC, lukelooker requested changes
Noted a few items inline as well as:

- [ ] Active tab doesn't show the "key" border at the bottom.
- [ ] Screenshot tests indicate that screenshots are out of date.

2021-08-09 23:57 UTC, lukelooker commented on packages/components/src/Tabs2/Tabs2.test.tsx
> +test('clicking on disable tab does not change panel', () => {
```suggestion
test('clicking on disabled tab does not change panel', () => {
```

2021-08-09 23:57 UTC, lukelooker commented on packages/components/src/Tabs2/Tabs2.tsx
> +export const Tab2: FC<Tab2Props> = ({ children }) => <>{children}</>
Represents a separate component so it should be in a separate file.

2021-08-10 00:00 UTC, lukelooker commented on packages/components/src/Tabs2/Tabs2.test.tsx
> +})
It'd be good to add a "controlled" example of `Tabs2` to make sure we have coverage of that use case within the test suite.

2021-08-11 23:28 UTC, closed without merging

2021-08-11 23:28 UTC, laraharrow commented
snapshot issue