draft(Spacing Values): Create new spacing tokens to represent new design system values
looker-open-source/components pull request #2661
Opened 2021-07-30 20:41 UTC by jhardy

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-07-30 20:42 UTC, jhardy commented on packages/design-tokens/src/system/space.ts
> +  | 'size16'
Interested in your opinion here @lukelooker, I've gone back and forth on naming a few times, but I feel like this is something memorable as well as not too different from our t-shirt sizing concept.

2021-07-30 20:43 UTC, jhardy commented on packages/design-tokens/src/theme/theme.ts
> +  spacing,
adding the new tokens under `spacing` instead of `space` so we can deprecate the old tokens.

2021-08-06 23:35 UTC, lukelooker commented on packages/design-tokens/src/system/space.ts
> +  | 'size16'
For some reason the idea of introducing `size` here raises my hackles a bit – I think perhaps the collision with the idea of `iconSize` and such?

What do you think of referencing `u` (for unit)? I guess I think the predicate here should be as diminutive as possible to encourage scannability of the difference value (`0.5`, `1`, `2`, etc...)

```
`u0.5`,
`u1`,
`u2`,
`u3`,
```

```
<Paragraph mb="size4" mt="size2">...
```
vs.
```
<Paragraph mb="u4" mt="u2">...
```

2021-08-09 18:02 UTC, lukelooker requested changes
Arg! I forgot to "Send" my review

2021-08-10 04:13 UTC, lukelooker approved these changes
LGTM

2021-08-10 04:13 UTC, merged