feat(NavTree): Added indicator toggle only behavior
looker-open-source/components pull request #2676
Opened 2021-08-02 18:21 UTC by ElliotTheHuman

- Isolated accordion toggle behavior in `NavTree` to only the indicator
- Unrelated: Added 8px of spacing to the `Nav` component suite "indent" (note: `NavTree` gets its additional 8px by adding padding to the indicator for a larger click target)
  - This was added to satisfy a feature request regarding larger indicator click targets for top-level `NavTree`s 

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-08-02 18:23 UTC, ElliotTheHuman commented on packages/components/src/NavTree/NavTree.tsx
> +  })
This is how we get the toggle behavior (and `tabIndex = -1`) onto the `AccordionIndicator` div since that isn't exposed to `useAccordion2` callers. 

Wondering if we should just find a way to do this within `useAccordion2` itself via an `indicatorToggleOnly` prop, but the `cloneElement` seemed like the least complicated solution.

2021-08-02 18:24 UTC, ElliotTheHuman commented on packages/components/src/NavList/NavList.tsx
> +      }};
I know I could just use `theme.sizes.large` or a combination of `theme.space.X`s to get the `2rem` I need, but I figure since `INDICATOR_SPACER` might need to be changed more than once based on DiscoNav feedback, it's better to just tie all our overrides to it.

2021-08-03 16:22 UTC, lukelooker requested changes
Can we split this into two PRs - with Jared OOO this week I'd prefer to ship the "label toggle" behavior sooner and then have the spacing / sizing conversation as a separate,  narrower conversation.

2021-08-03 16:44 UTC, ElliotTheHuman commented
Indicator spacing changes reverted in fea9b0a

2021-08-04 22:35 UTC, lukelooker reviewed
Early thoughts commented on here - would like to discuss how we can narrow `NavTree` some.

2021-08-04 22:35 UTC, lukelooker commented on packages/components/src/NavTree/NavTree.test.tsx
> +  test('Does not change accordion open state on label click', () => {
I think the implementation (and the test title/behavior by way of that) is slightly incorrect – the `ParentIcon` story doesn't have a link/onClick and therefore clicking the label _should_ open and close the underlying accordion.

2021-08-04 22:35 UTC, lukelooker commented on packages/components/src/NavTree/NavTree.test.tsx
> +  test('Does not change accordion open state on label click', () => {
I think a test for the `Link` example with a very similar test should be added however.

2021-08-04 22:35 UTC, lukelooker commented on packages/components/src/NavTree/NavTree.tsx
> +                )}
`NavTree` probably doesn't need this variant?

2021-08-04 22:35 UTC, lukelooker commented on packages/components/src/NavTree/NavTree.tsx
> +  itemRole = 'none', // By default, Tree's content container should be a 'div'
Can we trim `NavTree` back to a more minimal implementation removing things like `itemRole`?

2021-08-04 23:46 UTC, ElliotTheHuman commented
Next steps:
- Make label toggle behavior conditional based on if an `href` is passed in or not
- Tear out unused pieces like `labelBackgroundOnly` and `itemRole` weirdness
- Fix keyboard nav

2021-08-06 18:56 UTC, lukelooker commented on packages/components/src/NavTree/NavTree.tsx
> +  })
Dupe from `Tree`

2021-08-06 18:56 UTC, lukelooker commented on packages/components/src/NavTree/NavTree.tsx
> +    density: propsDensity,
Not sure we should support `density` on `NavTree`

2021-08-06 18:56 UTC, lukelooker commented on packages/components/src/NavTree/NavTree.tsx
> +  }
Extract to util

2021-08-06 18:57 UTC, lukelooker submitted a review, later dismissed

2021-08-06 19:53 UTC, lukelooker approved these changes
💥  Dope, ship it.

2021-08-06 20:22 UTC, merged