feat(Tabs2): Tabs with improved interface
looker-open-source/components pull request #2726
Opened 2021-08-11 23:29 UTC by laraharrow

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-08-12 19:41 UTC, lukelooker requested changes
- [x] Mark `Tab` & `Tabs` as `@deprecated` (see `Accordion`)
- [x] Update `tabs.mdx` to use `Tabs2`

2021-08-12 19:41 UTC, lukelooker commented on packages/components/src/Tabs2/TabList2.tsx
> +`
These should be exported and then imported into `TabList`

2021-08-12 19:41 UTC, lukelooker commented on packages/components/src/Tabs2/TabList2.tsx
> +  ${({ distribute }) => (distribute ? distributeCSS : defaultLayoutCSS)}
Shared this block between here an "Tab1"

2021-08-12 19:41 UTC, lukelooker commented on packages/components/src/Tabs2/TabList2.tsx
> +TabList2Layout.displayName = 'TabList2Layout'
Collapse this "into" `TabList`

2021-08-12 19:41 UTC, lukelooker commented on packages/components/src/Tabs2/TabList2.tsx
> +}
Make this a `type`

2021-08-12 19:41 UTC, lukelooker commented on packages/components/src/Tabs2/Tabs2.tsx
> +  const currentTab = tabs.find((tab) => tab.id === tabId)
Explain all the magic here-in

2021-08-12 19:41 UTC, lukelooker commented on packages/components/src/Tabs2/types.ts
> +    selected?: boolean
Add JSDoc

2021-08-12 19:41 UTC, lukelooker commented on packages/components/src/Tabs2/Tabs2.tsx
> +export const Tabs2 = ({
Add `JSDoc` explanation of `Tabs2`

2021-08-12 20:50 UTC, laraharrow commented on packages/components/src/Tabs/Tab.tsx
> +export const Tab = styled(
We are updating the file to use `Tab2` instead.
`Tab` will be deprecated and this file will eventually be removed so some of the code got removed from here and added to the new version `Tab2`.

2021-08-12 21:21 UTC, laraharrow commented on packages/components/src/Tabs2/TabList2.tsx
> +`
moving the style to `TabList` creates the same breaking that we were getting with having `Tab2Style` in a separated file. Basically somehow passing css style between the components is breaking the style.

2021-08-12 21:42 UTC, laraharrow commented on packages/components/src/Tabs2/TabList2.tsx
> +  ${({ distribute }) => (distribute ? distributeCSS : defaultLayoutCSS)}
read comment above.

2021-08-12 23:06 UTC, laraharrow commented on packages/components/src/Tabs/TabList.tsx
> +import { TabList2CSS } from '../Tabs2'
Adding the style via import is breaking the component.

2021-08-12 23:07 UTC, laraharrow commented on packages/components/src/Tabs2/Tabs2.test.tsx
> +import { Controlled } from './Tabs2.story'
seems like the * as stories doesn't import the stories that are not set as Template so I had to import the controlled version separated.

2021-08-12 23:09 UTC, laraharrow commented on packages/components/src/Tabs2/Tabs2.tsx
> +        draftTabs[draftTabs.findIndex((tab) => !tab.disabled === true)].id
I added a little bit of new logic to the setting of the `Tab` to take in account if the `draftTabs[0]` is set as disabled

2021-08-12 23:09 UTC, laraharrow commented on packages/components/src/Tabs2/index.ts
> +export { TabList2CSS } from './TabList2'
this may not be necessary?

2021-08-13 00:36 UTC, laraharrow commented on packages/components/src/Tabs/TabList.tsx
>  const defaultLayoutCSS = css`
check comment bellow on why the style is not imported from `TabList2`

2021-08-13 00:43 UTC, laraharrow commented on www/src/documentation/components/content/tabs.mdx
> -## Keyboard Navigation
I was going to update the code so the new `Tabs2` component has better relationship between `active` and `focus` but as I looked into the [figma](https://www.figma.com/file/zd6MjUXIIstvG7gTJWaX2Y/Looker-Components?node-id=6740%3A0) file, looks like we will soon be doing updates to this component based on the GM2 roadmap. So I held off on that so the work can be done on a separated PR.

2021-08-13 15:44 UTC, laraharrow commented
There is a problem with the snapshots. After making the changes to the area content of the `Tab` the snapshots seem to not be matching anymore but this is the first time we are logging them so I can't even see the diff other then on the `image snapshots` tab I see that the height dimensions are smaller then before and that as I understand is what we want.

2021-08-13 16:00 UTC, laraharrow commented
We are a-ok on test coverage:
![Screen Shot 2021-08-13 at 8 59 25 AM](https://user-images.githubusercontent.com/23616264/129386941-b9d5d52e-2ac0-4d21-a89c-5cf2494da1b2.png)

2021-08-13 17:14 UTC, lukelooker requested changes

2021-08-13 17:14 UTC, lukelooker commented on www/src/documentation/components/content/tabs.mdx
> +`<Tabs2>` expects to receive one or more `Tab2` components. `Tabs2` manages the visibility of the single `content` based on its internal `Tab2` content.
```suggestion
`Tabs2` contains one or more `Tab2` components. `Tabs2`, when left uncontrolled, manages the visible tab as well as switching between tabs.
```

2021-08-13 17:14 UTC, lukelooker commented on www/src/documentation/components/content/tabs.mdx
> +`Tab2` expects to have `label` that will be the value displayed on the `Tab` itself. The value passed as children will be displayed as its content area.
```suggestion
Each `Tab2` must have a `label`. The value passed as children will be displayed as its content area. `id` is optional (`label` will be used in its place if not supplied) but `id` is highly recommended when using `Tabs2` in a controlled state.
```

2021-08-13 17:14 UTC, lukelooker commented on www/src/documentation/components/content/tabs.mdx
> +  </Tab2>
`label` and `children` need to get inverted here so that the `Tabs2` has really long labels, not content :)

2021-08-13 17:14 UTC, lukelooker commented on www/src/documentation/components/content/tabs.mdx
> +To create a disabled Tab add the `disabled` prop to each individual `Tab2`.
```suggestion
To display a tab that can't be activated add the `disabled` prop.
```

2021-08-13 17:14 UTC, lukelooker commented on www/src/documentation/components/content/tabs.mdx
> +    {' '}
```suggestion
```

2021-08-13 17:14 UTC, lukelooker commented on www/src/documentation/components/content/tabs.mdx
> +    {' '}
```suggestion
```

2021-08-13 17:14 UTC, lukelooker commented on www/src/documentation/components/content/tabs.mdx
> +    {' '}
```suggestion
```

2021-08-13 17:14 UTC, lukelooker commented on www/src/documentation/components/content/tabs.mdx
> +      <Divider />
For the purposes of user-facing demonstrations i prefer to see "vanilla" HTML as it reduces the amount of context the reader needs about our component suite. 

```suggestion
  <button onClick={() => setTab(0)}>Go to A</button>
  <button onClick={() => setTab(1)}>Go to B</button>
```

NOTE: We _do_ use styled components within Storybook when we're taking image snapshots because we've seen slight rendering variations between browsers with vanilla components.


Also, above let's change: 

```
const [currentTabIndex, setTab] = useState(0)
```

to 
```
const [tabId, setTabId] = useState(0)
```

In keeping with the new `tabId` nomenclature.

2021-08-13 21:33 UTC, laraharrow commented
Updates done after the review!
I also updated the snapshots to integrate the test based on having the first `Tab` as `disabled`. The error on the snapshots remain thou.
@lukelooker any luck on that?

2021-08-16 22:25 UTC, lukelooker approved these changes
Change looks good to me but I'd like someone who was less "hands-on" to do another review as well. :)

2021-08-16 23:42 UTC, merged

2021-08-17 20:36 UTC, dbchristopher reviewed
This is all really great @laraharrow! The only real bug I found is with the types where it was meant to be enforce controlled vs uncontrolled prop combinations. Otherwise there was just some tiny typos and some possible (but really minor) css improvements. Great work!

2021-08-17 20:36 UTC, dbchristopher commented on packages/components/src/Tabs2/types.ts
> +export type Tabs2Props = (Controlled | Uncontrolled) & {
It looks like the intent here is to prevent users from using a `tabId` without also passing an `onTabChange` prop. That doesn't seem to work as expected! I can totally set `<Tabs2 tabId={currentTabId}>` or `<Tabs2 onTabChange={() => null}>` without typescript complaining. 

I took a bit to play around with the right type definitions, and I think I came up with a structure that requires you to do *both*  `tabId` and `onTabChange` OR do `defaultTabId`, but not any other combination. I think it should be structured something like this:

```suggestion
type Controlled = {
  /**
   * Controlled: which tab to show now
   */
  tabId: string
  /**
   * Callback called when tabId changes
   */
  onTabChange: (tabId: string) => void
  defaultTabId?: never
}

type Uncontrolled = {
  /**
   * Which tab to show on load
   */
  defaultTabId: string
  tabId?: never
  onTabChange?: never
}

type Default = {
  defaultTabId?: never
  tabId?: never
  onTabChange?: never
}

export type Tabs2Props = (Controlled | Uncontrolled | Default) & {
```

CC'ing @lukelooker to double check my logic there

2021-08-17 22:14 UTC, laraharrow commented on packages/components/src/Tabs2/index.ts
> +export * from './Tabs2'
the second option.  Right now all the `Tabs` work is set as `@depricated` and in the future the plan is to make `Tabs2` the official component's `Tabs`.

2021-08-17 22:15 UTC, laraharrow commented on packages/components/src/Tabs/Tabs.story.tsx
> +Scrolling.args = {
good idea

2021-08-17 22:38 UTC, laraharrow commented on packages/components/src/Tabs/Tabs.story.tsx
> +Scrolling.args = {
good idea!

2021-08-17 22:45 UTC, laraharrow commented on packages/components/src/Tabs2/Tab2.tsx
> +  }
good point

2021-08-17 22:59 UTC, laraharrow commented on packages/components/src/Tabs2/Tab2.tsx
> +  }
I had that test there on one of the clean ups it got removed, adding it again, good catch

2021-08-17 23:05 UTC, laraharrow commented on packages/components/src/Tabs2/TabList2.tsx
> +  }
Not really because that value gets removed if the prop `distribute` is passed so it needs to be a separated set of rules that gets toggled based on the value of  `distribute`

2021-08-17 23:06 UTC, laraharrow commented on packages/components/src/Tabs2/Tabs2.story.tsx
> +      </Tab2>
This is Lukes work 😅
Also Truffle doesn't know how to read so please don't tell him!

2021-08-17 23:23 UTC, laraharrow commented on packages/components/src/Tabs2/types.ts
> +export type Tabs2Props = (Controlled | Uncontrolled) & {
Oh man I always get so confused on the props that should and should not be a part of controlled or uncontrolled. 
You are right what I had didn't quite work , but I think both `Uncontrolled` and `Controlled` should have the possibility of passing `defaultTabId` and to be honest the `Default` option gets me even more confused. Seems like what you tried and what I tried is still not quite the right solution, I'm getting a TS error with ether variaton.

`
  Type '{ children: Element[]; defaultTabId?: string | undefined; tabId?: string | undefined; onTabChange?: ((tabId: string) => void) | undefined; distributed?: boolean | undefined; } | { ...; }' is not assignable to type 'IntrinsicAttributes & Tabs2Props'.
    Type '{ children: Element[]; defaultTabId?: string | undefined; tabId?: string | undefined; onTabChange?: ((tabId: string) => void) | undefined; distributed?: boolean | undefined; }' is not assignable to type 'IntrinsicAttributes & Tabs2Props'.
      Type '{ children: Element[]; defaultTabId?: string | undefined; tabId?: string | undefined; onTabChange?: ((tabId: string) => void) | undefined; distributed?: boolean | undefined; }' is not assignable to type 'Uncontrolled'.
      Types of property 'defaultTabId' are incompatible.
      Type 'string | undefined' is not assignable to type 'undefined'.
      Type 'string' is not assignable to type 'undefined'.
  `

2021-08-17 23:34 UTC, dbchristopher commented on packages/components/src/Tabs2/types.ts
> +export type Tabs2Props = (Controlled | Uncontrolled) & {
Ugh yeah this is really hard to type! Where is that error coming from?

About `defaultTabId` vs `tabId`, I'm pretty sure the best practice would be that you can't use them both simultaneously. My thinking is that if the values conflict, which one should the component implement? 

I looked up some articles about doing `value` vs `defaultValue` in forms, and they seem to confirm that the pattern should be mutually exclusive

https://scriptverse.academy/tutorials/reactjs-defaultvalue-value.html

<img width="681" alt="Screen Shot 2021-08-17 at 4 32 16 PM" src="https://user-images.githubusercontent.com/238293/129813962-f57799c5-5ba3-4adf-8c80-2b07a43f7010.png">

2021-08-17 23:38 UTC, dbchristopher commented on packages/components/src/Tabs2/types.ts
> +export type Tabs2Props = (Controlled | Uncontrolled) & {
>  to be honest the Default option gets me even more confused.

Yeah I totally understand that! I added it to account for the use case where they don't pass either `tabId` or `defaultTabId`. The thinking is that there are actually three possible scenarios here:

1. User can pass BOTH `tabId` and `onTabChange` (to require both you have to remove the optional `?` setting from those props)
2. User can pass ONLY `defaultTabId`
3. The user passes none of the above options. <-- that's the case that I added the `Default` option to describe. I agree that it seems like it might not be necessary, but it seemed to help in my local tests 🤷‍♂️

2021-08-18 20:15 UTC, roninjin10 reviewed
Addresses https://yaqs.corp.google.com/eng/q/4348128683202969600?from_email&action=view-question nicely!   Thanks!

![you-did-good-job-meme](https://user-images.githubusercontent.com/35039927/129965766-4aafc095-5667-4c3b-b992-a84230894001.jpeg)

2021-08-18 20:15 UTC, roninjin10 commented on packages/components/src/Tabs2/Tabs2.story.tsx
> +        <Tab2 id="cats" label="Cats">
Awesome!