feat(LkFieldTree): Add LkField suite of components
looker-open-source/components pull request #2731
Opened 2021-08-12 19:17 UTC by ElliotTheHuman

## Follow-up Work
- Tests for `LkFieldTree`

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-08-12 22:45 UTC, lukelooker commented on packages/components/src/Tree/types.ts
>       */
Should this get marked as `deprecated`? Can we switch to just `button` or `link` depending on presence of `href`?

2021-08-12 23:32 UTC, ElliotTheHuman commented on packages/components/src/Tree/types.ts
>       */
We totally could! I can mark this prop as deprecated on this PR, but did we want to include the auto-switching behavior on this PR as well? I think separate PR might be better because that would require story and test changes, so it'll probably add a sizable chunk to the line count.

2021-08-12 23:35 UTC, ElliotTheHuman commented on packages/components/src/Tree/types.ts
>       */
Actually, maybe it's better to mark this deprecated only after getting the auto-switch behavior. Thoughts?

2021-08-13 01:03 UTC, lukelooker requested changes
- [ ] Needs test coverage :)

2021-08-16 19:22 UTC, ElliotTheHuman commented
Tests are in! Note test additions increased line count by a bunch.

2021-08-16 23:41 UTC, lukelooker commented on packages/components/src/LkFieldTree/LkFieldItemLabel.tsx
> + */
Is this true? Wouldn't `LkFieldItemLabel` survive?

2021-08-16 23:41 UTC, lukelooker commented on packages/components/src/LkFieldTree/stories/FieldPicker.story.tsx
> +const BorderRadiusOverrideTree = styled(LkFieldTree)`
Were you thinking of building this in to LkFieldTree?

2021-08-16 23:41 UTC, lukelooker commented on packages/components/src/LkFieldTree/types.ts
> +    | 'density'
Does it need `density` support?

2021-08-16 23:41 UTC, lukelooker commented on packages/components/src/LkFieldTree/types.ts
> +  'density' | 'description' | 'itemRole' | 'truncate'
Ditto for `density`?

2021-08-16 23:41 UTC, lukelooker commented on packages/components/src/Tree/types.ts
>       */
I'm cool with that.

2021-08-16 23:46 UTC, ElliotTheHuman commented on packages/components/src/LkFieldTree/LkFieldItemLabel.tsx
> + */
:doh: Yep this comment only applies to stock `Tree`'s label. Deleted.

2021-08-16 23:47 UTC, ElliotTheHuman commented on packages/components/src/LkFieldTree/stories/FieldPicker.story.tsx
> +const BorderRadiusOverrideTree = styled(LkFieldTree)`
I was. More specifically, I was hoping to bake all style overrides from Field Picker in one-go in a follow up PR. If it's preferable to bring the border radius behavior right now though I can definitely do that.

2021-08-16 23:48 UTC, lukelooker commented on packages/components/src/LkFieldTree/stories/FieldPicker.story.tsx
> +const BorderRadiusOverrideTree = styled(LkFieldTree)`
Separately is totally fine - just checking in :)

2021-08-16 23:49 UTC, ElliotTheHuman commented on packages/components/src/LkFieldTree/types.ts
> +    | 'density'
I _think_ we settled on forcing `LkField` components to be at density = -3. I'm not super opposed to allowing density, _but_ it may make lead to some more tech debt when implementing the item padding refactor work (i.e. we may need to add a new attribute `heightWithDescription` to `ListItemDimensions`).

Happy to talk this over though and clarify why allowing multiple densities would lead to a new item dimension property.

2021-08-16 23:51 UTC, lukelooker commented on packages/components/src/LkFieldTree/types.ts
> +  'density' | 'description' | 'itemRole' | 'truncate'
I was backwards here.

2021-08-17 01:01 UTC, lukelooker approved these changes
LGTM

2021-08-17 01:25 UTC, merged