updates after review
looker-open-source/components pull request #2749
Opened 2021-08-17 23:29 UTC by laraharrow

## 👋👋 Thank you for contributing to Looker Components (⚡️🍣)

📺 Watch a quick video on how to you make your pull requests fast and easy for you and your reviewer(s):
https://threadit.app/thread/k45nyrqugoinw6xub9vf/message/fl8m57exhqg4r0a4hg01eebn

- 👆 Make sure your pull request title follows [Pull Request Title Guidelines](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#title-guidelines) from our [Contribution guide](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md)
- 👉 Don't forget to replace these instructions with your _✨awesome✨_ description of what this change _actually does_. Additionally it's great to include context on how it works and why the change was needed.
- 👇 Edit "Developer Checklist" to reflect items relevant to this PR (and try to make sure to check everything off before asking for review)

## Developer Checklist [ℹ️](https://github.com/looker-open-source/components/blob/main//CONTRIBUTING.md#developer-checklist)

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-08-17 23:36 UTC, laraharrow commented on packages/components/src/Tabs2/types.ts
> +  tabId: string
@lukelooker and @dbchristopher is this the correct behavior here, I was getting an error on the stories here.

Type '{ children: Element[]; defaultTabId?: string | undefined; tabId?: string | undefined; onTabChange?: ((tabId: string) => void) | undefined; distributed?: boolean | undefined; } | { ...; }' is not assignable to type 'IntrinsicAttributes & Tabs2Props'. Type '{ children: Element[]; defaultTabId?: string | undefined; tabId?: string | undefined; onTabChange?: ((tabId: string) => void) | undefined; distributed?: boolean | undefined; }' is not assignable to type 'IntrinsicAttributes & Tabs2Props'. Type '{ children: Element[]; defaultTabId?: string | undefined; tabId?: string | undefined; onTabChange?: ((tabId: string) => void) | undefined; distributed?: boolean | undefined; }' is not assignable to type 'Uncontrolled'. Types of property 'defaultTabId' are incompatible. Type 'string | undefined' is not assignable to type 'undefined'. Type 'string' is not assignable to type 'undefined'.

2021-08-18 16:47 UTC, dbchristopher requested changes
The changes look good to me! Looks like snapshots need to be rebuilt, probably because of the additional `disabled` tab added to the story template.

I also suggested a new test we could add to validate the restricted prop combinations

2021-08-18 16:47 UTC, dbchristopher commented on packages/components/src/Tabs2/Tabs2.test.tsx
> +    expect(screen.queryByText('Humans tab is disabled')).not.toBeInTheDocument()
nice cleanup 👍

2021-08-18 16:47 UTC, dbchristopher commented on packages/components/src/Tabs2/Tabs2.test.tsx
> -import { Tabs2 } from './Tabs2'
Now that we've set up some restricted prop combinations in typescript, we should validate that it validates props correctly. This would be a great use for `@ts-expect-error` which I found out about fairly recently. I was just playing around with it, and this seems to work:

```ts
  test('validates controlled vs uncontrolled prop combinations', () => {
    renderWithTheme(
      // @ts-expect-error: onTabChange required when tabId is set
      <Tabs2 tabId="3">
        <Tab2 id="tab" label="Tab">
          A single Tab
        </Tab2>
      </Tabs2>
    )

    renderWithTheme(
      // @ts-expect-error: tabId required when onTabChange is set
      <Tabs2 onTabChange="3">
        <Tab2 id="tab" label="Tab">
          A single Tab
        </Tab2>
      </Tabs2>
    )

    renderWithTheme(
      // @ts-expect-error: you can't set both tabId and defaultTabId simultaneously
      <Tabs2 tabId="3" defaultTabId="5">
        <Tab2 id="tab" label="Tab">
          A single Tab
        </Tab2>
      </Tabs2>
    )
  })
```

`@ts-expect-error` is cool because typescript will alert you if you do something like `<Tabs2 tabId="3" defaultTabId="5">` and it actually passes

2021-08-18 17:27 UTC, lukelooker requested changes
Only issue I see is that I'd prefer not have the "Basic" example include a `disabled` tab as that's not a pattern we commonly see (or particularly recommend).

See comments inline for further context.

2021-08-18 17:27 UTC, lukelooker commented on packages/components/src/Tabs2/Tabs2.story.tsx
> +      </Tab2>
I don't think this adds much of value to tabs (`disabled` tabs is an edge case we've never actually seen used in the real world) so I'd prefer not to include it in the global example set.

Might be sense to add another story (with storyshots disabled) to show a disabled tab in action so that folks reviewing the stories can see that in a limited scenario.

2021-08-18 17:27 UTC, lukelooker commented on packages/components/src/Tabs2/Tabs2.test.tsx
> -import { Tabs2 } from './Tabs2'
👍

2021-08-18 17:27 UTC, lukelooker commented on packages/components/src/Tabs2/Tabs2.test.tsx
> +    expect(screen.getAllByRole('tab')).toHaveLength(4)
```suggestion
    expect(screen.getAllByRole('tab')).toHaveLength(3)
```

2021-08-18 17:27 UTC, lukelooker commented on packages/components/src/Tabs2/Tabs2.test.tsx
> -    )
I'd made this change so that Storybook didn't feature a disabled tab by default. 

You could copy this into Storybook as a `Disabled` story and then use that here but as I noted above I'd prefer not to have a `disabled` tab included in the general example of Tabs.

2021-08-18 17:27 UTC, lukelooker commented on packages/components/src/Tabs2/Tabs2.story.tsx
> +}
👍

2021-08-18 18:18 UTC, laraharrow commented on packages/components/src/Tabs2/Tabs2.test.tsx
> -import { Tabs2 } from './Tabs2'
the `@ts-expect-error` its a great tool!
thanks for sharing I didn't know about it!

2021-08-18 20:19 UTC, dbchristopher commented on packages/components/src/Tabs2/Tabs2.story.tsx
> +}
I think we would want to capture one snapshot that includes the disabled state, right?

2021-08-18 21:52 UTC, laraharrow commented on packages/components/src/Tabs2/Tabs2.story.tsx
> +      <p>The current selected tab is: {currentTabId}</p>
I added this as an example for Bryn based on what he wanted from ticket: https://buganizer.corp.google.com/issues/183439880

2021-08-18 22:31 UTC, lukelooker reviewed
Looks good to me. I'll let Daniel have the last word / approval :)

2021-08-19 16:13 UTC, dbchristopher approved these changes

2021-08-19 16:50 UTC, merged