first commit
looker-open-source/components pull request #2765
Opened 2021-08-23 17:22 UTC by laraharrow

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-08-23 20:14 UTC, laraharrow commented on packages/components/src/Form/Inputs/Checkbox/FauxCheckbox.tsx
> +export type FauxCheckboxProps = {
This was added to support the use of this component on ComboboxMultiOption.

2021-08-23 20:15 UTC, laraharrow commented on packages/components/src/Form/Inputs/Combobox/ComboboxMultiOption.tsx
> +  // eslint-disable-next-line react/display-name
this was added to fix the TS error of display-name request

2021-08-23 20:16 UTC, laraharrow commented on packages/components/src/Form/Inputs/Combobox/ComboboxMultiOption.tsx
> +            <FauxCheckbox isSelected={isSelected}>
This component didn't need the complexity of Checkbox, just the displayed element. This change makes it so Changes to Checkbox won't affect this component.

2021-08-23 20:22 UTC, laraharrow commented on packages/components/src/Form/Inputs/Checkbox/FauxCheckbox.tsx
> +}
The changes added here is to support the transition of `ComboboxMultiOption` to not using the Checkbox component. The component and its complexities are irrelevant to `ComboboxMultiOption` all it needs is a place holder in the shape of a checkbox and `FauxCheckbox` is the perfect solution for that.

2021-08-23 20:25 UTC, laraharrow commented on packages/components/src/Form/Inputs/Combobox/ComboboxMultiOption.tsx
> +export const ComboboxMultiOption = styled(
updated code to follow the new pattern on `styled`. While doing that a TS error was coming up, display-name was missing. The comment on line 51 is to mitigate it. Open to new ideas here - Couldn't figure out why the error was being trigged.

2021-08-23 20:27 UTC, laraharrow commented on packages/components/src/Form/Inputs/Combobox/ComboboxMultiOption.tsx
> +            <FauxCheckbox isSelected={isSelected}>
Simplifying this work by removing Checkbox from here. FauxCheckbox renders as a checkbox but without the complexity of the component.

2021-08-23 22:37 UTC, mdodgelooker requested changes
This looks great! I think it might be good to remove the duplicated styles in `Checkbox.tsx` though.

2021-08-23 22:37 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Combobox/ComboboxMultiOption.tsx
> +export const ComboboxMultiOption = styled(
That is so weird because `ButtonBase` uses `forwardRef` too but no error in that file. I'm fine with the comment if you are, @lukelooker.

2021-08-23 22:37 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Checkbox/FauxCheckbox.tsx
> +  border-color: ${({ isSelected, theme }) => isSelected && theme.colors.key};
This works great but now we have these styles duplicated both here and in `Checkbox.tsx`: https://github.com/looker-open-source/components/blob/main/packages/components/src/Form/Inputs/Checkbox/Checkbox.tsx#L127
which might be confusing if someone needs to update them later.
What do you think about removing them from `Checkbox.tsx` and adding the `isSelected` prop there instead?

2021-08-24 16:39 UTC, laraharrow commented on packages/components/src/Form/Inputs/Checkbox/FauxCheckbox.tsx
> +  border-color: ${({ isSelected, theme }) => isSelected && theme.colors.key};
This is not just repeated code. inside `Checkbox`, the style is referent to `FauxCheckbox` and `input` removing it created a domino effect on a few different components (FieldCheckbox, FieldCheckboxGroup). My thought here is that even thou the styles are very similar they are actually accomplishing different things. As in `Checkbox` has a bigger scope and removing the style from it will change other styled of components using `Checkbox` that is not our intention.

2021-08-24 17:30 UTC, laraharrow commented on packages/components/src/Form/Inputs/Combobox/ComboboxMultiOption.tsx
> +export const ComboboxMultiOption = styled(
just trying following the same pattern for Radio and got the same TS error FYI

2021-08-24 20:25 UTC, mdodgelooker approved these changes
LGTM!

2021-08-24 20:25 UTC, mdodgelooker commented on packages/components/src/Form/Inputs/Checkbox/FauxCheckbox.tsx
> +  border-color: ${({ isSelected, theme }) => isSelected && theme.colors.key};
You're right, the changes I'm thinking of would cause some breakage. I made a PR to see what breaks: https://github.com/looker-open-source/components/pull/2771
(Sorry, I accidentally pushed that change to your branch instead but then reverted it.)

I'm not quite sure why it breaks the `FieldCheckboxGroup` snapshot but I don't think it's worth the time – what you've done already works just fine. For future reference my reasoning was to:
1. Reduce "contextual overrides" i.e. referencing `FauxCheckbox` inside the style block of another component `Checkbox`, which reduces our ability to control a component from inside the component itself
2. Have a single source of truth for the purple bg & border color styles, in case they ever need to be modified

2021-08-24 21:04 UTC, merged