feat(LkFieldTree): Added LkFieldViewTree and LkFieldGroupTree
looker-open-source/components pull request #2768
Opened 2021-08-23 20:11 UTC by ElliotTheHuman

- Created new `LkFieldViewTree` and `LkFieldGroupTree` to handle specific `Tree` style overrides
- Baked in "xxsmall" label padding-left into all `LkField` components
- Updated `FieldPicker` story

- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-08-23 20:28 UTC, lukelooker requested changes
Lots of questions, minor documentation asks.

2021-08-23 20:28 UTC, lukelooker commented on packages/components/src/LkFieldTree/LkFieldGroupTree.tsx
> +export const LkFieldGroupTree = styled(LkFieldTree)`
Can you add a simple JSDoc explanation that explains what this component is for?

2021-08-23 20:28 UTC, lukelooker commented on packages/components/src/LkFieldTree/LkFieldTree.tsx
> +export const LkFieldTreeAccordionContent = styled.div``
Could these be moved to separate files? I'm mostly thinking that it'd be nice to "locally" export them but not make them visible to external consumers.

2021-08-23 20:28 UTC, lukelooker commented on packages/components/src/LkFieldTree/LkFieldViewTree.tsx
> +export const LkFieldViewTree = styled(LkFieldTree)`
Can you add a simple JSDoc explanation that explains what this component is for?

2021-08-23 20:28 UTC, lukelooker commented on packages/components/src/LkFieldTree/stories/FieldPicker.story.tsx
> +      <FieldGroupHeading pt="0">DIMENSIONS</FieldGroupHeading>
```suggestion
      <FieldGroupHeading pt="none">DIMENSIONS</FieldGroupHeading>
```

Should this just be baked in to `FieldGroupHeading`?

2021-08-23 20:28 UTC, lukelooker commented on packages/components/src/LkFieldTree/stories/FieldPicker.story.tsx
> +        label={<Box fontWeight="bold">Orders</Box>}
```suggestion
        label={<strong>Orders</strong>}
```

2021-08-23 20:28 UTC, lukelooker commented on packages/components/src/LkFieldTree/stories/FieldPicker.story.tsx
> +      <LkFieldViewTree label={<Box fontWeight="bold">Order Items</Box>}>
```suggestion
      <LkFieldViewTree label={<strong>Order Items</strong>}>
```

2021-08-23 20:28 UTC, lukelooker commented on packages/components/src/LkFieldTree/stories/FieldPicker.story.tsx
> +      <LkFieldViewTree label={<Box fontWeight="bold">Users</Box>}>
```suggestion
      <LkFieldViewTree label={<strong>Users</strong>}>
```

2021-08-23 20:28 UTC, lukelooker commented on packages/components/src/LkFieldTree/stories/FieldPickerItem.tsx
> +      <Flex alignItems="center">
Should this be built into `LkFieldItem`?

2021-08-23 21:25 UTC, ElliotTheHuman commented on packages/components/src/LkFieldTree/stories/FieldPicker.story.tsx
> +      <LkFieldViewTree label={<Box fontWeight="bold">Users</Box>}>
👍  c8e5ec1

2021-08-23 21:25 UTC, ElliotTheHuman commented on packages/components/src/LkFieldTree/stories/FieldPicker.story.tsx
> +      <LkFieldViewTree label={<Box fontWeight="bold">Order Items</Box>}>
👍  c8e5ec1

2021-08-23 21:25 UTC, ElliotTheHuman commented on packages/components/src/LkFieldTree/LkFieldViewTree.tsx
> +export const LkFieldViewTree = styled(LkFieldTree)`
👍  c8e5ec1

2021-08-23 21:25 UTC, ElliotTheHuman commented on packages/components/src/LkFieldTree/LkFieldTree.tsx
> +export const LkFieldTreeAccordionContent = styled.div``
👍  c8e5ec1

2021-08-23 21:28 UTC, ElliotTheHuman commented on packages/components/src/LkFieldTree/LkFieldGroupTree.tsx
> +export const LkFieldGroupTree = styled(LkFieldTree)`
👍  13cd9a0

2021-08-23 21:33 UTC, ElliotTheHuman commented on packages/components/src/LkFieldTree/stories/FieldPicker.story.tsx
> +      <FieldGroupHeading pt="0">DIMENSIONS</FieldGroupHeading>
Explore actually wants the first heading to NOT have any `pt` (probably since the actual accordion content container has that `0.5rem` of vertical padding in their View-level Trees). Note that the "Filter-Only Fields" heading appears to have `pt` but really it's just the `pt` from the Tree style override.
![Screen Shot 2021-08-23 at 2 30 22 PM](https://user-images.githubusercontent.com/16812885/130522080-7d619060-20f8-474c-8378-ff112e7b6d83.png)

Wanted to note that our `FieldGroupHeading` actually isn't exported as component (it's just a styled `<p>` used in the story). That being said, I _could_ create / export a `LkFieldHeading` if we wanted to do something like that.

2021-08-23 21:46 UTC, ElliotTheHuman commented on packages/components/src/LkFieldTree/stories/FieldPickerItem.tsx
> +      <Flex alignItems="center">
Actually, I don't think we need this `alignItems` now that I'm thinking about it.

That being said, we do still want this outermost `Flex` unless we want to pursue a deeper `ListItemLabel` refactor. TLDR, the direct parent of the `LkFieldItem` children ends up being the `TruncateOptionally` component, which doesn't have any flex behaviors baked into it. Without this outermost `Flex`, the composition flops over:
![Screen Shot 2021-08-23 at 2 46 13 PM](https://user-images.githubusercontent.com/16812885/130523711-410f355a-be3f-43aa-b947-7cced703791e.png)

2021-08-23 23:31 UTC, lukelooker commented on packages/components/src/LkFieldTree/stories/FieldPicker.story.tsx
> +      <FieldGroupHeading pt="0">DIMENSIONS</FieldGroupHeading>
Ah - that makes sense, I don't see much sense in export `FieldGroupHeading` :)

2021-08-24 00:04 UTC, lukelooker commented on packages/components/src/LkFieldTree/stories/FieldPickerItem.tsx
> +      <Flex alignItems="center">
👍

2021-08-24 00:04 UTC, lukelooker approved these changes

2021-08-24 00:42 UTC, merged