fix(useAccordion2): Ignore changes to defaultOpen
looker-open-source/components pull request #2785
Opened 2021-08-27 23:27 UTC by lukelooker

Currently `useAccordion2` (and by proxy `Accordion2` & `Accordion`) responds to mutations of the `defaultOpen` property. Instead it should be a one-and-done property – changes should be ignored.

2021-08-27 23:58 UTC, ElliotTheHuman requested changes

2021-08-27 23:58 UTC, ElliotTheHuman commented on packages/components/src/Accordion2/Accordion2.spec.tsx
> +    expect(screen.queryByText('World')).not.toBeInTheDocument()
Dumb question, but we want `defaultOpen` to NOT change the open state after initial render right?

In which case, we'd want this line of the test to also be, I think?
```
expect(screen.getByText('World')).toBeInTheDocument()
```

2021-08-27 23:58 UTC, ElliotTheHuman commented on packages/components/src/Accordion2/Accordion2.spec.tsx
> +          )
I don't think this closing parenthesis has a corresponding open one. Should be able to just delete it.

2021-08-27 23:58 UTC, ElliotTheHuman commented on packages/components/src/Accordion2/useAccordion2.tsx
> +  })
Should be able to get the desired "one and done" behavior by passing an empty array in as the second argument of this `useEffect`.

2021-08-28 00:02 UTC, lukelooker commented on packages/components/src/Accordion2/useAccordion2.tsx
> +  })
Doh!

2021-08-28 00:02 UTC, lukelooker commented on packages/components/src/Accordion2/Accordion2.spec.tsx
> +          )
Done! :)

2021-08-28 00:12 UTC, ElliotTheHuman approved these changes
LGTM!!

2021-08-30 17:06 UTC, ElliotTheHuman requested changes
Looking at the image snapshot / storybook errors, I think the issue is that the `Tree` / `Accordion` will always initially render as closed, but after that initial render the `useEffect` will fire and then change the state to open. So in snapshot land, you get this weird effect where the accordions / trees start as closed but quickly switch to open (eye tests in storybook support this).

Ideally, we'd just want that initial render to know that it should be open, so maybe a viable option would be to have the existing `defaultOpen` implementation, and then add a state piece that checked for the initial render. If the initial render happened, then use the added state to ignore the `defaultOpen` on subsequent rerenders.

2021-08-31 17:53 UTC, ElliotTheHuman approved these changes
LGTM

2021-08-31 17:54 UTC, merged