fix(Checkbox): update stories and tests
looker-open-source/components pull request #2800
Opened 2021-09-01 19:31 UTC by laragoogle

- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-09-01 19:35 UTC, laragoogle commented on packages/components/src/Form/Inputs/Checkbox/Checkbox.story.tsx
> +  ...Basic,
Some of the stories using Template were not displaying correctly. I couldn't find a solution for it that still use Template so I rewrote the stories.

2021-09-01 21:37 UTC, lukelooker requested changes
The updated snapshots look good but I'd like to see the stories consistently use the CFS format - added a specific comment about what I suspect was going wrong there.

Thanks for adding additional unit test coverage along the way!

2021-09-01 21:37 UTC, lukelooker commented on packages/components/src/Form/Inputs/Checkbox/Checkbox.story.tsx
> +export const ReadOnlyCheckedMixed = () => <Checkbox readOnly checked="mixed" />
Looking at the examples you replaced it looks like a lot of the `args` assignments we're mixed up:

![image](https://user-images.githubusercontent.com/34253496/131747294-25b1534f-3d17-433e-b7d6-9ee82533a6eb.png)

`DisabledMixed` also has this scenario.

I checked out your branch and got it working with these CSF-style stories:

```

export const DisabledChecked = Template.bind({})
DisabledChecked.args = {
  ...Disabled.args,
}

export const DisabledCheckedMixed = Template.bind({})
DisabledCheckedMixed.args = {
  ...Disabled.args,
  ...MixedChecked.args,
}

export const ReadOnly = Template.bind({})
ReadOnly.args = {
  readOnly: true,
}

export const ReadOnlyChecked = Template.bind({})
ReadOnlyChecked.args = {
  ...Checked.args,
  readOnly: true,
}

export const ReadOnlyCheckedMixed = Template.bind({})
ReadOnlyCheckedMixed.args = {
  ...MixedChecked.args,
  readOnly: true,
}
```

2021-09-01 21:37 UTC, lukelooker commented on packages/components/src/Form/Inputs/Checkbox/Checkbox.spec.tsx
> +  test('renders checked', () => {
```suggestion
  test('checked', () => {
```

2021-09-01 21:37 UTC, lukelooker commented on packages/components/src/Form/Inputs/Checkbox/Checkbox.spec.tsx
> +  test('renders checked mixed', () => {
```suggestion
  test('mixed', () => {
```

2021-09-01 21:37 UTC, lukelooker commented on packages/components/src/Form/Inputs/Checkbox/Checkbox.spec.tsx
> +  test('renders disabled', () => {
```suggestion
  test('disabled', () => {
```

2021-09-01 21:37 UTC, lukelooker commented on packages/components/src/Form/Inputs/Checkbox/Checkbox.spec.tsx
> +  test('renders disabled checked', () => {
```suggestion
  test('disabled & checked', () => {
```

2021-09-01 21:37 UTC, lukelooker commented on packages/components/src/Form/Inputs/Checkbox/Checkbox.spec.tsx
> +    expect(checkboxInput as HTMLInputElement).toBeChecked()
`as HTMLInputElement` shouldn't be needed - poking at it locally tests appear to work without explicitly forcing the typing on these. Can you remove this explicit assignments?

```suggestion
    expect(checkboxInput).toBeChecked()
```

2021-09-01 21:53 UTC, laragoogle commented on packages/components/src/Form/Inputs/Checkbox/Checkbox.story.tsx
> +export const ReadOnlyCheckedMixed = () => <Checkbox readOnly checked="mixed" />
oh no I can't believe I missed that 🤦🏽‍♀️

2021-09-02 01:40 UTC, lukelooker approved these changes
Looks good!

2021-09-02 01:41 UTC, merged