feat(Dialog): add methods onAfterClose and OnAfterOpen
looker-open-source/components pull request #2842
Opened 2021-09-20 23:17 UTC by laragoogle

Update Dialog to have a method available before the component opens and after it closes.

- [ ] 📚 Documentation updated
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-09-20 23:19 UTC, laragoogle commented on packages/components/src/Dialog/useDialog.tsx
> +    if (className === 'exiting' && onAfterClose) onAfterClose()
I'm using `exiting` as oppose to `exited` because that value is actually used before `Dialog` is opened as well as after its closed.

2021-09-20 23:30 UTC, lukelooker requested changes

2021-09-20 23:30 UTC, lukelooker commented on packages/components/src/Dialog/useDialog.tsx
> +    if (className === 'exiting' && onAfterClose) onAfterClose()
1. I wouldn't tie to the `className` here since we may (at some future point) want to separate the styles attached from the callbacks. Instead I'd extend `useAnimationState` to return an `animationState` that could use here.
2. The `animationState` should get fixed up if it's incorrect currently - we really only want to call `onAfterClose` immediately after the animation has finished the sequence was originally conceived to be:

```Entering => Entered => Exiting => Exited```

2021-09-21 00:20 UTC, laragoogle commented on packages/components/src/Dialog/useDialog.tsx
> +    if (className === 'exiting' && onAfterClose) onAfterClose()
1. `[className](https://github.com/looker-open-source/components/blob/214d0232febb3f8e44ad144722ae13b1fbaa0673/packages/components/src/utils/useAnimationState.ts#L44)` is how the state is passed from `useAnimationState` as far as I can tell.
2. I think the status make sense thou, because when `Dialog` has not been opened it is for all intents and purposes `exited`. Basically we could create a new value to be the default value of `state` meaning when the component is rendered that is what it would be.

2021-09-22 22:48 UTC, lukelooker requested changes

2021-09-22 22:48 UTC, lukelooker commented on packages/components/src/Dialog/useDialog.tsx
> +  }, [className, onAfterClose, onAfterOpen])
While className does reflect the state today I'd prefer not to directly tie those together because that may change at future point. For instance in this particular refactor we may want to be able to add another "state" for the callbacks but leave the className behavior as-is to save having to refactor the CSS.

`hasBeenOpenRef.current = false` is a clever workaround but really this could done more cleanly by returning a some kind of state value from the `useAnimation` hook that encapsulates that behavior (on/off) completely within the useAnimation hook rather than having to do inference here via the `useRef`

2021-09-22 22:48 UTC, lukelooker commented on packages/components/src/Drawer/stories/Drawer.stories.tsx
> +export const AfterCloseAfterOpenMethods = Template.bind({})
Ditto for renaming above.

2021-09-23 16:20 UTC, mdodgelooker commented on packages/components/src/Dialog/useDialog.tsx
> +  }, [className, onAfterClose, onAfterOpen])
I think `useRef` will be necessary in some form because you need to capture when the animation state changes to `'exited'` from one of the other values:
1) Initial render, also `'exited'` – though you might be able around this by creating a new animation state value `'initial'`...
2) `onAfterOpen` or `onAfterClose` props change while animation state remains `'exited'`.

But actually I think it might be good to move both this whole new chunk of code into `useAnimationState` so it can be easily accessed by other components like `Panel`. Thoughts?

2021-09-23 19:01 UTC, laragoogle commented on packages/components/src/Dialog/stories/Dialog.stories.tsx
> +    // eslint-disable-next-line no-console
After all of this I think we still have to use useRef. as I'm testing the component on render this is what comes back from the consologs:
![Screen Shot 2021-09-23 at 11 59 57 AM](https://user-images.githubusercontent.com/89867109/134567812-94a089e3-1143-4d80-bc75-b1386c5f336c.png)

2021-09-23 20:51 UTC, mdodgelooker commented on packages/components/src/Dialog/stories/Dialog.stories.tsx
> +    // eslint-disable-next-line no-console
Ah yes, `useAnimationState` is acting funny because of `undefined`. I'll add a comment over there but it may be a moot point if you decide to go back to `useRef`.

The issue with changed animation callbacks getting called at inappropriate times is a concern. If you add this story, you can see it in action:
```

export const ChangingCallbacks = () => {
  const { value, toggle } = useToggle()
  const { value: value2, toggle: toggle2 } = useToggle()
  const onAfterOpen = useCallback(() => {
    alert(value ? 'The changed onAfterOpen' : 'The original onAfterOpen')
  }, [value])
  const onAfterClose = useCallback(() => {
    alert(value2 ? 'The changed onAfterClose' : 'The original onAfterClose')
  }, [value2])
  return (
    <Space>
      <Dialog
        onAfterOpen={onAfterOpen}
        onAfterClose={onAfterClose}
        content={
          <DialogLayout>
            <FieldToggleSwitch
              label="Change onAfterOpen"
              on={value}
              onChange={toggle}
            />
          </DialogLayout>
        }
      >
        <Button>Open Dialog</Button>
      </Dialog>
      <FieldToggleSwitch
        label="Change onAfterClose"
        on={value2}
        onChange={toggle2}
      />
    </Space>
  )
}
```

2021-09-23 20:51 UTC, mdodgelooker commented on packages/components/src/utils/useAnimationState.ts
> +  const definedState = state === undefined ? 'exited' : state
There's a bunch of logic looking at `state` in the `useEffect` above, but it would need to look at `definedState` now.

2021-09-23 21:13 UTC, mdodgelooker commented
Also, you might notice that `onAfterOpen` seems to get called before the animation. This is due to using CSS transition instead of animation and I think we should address it separately so I made a new ticket.

2021-09-23 22:12 UTC, laragoogle commented
@lukelooker what are your thoughts on how to move forward here?
Should we go back to the first approach and use `useRef` or there is a better option here with some refactoring?
@mdodgelooker thanks for the story, that was helpful to see. Also what are your thoughts on what we should do here?

2021-09-27 15:46 UTC, mdodgelooker commented
My vote would be to go back the the first version with `useRef` BUT to implement it inside of `useAnimationState` instead of in `useDialog`. That way we can eventually add the callbacks to `Panel` as well.

2021-09-27 16:30 UTC, laragoogle commented
@mdodgelooker I think that is what we have right now, I agree with you so I went back to the version using `useRef` but now also using a new prop `transitionState`. Let me know if you see any other change I should do.

2021-09-27 23:37 UTC, lukelooker submitted a review, later dismissed
This looks great. 

Test coverage is showing a reduction on coverage for `useAnimationState` hook because there are no tests that leverage `onAfterOpen` & `onAfterClose`. Can you add a test for `Dialog` that shows those working so we can get that coverage number back up?

2021-09-28 17:36 UTC, laragoogle commented on packages/components/src/Dialog/Dialog.spec.tsx
> +  test('props onAfterClose and onAfterOpen are called on appropriated time', async () => {
Ok we have test for the new functions. expect `onAfterOpen` doesn't seem to be called. I wrote the same dialog example here as a story and that works as we would expect. So I'm not sure why its not recognizing the call here.
The other point is that even with this test `coverage` is telling me that the file is not completely tested.
![Screen Shot 2021-09-28 at 10 03 51 AM](https://user-images.githubusercontent.com/89867109/135137513-4b27cace-1637-4327-84dd-904e8b834922.png)

2021-09-28 17:40 UTC, mdodgelooker requested changes

2021-09-28 17:40 UTC, mdodgelooker commented on packages/components/src/Dialog/Dialog.spec.tsx
> +    expect(onAfterOpen).toBeCalled()
Since there's a delay before this is called, you'll need to use jest timers. Copy over the 1st & last line from the test below and put the `act` bit right before this line. 
https://github.com/looker-open-source/components/blob/main/packages/components/src/CopyToClipboard/CopyToClipboard.spec.tsx#L74-L85

2021-09-28 20:55 UTC, mdodgelooker commented on packages/components/src/utils/useAnimationState.ts
> +
Looks like the "changing callbacks" issue demonstrated [here](https://github.com/looker-open-source/components/pull/2842#discussion_r715142617) is still an issue for `onAfterOpen`. Just need a slight tweak to fix it:
```suggestion
  const previousStateRef = useRef(state)

  useEffect(() => {
    if (state === 'entered' && previousStateRef.current !== 'entered') {
      onAfterEntered?.()
    }

    if (state === 'exited' && previousStateRef.current !== 'exited') {
      onAfterExited?.()
    }
    previousStateRef.current = state
  }, [state, onAfterExited, onAfterEntered])

```

2021-09-30 17:16 UTC, mdodgelooker approved these changes
Awesome! 🚢 it!

2021-09-30 17:35 UTC, merged