fix(FiledInline): update code for accessibility
looker-open-source/components pull request #2849
Opened 2021-09-22 22:52 UTC by laragoogle

- [ ] ♿️ Accessibility addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-09-22 23:03 UTC, lukelooker requested changes
Noted issues inline.

Might need some test coverage additions perhaps too?

2021-09-22 23:03 UTC, lukelooker commented on packages/components/src/Form/Fields/FieldInline.tsx
> +      {detail && <FieldDetail id={id}>{detail}</FieldDetail>}
Not sure how to attach the detail to the input but `id={id}` will definitely bust things.

```suggestion
      {detail && <FieldDetail id={`${id}-detail`}>{detail}</FieldDetail>}
```

2021-09-23 17:18 UTC, laragoogle commented
I think the code is good here, but I'm having a problem with the tests, seems to be unrelated to the work on this PR.

2021-09-24 05:18 UTC, lukelooker requested changes
Pushed a small commit - 81fafaead95ce104a9f7f22c858d9a7e2e30da07 to address feedback. 

- Since `amendedChildren` is really only used within the component I'd just assign it as a const within the function/component itself.
- Build `aria-describedby` ID string once and re-use as `const` to prevent typoes
- Remove `as="span"` (this fixes all but 3 or 4 test breakage issues)
- Only assign `describedbyId` as an `id` in one place (`FieldDescription` ✅ , `FieldDetail` 🚫 )

Once tests are fixed up I think this should be good-to-go.

2021-09-24 23:43 UTC, lukelooker requested changes

2021-09-24 23:43 UTC, lukelooker commented on packages/components/src/Form/Fields/Field/FieldInline.tsx
> +      <MessageArea>
ARIA id needs to be assigned here to keep the "validationMessage" tied to the input for screen-reader announcement.

```suggestion
      <MessageArea id={`${id}-describedby`}>
```

2021-09-24 23:43 UTC, lukelooker commented on packages/components/src/Form/Fields/FieldCheckbox/FieldCheckbox.spec.tsx
> +    )
This connects the description text nicely but the validationMessage is not because the ARIA id was moved. Fix commit incoming.

2021-09-24 23:43 UTC, lukelooker commented on packages/components/src/Form/Fields/FieldToggleSwitch/FieldToggleSwitch.spec.tsx
> +    expect(id).toEqual('test-description')
In the interest of reducing downstream snapshot changes I think we should go back to the old format (either's fine, not changing means less "noise" in snapshots and changeset here). Update incoming.

```suggestion
    expect(id).toEqual('describedby-test')
```

2021-09-24 23:59 UTC, laragoogle commented
Thanks Luke!

2021-09-25 00:04 UTC, lukelooker approved these changes

2021-09-25 00:06 UTC, merged