feat(FieldSelect, FieldChips, FieldTime, FieldTimeSelect): Google Material label style
looker-open-source/components pull request #2868
Opened 2021-09-27 19:12 UTC by mdodgelooker

- Updates 4 fields to use `FloatingLabelField`:
  - `FieldSelect`
  - `FieldChips`
    - There's no "uncontrolled" version so `hasValue` is derived simply from `props.values`
    - `checkValueOnBlur` is set to `false`, meaning `FloatingLabelField` doesn't need to check for a value in the internal input on blur event, since that is automatically converted to a chip on blur (via `onChange`)
  - FieldTime
    - Custom `checkValueOnBlur` since there are actually 3 internal inputs to check
- Wrapped all the story templates in `ExtendedComponentsThemeProvider` so that `externalLabel` can be toggled in the controls
- Added a few explicitly `externalLabel: false` stories

2021-09-27 22:13 UTC, lukelooker requested changes
Using `externalLabel = true` when deconstructing properties in the stories for each component would remove the need to change existing stories (see inline comment)

The only other thing that struck me as odd is the behavior of the "Placeholder" popping up before I pick a value a-la: 

![image](https://user-images.githubusercontent.com/34253496/134992271-45cde08f-42eb-46d6-b64d-4f52e59848de.png)

Perhaps this is Material-correct and just read's funny because the placeholder text is "Placeholder" instead of something like "Select a cheese"? I could see a scenario where the label stayed in place until an actual value is selected.

FieldChips looks smooshed as we've discussed. I look forward to `density` :)

2021-09-27 22:13 UTC, lukelooker commented on packages/components-date/src/FieldTime/FieldTime.stories.tsx
> +  externalLabel: true,
Rather than adding this here you could add it as a default value to the template (see comment above)

2021-09-27 22:13 UTC, lukelooker commented on packages/components-date/src/FieldTime/FieldTime.stories.tsx
> +  externalLabel,
Doing this would remove the need to make any changes to existing stories.

```suggestion
  externalLabel = true,
```

2021-09-27 22:13 UTC, lukelooker commented on packages/components-date/src/FieldTimeSelect/FieldTimeSelect.stories.tsx
> +  externalLabel,
See proposed revision to `FieldTime` 

```suggestion
  externalLabel = true,
```

2021-09-27 23:09 UTC, mdodgelooker commented on packages/components-date/src/FieldTime/FieldTime.stories.tsx
> +  externalLabel: true,
If I remove `externalLabel: true` here then it disappears from the storybook controls. I bet there's a different way to add it back though? 
![image](https://user-images.githubusercontent.com/53451193/134997210-24848fb1-5660-4afe-8964-7adf1aa61409.png)

2021-09-28 00:35 UTC, mdodgelooker commented
@lukelooker I see your point about the placeholder. With text fields, Material seems to allow placeholder but barely mention it in docs: https://material.angular.io/components/form-field/overview#form-field-appearance

But it doesn't seem to exist at all for selects. But the label does move up on focus for selects. Do we want to stop just supporting `placeholder` on `Select`? Or at least I can remove it from our examples...

2021-09-28 19:01 UTC, jhardy commented
My guess is that we have quite a few uses of `placeholder`'s in select, I would be hesitant to remove them.

2021-09-28 19:31 UTC, mdodgelooker commented
@lukelooker I was trippin about `externalLabel` in the stories – it does show in the controls whether or not you have it in the story args.

As for the `Select` placeholder... it seems like we need to move the label up immediately on focus to be material-y, but disabling `placeholder` might be too risky. Maybe we just discourage its use in the docs (once we turn `externalLabel` off by default in 3.0) or say to only use it with `externalLabe={true}`? Any other ideas?

2021-09-28 22:06 UTC, lukelooker commented
> @lukelooker I was trippin about `externalLabel` in the stories – it does show in the controls whether or not you have it in the story args.

👍 

> As for the `Select` placeholder... it seems like we need to move the label up immediately on focus to be material-y, but disabling `placeholder` might be too risky. Maybe we just discourage its use in the docs (once we turn `externalLabel` off by default in 3.0) or say to only use it with `externalLabe={true}`? Any other ideas?

I'm fine with moving ahead as-is – I suspect we'll see people downplay the use of placeholders in designs with this new design and I do think it'll be less disconcerting with _real_ placeholder / label text. :)

2021-09-28 23:34 UTC, lukelooker commented
Happy to re-review when the stories are cleaned up (use `externalLabel = true`in template instead of modifying all stories) :)

2021-09-29 00:21 UTC, mdodgelooker commented
@lukelooker I think the externalLabel fixes are all in.

2021-09-29 00:26 UTC, lukelooker approved these changes
LGTM! :)

(Sorry, missed the update commit)

2021-09-29 00:27 UTC, merged