feat(FieldDateRange): add label animation to component
looker-open-source/components pull request #2873
Opened 2021-09-28 20:55 UTC by laragoogle

- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 👾 Browsers tested
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] IE11

2021-09-28 21:00 UTC, laragoogle commented
Here is the first run at it!
1. Should I add documentation on the changes to gatsby?
2. when I check the test coverage, looks looks like its not covered at all, but then the  file it self shows as 100% covered.
![95c743db-2dc9-4af0-957e-3d2bc79d7e45](https://user-images.githubusercontent.com/89867109/135164575-83c044ec-b4c9-41b4-bef5-f85b5e03d0dc.gif)

2021-09-28 22:50 UTC, mdodgelooker requested changes
No need to add documentation. We'll do that in a separate PR once all the fields are updated. And I wouldn't worry about testing, I think coverage is good.

A couple issues I saw:
1) Can you use the `.label-down` class to hide the `HyphenWrapper` via CSS? 
![image](https://user-images.githubusercontent.com/53451193/135175913-2105d74c-8c77-4874-8d5e-cc2fc8a57cc9.png)
2) It looks like a custom function for `checkValueOnBlur` will be necessary, because the label moves down if you only clear the "from" date. [Check out `FieldTime` for an example](https://github.com/looker-open-source/components/pull/2868/files#diff-0a1d6048ab4ccaedfbed4956df1f05438e34ea844e90eb8506182006a94b74c3R46)
![c8c83ba2-01fb-43d3-9b92-72aee1068e5d](https://user-images.githubusercontent.com/53451193/135176101-4dad4df2-3ec9-4f7e-8f37-caaa2850e74b.gif)
.

2021-09-28 22:50 UTC, mdodgelooker commented on packages/components-date/src/FieldDateRange/FieldDateRange.stories.tsx
> +  ({ externalLabel, ...args }) => (
Set the default for `externalLabel` to true here, then add one or two stories that explicitly have `externalLabel: false`. That way the existing snapshots don't change but we have some new ones to capture the floating label style.

```suggestion
  ({ externalLabel = true, ...args }) => (
```

2021-09-30 18:53 UTC, mdodgelooker requested changes
Getting close! `hasValue` needs an update.

2021-09-30 18:53 UTC, mdodgelooker commented on packages/components-date/src/FieldDateRange/FieldDateRange.tsx
> +        hasValue={!!props.defaultValue}
This works for uncontrolled but not for controlled. If you add the story below, you'll see the label initially in the wrong position.
![image](https://user-images.githubusercontent.com/53451193/135513902-56e2e376-74c8-4efa-aa40-0c2c0027226c.png)
```js
export const Controlled = () => {
  const [range, setRange] = useState<FieldInputDateRangeProps['value']>({
    from: new Date('May 18, 2020'),
    to: new Date('May 21, 2020'),
  })
  return (
    <ExtendComponentsThemeProvider
      themeCustomizations={{ defaults: { externalLabel: false } }}
    >
      <FieldDateRange
        externalLabel={false}
        label="Controlled"
        value={range}
        onChange={setRange}
      />
    </ExtendComponentsThemeProvider>
  )
}
```

2021-09-30 19:56 UTC, laragoogle commented on packages/components-date/src/FieldDateRange/FieldDateRange.tsx
> +        hasValue={!!props.defaultValue}
good catch, fixed!

2021-09-30 21:31 UTC, mdodgelooker approved these changes
LGTM!

2021-09-30 22:38 UTC, merged